### ISSUE TITLE
aperture_photometry Memory error

### ISSUE THREAD

**Issue by samfederman** [astropy/photutils#1003]
I am having an issue with the aperture_photometry function. Basically, I'm starting with a 100x100 pixel array, and once running through photutils it somehow becomes a 15881x15881 element array resulting in a memory error. I have attempted using all 3 methods (exact, center, subpixel) and the problem persists. I am attaching a snapshot of the jupyter notebook page and the error for reference. If you are at all familiar with photutils or have had similar issues any advice would be appreciated.

![photutils_snapshot](https://user-images.githubusercontent.com/54328492/69659875-1fc8c900-104d-11ea-94b7-4207bf11c7d8.PNG)
![photutils_error_snapshot](https://user-images.githubusercontent.com/54328492/69659982-59013900-104d-11ea-99c5-0b842edd89d0.PNG)

**Comment by larrybradley** [comment]
@samfederman   I suspect that your aperture radius (in pixels) is a huge value, i.e. `(15881 - 1) / 2 = 7490` pixels.  Can you please check your value of `r=(f*6.5)/cell`?  If that's not it, I would need your FITS data to investigate further.

**Comment by samfederman** [comment]
@larrybradley it would appear that the aperture radius is the issue here. When I input a radius of 5 for instance, the function operates as normal.

**Comment by larrybradley** [comment]
Thanks for reporting back, @samfederman.  In your example, you can check the radius value after defining `circle` by doing `print(circle.r)`.

Just for reference, creating a `(15881, 15881)` array requires ~2GB of RAM.
