### ISSUE TITLE
b4 parameter

### ISSUE THREAD

**Issue by shivangeerathi** [astropy/photutils#1004]
Hi,
I am analysing the b4 parameter from the elliptical isophote fitting. I am getting very different (orders of magnitude higher) values than what I am getting from IRAF task 'ellipse' for very similar geometrical parameters. Does anyone know why does this happen ?

From Jedrzejewski's original paper, it seems that there is some transformation at play:

> To interpret the amplitudes obtained, they are transformed from intensity coefficients to coefficients describing deviations from a unit circle as in Carter (1977), by dividing by the local slope of the intensity profile and by the semi-major axis length.

So, I checked if this is the missing part, but apparently not.

**Comment by shivangeerathi** [comment]
From the first look, it seems that there is an error in the 'isophote.py'.
In the `_compute_deviations()` function, it says:
`c = fit_upper_harmonic(residual, sample.values[2], n)`,
where residual is the difference between the true and the modelled intensity as a function of angle phi from the semi-major axis.

However, in the definition of `fit_upper_harmonic()` in the 'harmonics.py', the first argument is the angle `phi`. 

Please correct me if I am wrong.

**Comment by larrybradley** [comment]
@ibusko Can you take a look?

**Comment by ibusko** [comment]
Yes, I will look into it.

**Comment by ibusko** [comment]
@larrybradley I will look into this.

**Comment by ibusko** [comment]
@shivangeerathi indeed, the calculation for the upper harmonics was wrong. I don't know how that happened, but I bet not many users do care for these parameters, and also, we haven't added any specific test to check the calculation. Now we have :-)

Thanks for pointing this out!
