### ISSUE TITLE
Installing photutils

### ISSUE THREAD

**Issue by ibusko** [astropy/photutils#1005]
When installing from a local repo cloned from github, or directly with the command 
`pip install git+https://github.com/astropy/photutils.git`
I get this error when trying to import:
>>> 
>>> import photutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/busko/Projects/photutils/photutils/__init__.py", line 19, in <module>
    from .aperture import *  # noqa
  File "/Users/busko/Projects/photutils/photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "/Users/busko/Projects/photutils/photutils/aperture/circle.py", line 15, in <module>
    from ..geometry import circular_overlap_grid
  File "/Users/busko/Projects/photutils/photutils/geometry/__init__.py", line 6, in <module>
    from .circular_overlap import *  # noqa
ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'
>>> 
>>>

**Comment by larrybradley** [comment]
It looks like your installation failed because of a missing C compiler (or `Cython` is missing).  The `geometry` subpackage contains `cython` code that needs to be compiled during installation from source.

**Comment by ibusko** [comment]
From the build log, it looks like the C extensions are being properly processed. See the attached log file. 
[temp.txt](https://github.com/astropy/photutils/files/3928490/temp.txt)

**Comment by larrybradley** [comment]
Yes that looks fine.  Your `python setup.py install`command is installing photutils in your conda environment called `isophote`.
Are you then starting up python and then doing `import photutils` from within the source directory?  If so, the above command will not build the extensions in place.  Instead you need to do a develop install (`python setup.py develop` OR better `pip install -e .`, which is now preferred).

**Comment by ibusko** [comment]
Thanks, that did it! Now that you say, I recall having this same problem ages ago. I have to write this down somewhere! :-)
