### ISSUE TITLE
ModuleNotFoundError: No module named 'photutils'

### ISSUE THREAD

**Issue by Johnnyboy183** [astropy/photutils#1010]
installed using conda install -c astropy photutils. All went well. 

However, in spyder, I get the ModuleNotFoundError: No module named 'photutils'

Feel like we've tried everything. Other astropy modules work without issue.

**Comment by larrybradley** [comment]
@Johnnyboy183 Thanks for reporting this.  I'm not sure what the issue could be.  I don't have any experience with `spyder`.  Is it using conda for package installs?  The `-c astropy` specifies that conda needs to look in the `astropy` conda channel to find `photutils`.  I'm just guessing that this might be the issue -- is there a way to specify conda channels in spyder?

@bsipocz Do you have any experience using `spyder`?

**Comment by larrybradley** [comment]
@Johnnyboy183 Can you install other astropy coordinated packages in `spyder`, e.g. `specutils` or `ccdproc`?

**Comment by Johnnyboy183** [comment]
> @Johnnyboy183 Can you install other astropy coordinated packages in `spyder`, e.g. `specutils` or `ccdproc`?

Yes other packages installed. I was able to get astropy photutils working. I uninstalled and reinstalled numpy and that seemed to do the trick.

**Comment by larrybradley** [comment]
Glad you got it working.  That's very great to hear that `photutils` was helpful in your project!  I like hearing this kind of feedback. 😄
