### ISSUE TITLE
GriddedPSFModel method to give a "local" FittableImageModel?

### ISSUE THREAD

**Issue by Vb2341** [astropy/photutils#1011]
The GriddedPSFModel is very useful for handling spatially variable PSFs.  However, bilinearly interpolating between the different models on the grid is quite slow.  It would be nice to have a method that returns a "local" FittableImageModel, to use when fitting a source that only covers a few pixels, as the evaluating the FittableImageModel is ~10x faster than evaluating the GriddedPSFModel.  This adds up when using iterative fitting methods.  If a local FittableImageModel were returned, this would require the bilinear interpolation to only be calculated once, which could likely drastically improve performance when fitting many stars.

I looked at the code, and it seems it would be very straightforward to do this, it would just be breaking GriddedPSFModel.evaluate() into two methods: one to first generate the local FittableImageModel, and the second to use the evaluate() method on that generated model, which is exactly what the current method does.  I'll open a PR with this in there in the next couple of days.  But I figured I'd open an issue for discussion just in case.

**Comment by larrybradley** [comment]
Closed in #1012.
