### ISSUE TITLE
Issue with star detection

### ISSUE THREAD

**Issue by druidowm** [astropy/photutils#1017]
Hi all,

I am trying to use PhotUtils to do PSF photometry. I am following one of the examples in the documentation, and am using get_residual_image() to check that the photometry is accurate. It seems to work very well on the stars the code detects. The issue is that the code does not find many of the stars. Strangely, these tend to be the brightest stars in the image. Here is my code:

```
from matplotlib.colors import LogNorm
from photutils.datasets import (make_random_gaussians_table,
                                make_noise_image,
                                make_gaussian_sources_image)
from photutils.psf import (IterativelySubtractedPSFPhotometry,
                           BasicPSFPhotometry)
from photutils import MMMBackground
from photutils.psf import IntegratedGaussianPRF, DAOGroup
from photutils.detection import DAOStarFinder
from photutils.detection import IRAFStarFinder
from astropy.table import Table
from astropy.modeling.fitting import LevMarLSQFitter

fitsStars = fits.open("test.fits")
imgStars = fitsStars[0].data.astype(np.float64)

daogroup = DAOGroup(crit_separation=8)
mmm_bkg = MMMBackground()
iraffind = DAOStarFinder(threshold=2*mmm_bkg(imgStars), fwhm=4.5)
fitter = LevMarLSQFitter()
gaussian_prf = IntegratedGaussianPRF(sigma=2.05)
gaussian_prf.sigma.fixed = False
photTester = IterativelySubtractedPSFPhotometry(finder=iraffind,
                                                   group_maker=daogroup,
                                                   bkg_estimator=mmm_bkg,
                                                   psf_model=gaussian_prf,
                                                   fitter=fitter,
                                                   fitshape=(11, 11),
                                                   niters=2)

photResults = photTester(imgStars)

finalImg = photTester.get_residual_image()

fig,axes = plt.subplots(1,2,sharex=True,sharey=True)
axes[0].imshow(-finalImg, cmap=cm.gray)
axes[1].imshow(-imgStars, cmap=cm.gray)
plt.show()
```

I attach an image of my results. The image on the left is the image with the stars removed, whereas the image on the right is the original image.
<img width="1338" alt="Screen Shot 2020-02-07 at 6 28 51 PM" src="https://user-images.githubusercontent.com/16171230/74073520-9c2a4180-49d8-11ea-8843-8821fcd0d6c4.png">

I also tried using the DAOStarFinder class, but that performed worse. It did not find any more stars, and the stars it did find it overcompensated for.

Any help would be greatly appreciated!

Sincerely,
Owen

**Comment by larrybradley** [comment]
@druidowm If you think the issue is with the star detection, have you tried changing the `threshold` and `fwhm` parameters?  I see you have currently set the threshold to 2 times the background level.  Usually one would want to set the threshold to the background value plus a specified sigma above the background noise, e.g. `threshold = bkg + (nsigma * bkg_rms)` where `nsigma` is the desired detection significance (per pixel).

You can run the star detection independent of the PSF-fitting code and inspect its results by running something like:

```python
mmm_bkg = MMMBackground()
finder = DAOStarFinder(threshold=2*mmm_bkg(imgStars), fwhm=4.5)
sources = finder(imgStars)

from photutils import CircularAperture
import matplotlib.pyplot as plt

positions = np.transpose((sources['xcentroid'], sources['ycentroid']))
apertures = CircularAperture(positions, r=4.)
plt.imshow(imgStars, origin='lower')
apertures.plot(color='red')
```

I would need to have your input data to investigate further.
