### ISSUE TITLE
Fails with negative CRVAL1

### ISSUE THREAD

**Issue by pmisson** [astropy/photutils#1024]
aper.to_pixel(wcs) gives wrong pixel locations if CRVAL1 is expressed in negative values.

I solved by changing the format of the image. It looks like is a Photutils problem because astropy does it correctly.

**Comment by larrybradley** [comment]
@pmission  `photutils` uses `astropy` to do all WCS transformations (i.e., x, y = wcs.world_to_pixel(skycoord))  Could you please provide a minimal example showing the bug?

**Comment by pmisson** [comment]
My CRval1 was -3.45 and my crval2 was 40.675. the regions were located at pixel 19000000. Clearly, at the complete opposite side.

**Comment by larrybradley** [comment]
@pmission  Can you please provide a minimal working code example showing your bug or your FITS file (you can replace the data with zeros if proprietary) and sample code showing the issue?  Without those, unfortunately we cannot further investigate this issue.

What does `wcs.world_to_pixel(skycoord)` return for your `wcs` object, where `skycoord` is an `astropy.coordinates.SkyCoord` object?  `photutils` is simply using this astropy method to do the sky to pixel transformation (see http://docs.astropy.org/en/stable/wcs/wcsapi.html for details). 


There could be an issue with your WCS.  Note that negative CRVALs (or CRPIXs) are perfectly fine.  Here's a simple example with a negative CRVAL1 (your values for CRVALs):

```
from astropy.wcs import WCS
wcs = WCS(naxis=2)
rho = np.pi / 3.
scale = 0.1 / 3600.
wcs.pixel_shape = (500, 500)
wcs.wcs.crpix = [250, 250]
wcs.wcs.crval = [-3.45, 40.675]
wcs.wcs.cd = [[-scale * np.cos(rho), scale * np.sin(rho)],
              [scale * np.sin(rho), scale * np.cos(rho)]]
wcs.wcs.radesys = 'ICRS'
wcs.wcs.ctype = ['RA---TAN', 'DEC--TAN']

from astropy.coordinates import SkyCoord
import astropy.units as u
from photutils import SkyCircularAperture
position = wcs.pixel_to_world(250, 250)
aper = SkyCircularAperture(position, r=1.*u.arcsec)
aper.to_pixel(wcs)
```
which gives the expected result:
```
<CircularAperture([250., 250.], r=10.000000000294463)>
```

**Comment by larrybradley** [comment]
@pmisson Please reopen if you are having issues or open a WCS issue on the astropy issue tracker.
