### ISSUE TITLE
apply_poisson_noise

### ISSUE THREAD

**Issue by arjung128** [astropy/photutils#1030]
Hi,

I was looking at the apply_poisson_noise function ([here](https://photutils.readthedocs.io/en/stable/api/photutils.datasets.apply_poisson_noise.html#photutils.datasets.apply_poisson_noise)), and I had two questions:

1. How much Poisson noise is applied?
2. Is there a way to change the amount of Poisson noise applied?

Thanks!

**Comment by larrybradley** [comment]
@arjung128 The amount of noise applied depends on the amount of signal (number of counts) in the input image.  From the docs:  "Each pixel in the output array is generated by drawing a random sample from a Poisson distribution whose expectation value is given by the pixel value in the input array."

Please also see https://en.wikipedia.org/wiki/Shot_noise
