### ISSUE TITLE
A simple typo in build_ellipse_model?

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#1042]
In the ``build_ellipse_model``, when ``high_harmonics`` is ``True``, a factor ``harm`` is calculated at [code line 120](https://github.com/astropy/photutils/blob/master/photutils/isophote/model.py#L120). 

I am not sure about the science here, but I feel the division by 4, if needed, should be done to the sum of all higher-harmonic terms, not only to B4, so maybe we should modify 

```python
               harm = ((a3_array[index] * np.sin(3.*phi) +
                        b3_array[index] * np.cos(3.*phi) +
                        a4_array[index] * np.sin(4.*phi) +
                        b4_array[index] * np.cos(4.*phi)) / 4.)
```

Am I correct?

**Comment by larrybradley** [comment]
Thanks, @ysBach.  @ibusko, is this a bug or should only b4 be divided by 4?

**Comment by cuernodegazpacho** [comment]
@ysBach @larrybradley yes, this is a typo. I suppose we do not have a test to check for that condition. Good catch!

**Comment by ibusko** [comment]
@ysBach @larrybradley yes, it's a typo. I suppose we don't have a test to check for that condition. Good catch! I will plan to fix this as soon as I can.

**Comment by larrybradley** [comment]
Fixed in https://github.com/astropy/photutils/pull/1052
