### ISSUE TITLE
TST: pytest header is misleading

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1046]
Same as astropy/astropy-healpix#145

**Comment by larrybradley** [comment]
I'm not seeing this in the dev version.  Photutils version is listed at the top and the Astropy version is listed with the other packages, e.g.:

```
Running tests with photutils version 0.8.dev201+gb19a3f30.
Running tests in photutils/utils.

Date: 2020-07-09T14:37:37

Platform: macOS-10.15.5-x86_64-i386-64bit

Executable: /Users/lbradley/.pyenv/versions/3.8.2/bin/python3.8

Full Python Version:
3.8.2 (default, Jun  8 2020, 23:03:23)
[Clang 11.0.3 (clang-1103.0.32.62)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions:
Numpy: 1.19.0
Scipy: 1.5.1
Matplotlib: 3.2.2
Cython: 0.29.20
Astropy: 4.0.1.post1
scikit-image: 0.17.2
scikit-learn: 0.23.1
astropy-helpers: 4.0.1

Using Astropy options: remote_data: none.
```

**Comment by pllim** [comment]
What is your pytest-astropy-header version, @larrybradley ?

**Comment by larrybradley** [comment]
0.1.2

**Comment by pllim** [comment]
Well, I'll just trust you then. Thanks for checking!

**Comment by larrybradley** [comment]
It works fine when running `pytest` directly (as I reported above), but *not* when running tests with `tox`.  The `conftest.py` is OK, so I'm not sure why there's a difference.

**Comment by pllim** [comment]
Why does this sound familiar... maybe @astrofrog remembers.

**Comment by larrybradley** [comment]
And tox was using the same version of `pytest-astropy-header 0.1.2`.

**Comment by pllim** [comment]
Maybe tox is not seeing https://github.com/astropy/photutils/blob/master/photutils/conftest.py ? What if you move it to root directory?

**Comment by larrybradley** [comment]
xref https://github.com/astropy/package-template/issues/439
