### ISSUE TITLE
Request supporting python 3.8 in wheels as well

### ISSUE THREAD

**Issue by mworion** [astropy/photutils#1047]
Hi all,

I really excited seeing your library and started using it in my application. The only point about is, that there is wheel support only for python 3.6 and 3.7. As many users already work on python 3.8 and I can't get them back, is there any chance to get the wheels also done for python 3.8. 

Thanks in advance,

Michel

**Comment by larrybradley** [comment]
Thanks, @mworion.  Python 3.8 wheels are now on PyPI.

**Comment by mworion** [comment]
Many thanks !

Michel
