### ISSUE TITLE
no stars found with DaoStarFinder in IterativelySubtractedPSFPhotometry

### ISSUE THREAD

**Issue by kangourouille** [astropy/photutils#1053]
I'm trying to remove PSF from stars in an image, but while the DAOStarFinder does find stars when I run it alone (it counts 206 stars in my data), it no longer holds when used as a parameter in IterativelySubtractedPSFPhotometry, giving me the warning "No sources were found. [photutils.detection.findstars]".

I don't have a clue where does this difference come from and got stuck with that for more than three weeks now.

**Comment by larrybradley** [comment]
The only difference is that `IterativelySubtractedPSFPhotometry` is subtracting the background from the data (using the input `bkg_estimator` function/class) before running `DAOStarFinder`.  With the background subtracted, the `DAOStarFinder` threshold may need to be changed.

**Comment by larrybradley** [comment]
Please report back if you are seeing issues beyond background subtraction differences.  Thanks.
