### ISSUE TITLE
Elliptical isophote model builder fails under certain combinations of input data

### ISSUE THREAD

**Issue by ibusko** [astropy/photutils#1054]
On Jun 15, 2020, at 8:05 AM, Cantiello, Michele <michele.cantiello@inaf.it> wrote:

External Email - Use Caution

Dear Ivo,

I am writing to ask about ISOPHOTE/ELLIPSE. I have used a lot these tasks/programs under IRAF and pyRAF, in the last twenty years or so. Mostly I am interested in doing surface brightness fluctuations (SBF) analysis in spheroidal galaxies, and -related to that- in the study of the globular cluster systems in such galaxies. 

I know that IRAF will not be maintained and, also because of the recent issues of it with OS Catalina, I am looking around for a useful substitute of ELLIPSE/BMODEL for modeling the brightness profiles of galaxies in 2D images. 

I have tried some candidates (like imfit by P. Erwin), but none really seems a valid option. I've found some python photutils programs,  which I understand you are somehow involved in, and this includes a repository from github (https://github.com/ibusko/isophote/) but the notebooks there seem not to work.

Do you have suggestions? I would really appreciate any advice on that.

Thanks for your time,

Michele 

°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
Michele Cantiello - PhD
INAF - Osservatorio Astronomico d'Abruzzo
via Mentore Maggini, snc - 64100 Teramo
tel. 0861439749 
e-mail: michele.cantiello@inaf.it
Skype micantiello
°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

**Comment by ibusko** [comment]
Hi Michele,

You are right that IRAF and all tasks developed under it are no longer maintained. A plethora or replacements have been developed along the years. As the author of the original Isophote package under STSDAS (which was an IRAF package to support HST), I took to myself to convert isophote to be a pure python set of modules. 

What you found in my GitHub repository is an older version of that work. The current version is part of the official release of the `photutils` package in astropy: https://photutils.readthedocs.io/en/stable/. Installation instructions can be found there.

Look for the Elliptical Isophote Analysis section. In there, there is a basic example on how to use the package. Also, look for the notebooks (linked at the bottom of the doc page) which demonstrate the use of the package under more realistic conditions. These notebooks are kept under the astropy/photoutils-datasets repository, which you can clone from Github.

Please, let me know in case you need any help.

Regards,

Ivo Busko

**Comment by ibusko** [comment]
Dear Ivo,
thanks for your reply.

I already used the photutils.ellipse stuff these days, this was one of the tests I made before, with no great success. That's why I was asking for something different. I understand, then, that I have to dig deeper in photutils.isophote.

Clearly the tests suggested by the notebooks worked well with the reference images. However, when I tried using some other images, I couldn't use the notebooks. I always got stock around at the  'build_ellipse_model' stage, with no suggestions from the system of what is making the program stop.

I am sharing with you a revised version of one of the notebooks at the repository, with a few modifications in the first lines. I made lots of testing, with simulated and real images. I'm also sharing one of the images I used (real, from VLT). When I run it, it doesn't complain, just it gets stocked at the 'build_ellipse_model' stage. I tried with different platforms (python, ipython, spyder, jupyter-notebook), but the result is always the same.

Please, if you have any idea on how to solve this problem (including something like: "don't ask me, but write to THIS_OTHER_ONE") I would really appreciate that.

I should say that I am kind of well experienced in using ELLIPSE within IRAF, but I am probably a newbie with python. 

Thanks 
Michele


°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
Michele Cantiello - PhD
INAF - Osservatorio Astronomico d'Abruzzo
via Mentore Maggini, snc - 64100 Teramo
tel. 0861439749 
e-mail: michele.cantiello@inaf.it
Skype micantiello
°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

**Comment by ibusko** [comment]
Hi Michele,

I am glad that you know already the python version. And thanks for sending me the test data.

I tried the mik1 notebook, and found that indeed build_ellipse_model fails. It actually enters an infinite loop. The condition manifests itself with only certain combinations of geometry parameters, and it seems that your data induces the algorithm in that corner case. It might have to do with the fact that the center of the galaxy image seems to be saturated. That may cause the fit algorithm to get unrealistic results.

I am preparing a fix to be included in the next release. In the meantime, if you want to fix it yourself, it’s a possibility, but you have to be able to install photutils from source code. You would have to edit one line of one source file only to add the fix yourself, and then build the package into your environment (a one-liner too). Are you familiar with the procedure?

Ivo

**Comment by larrybradley** [comment]
Fixed in #1056.
