### ISSUE TITLE
Circular segments for apertures

### ISSUE THREAD

**Issue by ivvv** [astropy/photutils#1055]
I've been trying to implement a user-defined aperture in a form of a circular segment and annulus (wedge), including only a range of angles. [So, circular aperture would be a a sub-set of this class with the angles (0,360)]

The circular wedge (like a pie) should have a centre, radius  and two angles, while the annular segment should have inner and outer radius, correspondingly. As the documentation is a bit scarce on user-defined apertures, and no examples, I would like to understand how I can do this: is it only by defining the aperture patch via `matplotlib.mpatches.Wedge()` or is there something else?

**Comment by ivvv** [comment]
Just to give you a use case: if you want to build a radial profile of source at different azimuth ranges, 0-30 deg, 30-60, 60-90 etc...

**Comment by larrybradley** [comment]
@ivvv You would need to define a custom `to_mask` method that produces a weight array (values ranging from 0 - 1, inclusive) for your given aperture such that weight array represents the fractional overlap of your aperture (given its position, radius, and angle parameters) with the pixel grid.  In general, that's not a trivial step, especially if you want to handle "exact" pixel overlaps.  The fractional overlaps are generated for the define photutils apertures by the low-level geometry functions (https://photutils.readthedocs.io/en/latest/geometry.html).

If you want a quick and rough approximate, one workaround would be to create an `ApertureMask` from a circular aperture (using the `to_mask()`) method, *then* mask that array based on your desired azimuthal angles to create a custom `ApertureMask` object, then use the `ApertureMask.multiply()` method and manually do the photometry.  This section of the docs shows an example of using Aperture masks:  https://photutils.readthedocs.io/en/latest/aperture.html#sigma-clipped-median-within-a-circular-annulus
