### ISSUE TITLE
ImportError: cannot import name 'CompoundModel' from 'astropy.modeling.core' 

### ISSUE THREAD

**Issue by jun01ee** [astropy/photutils#1057]
I got the following error when trying to import photutils,

I got: 
photutils 0.7.2
astropy 4.0.1.post1 (not sure what it mean by .post1)
numpy  1.15.4
------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-81-fb9f6c201c90> in <module>
      3 # ! pip install photutils
      4 # from photutils import CircularAperture
----> 5 import photutils
      6 photutils.test()

~\Anaconda3\lib\site-packages\photutils\__init__.py in <module>
     32 
     33 if not _ASTROPY_SETUP_:  # noqa
---> 34     from .aperture import *  # noqa
     35     from .background import *  # noqa
     36     from .centroids import *  # noqa

~\Anaconda3\lib\site-packages\photutils\aperture\__init__.py in <module>
      6 
      7 from .bounding_box import *    # noqa
----> 8 from .circle import *          # noqa
      9 from .core import *            # noqa
     10 from .ellipse import *         # noqa

~\Anaconda3\lib\site-packages\photutils\aperture\circle.py in <module>
      5 from astropy.coordinates import SkyCoord
      6 
----> 7 from .core import PixelAperture, SkyAperture
      8 from .bounding_box import BoundingBox
      9 from .mask import ApertureMask

~\Anaconda3\lib\site-packages\photutils\aperture\core.py in <module>
     17                                wcs_to_celestial_frame)
     18 
---> 19 from ..utils import get_version_info
     20 from ..utils.misc import _ABCMetaAndInheritDocstrings
     21 from ..utils.wcs_helpers import pixel_scale_angle_at_skycoord

~\Anaconda3\lib\site-packages\photutils\utils\__init__.py in <module>
      6 from .check_random_state import *    # noqa
      7 from .colormaps import *             # noqa
----> 8 from .convolution import *           # noqa
      9 from .cutouts import *               # noqa
     10 from .errors import *                # noqa

~\Anaconda3\lib\site-packages\photutils\utils\convolution.py in <module>
      4 
      5 import numpy as np
----> 6 from astropy.convolution import Kernel2D
      7 from astropy.utils.exceptions import AstropyUserWarning
      8 

~\Anaconda3\lib\site-packages\astropy\convolution\__init__.py in <module>
      6 from .utils import discretize_model  # noqa
      7 
----> 8 from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models  # noqa
      9 
     10 # Deprecated kernels that are not defined in __all__

~\Anaconda3\lib\site-packages\astropy\convolution\convolve.py in <module>
     15 from astropy import units as u
     16 from astropy.nddata import support_nddata
---> 17 from astropy.modeling.core import CompoundModel
     18 from astropy.modeling.core import SPECIAL_OPERATORS
     19 from .utils import KernelSizeError, has_even_axis, raise_even_kernel_exception

ImportError: cannot import name 'CompoundModel' from 'astropy.modeling.core' (C:\Users\junolee\Anaconda3\lib\site-packages\astropy\modeling\core.py)

**Comment by larrybradley** [comment]
Your error is actually coming from `astropy`.  It appears that the `astropy` installation failed somehow (note `4.0.1.post1` is the correct latest version) .  You can test this by starting python and enter "from astropy.modeling.core import CompoundModel".  You should not get an `ImportError` from running that statement.

**Comment by jun01ee** [comment]
I tried running "from astropy.modeling.core import CompoundModel", I got an error telling me that I need Numpy 1.16 or above for Astropy 4.0.1.post1.
I update my numpy, another error occurs.
-------------------------------------------------------------------------------------------------------
WARNING: AstropyDeprecationWarning: The InheritDocstrings class is deprecated and may be removed in a future version.
        Use Sphinx>=1.7 automatically inherits docstring instead. [photutils.background.core]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-fb9f6c201c90> in <module>
      3 # ! pip install photutils
      4 # from photutils import CircularAperture
----> 5 import photutils
      6 photutils.test()

~\Anaconda3\lib\site-packages\photutils\__init__.py in <module>
     34     from .aperture import *  # noqa
     35     from .background import *  # noqa
---> 36     from .centroids import *  # noqa
     37     from .detection import *  # noqa
     38     from .morphology import *  # noqa

~\Anaconda3\lib\site-packages\photutils\centroids\__init__.py in <module>
      5 """
      6 
----> 7 from .core import *    # noqa

~\Anaconda3\lib\site-packages\photutils\centroids\core.py in <module>
     23 
     24 
---> 25 class _GaussianConst1D(Const1D + Gaussian1D):
     26     """A model for a 1D Gaussian plus a constant."""
     27 

~\Anaconda3\lib\site-packages\astropy\modeling\core.py in <lambda>(left, right)
     55     or ``'**'``.
     56     """
---> 57     return lambda left, right: CompoundModel(oper, left, right, **kwargs)
     58 
     59 

~\Anaconda3\lib\site-packages\astropy\modeling\core.py in __init__(self, op, left, right, name, inverse)
   2325             self.inverse = inverse
   2326 
-> 2327         if op != 'fix_inputs' and len(left) != len(right):
   2328             raise ValueError(
   2329                 'Both operands must have equal values for n_models')

TypeError: object of type '_ModelMeta' has no len()

**Comment by jun01ee** [comment]
I reinstalled an earlier version of Astropy (astropy3.2.4), I can now import photutils without error.
However, when I run the `photutils.test()`, it spotted two errors.
---------------------------------------------------------------------------------
================================================= test session starts =================================================
platform win32 -- Python 3.7.1, pytest-4.0.2, py-1.7.0, pluggy-0.8.0

Running tests with photutils version 0.6.
Running tests in Anaconda3\lib\site-packages\photutils.

Date: 2020-06-26T11:49:30

Platform: Windows-10-10.0.18362-SP0

Executable: C:\Users\junolee\Anaconda3\python.exe

Full Python Version: 
3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

encodings: sys: utf-8, locale: cp1252, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.19.0
Scipy: 1.1.0
Matplotlib: 3.0.2
Cython: 0.29.2
Astropy: 3.2.3
scikit-image: not available
scikit-learn: 0.20.1
astropy_helpers: 3.2.2
Using Astropy options: remote_data: none.

rootdir: C:\Users\junolee, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.1, doctestplus-0.2.0, arraydiff-0.3
collected 1201 items / 2 errors

======================================================= ERRORS ========================================================
______________ ERROR collecting Anaconda3/lib/site-packages/photutils/aperture/tests/test_photometry.py _______________
ImportError while importing test module 'C:\Users\junolee\Anaconda3\lib\site-packages\photutils\aperture\tests\test_photometry.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
Anaconda3\lib\site-packages\photutils\aperture\tests\test_photometry.py:20: in <module>
    from ..photometry import aperture_photometry
Anaconda3\lib\site-packages\photutils\aperture\photometry.py:19: in <module>
    from ..utils.misc import _get_version_info
E   ImportError: cannot import name '_get_version_info' from 'photutils.utils.misc' (C:\Users\junolee\Anaconda3\lib\site-packages\photutils\utils\misc.py)
_______________ ERROR collecting Anaconda3/lib/site-packages/photutils/utils/tests/test_convolution.py ________________
ImportError while importing test module 'C:\Users\junolee\Anaconda3\lib\site-packages\photutils\utils\tests\test_convolution.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
Anaconda3\lib\site-packages\photutils\utils\tests\test_convolution.py:13: in <module>
    from ..convolution import _filter_data
E   ImportError: cannot import name '_filter_data' from 'photutils.utils.convolution' (C:\Users\junolee\Anaconda3\lib\site-packages\photutils\utils\convolution.py)
================================================== warnings summary ===================================================
Anaconda3\lib\site-packages\_pytest\config\__init__.py:754
  C:\Users\junolee\Anaconda3\lib\site-packages\_pytest\config\__init__.py:754: PytestWarning: Module already imported so cannot be rewritten: pytest_remotedata
    self._mark_plugins_for_rewrite(hook)
  C:\Users\junolee\Anaconda3\lib\site-packages\_pytest\config\__init__.py:754: PytestWarning: Module already imported so cannot be rewritten: pytest_openfiles
    self._mark_plugins_for_rewrite(hook)
  C:\Users\junolee\Anaconda3\lib\site-packages\_pytest\config\__init__.py:754: PytestWarning: Module already imported so cannot be rewritten: pytest_doctestplus
    self._mark_plugins_for_rewrite(hook)
  C:\Users\junolee\Anaconda3\lib\site-packages\_pytest\config\__init__.py:754: PytestWarning: Module already imported so cannot be rewritten: pytest_arraydiff
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 4 warnings, 2 error in 0.72 seconds =========================================

**Comment by larrybradley** [comment]
There is clearly something wrong with your environment.  The `TypeError: object of type '_ModelMeta' has no len()` error is caused by having an older version of photutils (<= 0.6) with a newer version of astropy (see https://github.com/astropy/photutils/issues/1021#issuecomment-624243926).  The above `photutils.test()` errors are puzzling because those `utils` modules are available in photutils releases -- but they were deprecated in v0.7 and are now removed in the unreleased development code.  There appears to be a mismatch of code versions.

**Comment by larrybradley** [comment]
Please report back if you are still having issues.
