### ISSUE TITLE
watershed is deprecated; use skimage.segmentation.watershed instead

### ISSUE THREAD

**Issue by entaylor** [astropy/photutils#1059]
I'm starting my first big photutils project; it's quite ambitious, but i'm really excited by how powerful i've found photuilts to be so far.  I'm hoping i can become a contributor, if/when i can find a gap i can fill.

My first issue is pretty mundane: i'm getting a deprecation warning when running deblend_sources, which i imagine should be an easy fix, if it's not fixed already.

Minimal code to reproduce the issue (and following the segmentation/deblending demo), including version info follows:
```
import numpy, astropy, skimage
print( 'numpy version:', numpy.__version__ )
print( 'astropy version:', astropy.__version__ )
print( 'skimage version:', skimage.__version__ )

from astropy.convolution import Gaussian2DKernel

import photutils
print( 'photutils version:', photutils.__version__ )
```
numpy version: 1.18.5
astropy version: 4.0.1.post1
skimage version: 0.17.2
photutils version: 0.7.2
```
# create mock data
data = photutils.datasets.make_100gaussians_image()

# set detection threshold
threshold = photutils.detect_threshold( data, nsigma=2. )
# define convolution kernel for detection
kernel = Gaussian2DKernel( 1.3, x_size=3, y_size=3 )
kernel.normalize()
# make detection map
segm = photutils.detect_sources(
    data, threshold, npixels=5, filter_kernel=kernel )

# and deblend; this is where the exceptions are thrown
segm_deblend = photutils.deblend_sources(
    data, segm, npixels=5, filter_kernel=kernel )
```
The exception is:
```
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
```
The same exception is thrown multiple times, presumably at successive iterations of the deblending.

In the interim of a fix, is there any easy way to disable the warning, to prevent it overrunning my log files?  : )

Hope that's some (very small!) help.

**Comment by larrybradley** [comment]
The watershed import was updated in https://github.com/astropy/photutils/pull/1041.  Unfortunately there isn't a way to disable this warning as the `scikit-image` code explicitly sets the deprecation warning level to 'always'.  The simplest workaround would be to install `scikit-image 0.17.1`.

**Comment by robelgeda** [comment]
I am getting same issue, thanks @larrybradley for the explanation!

**Comment by ipcoder** [comment]
@larrybradley 
I am running 0.17.2 and still have this warning.
Also I am not sure updating `scikit-image` can help, may be in opposite - to downgrade it to the version where the function used by `deblend_sources` is not deprecated yet.

Warning suggests old version of function is used in `deblend_sources` and it seems there it should be changed.

**Comment by larrybradley** [comment]
@ipcoder My recommendation above was a downgrade of `scikit-image` (to 0.17.1).  In any case `photutils 1.0.0` is released and doesn't have this issue.
