### ISSUE TITLE
find_peaks handling of masked data

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1071]
If I understood [find_peaks API doc](https://photutils.readthedocs.io/en/stable/api/photutils.detection.find_peaks.html) correctly, if I already have masked array, I need to break out the `data` and `mask` portions before passing them in separately?

**Comment by larrybradley** [comment]
@pllim `find_peaks` `data` must be a `ndarray`, not a `MaskedArray`, so you'll need to pass in both the data and mask separately.  I'll update the docs for `data` type to say `ndarray`.
