### ISSUE TITLE
PSF photometry on just one star

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1074]
Let's consider this work flow:

1. Select one star.
2. Construct a 2D model (e.g., `Gaussian2D`, `Moffat2D`, or a non-existent `Lorentz2D`).
3. Feed the model some rough initial estimates.
4. Fit the model to the star.
5. Obtain or derive the following values from fit:
    * Centroid
    * FWHM (X, Y, and overall?)
    * Brightness
    * Ellipticity
    * Background (sky level)

Is this something that PSF photometry can/should do? If not, is this something that `photutils` should support outside of PSF photometry domain?

More context: I discussed this with @larrybradley and @eteq offline. Erik suggested [prepare_psf_model](https://photutils.readthedocs.io/en/stable/api/photutils.psf.prepare_psf_model.html) that seems to go with [BasicPSFPhotometry](https://photutils.readthedocs.io/en/latest/api/photutils.psf.BasicPSFPhotometry.html). However, `BasicPSFPhotometry` requires things like `group_maker`, which does not seem very relevant for one-star use case, and I am unable to find a good example for the use case above given #557.

xref ejeschke/ginga#896 and https://github.com/ejeschke/ginga/blob/965d1ec23fdf02b7a48c86b428153346c6ce5cad/ginga/util/iqcalc.py#L466

**Comment by larrybradley** [comment]
@pllim I've added an example in the docs how to perform PSF photometry on only one star:
https://photutils.readthedocs.io/en/latest/psf.html#fitting-a-single-source
