### ISSUE TITLE
ImportError: cannot import name 'NUMPY_LT_1_14' from 'astropy.utils.compat'

### ISSUE THREAD

**Issue by PauliPalbi** [astropy/photutils#1077]
Hi, I just re-installed Anaconda on my computer (Mac) and I have the following problem with Astropy. It happens when I try to import other packages such as Photutils and vip_hci.

When importing photutils as:
import photutils
I get:
ImportError: cannot import name 'NUMPY_LT_1_14_1' from 'astropy.utils.compat' (/Users/palmabifani/opt/anaconda3/lib/python3.8/site-packages/astropy/utils/compat/__init__.py)

My numpy version is '1.18.5' and the astropy version is '4.0.1.post1'. (I don't get the error when importing Astropy). So what I did was to run astropy.test() and the output is:

============================= test session starts ==============================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/palmabifani
plugins: doctestplus-0.8.0, remotedata-0.3.2, arraydiff-0.2, openfiles-0.5.0, hypothesis-5.29.0, astropy-header-0.1.2
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../../../../../../opt/anaconda3/lib/python3.8/site-packages/_pytest/config/__init__.py:495: in _importconftest
    return self._conftestpath2mod[key]
E   KeyError: PosixPath('/Users/palmabifani/opt/anaconda3/lib/python3.8/site-packages/astropy/coordinates/tests/conftest.py')

During handling of the above exception, another exception occurred:
../../../../../../opt/anaconda3/lib/python3.8/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
../../../../../../opt/anaconda3/lib/python3.8/site-packages/astropy/coordinates/__init__.py:10: in <module>
    from .angles import *
../../../../../../opt/anaconda3/lib/python3.8/site-packages/astropy/coordinates/angles.py:16: in <module>
    from astropy.utils.compat import NUMPY_LT_1_14_1, NUMPY_LT_1_14_2
E   ImportError: cannot import name 'NUMPY_LT_1_14_1' from 'astropy.utils.compat' (/Users/palmabifani/opt/anaconda3/lib/python3.8/site-packages/astropy/utils/compat/__init__.py)
=========================== short test summary info ============================
ERROR ../../../../../.. - ImportError: cannot import name 'NUMPY_LT_1_14_1' f...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.46s ===============================

On that path ((/Users/palmabifani/opt/anaconda3/lib/python3.8/site-packages/astropy/utils/compat/) I have a numpycompat.py file that has the following lines in it.

"""
This is a collection of monkey patches and workarounds for bugs in
earlier versions of Numpy.
"""
from astropy.utils import minversion

__all__ = ['NUMPY_LT_1_14', 'NUMPY_LT_1_14_1', 'NUMPY_LT_1_14_2',
           'NUMPY_LT_1_15', 'NUMPY_LT_1_16', 'NUMPY_LT_1_17']

#TODO: It might also be nice to have aliases to these named for specific
#features/bugs we're checking for (ex:
#astropy.table.table._BROKEN_UNICODE_TABLE_SORT)
NUMPY_LT_1_14 = not minversion('numpy', '1.14')
NUMPY_LT_1_14_1 = not minversion('numpy', '1.14.1')
NUMPY_LT_1_14_2 = not minversion('numpy', '1.14.2')
NUMPY_LT_1_15 = not minversion('numpy', '1.15')
NUMPY_LT_1_16 = not minversion('numpy', '1.16')
NUMPY_LT_1_17 = not minversion('numpy', '1.17')

Does anyone know how to solve this error?

**Comment by larrybradley** [comment]
@PauliPalbi This error is coming from `astropy`, not `photutils`.  My guess is there was an issue with your astropy installation.  I would try installing `astropy 4.1`.  If you are still having issues, please report it on the astropy GitHub tracker.

**Comment by PauliPalbi** [comment]
Hi,

I indeed solved it by installing it again like this.

conda install photutils -c astropy

Cheers
Paulina

----------------------------------------
Paulina Palma Bifani
MSc. Student
Departamento de Astronomía
Universidad de Chile
----------------------------------------



On Oct 28, 2020, at 12:33, Larry Bradley <notifications@github.com<mailto:notifications@github.com>> wrote:



@PauliPalbi<https://github.com/PauliPalbi> This error is coming from astropy, not photutils. My guess is there was an issue with your astropy installation. I would try installing astropy 4.1. If you are still having issues, please report it on the astropy GitHub tracker.
