### ISSUE TITLE
Import error in python3.6, new in v1.0.1

### ISSUE THREAD

**Issue by dstndstn** [astropy/photutils#1095]
Hi,

Starting from a fresh (docker) ubuntu 18.04 image,

```
# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
# pip3 install photutils==1.0.0
...
# python3.6 -c "import photutils" && echo ok
ok
# pip3 install photutils==1.0.1
...
# python3.6 -c "import photutils" && echo ok
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/photutils/__init__.py", line 38, in <module>
    __citation__ = __bibtex__ = _get_bibtex()
  File "/usr/local/lib/python3.6/dist-packages/photutils/__init__.py", line 31, in _get_bibtex
    refs = citation.read().split('@software')[1:]
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 954: ordinal not in range(128)
```

**Comment by larrybradley** [comment]
Thanks, @dstndstn.  I can't reproduce this on OSX with py3.6, but undoubtedly it's because of unicode characters in the `CITATION.rst` file.  Can you check if https://github.com/astropy/photutils/pull/1097 fixes the issue for you?

**Comment by dstndstn** [comment]
Thanks @larrybradley , yes, that does seem to fix it.  (And that seems like the right way to do accented characters in TeX anyway)

**Comment by karpov-sv** [comment]
Hi @larrybradley, it seems the change fixing this issue was reverted in commit b3465c3f6a9b46fcb3fb4687abae8270f4da5f99 . So now the problem happens again.

**Comment by larrybradley** [comment]
Thanks, @karpov-sv.  The updated BibTeX file was copied from Zenodo, which contains unicode characters.  Fixed in https://github.com/astropy/photutils/pull/1606.
