### ISSUE TITLE
Background2D._prepare_data is susceptible to bug in numpy.ma

### ISSUE THREAD

**Issue by jdermigny** [astropy/photutils#1105]
According to an issue noted [here](https://github.com/numpy/numpy/issues/17046), numpy masked arrays are extremely slow when created with the mask parameter set to `None` instead of `False`. photutils.background2d requires that users set mask=None, raising an error if False is used instead. This slows down photutils.background2d._prepare_data where the masked arrays are created.

**Comment by jdermigny** [comment]
I have tested code to correct this and will create a pull request soon.

**Comment by larrybradley** [comment]
@jdermigny Many thanks for reporting this.  I went ahead and fixed it while working on some other `Background2D` performance improvements in #1108.
