### ISSUE TITLE
Background estimation for a 2D spectral image

### ISSUE THREAD

**Issue by cylammarco** [astropy/photutils#1115]
I was looking at specutils and ccdprocs, the former is only handling 1D spectral data, the latter handles detector-related processing. It looks like photutils could be where this problem can be addressed in the astropy-ecosystem.

Is there any recommendation for (not) using the `photutils.background` to build a 2D sky model for a dispersed 2D spectral image?

**Comment by larrybradley** [comment]
@cylammarco `Background2D` wasn't intended for that purpose, but you could try it out.  In principal it should work fine in regions of only "background".
