### ISSUE TITLE
Effective area of a masked aperture / annulus

### ISSUE THREAD

**Issue by cmillion** [astropy/photutils#1118]
When passing a masked array to `aperture_photometry` as described [here](https://photutils.readthedocs.io/en/stable/aperture.html#pixel-masking), is there an existing method of returning the effective area of aperture / annulus, i.e. the area of the aperture minus the areas of masked pixels and subpixels?

**Comment by cmillion** [comment]
I have achieved the desired result by doing identical aperture photometry on a `np.ones` area to which the same mask has been applied, e.g.:

    annulus = CircularAnnulus([pos],r_in,r_out)
    photometry = aperture_photometry(masked_img, annulus)
    areamap = np.ones(masked.shape)
    effective_area = aperture_photometry(areamap, annulus, mask=masked_img.mask)

Is there an existing capability for this? It seems like there should be a way to do it with the `to_mask` method of `CircularAnnulus`.

**Comment by cmillion** [comment]
I see that there's an existing pull request #874 by @griffin-h for this from summer of 2019. It seems to pass all checks, but there was no discussion. Is there a reason it hasn't been merged? How can I help?

**Comment by griffin-h** [comment]
I'm also happy to help update the PR if it's of interest to others!

**Comment by larrybradley** [comment]
Added in #874.
