### ISSUE TITLE
aperture.area is not equal the area of photometry? 

### ISSUE THREAD

**Issue by TakuNishiumi** [astropy/photutils#1131]
Hi, 

I would like to ask you a question.

```
aperture = CircularAperture(positions, r=20)
phot_table = aperture_photometry(data, apertures)
bkg_sum = bkg_mean * aperture.area
final_sum = phot_table['aperture_sum_0'] - bkg_sum
```
`bkg_mean` is mean of sky backgroud.

In this calculation, we collect the subpixels' values within the aperture.
And `aperture.area` calculate pi*r^2.
I think we are too subtracting sky background because the area of subpixels and the area of `aperture.area` are different.
Is this correct?

**Comment by larrybradley** [comment]
The aperture `area` method always returns the *exact* area of the geometric shape.  If you are using the 'center' or 'subpixel' modes, you can find the area by using the `ApertureMask` object, e.g.:

```python
>>> from photutils import CircularAperture, aperture_photometry
>>> aper = CircularAperture((50, 50), r=3)

>>> apermask = aper.to_mask(method='center')
>>> apermask.data.sum()
25.0

>>> apermask = aper.to_mask(method='subpixel')
>>> apermask.data.sum()
27.96

>>> apermask = aper.to_mask(method='exact')
>>> apermask.data.sum(). # same as aper.area = np.pi * r**2
28.274333882308138

>>> aper.area (np.pi * r**2)
28.274333882308138
```

Equivalently, use can perform `aperture_photometry` with these aperture on an array whose values are all 1.
