### ISSUE TITLE
SExtractor User Manual Link Issue

### ISSUE THREAD

**Issue by Yash-10** [astropy/photutils#1134]
While going through the [Background Estimation](https://photutils.readthedocs.io/en/stable/background.html#d-background-and-noise-estimation) documentation, I realised that the link to the `SExtractor`'s User Manual prevents users visiting the website, at least starting from Google Chrome 81,  probably because it uses outdated security configurations i.e. TLS 1.0 or TLS 1.1. 

Instead, users can be directed to https://sextractor.readthedocs.io/en/latest/ to prevent the problem?

**Comment by larrybradley** [comment]
@Yash-10 Many thanks for reporting this.  It was fixed in #1138.  The "latest" docs are updated (https://photutils.readthedocs.io/en/latest/background.html).  The "stable" docs will be updated for the next release.  Thanks.
