### ISSUE TITLE
Importing Photutils gives: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

### ISSUE THREAD

**Issue by TrystanScottLambert** [astropy/photutils#1149]
I've been having a lot of grief with the above error message. When I simply run ``` import photutils ``` then I get the error. Downgrading numpy does nothing. 

I also get this error intermittently when trying to import astropy.stats. 

``` In [1]: import photutils
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-5-e3d8b5fe96af> in <module>
----> 1 import photutils

~/.local/lib/python3.6/site-packages/photutils/__init__.py in <module>
     15 # ----------------------------------------------------------------------------
     16 
---> 17 from .aperture import *  # noqa
     18 from .background import *  # noqa
     19 from .centroids import *  # noqa

~/.local/lib/python3.6/site-packages/photutils/aperture/__init__.py in <module>
      5 
      6 from .bounding_box import *  # noqa
----> 7 from .circle import *  # noqa
      8 from .core import *  # noqa
      9 from .ellipse import *  # noqa

~/.local/lib/python3.6/site-packages/photutils/aperture/circle.py in <module>
     13 from .core import PixelAperture, SkyAperture
     14 from .mask import ApertureMask
---> 15 from ..geometry import circular_overlap_grid
     16 
     17 __all__ = ['CircularMaskMixin', 'CircularAperture', 'CircularAnnulus',

~/.local/lib/python3.6/site-packages/photutils/geometry/__init__.py in <module>
      4 """
      5 
----> 6 from .circular_overlap import *  # noqa
      7 from .elliptical_overlap import *  # noqa
      8 from .rectangular_overlap import *  # noqa

photutils/geometry/circular_overlap.pyx in init photutils.geometry.circular_overlap()

RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject ```

#Sytem:
Linux-5.3.0-28-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
Numpy 1.19.5
astropy 4.1
Scipy 1.5.4
Matplotlib 3.3.3

**Comment by TrystanScottLambert** [comment]
Funny enough what I've just noticed is that if I do everything in ipython via terminal first then it works and I can run my script. but just running the script right away causes the above errors and if I've attempted to run it once (via ipython) then I continue to get the same error.

**Comment by larrybradley** [comment]
@TrystanScottLambert This is just a warning (not an error) and it's nothing to worry about.  This warning should be suppressed in recent releases of `photutils` (e.g., see https://github.com/astropy/photutils/blob/master/setup.cfg#L63).

**Comment by TrystanScottLambert** [comment]
Thanks for the reply. It is a warning but python still crashes. It won't ignore the warning.

**Comment by larrybradley** [comment]
Python crashes because of this warning?  What version of photutils are you using and how did you install it (e.g., pip, conda, etc.)?

**Comment by jamienoss** [comment]
@larrybradley Hey Larry, we're getting a similar issue over [here](https://github.com/spacetelescope/catkit/pull/218/checks?check_run_id=2176266394#step:6:71) except that it's a hard error.
```python
catkit\hardware\newport\NewportPicomotorController.py:18: in <module>
    from photutils import centroid_1dg, centroid_2dg
C:\Miniconda\envs\ci-env\lib\site-packages\photutils\__init__.py:17: in <module>
    from .aperture import *  # noqa
C:\Miniconda\envs\ci-env\lib\site-packages\photutils\aperture\__init__.py:7: in <module>
    from .circle import *  # noqa
C:\Miniconda\envs\ci-env\lib\site-packages\photutils\aperture\circle.py:15: in <module>
    from ..geometry import circular_overlap_grid
C:\Miniconda\envs\ci-env\lib\site-packages\photutils\geometry\__init__.py:6: in <module>
    from .circular_overlap import *  # noqa
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

photutils\geometry\circular_overlap.pyx:1: ValueError
```

**Comment by larrybradley** [comment]
@jamienoss I looked into this more and everything I've read suggests that this should be a benign warning from `numpy` (https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility). Since you are installing from `conda-forge`, the bottom line is the `numpy` version `conda-forge` used to build the package (logs here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=292969&view=results) is different from the `numpy` version in your environment.  I've never seen it raise a `ValueError` (but I no longer use conda) and I was unable to reproduce it.

A couple of things to try:  
* install photutils from the `astroconda` channel instead of the `conda-forge` channel (NOTE: the `astropy` conda channel is simply a mirror of `conda-forge`)
* install photutils using pip

**Comment by jamienoss** [comment]
@larrybradley Hey, thanks for helping.

So, I'm not sure that this is supposed to be a warning,  As of numpy 1.20, they changed the struct size of ndarray, and is no longer backward compatible without re-compilation (and even then builds are then tethered to their numpy version).

So ``astroconda`` is a no go as we need this for windows and that's only linux and osx.
I'm trying ``pip`` again, however, it's a wheel and I think must be built against 1.20 but I'm not sure how to clearly verify this (other than that I still get the size error). I'm trying ``--no-binary`` options now, and gonna look for an older version that just happens to have not been recently rebuilt...

Would you be able to check which version of numpy was used for the recent photutils pypi builds, please?

**Comment by larrybradley** [comment]
The `photutils` PyPI wheels should be using the "oldest supported numpy" (https://github.com/astropy/photutils/blob/main/pyproject.toml#L6), which is `1.17.*`.

**Comment by larrybradley** [comment]
The `win64` `photutils` wheel was built with `numpy-1.17.0-cp37-cp37m-win_amd64.whl`

**Comment by espinozagaleas** [comment]
Hi everybody, same error here:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`
 
Numpy version:
NAME
    numpy.version

DESCRIPTION
    # THIS FILE IS GENERATED FROM NUMPY SETUP.PY
    #
    # To compare versions robustly, use `numpy.lib.NumpyVersion`

DATA
    full_version = '1.19.2'
    git_revision = '68752f786df542d340f25c41a8920d9b2aed66cf'
    release = True
    short_version = '1.19.2'
    version = '1.19.2'

FILE
    /opt/anaconda3/lib/python3.8/site-packages/numpy/version.py

Please help

**Comment by jamienoss** [comment]
I think conda-forge's photutils 1.1.0 was built against numpy 1.20.

Using either cond-forge's 1.0.2 or using pip (even for 1.1.0) worked for me.

**Comment by jamienoss** [comment]
@larrybradley Thanks for the help 👍

**Comment by larrybradley** [comment]
I just rebuilt the `conda-forge` packages with numpy 1.17 (https://anaconda.org/conda-forge/photutils/files).

@TrystanScottLambert , @espinozagaleas , @jamienoss : Can you please try updating/reinstalling photutils and let me know if it works?

**Comment by rainerschoedel** [comment]
Hi, I have the same problem. I have just installed photutils with conda and also get 

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by rainerschoedel** [comment]
@jamienoss photutils1.0.2 appears to work
Thanks

**Comment by espinozagaleas** [comment]
I tried update photutils as @larrybradley suggested: It did not work.
I tried downgrade to photutils1.0.2 as @jamienoss suggested: It works!
Thanks.

**Comment by larrybradley** [comment]
Hmm, according to @jamienoss report about numpy 1.20 not being backwards compatible, using numpy 1.17 for the conda builds should have fixed this. 

For those getting this error with photutils 1.1.0, can you please let me know:

* What is your platform (windows, linux, OSX)?
* How are you installing photutils -- what is the exact command you are using?
* What versions of Python, Numpy, and Astropy are in the environment that you installed photutils?

**Comment by jamienoss** [comment]
Sorry, I should have also noted that downgrading photutils alone did not solve the issue, I had to also pin numpy<1.20.

It seems to me that any releases with compiled code will now need two builds - one for numpy <1.20 and another for >=1.20.

**Comment by larrybradley** [comment]
@jamienoss Did you try the new `conda-forge` version?  The updated version uses numpy 1.17 for python 3.7 and 3.8 and numpy 1.20 for python 3.9.

**Comment by jamienoss** [comment]
Nope, sorry, not yet, I'll do that today.

**Comment by rainerschoedel** [comment]
HI,

- I use Mac OS 10.15.7 
- installed photutils 1.0.2 with conda install -c astropy photutils
- for photutils 1.1.0 I used  conda install -c conda-forge photutils
- Python 3.8.3, Astropy 4.0.1post1, numpy 1.18.5
cheers

**Comment by larrybradley** [comment]
Thanks, @rainerschoedel and @jamienoss.  I just rebuilt the conda-forge binaries again, and I *think* they should work now.  Can you please try yet again?  The fixed version should have "_2" appended to the version hash, e.g.,
`conda list | grep photutils` (version/build hash in 3rd column):
<pre>
photutils                 1.1.0            py39hc89836e_2    conda-forge
</pre>

**Comment by jamienoss** [comment]
@larrybradley Yep, whatever you did it worked. 👍

**Comment by rainerschoedel** [comment]
Thanks, I think it works now.

Rainer

**Comment by larrybradley** [comment]
Thanks, all!
