### ISSUE TITLE
Test tolerance is too high for scipy 1.6

### ISSUE THREAD

**Issue by olebole** [astropy/photutils#1150]
I just got the following bug report ([Debian#980304](https://bugs.debian.org/980304)) for the photutils Debian package (1.0.1-1)  by @drew-parsons :

> Under scipy 1.6 some test results in photutils have shifted slightly and no longer match within the indicated tolerance.
>
> See debci logs, e.g. https://ci.debian.net/data/autopkgtest/testing/amd64/p/photutils/9744053/log.gz
>
> The tests affected are all in `photutils/background/tests/test_background_2d.py`
>
> The current tolerance is rtol=1e-7.
> 
> Tests should be able to pass using rtol=2e-6 or 2e-5.

**Comment by larrybradley** [comment]
Thanks, @olebole.  I changed the tolerances in #1151.  This will appear in v1.0.2, which will be released within a day or two.
