### ISSUE TITLE
installation error:  lookuperror :setuptools-scm was unable to detect version for '/Users/gggg/Downloads/photutils-master'

### ISSUE THREAD

**Issue by guosufen** [astropy/photutils#1153]
I am installing photutils, but get the following error, can someone help me? I'd be really appreciated If you could help me deal with it!
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    ext_modules=get_extensions())
  File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "//miniconda3/envs/py36rc/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/setuptools/dist.py", line 430, in __init__
    k: v for k, v in attrs.items()
  File "//miniconda3/envs/py36rc/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/setuptools/dist.py", line 721, in finalize_options
    ep(self)
  File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/Users/gggg/Downloads/photutils-master/.eggs/setuptools_scm-5.0.1-py3.6.egg/setuptools_scm/integration.py", line 26, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/Users/gggg/Downloads/photutils-master/.eggs/setuptools_scm-5.0.1-py3.6.egg/setuptools_scm/__init__.py", line 173, in _get_version
    parsed_version = _do_parse(config)
  File "/Users/gggg/Downloads/photutils-master/.eggs/setuptools_scm-5.0.1-py3.6.egg/setuptools_scm/__init__.py", line 142, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/Users/gggg/Downloads/photutils-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by larrybradley** [comment]
It appear you have conda installed, so `conda install photutils -c astropy` should work fine.

If you want to install the latest development version, use `pip install .[all,test]`.  `python setup.py install` is no longer recommended.

Please see the installation docs here:  https://photutils.readthedocs.io/en/latest/install.html

**Comment by guosufen** [comment]
Thank you very much!  I have photutils successfully installed but when i run photutils.test(), get the warnings/errors:

>>> import photutils
WARNING: leap-second auto-update failed due to the following exception: ValueError("Malformed URL: '//miniconda3/envs/py36rc/lib/python3.6/site-packages/astropy/utils/iers/data/Leap_Second.dat'",) [astropy.time.core]
>>> photutils.test()
============================= test session starts ==============================
platform darwin -- Python 3.6.12, pytest-6.2.2, py-1.10.0, pluggy-0.13.1

Running tests with photutils version 1.0.2.
Running tests in //miniconda3/envs/py36rc/lib/python3.6/site-packages/photutils.

Date: 2021-01-31T16:08:48

Platform: Darwin-18.7.0-x86_64-i386-64bit

Executable: //miniconda3/envs/py36rc/bin/python

Full Python Version: 
3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Scipy: 1.5.2
Matplotlib: 3.3.2
Cython: 0.29.21
Astropy: 4.1
scikit-image: 0.17.2
scikit-learn: 0.23.2

Using Astropy options: remote_data: none.

rootdir: //miniconda3/envs/py36rc/lib/python3.6/site-packages/photutils
plugins: hypothesis-6.1.0, arraydiff-0.3, remotedata-0.3.2, cov-2.11.1, filter-subpackage-0.1.1, asdf-2.7.2, openfiles-0.5.0, astropy-header-0.1.2, doctestplus-0.9.0, mock-3.5.1
collected 1247 items                                                           
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/runner.py", line 108, in pytest_runtest_protocol
INTERNALERROR>     ihook.pytest_runtest_logstart(nodeid=item.nodeid, location=item.location)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/compat.py", line 364, in __get__
INTERNALERROR>     value = instance.__dict__[self.func.__name__] = self.func(instance)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/nodes.py", line 589, in location
INTERNALERROR>     relfspath = self.session._node_location_to_relpath(fspath)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/main.py", line 491, in _node_location_to_relpath
INTERNALERROR>     return self._bestrelpathcache[node_path]
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/main.py", line 444, in __missing__
INTERNALERROR>     r = bestrelpath(self.path, path)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/site-packages/_pytest/pathlib.py", line 654, in bestrelpath
INTERNALERROR>     reldirectory = directory.relative_to(base)
INTERNALERROR>   File "//miniconda3/envs/py36rc/lib/python3.6/pathlib.py", line 874, in relative_to
INTERNALERROR>     .format(str(self), str(formatted)))
INTERNALERROR> ValueError: '//miniconda3/envs/py36rc/lib/python3.6/site-packages/photutils' does not start with '/miniconda3/envs/py36rc/lib/python3.6/site-packages/photutils'

============================= 3 warnings in 2.00s ==============================
<ExitCode.INTERNAL_ERROR: 3>
>>>

**Comment by larrybradley** [comment]
@guosufen None of those errors are actually coming from `photutils`.  The `photutils` tests haven't even been run yet.  Those all still look like errors coming from something wrong in your enviroment.
