### ISSUE TITLE
Fit in BasicPSFPhotometry does not change star positions

### ISSUE THREAD

**Issue by krachyon** [astropy/photutils#1163]
When trying to fit stars with an EPSF, the original guesses where not modified in any meaningful way. The fit terminated without doing much.

the issue seems to be that in `psf.models.EPSFModel.evaluate` the following block is always filling everything:
```python
if self._fill_value is not None:
    # find indices of pixels that are outside the input pixel
    # grid and set these pixels to the 'fill_value':
    invalid = (((xi < 0) | (xi > (self._nx - 1)
                            / self.oversampling[0])) |
               ((yi < 0) | (yi > (self._ny - 1)
                            / self.oversampling[1])))
    evaluated_model[invalid] = self._fill_value
```
It looked to me that the coordinates where shifted in the wrong direction from origin,
so i tried replacing the `Shifts` added to the model in `prepare_psf_model()` with

```python
class InverseShift(models.Shift):
    @staticmethod
    def evaluate(x, offset):
        return x - offset
```
and this seemed to solve the issue. 

I'm a bit hesitant if this is really the core issue here or if I'm missing anything.  The tests pass with the modification on my current branch (https://github.com/krachyon/photutils/tree/working). If this is reproducible for others and does not break anything else I can turn this into a PR....

Example to reproduce, single star in image with known PSF: 

```python
from astropy.convolution import Gaussian2DKernel, convolve_fft
from photutils.psf import EPSFModel, prepare_psf_model
import numpy as np
from astropy.table import Table
from astropy.modeling.models import Gaussian2D
from photutils.psf import *

σ = 1
img_size = 512
names = ('x_0', 'y_0', 'flux_0')

# star position
x_float = np.array([400.])
y_float = np.array([300.])

data = np.zeros((img_size, img_size))

# distribute point source over neighbour pixels
x, x_frac = np.divmod(x_float, 1)
y, y_frac = np.divmod(y_float, 1)
x, y = x.astype(int), y.astype(int)
data[y, x] = (1 - x_frac) * (1 - y_frac)
data[y + 1, x] = (x_frac) * (1 - y_frac)
data[y, x + 1] = (1 - x_frac) * (y_frac)
data[y + 1, x + 1] = y_frac * x_frac

# convolve image to simulate PSF
kernel = Gaussian2DKernel(σ, σ)
image = convolve_fft(data, kernel)
input_table = Table((x_float.ravel(), y_float.ravel(), 1000 * np.ones(x.size)), names=names)

# build EPSF that matches exactly
# +0.1 for including end value; 0.5 -> 2x oversampling
x, y = np.mgrid[-2:2.1:0.5, -2:2.1:0.5]
epsf_data = Gaussian2D(x_stddev=σ, y_stddev=σ)(x, y)

epsf = prepare_psf_model(
    EPSFModel(epsf_data, flux=1, normalize=False, oversampling=2),
    renormalize_psf=False, fluxname='flux')

# fit should not touch this, does not touch it
basic_phot = BasicPSFPhotometry(group_maker=DAOGroup(2),
                                bkg_estimator=None, psf_model=epsf,
                                fitshape=[5, 5])
exact_result = basic_phot(image, input_table)
#assert_allclose(input_table['x_0'], exact_result['x_fit'])
#assert_allclose(input_table['y_0'], exact_result['y_fit'])

perturbed_input = input_table.copy()
perturbed_input['x_0'] += 0.1
perturbed_input['y_0'] += 0.1

# fit should improve this, assertions fail with regular shift, works with InverseShift
result = basic_phot(image, perturbed_input)
#assert_allclose(input_table['x_0'], result['x_fit'])
#assert_allclose(input_table['y_0'], result['y_fit'])
```

**Comment by emirkmo** [comment]
Any updates on this? Is it still working for you? I've sometimes observed an improvement from keeping the positions fixed. I thought this was about background objects but perhaps it's actually a result of this?

**Comment by krachyon** [comment]
What I observed on generated test images was exactly that, if `init_guesses` is passed to `BasicPSFPhotometry` you'll get them back almost exactly as you put them in, with some noise added when the fitter tried to find some gradient on a flat array.

If you don't pass init_guesses I think you'll get back whatever the `finder` spits out mostly unchanged. I think the easiest way to verify if it's also happening to you is to forgo the `finder` argument to `Photometry` and see if your (imperfect) initial guesses are changed meaningfully for your data. 
If that's the case, maybe my branch works better for you, would be nice to have an independent verification that it works and does not blow anything else up...

**Comment by emirkmo** [comment]
Right, I actually pre-compute star locations and always pass init_guesses as accurately as possible. Will give your suggestion a try and get back to you.

**Comment by krachyon** [comment]
To clarify because I just failed to reproduce this in a slightly different context: This bug is only ocuring if you call `prepare_psf_model` without `xname` and `yname`. So if you create an `EPSFModel` or anything else that has the parameters `x_0, y_0` it will use those instead of adding a `Shift` and work fine.

**Comment by krachyon** [comment]
Should be fixed with the merged PR now.
