### ISSUE TITLE
build_ellipse_model is very slow

### ISSUE THREAD

**Issue by nandinihazra** [astropy/photutils#1168]
Hello Ivo, Larry, Brigitta and others

My advisor Michele Cantiello ( @cantiello) and I have been working on ~3500x3500 pixel FITS images of bright, extended elliptical galaxies in which we fit elliptical isophotes upto maximum semi-major axis lengths of about 500-600 pixels. However, even though the fit itself takes about 20-40 seconds to complete, the build_ellipse_model takes several minutes to run and generate the model image. We spoke to Ivo briefly about this and it seems that the issue might already be on your radar. Since it is posing a significant problem for us at the moment we would really appreciate if you could take a look at it again, or let us know if we can optimise our runs better to get around the bottleneck.

Thank you
Nandini Hazra

**Comment by larrybradley** [comment]
@ibusko

**Comment by larrybradley** [comment]
Ivo has since retired and unfortunately was the author (and expert) for this code.  There is a PR to speed up `build_ellipse model`. Thanks!
