### ISSUE TITLE
Centroid_sources with oversaturated pixels

### ISSUE THREAD

**Issue by TSA26** [astropy/photutils#1179]
Can centroid_sources() accurately detect centroid in case of oversaturated pixels in the center of the source?
Oversaturated pixels occupy roughly 70 % of the source.
Is it possible to ignore those pixels and use only edges to determine the center of the source?

**Comment by larrybradley** [comment]
@TSA26 The only thing to try would be to create a boolean mask array of the saturated pixels and pass that into the `mask` keyword.

**Comment by TSA26** [comment]
Thank you for suggestion.
I already tried creating mask for those pixels.
Is it possible to interpolate those pixels based on values of pixels on the edge?

**Comment by larrybradley** [comment]
It's not really possible to compute an accurate centroid if the center values are saturated.  Those central pixels are where the profile is peaked, and thus provide the most weight for the centroid.  I don't know how you could interpolate to recover those pixels.
