### ISSUE TITLE
HTTP Error 404: Not Found Dataset not found

### ISSUE THREAD

**Issue by TSA26** [astropy/photutils#1181]
`from photutils import datasets 
hdu = datasets.load_simulated_hst_star_image()   
data = hdu.data  `

Code above results with an error from the title.
It looks like it cannot reach database.

![Screenshot_2021-03-11 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/49925298/110757330-8cb8a000-824b-11eb-99cb-fc1cde54fbfc.png)

**Comment by larrybradley** [comment]
Thanks, @TSA26.  This was caused by renaming the default branch in the `photutils-datasets` from master to main.  I've reverted that change.
