### ISSUE TITLE
Overlapping sources

### ISSUE THREAD

**Issue by TSA26** [astropy/photutils#1183]
Hi.
This is not an issue, I just need help, so I thought maybe to ask here.
If it doesn't belong here, delete it, please.
I have LEDs on the image some of which are partially overlapped with reflecting square.
The majority of the square is oversaturated(65k) and the LED center(roughly 70%) also.
I want to know how can I distinguish these two sources because I need to precisely measure the centroid of LED.
I tried with Source Deblending, but the problem is both of these sources have oversaturated pixels and it doesn't work well.
You can see in the picture below, two LEDs and mentioned reflective square.
Thank you in advance.
![a](https://user-images.githubusercontent.com/49925298/111074242-67918f00-84e2-11eb-9084-a4e7792af5b6.png)

**Comment by larrybradley** [comment]
@TSA26 The deblending algorithm requires a saddle point between the two sources.  Unfortunately, that will not work here.
