### ISSUE TITLE
TypeError: unexpected keyword argument 'coverage_mask'

### ISSUE THREAD

**Issue by anavudragovic** [astropy/photutils#1200]
Photutils: Background2D
When I include coverage_mask=coverage_mask, fill_value=0.0 I get an error. 

Then I run, as recommended: 
import photutils
photutils.test()
And got an error: 
---------------------------------------------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-74-85e28d12fd87>", line 1, in <module>
    photutils.test()

  File "/opt/anaconda3/lib/python3.8/site-packages/astropy/tests/runner.py", line 265, in test
    return runner.run_tests(**kwargs)

  File "/opt/anaconda3/lib/python3.8/site-packages/astropy/tests/runner.py", line 610, in run_tests
    return super().run_tests(**kwargs)

  File "/opt/anaconda3/lib/python3.8/site-packages/astropy/tests/runner.py", line 207, in run_tests
    self._has_test_dependencies()  # pragma: no cover

  File "/opt/anaconda3/lib/python3.8/site-packages/astropy/tests/runner.py", line 187, in _has_test_dependencies
    raise RuntimeError(

RuntimeError: Test dependencies are missing: pytest_remotedata. You should install the 'pytest-astropy' package (you may need to update the package if you have a previous version installed, e.g., 'pip install pytest-astropy --upgrade' or the equivalent with conda).
---------------------------------------------------------------------------------------------------

Then I did as recommended again:
pip install pytest-astropy --upgrade

But the error remains; Background2D doesn't recognize coverage_mask.

**Comment by larrybradley** [comment]
The `coverage_mask` keyword was added to `Background2D` in photutils version 1.0.0.  You likely need to update your photutils version:  `pip install photutils -- upgrade`.  You can check the photutils version from within python:

```python
>>> import photutils
>>> photutils.__version__
```

**Comment by anavudragovic** [comment]
Thank you, this solved the problem.

**Comment by anavudragovic** [comment]
Thank you, the problem is solved.
--------------------------------------------- 
Ana Vudragović
Research Associate
Astronomical Observatory
Volgina 7, 11060 Belgrade, Serbia
