### ISSUE TITLE
"valueError: "b_out" must be greater than "b_in"." thrown wrongly for EllipticalAnnulus in photutils > 0.7

### ISSUE THREAD

**Issue by NikkiZabel** [astropy/photutils#1208]
Upgraded to Python 3.8 and photutils 1.1.0 and suddenly my code was throwing this error in the line "aperture = EllipticalAnnulus(centre, a_in, a_out, b_out, theta)". Have printed a_in, a_out, b_in, and b_out and definitely b_out > b_in. Downgraded to 0.7.2 and code works fine.

**Comment by larrybradley** [comment]
@NikkiZabel, an additional (and optional) `b_in` parameter was added between version 0.7.2 and 1.1.0.  The calling sequence is now `EllipticalAnnulus(position, a_in, a_out_, b_out, b_in, theta)`, where `b_in` and `theta` are optional keyword arguments.  For your code, you can either input `theta` as a keyword argument, e.g. `EllipticalAnnulus(centre, a_in, a_out, b_out, theta=theta)` (recommended) or you could input `None` for `b_in`:  `EllipticalAnnulus(centre, a_in, a_out, b_out, None, theta`)
