### ISSUE TITLE
Projection of apertures along a dimension: photutils->3D spectrum extraction

### ISSUE THREAD

**Issue by keflavich** [astropy/photutils#121]
This is a feature request for IFU and Spectral Cube purposes.  A wrapper to extract photometry from each channel in a cube (and preserve the relevant WCS information) would be very helpful.

For radio cubes, this is generally trivial (i.e., photutils probably isn't even needed), but for IFUs you often want to weight by the PSF to do "optimal" spectral extraction for stars.

**Comment by larrybradley** [comment]
@keflavich Aperture masks can now be created (added in #453), which you could broadcast along the 3rd dimension.  This is similar to what is now being added to `regions`.

Basic docs:
http://photutils.readthedocs.io/en/stable/photutils/aperture.html#aperture-masks

I need to expand the docs, but essentially there is a `.to_mask()` method on `PixelAperture` objects that returns an `ApertureMask` object (actually a *list* of `ApertureMask` objects, one for each aperture position).  You can use the `ApertureMask` `to_image()` method, if you want a mask `ndarray` image that you can broadcast.
