### ISSUE TITLE
Possibly Excessive resource usage in PSF Photometry

### ISSUE THREAD

**Issue by krachyon** [astropy/photutils#1217]
On some images with high crowding, applying the EPSF workflow takes a very long time or even crashes.

The reason is that subsequent combinations of an astropy model require quite a bit of memory and time. This is triggered in `*PSFPhotometry.get_grouped_psf_model` if too many stars are combined into a group. Choosing the separation criterion for the group_maker poorly can result in a crash due to limited recursion depth. Even for more reasonable groups the fit gets bogged down quite heavily as for an evaluation of the compound model the execution apparently recurses through the whole model tree's (more a chain in this case) `evaluate()` methods.

I'm not sure if this issue is easily solved with the current model framework, but spending more than 2GB of RAM just to represent ~1000 2D-Gaussians seems a little excessive. I'd guess that constructing a flat model for the compound EPSF with a single copy of the array could yield a significant speedup and sidestep the parameter_name issues (https://github.com/astropy/photutils/pull/1135)

From my limited experience with the workflow large groups (>8 stars) don't seem to produce a reliably useful fit anyways, so maybe it would be enough to limit the maximum group size and suggest a workflow/parameters where the brightest star in a given group is fit first and iteratively subtracted out.

Reproduction:

```python
from astropy.modeling.functional_models import Gaussian2D
from resource import getrusage, RUSAGE_SELF
import time
import copy

# analytic model chosen for brevity, an EPSF model makes memory usage
# a lot worse as the underlying array is copied for each submodel
model_template = Gaussian2D()
model = model_template.copy()

start = time.time()
for i in range(1000):
    model += model_template.copy()
    
    print(f'loop {i}: {getrusage(RUSAGE_SELF).ru_maxrss/1024:.2f} MB of RAM used, {time.time()-start:.2f}s passed')
```

output (16 GiB RAM, Linux 5.12.5-arch1-1, Python 3.9.5, astropy==4.2.1):

```
loop 0: 77.09 MB of RAM used, 0.00s passed
loop 1: 77.09 MB of RAM used, 0.00s passed
loop 2: 77.09 MB of RAM used, 0.00s passed
loop 3: 77.09 MB of RAM used, 0.00s passed
[...]
loop 66: 87.89 MB of RAM used, 0.10s passed
loop 67: 88.14 MB of RAM used, 0.10s passed
loop 68: 88.40 MB of RAM used, 0.11s passed
loop 69: 88.66 MB of RAM used, 0.11s passed
[...]
loop 988: 2466.21 MB of RAM used, 19.43s passed
loop 989: 2471.36 MB of RAM used, 19.46s passed
loop 990: 2476.78 MB of RAM used, 19.49s passed
loop 991: 2482.19 MB of RAM used, 19.53s passed
Traceback (most recent call last):
  File "repro.py", line 11, in <module>
    model += model_template.copy()
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 58, in <lambda>
    return lambda left, right: CompoundModel(oper, left, right, **kwargs)
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 2627, in __init__
    self._map_parameters()
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 3125, in _map_parameters
    self._make_leaflist()
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 2894, in _make_leaflist
    make_subtree_dict(self, '', tdict, leaflist)
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 3551, in make_subtree_dict
    make_subtree_dict(tree.left, nodepath+'l', tdict, leaflist)
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 3551, in make_subtree_dict
    make_subtree_dict(tree.left, nodepath+'l', tdict, leaflist)
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 3551, in make_subtree_dict
    make_subtree_dict(tree.left, nodepath+'l', tdict, leaflist)
  [Previous line repeated 989 more times]
  File "/usr/lib/python3.9/site-packages/astropy/modeling/core.py", line 3547, in make_subtree_dict
    if not hasattr(tree, 'isleaf'):
RecursionError: maximum recursion depth exceeded

```

**Comment by larrybradley** [comment]
The PSF photometry tools have been rewritten, but this is still an issue (#1808) when large groups are constructed (needing large compound models).  Ultimately it needs to be addressed upstream in Astropy as was reported in https://github.com/astropy/astropy/issues/16701.  I'm going to keep #1808 open and close this issue.  They are the same, but #1808 uses the new tools.  Thanks.
