### ISSUE TITLE
ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'

### ISSUE THREAD

**Issue by SophicSansan** [astropy/photutils#1225]
Does anyone know how to solve this problem?  any help would be appriciated!

in my pycharm i get this error:

 - Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
 - Type 'copyright', 'credits' or 'license' for more information
 - IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.
 - PyDev console: using IPython 7.26.0
 - File "\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
 -     exec(code_obj, self.user_global_ns, self.user_ns)
 -   File "<ipython-input-2-4dc67501548e>", line 1, in <module>
 -     runfile('D:/Astro_Image_Photometry/User_Interface.py', wdir='D:/Astro_Image_Photometry')
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
-     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
-     exec(compile(contents+"\n", file, 'exec'), glob, loc)
-   File "D:/Astro_Image_Photometry/User_Interface.py", line 10, in <module>
 -     from ApeturePhot import *
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
 -   File "D:\Astro_Image_Photometry\ApeturePhot.py", line 2, in <module>
-     from photutils import datasets
-   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
 -   File "D:\Astro_Image_Photometry\photutils\__init__.py", line 19, in <module>
 -     from .aperture import *  # noqa
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
 -   File "D:\Astro_Image_Photometry\photutils\aperture\__init__.py", line 7, in <module>
 -     from .circle import *  # noqa
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
 -   File "D:\Astro_Image_Photometry\photutils\aperture\circle.py", line 15, in <module>
 -     from ..geometry import circular_overlap_grid
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
-   File "D:\Astro_Image_Photometry\photutils\geometry\__init__.py", line 5, in <module>
 -     from photutils.geometry.circular_overlap import circular_overlap_grid
 -   File "D:\Program Files (x86)\pyCharm\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
 -     module = self._system_import(name, *args, **kwargs)
 - ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'

**Comment by larrybradley** [comment]
How are you installing `photutils`?  The error message suggests that you are trying to install `photutils` from the source distribution, which requires Cython and a C compiler -- `circular_overlap` is a compiled module.  See the install docs https://photutils.readthedocs.io/en/latest/install.html for more details.

**Comment by SophicSansan** [comment]
> How are you installing `photutils`? The error message suggests that you are trying to install `photutils` from the source distribution, which requires Cython and a C compiler -- `circular_overlap` is a compiled module. See the install docs https://photutils.readthedocs.io/en/latest/install.html for more details.

 indeed, I install 'photutils' and Cython according to https://photutils.readthedocs.io/en/latest/install.html.  I‘ve tried both pip and conda, but they all have the same problem. By the way, my OS is Windows and 'photutils test()' give the result as follows:


================================================ 1234 passed, 66 skipped, 2 xfailed, 53 warnings in 133.51s (0:02:13) ================================================
<ExitCode.OK: 0>


Thanks for having a look into this!

**Comment by SophicSansan** [comment]
runfile('D:/Astro_Image_Process/User_Interface.py', wdir='D:/Astro_Image_Process')
Reloaded modules: display, globalvar, fits_io, photutils.version, photutils._astropy_init, photutils.aperture.bounding_box, photutils.aperture.attributes, photutils.aperture._photometry_utils, photutils.utils.check_random_state, photutils.utils.colormaps, photutils.utils.convolution, photutils.utils.errors, photutils.utils.exceptions, photutils.utils.interpolation, photutils.utils.misc, photutils.utils.stats, photutils.utils, photutils.utils._wcs_helpers, photutils.aperture.core, photutils.aperture.mask
Traceback (most recent call last):

  File "D:\Astro_Image_Process\User_Interface.py", line 10, in <module>
    from ApeturePhot import *

  File "D:\Astro_Image_Process\ApeturePhot.py", line 2, in <module>
    from photutils import datasets

  File "D:\Astro_Image_Process\photutils\__init__.py", line 19, in <module>
    from .aperture import *  # noqa

  File "D:\Astro_Image_Process\photutils\aperture\__init__.py", line 7, in <module>
    from .circle import *  # noqa

  File "D:\Astro_Image_Process\photutils\aperture\circle.py", line 15, in <module>
    from ..geometry import circular_overlap_grid

  File "D:\Astro_Image_Process\photutils\geometry\__init__.py", line 6, in <module>
    from .circular_overlap import *  # noqa

ModuleNotFoundError: No module named 'photutils.geometry.circular_overlap'

**Comment by SophicSansan** [comment]
I've solved it！Thanks!

**Comment by AmitEisinger** [comment]
Faced the same issue.
Tried to convert my code to EXE using PyInstaller and once I tried running the EXE I received the error message mentioned above.

**Comment by SophicSansan** [comment]
> Facing the same issue.
> Tried to convert my code to EXE using PyInstaller and once I tried running the EXE I received the error message mentioned above.

My error is due to my project has the 'photutils' package and my OS also has been installed 'photutils', they have the same name. I just need delete the one in my project.

**Comment by Lynne-Du-98** [comment]
> > Facing the same issue.
> > Tried to convert my code to EXE using PyInstaller and once I tried running the EXE I received the error message mentioned above.
> 
> My error is due to my project has the 'photutils' package and my OS also has been installed 'photutils', they have the same name. I just need delete the one in my project.

I met the same problem and I think your solution may work for me. But I don't know what "my project has the 'photutils' package" means and how to "delete the one in my project". Could you give a concrete example? 
Thank you very much!

**Comment by SophicSansan** [comment]
> > > Facing the same issue.
> > > Tried to convert my code to EXE using PyInstaller and once I tried running the EXE I received the error message mentioned above.
> > 
> > 
> > My error is due to my project has the 'photutils' package and my OS also has been installed 'photutils', they have the same name. I just need delete the one in my project.
> 
> I met the same problem and I think your solution may work for me. But I don't know what "my project has the 'photutils' package" means and how to "delete the one in my project". Could you give a concrete example? Thank you very much!

you just need to delete the photutils package in your project, not OS.

**Comment by Lynne-Du-98** [comment]
> 

Ok, I will have a try. Thanks again!

**Comment by Lynne-Du-98** [comment]
I made it! The error here is caused by a python documentation named "photutils.py" under the same path. After I removed it, 
 everything works fine.

**Comment by tinhle01** [comment]
Hi, everyone
I have the same problem, I try to find "photutils.py" like you said but it does not exist.

**Comment by astropilgrim** [comment]
> 

Hi, tinhle01
What is the content of the error reported by your code? The error I have met is "ModuleNotFoundError: No module named 'photutils.aperture'; 'photutils' is not a package", and then I found the file associated with the error by using the command "locate". After I removed it, everthing goes Okay.
 I hope these may inspire some ideas about solving your problem.

**Comment by tinhle01** [comment]
Hi astropilgrim,
Thank you for your response. My problem is when I try to test photutils and I get the error, you can see the picture below.
![Screenshot from 2022-09-22 23-37-02](https://user-images.githubusercontent.com/66545412/191811497-232c5793-9521-4da3-b77f-7278a970842c.png)
