### ISSUE TITLE
Different centroids by IRAFStarFinder and DAOStarFinder

### ISSUE THREAD

**Issue by mcara** [astropy/photutils#1243]
I have an image with a sharp simulated PSF. I used three methods to find the center of the PSF: `drizzlepac.tweakreg`, `IRAFStarFinder`, and `DAOStarFinder`. First two give almost indistinguishable (but not identical) results. The last one is way off.

I have attached an image that shows the centroids obtained with these methods. On the left side is the "original" data image and on the right side is the density enhanced image (data convolved with the kernel). I chose a kernel with FWHM=3 in order to enhance the effect.

My understanding is that DAOFIND looks for peaks in the density enhanced image. Looking at that image I do not see how DAOFIND algorithm would find a peak at the green marker and miss the real, strong, peak.

Is this a bug in the implementation of the DAOFIND algorithm? Thanks!

<img width="800" alt="comparison" src="https://user-images.githubusercontent.com/5985250/133020232-9318bccd-33cc-44dd-9883-84acfe937611.png">

**Comment by larrybradley** [comment]
I've discussed this issue offline with @mcara.  In summary, the center of the star was rejected because its `sharpness` was larger than the `sharphi` limit.  The center of the star is found if `sharphi` is increased.

**Comment by mcara** [comment]
What is the maximum possible value for the `sharphi` parameter? For example, what would the sharpness be for a delta-function PSF?
