### ISSUE TITLE
aperture_photometry does not understand astropy regions

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1261]
I have astropy `regions` object and I was hoping I can just pass it in as aperture for `photutils.aperture.aperture_photometry` but it failed with the following error:

```
.../photutils/aperture/photometry.py in aperture_photometry(data, apertures, error, mask, method, subpixels, wcs)
    183     # convert sky to pixel apertures
    184     skyaper = False
--> 185     if isinstance(apertures[0], SkyAperture):
    186         if wcs is None:
    187             raise ValueError('A WCS transform must be defined by the input '

TypeError: 'EllipsePixelRegion' object is not subscriptable
```

https://github.com/astropy/photutils/blob/17192d6ee4517514187fc01c7624fe6eb4b0e233/photutils/aperture/photometry.py#L184

I saw a similar discussion in #684 from 2018 though I am not looking for deprecating aperture. I am just too lazy to write translation layers from `regions` to `photutils` objects.

Is there any plan at all for `photutils` to understand `regions`?

**Comment by larrybradley** [comment]
Feature request in #1811

**Comment by pllim** [comment]
also https://github.com/astropy/photutils/pull/2009
