### ISSUE TITLE
Enable specifying x and y peak positions for `centroid_quadratic()` in `centroid_sources()`

### ISSUE THREAD

**Issue by vandalt** [astropy/photutils#1270]
Hello,

I have a use case where I'm trying to find the centroid of a a shape in a crowded region, and the maximum pixel falls on the edge of the image. When I use `centroid_quadratic` directly, I am able to specify the `xpeak` and `ypeak` arguments to fit the centroid properly. However, when using it with `centroid_sources()`, there is no way (in my understanding) to pass `xpeak` and `ypeak`, so I get [a warning  that the max is on the edge and no fit will be perfomed](https://github.com/astropy/photutils/blob/main/photutils/centroids/core.py#L193). I think it would be good to either have the option to specify extra keyword arguments for `xpeak` and `ypeak` in `centroid_sources()` or to use `xpos` and `ypos` directly (but this last option might be less clear and flexible).

If there is interest for this, I would be happy to send a PR with the additions !

**Comment by larrybradley** [comment]
Thanks, @vandalt!  I added this feature in https://github.com/astropy/photutils/pull/1276.  It will appear in the 1.3.0 release, which will happen next week.
