### ISSUE TITLE
SourceCatalog.circular_photometry using detection_cat centroids

### ISSUE THREAD

**Issue by jzabl** [astropy/photutils#1272]
When the `SourceCatalog` gets initiated with a `detection_cat`, I wasn't sure which centroids are used when running `SourceCatalog.circular_photometry()`. 
It could in principle be the centroids from the measurement image (=data provided to SourceCatalog)  or those from the `detection_cat`. 
After checking the code (and some outputs) it seems to be the centroids from the measurement image. In my use case I would need the centroids from the detection image (to do matched photometry). I would think this is not an uncommon use case. [I understand that the `detection_cat` centroids are used for the Kron apertures, but I am here not interested in Kron apertures]
 
I would suggest an option that allows  to switch to the `detection_cat`  centroids. This should be rather simple to implement, if I am not overlooking something. Something along the lines?

```      
def circular_aperture(self, radius, use_detection_centroids=False):
        
    ...

    if use_detection_centroids and self._detection_cat is not None:
        xcentroid = self._detection_cat.xcentroid
        ycentroid = self._detection_cat.ycentroid
    else:
        xcentroid = self.xcentroid
        ycentroid = self.ycentroid
    ...
    for (xcen, ycen) in zip(xcentroid, ycentroid):

    ...

def circular_photometry(self, radius, use_detection_centroids=False):
    
    ...

    apertures = self.circular_aperture(radius,
            use_detection_centroids=use_detection_centroids)

    ...

    if use_detection_centroids and self._detection_cat is not None:
        xcentroid = self._detection_cat.xcentroid
        ycentroid = self._detection_cat.ycentroid
    else:
        xcentroid = self.xcentroid
        ycentroid = self.ycentroid

    for (label, aperture, xcen, ycen, bkg) in zip(
                self.labels, apertures, xcentroid, ycentroid,
                self._local_background):

        ....
Does this make sense?
Or is the functionality that I am describing already implemented, and I just missed it in the documentation? 

(I guess, in principle the result can also be obtained by directly using `photutils.aperture.aperture_photometry`; the disadvantage is that there the `apermask_method` parameter is not directly available to correct for blended objects)

**Comment by larrybradley** [comment]
@jzabl This was already fixed back in https://github.com/astropy/photutils/pull/1264.  It will appear in the next release (possibly next week).
