### ISSUE TITLE
photutils.segmentation.detect_sources v1.3.0 now throws KernelSizeError

### ISSUE THREAD

**Issue by gabicca** [astropy/photutils#1282]
After upgrading to photutils==1.3.0, `segmentation.detect_sources` produces a `KernelSizeError` for code which used to run without any errors.

Here is an example test (note, here image is all 0s, but in original there were non-zero values, but this seems irrelevant to the current problem):

```
def test_photutils():
    from astropy.convolution import Gaussian2DKernel
    from photutils import segmentation

    sigma = 1.2739827004320285
    kernel = Gaussian2DKernel(sigma, x_size=2, y_size=2)
    kernel.normalize()

    image = numpy.zeros((512, 512))

    segments = segmentation.detect_sources(
        image, 0.3, npixels=5, filter_kernel=kernel
    )
```

When run with photutils==1.2.0, code passes.
When run with photutils==1.3.0, the following error is produced:

```
>       segments = segmentation.detect_sources(
            image, 0.3, npixels=5, filter_kernel=kernel
        )
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lib/python3.9/site-packages/astropy/utils/decorators.py:547: in wrapper
    return function(*args, **kwargs)
lib/python3.9/site-packages/photutils/segmentation/detect.py:395: in detect_sources
    return _detect_sources(data, (threshold,), npixels, kernel=kernel,
lib/python3.9/site-packages/photutils/segmentation/detect.py:247: in _detect_sources
    data = convolve(data, kernel, mask=mask, normalize_kernel=True)
lib/python3.9/site-packages/astropy/nddata/decorators.py:246: in wrapper
    result = func(data, *args, **kwargs)
/lib/python3.9/site-packages/astropy/convolution/convolve.py:268: in convolve
    raise_even_kernel_exception()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def raise_even_kernel_exception():
>       raise KernelSizeError("Kernel size must be odd in all axes.")
E       astropy.convolution.utils.KernelSizeError: Kernel size must be odd in all axes.
```

Python version: 3.9.7

I know that this occurs now because `detect_sources` now uses `astropy.convolution.convolve.convolve`, but can someone please take a look and explain why this is an accepted behaviour and if it isn't, could you please add a fix?

**Comment by larrybradley** [comment]
@gabicca This error is now raised because the code uses the `astropy` convolve function instead of the `scipy` convolve function.  The `astropy` convolve function is more strict and raises an error if the kernel is not odd in all dimensions.  That is a good thing.  If you convolve an image with an even sized kernel, you will shift the position of the sources (resulting in incorrect centroids) because the kernel does not have a well-defined center pixel.

A simple example:

```python
>>> from astropy.convolution import Gaussian2DKernel
>>> sigma = 1.2739827004320285
>>> kernel_even = Gaussian2DKernel(sigma, x_size=2, y_size=2)
>>> kernel_even.normalize()
>>> kernel_odd = Gaussian2DKernel(sigma, x_size=3, y_size=3)
>>> kernel_odd.normalize()

>>> from scipy.ndimage import convolve
>>> size = 5
>>> cen = (size - 1) // 2
>>> data = np.zeros((size, size))
>>> data[cen, cen] = 1.
>>> convdata_even = convolve(data, kernel_even)
>>> convdata_odd = convolve(data, kernel_odd)
```

![kernel_size](https://user-images.githubusercontent.com/4992897/148569840-65e538ac-5612-4e49-99c0-130d49c44a34.jpg)

**Comment by gabicca** [comment]
Hi @larrybradley,

Thank you for your reply, I really appreciate it! That means we will have to rewrite our code. It is a test which now fails, so hopefully the solution is easy and the code isn't affected.

Thanks again, the issue can be closed.
