### ISSUE TITLE
Question: Use of existing noise maps 

### ISSUE THREAD

**Issue by rainerschoedel** [astropy/photutils#1284]
I am currently learning photutils to benchmark it against StarFinder in Adaptive Optics images.

If I have already a noise map that provides me with the empirically estimated noise for each pixel of an image, is there an easy way to use it? Thanks.

**Comment by larrybradley** [comment]
@rainerschoedel The star finders in `photutils` have a `threshold` parameter, which defines the image value above which sources are detected.  Typically, the threshold is defined relative to a background-only noise map, e.g., 3-sigma above the background.  That will give you a threshold image, but most of the star finders require `threshold` to be a scalar float.  So you will need to take a mean/median of your threshold image to get a `threshold` value.  The `find_peaks` function (https://photutils.readthedocs.io/en/latest/api/photutils.detection.find_peaks.html#photutils.detection.find_peaks) is the only one where you can input a `threshold` image.

**Comment by rainerschoedel** [comment]
Thank you!
