### ISSUE TITLE
Background2D pad bug

### ISSUE THREAD

**Issue by yas-nakajima** [astropy/photutils#1289]
Hi. I think `Background2D` could fail when using the `pad` edge method. 
I expected `bkg2.background_mesh.shape` to be (9, 16) in the following. 

```
data1 = np.ones((128, 256))
data2 = np.ones((129, 256))
bkg1 = Background2D(data1, (16, 16))
bkg2 = Background2D(data2, (16, 16))
print(bkg1.background_mesh.shape, bkg2.background_mesh.shape)
```
```
(8, 16) (9, 17)
```

I'm using photutils==1.3.0 

Thanks

**Comment by larrybradley** [comment]
@yas-nakajima Many thanks for reporting this bug!  It is fixed by https://github.com/astropy/photutils/pull/1292 and will appear in the next release.

**Comment by yas-nakajima** [comment]
thanks!
