### ISSUE TITLE
Clarification on Stable, is it V1.3? + Request for dependency version being mentioned in changelog or in "what's new".

### ISSUE THREAD

**Issue by emirkmo** [astropy/photutils#1301]
It's that time of the year again where our photometry pipeline would like to bump our outdated photutils dependency (current V1.1.0).

Is stable V1.3 or V1.2? Also, could the very nice changelog include changes to the build dependency requirements or could this be added to somewhere in Dev? (Helps with updating locked dependencies).

I think we can safely go to V1.2 with zero code changes from V1.1 (we mainly use psf, EPSF builder), and to V1.3 by making sure we handle the ValueErrors for misconfigured x/y guesses. But which one is "stable"? 

And do the versions have different dependency requirements (I'll look up the answer to the second question).

**Comment by larrybradley** [comment]
@emirkmo We list any updated dependencies in the changelog under the "General" section, e.g.:
  * 1.4.0: https://photutils.readthedocs.io/en/latest/changelog.html#unreleased
  * 1.2.0: https://photutils.readthedocs.io/en/latest/changelog.html#id7
  * 1.1.0:  https://photutils.readthedocs.io/en/latest/changelog.html#id12

There weren't any dependency changes for 1.3.0.  The next release, 1.4.0, will occur this week.

The last changes to the PSF-fitting tools were in 1.2.0.  I'm going to be working on those tools for the 1.5.0 release, so I expect some updates in that release.

Also, all releases are stable.  There are times where bug fixes may result in different outputs, but those outputs are intended to be correct.  For API changes, we first deprecate with deprecation warnings for at least one release cycle before making the final change in the following release to prevent surprising breaking changes.

**Comment by larrybradley** [comment]
@emirkmo 1.4.0 was released on 3/25.  Please reopen if you have additional questions.
