### ISSUE TITLE
SourceCatalog: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by andreok** [astropy/photutils#1302]
Hello,

I'm trying to extract some source properties using the photutils.segmentation.SourceCatalog, however I'm getting the following error for properties corresponding to ADU counts:
`---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
/var/folders/t2/pdxc8twj5q7c1mfhc61y5ts40000gw/T/ipykernel_28748/4271812969.py in <module>
    182         print(cat_subset.orientation)
    183         source_angle.append(cat_subset.orientation)
--> 184         print(cat_subset.max_value)
    185         source_peak.append(cat_subset.max_value)
    186         print(cat_subset.fwhm)

~/anaconda3/lib/python3.7/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    756                 return val
    757             else:
--> 758                 val = self.fget(obj)
    759                 obj.__dict__[self._key] = val
    760                 return val

~/anaconda3/lib/python3.7/site-packages/photutils/segmentation/catalog.py in _decorator(*args, **kwargs)
     44     @functools.wraps(method)
     45     def _decorator(*args, **kwargs):
---> 46         result = method(*args, **kwargs)
     47         try:
     48             return (result[0] if args[0].isscalar and len(result) == 1

~/anaconda3/lib/python3.7/site-packages/photutils/segmentation/catalog.py in max_value(self)
   1338         """
   1339         values = np.array([np.max(array) for array in self._data_values])
-> 1340         values -= self._local_background
   1341         if self._data_unit is not None:
   1342             values <<= self._data_unit

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'`

It looks like the image data from my FITS file has type dtype('float64'), but the SourceCatalog expects the data as dtype('uint16')?

Thanks,
Andre

**Comment by larrybradley** [comment]
@andreok Many thanks for reporting this issue.  This `UFuncTypeError` error is raised because a float array is being subtracted from an integer array.  That is caused because your input `data` to `SourceCatalog` is actually integer type, when it expects a float type.  Here's a simple example to reproduce the error:

```python
from photutils.segmentation import SegmentationImage, SourceCatalog

# integer dtype
data = np.zeros((25, 25), dtype=np.uint16)
data[8:16, 8:16] = 10

segmdata = np.zeros((25, 25))
segmdata[8:16, 8:16] = 1
segm = SegmentationImage(segmdata)

cat = SourceCatalog(data, segm, localbkg_width=3)
print(cat.min_value)
```
which results in:
```
UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
```

If you change the input to float, it works:
```python
>>> cat = SourceCatalog(data.astype(float), segm, localbkg_width=3)
>>> print(cat.min_value)
10
```

I've fixed this issue in #1312 so that if one inputs a `int` `data` array, `SourceCatalog` will no longer raise the `UFuncTypeError`.  That fix will appear in the next photutils release, which will occur next week.
