### ISSUE TITLE
Issue with find_peaks when using centroids.centroid_2dg as centroid_func

### ISSUE THREAD

**Issue by chioettop** [astropy/photutils#1307]
Hi,

previous to version 1.3 of photutils, I used to be able to pass `centroids.centroid_2dg` as centroiding function to `find_peaks`.
Upgrading to verison 1.3, I get the following error:
```
...
  File ~\Miniconda3\lib\site-packages\photutils\detection\peakfinder.py:185 in find_peaks
    x_centroids, y_centroids = centroid_sources(

  File ~\Miniconda3\lib\site-packages\photutils\centroids\core.py:405 in centroid_sources
    error_cutout = centroid_kwargs['error'][slices_large]

TypeError: 'NoneType' object is not subscriptable
```

It seems that `centroids.centroid_2dg`, whose arguments include the default `error=None`, is no longer compatible with the function `centroid_sources`, called by `find_peaks`, since it is now expecting the keyword argument `error` to be some value or not to be present at all.

Thank  you,

Paolo

**Comment by larrybradley** [comment]
@chioettop Thanks for your report.  This was previously reported in #1294 and was fixed in #1297.  It will appear in the next photutils release, which should happen early next week.
