### ISSUE TITLE
How to get effective area of EllipticalAnnulus on a masked image?

### ISSUE THREAD

**Issue by pinsongzhao** [astropy/photutils#1325]
Hi, I am using function `EllipticalAnnulus' on a masked image. 
$ phot_table = aperture_photometry(img_mask, ellip_annulli, method = 'exact')
I find phot_table['aperture_sum_0'].data will give the correct result of the sum of fluxes for all un-masked pixels within that annulli, 
is there any convenient way that can tell me the total number of all un-masked pixels?

Thank you for your time.

**Comment by larrybradley** [comment]
@pinsongzhao  There are two ways to get the area of the unmasked pixels within the aperture.

The first way is to use the `area_overlap` method, which is available for all `PixelAperture` objects:

```python
>>> from photutils.aperture import EllipticalAperture

# make a simple image of all ones
>>> data = np.ones((51, 51))
>>> mask = np.zeros(data.shape, dtype=bool)
>>> mask[0:25] = True    # let's mask half the data

>>> aper = EllipticalAperture((25, 25), 10, 5)
>>> print(aper.area)   # exact analytical area of the ellipse shape
157.07963267948966

# area of unmasked pixels within the aperture
>>> print(aper.area_overlap(data, mask=mask))
88.52312458335591
```

The second method uses the new `ApertureStats` class:

```python
>>> apstats = ApertureStats(data, aper, mask=mask)

# aperture photometry
>>> print(apstats.sum)
88.52312458335591

# area of unmasked pixels within the aperture used for the sum
>>> print(apstats.sum_aper_area)
<Quantity 88.52312458 pix2>
```

**Comment by larrybradley** [comment]
@pinsongzhao I'm closing this issue, but please reopen if I did not answer your question.
