### ISSUE TITLE
detection with DAOStarFinder, yields "RuntimeError: filter weights array has incorrect shape"

### ISSUE THREAD

**Issue by blackbianca** [astropy/photutils#1328]
Helllo,
I'm trying to load a fits file into DAOStarFinder to detect sources in the observed field, following the example provided in the manual step-by-step. I'm working in Ubuntu 20.04 and running Photutils inside a conda environment with the following specs
python 3.8.8
numpy 1.21.4
astropy 5.0
photutils 1.0.1

Here's the code.

```
from astropy.stats import sigma_clipped_stats
from astropy.io import fits

file = fits.open("myfitsfile.fits")
image_hdu = file['PRIMARY']
data = image_hdu.data
mean, median, std = sigma_clipped_stats(data, sigma=3.0)
print(mean, median, std)
```

```
from photutils.detection import DAOStarFinder

daofind = DAOStarFinder(fwhm=3.0, threshold=5.*std)
sources = daofind(data-median) 
```

The first chunk of code works fine. The second chunk fails at the last line, with the following log.
[log.txt](https://github.com/astropy/photutils/files/8372398/log.txt)
What are the weights mentioned in the error log? How can I solve this?

I apologize in advance if the question is poorly formulated. I'm not experienced at all nor with photutils neither with github issues.
Many thanks!

**Comment by larrybradley** [comment]
@blackbianca The error indicates that your `data` array has the wrong number of dimensions.  `DAOStarFinder` requires that the data be a 2D array.  For a numpy array, you can check this with the `ndim` attribute (e.g., `print(data.ndim)`).  If `ndim` is not 2, then `DAOStarFinder` will not work.
