### ISSUE TITLE
Artificial star testing

### ISSUE THREAD

**Issue by conornally** [astropy/photutils#1330]
I'm in the process of putting together a JWST specific PSF photometry pipeline and have reached artificial star testing. I notice that photutils contains all the underlying low-level code for artificial star testing but doesn't package it as a high-level module. Is there any work being done on this and or would this be a valuable pull request if I were to put a first draft together

**Comment by emirkmo** [comment]
I'm not a maintainer so I don't know, but this feature would be highly appreciated by users (like me).

**Comment by larrybradley** [comment]
There are a few new tools in photutils that can be used to create simulated images from (PSF) models, including:

- `make_psf_model`: https://photutils.readthedocs.io/en/latest/api/photutils.psf.make_psf_model.html#photutils.psf.make_psf_model
- `make_model_image`: https://photutils.readthedocs.io/en/latest/api/photutils.datasets.make_model_image.html#photutils.datasets.make_model_image
- `make_model_param`: https://photutils.readthedocs.io/en/latest/api/photutils.datasets.make_model_params.html#photutils.datasets.make_model_params

These are used for internal testing and documentation.
Here's an example notebook using `make_psf_model`:  https://gist.github.com/larrybradley/b1e4112cf556e159a3c18e38e34a7fa1
