### ISSUE TITLE
Changing AngleOrPixelScalarQuantity to ScalarAngleOrPixel

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#1335]
I recently found ``AngleOrPixelScalarQuantity`` is removed (https://github.com/astropy/photutils/commit/d61630e2ab835113db93f28f6fd427790329090e). 

This made my package to fail when I tried to import it (I used ``AngleOrPixelScalarQuantity`` to make custom aperture classes), so I need a fix.

Will everything be fine if I change ``AngleOrPixelScalarQuantity`` to ``ScalarAngleOrPixel``, or do I need more?

**Comment by ysBach** [comment]
Oh I have just found there are more changes in the internal API (`_shape_params`, etc)...

**Comment by larrybradley** [comment]
@ysBach Yes, you can simply replace `AngleOrPixelScalarQuantity` with `ScalarAngleOrPixel`.  These descriptor classes (and also `_shape_params`) aren't part of the "public" user-facing API, so these changes aren't in the change log or undergo a deprecation period.  I don't think very many people have made custom aperture classes.  In fact, you are the first person I've heard to do this.  Sorry for any disruption.
