### ISSUE TITLE
Using SEP as source detector for PSF photometry

### ISSUE THREAD

**Issue by cnaw** [astropy/photutils#1336]
This  is more of a question than an issue. 
Because of the shapes of JWST PSFs, I have been having more success detecting point sources using SEP through the use of the magnitude versus  half-light radius distribution  than using DAOPHOT or IRAFFIND. My task here is to examine the residuals of PSF fits throughout an image, and this photutils task is the way to go:
 
IterativelySubtractedPSF 

My question  is how can I feed this task  in a list of already detected  sources ?  From the Readthedocs page I find this statement:

photometry = IterativelySubtractedPSFPhotometry(finder=iraffind,
                                                group_maker=daogroup,
                                                bkg_estimator=mmm_bkg,
                                                psf_model=psf_model,
                                                fitter=LevMarLSQFitter(),
                                                niters=1, fitshape=(11, 11))

which  implies that the parameters passed by any alternative code  and irraffind be identical and that the  task will run the source-identification - or is there a way to by-pass this (i.e., is it possible to feed only  a list of x-centroids, y_centroids) ?
Thanks!
Christopher Willmer

**Comment by cnaw** [comment]
I guess  #1271 addresses this: set finder = None and use the list of objects derived from SEP as init_guesses:

photometry = IterativelySubtractedPSFPhotometry(finder=None, 
group_maker=daogroup,
bkg_estimator=mmm_bkg,
psf_model=psf_model,
fitter=LevMarLSQFitter(),
niters=1, fitshape=(11, 11))

and then use the SEP objects as initial guesses.

psf = psf_photometry(newimg, init_guesses=pos_table)

Sorry for the false alarm.

**Comment by larrybradley** [comment]
@cnaw For `IterativelySubtractedPSFPhotometry` the `finder` cannot be `None` because it is needed during the iterations after subtraction.  However, it may be useful to allow the initial guesses to be used instead of the `finder` for the *first* iteration.  The current API doesn't allow that, but I will look into adding that possibility.

**Comment by larrybradley** [comment]
Also, if you want to use a segmentation-based catalog, photutils can produce that as well:  https://photutils.readthedocs.io/en/latest/segmentation.html

**Comment by larrybradley** [comment]
@cnaw Actually, it appears that you can use `init_guesses` with `IterativelySubtractedPSFPhotometry`, but `finder` cannot be `None`. The initial guesses are used only for the first iteration.  After the first iteration, the fitted stars are subtracted and then the `finder` is used to find more stars in each subsequent iteration.

It is possible to use a custom (e.g., segmentation-based) finder with the PSF-fitting tools.  You would need to create a function that returns the star x, y positions in an astropy table and then pass that function into the `finder` keyword.

**Comment by cnaw** [comment]
@larrybradley, thanks for the feedback, which is very helpful.  I think I have a working version of my script now (I ended up resorting to IRAFFIND) but clearly in some of the fields there are issues of close neighbors biasing the measurements.  Your comments show a path to get this working.  Thanks for your time!
