### ISSUE TITLE
Photometry overestimates point source maximum brightness

### ISSUE THREAD

**Issue by vrmarquezpacheco** [astropy/photutils#1349]
Hello! I have been using the different photometry routines on the point source AGN. However, I keep finding that the maximum brightness of the point source is larger than the maximum brightness of the original image, leaving a negative value in the residual image. I'm new to this and I haven't encoutered this issue before. I wondered if anyone had also encoutered this problem. Thanks!

**Comment by larrybradley** [comment]
@vrmarquezpacheco Can you please provide more details, ideally with a minimal example?
