### ISSUE TITLE
Offset among SAO DS9 and photutils pixel coordinates

### ISSUE THREAD

**Issue by UrosM13** [astropy/photutils#1360]
Hi,

I am using photutils to do some aperture photometry (EllipticalAperture) using pixel coordinates.

First I am manually creating an elliptical aperture in SAO DS9 and then copy-paste parameters of that aperture to the python script to perform photometric measurements with photutils.
I notice that there exists an offset between the aperture position (with the same parameters) between DS9 and photutils.
Image attached:
<img width="1396" alt="img" src="https://user-images.githubusercontent.com/93936495/173090748-c5d7e0a9-af22-463d-826f-8f825e90a4dd.png">

I am not sure if this is some bug or, I am not using photutils in a proper way?
What can cause this offset and how to fix this?

Here are lines of code which produce photutils image (actually I am trying to folow instructions from https://photutils.readthedocs.io/en/stable/aperture.html )

##### code start from here #######

position = (62.087293, 34.429379) 
a = 2.7862884
b = 2.4380023
theta = Angle(0, 'deg')

aperture = EllipticalAperture(position, a, b, theta)
phot = aperture_photometry(original, aperture, method='exact')

plt.imshow(original, cmap='viridis', origin='lower')
plt.axis('off')
show_ap = aperture.plot(color='white', lw=2)

##### code ends here #######

Please let me know if somethin else I neeed to provide.

Thanks.

Uros

**Comment by larrybradley** [comment]
@UrosM13 DS9 uses 1-based pixels (origin = (1, 1)), while Python uses 0-based pixels (origin = (0, 0)).  You will need to translate your DS9 pixels by (-1, -1).
