### ISSUE TITLE
Bug?: BasicPSFPhotometry PSF flux uncertainty shrinks with increasing fitsize

### ISSUE THREAD

**Issue by emirkmo** [astropy/photutils#1369]
![output_flux](https://user-images.githubusercontent.com/11209690/174990819-b1849462-f749-4dcf-86e8-a78e483cd447.png)

This was previously reported, but the fitsize parameter of BasicPSFPhotometry has a shrinking uncertainty with increasing fitsize. I'm attaching a figure which shows this. 

To be clear what we are doing is getting a star cutout (region of image with a few x FWHM, centered around the star [we often have sparse fields]), using our EPSF (built previously), and running BasicPSFPhotometry on the input to get a PSF flux and flux uncertainty.

The PSF flux uncertainty (error bars) shrinks with increasing fitsize even though the determined flux reaches an absolute peak value pretty quickly at around ~2x the image FWHM. This is also easily visible in the full calibrated instrumental magnitude plot attached at the end. The most likely reason for this decreasing uncertainty is some sort of overfitting, or overconfidence of the fit to the relatively smooth background. This creates an issue where the error bars are smaller than they should be. Basically, the background, instead of adding uncertainty via Poisson noise, takes away from the error budget as more of it is included in the fit.

Is there a smart way of getting around this while continuing to use the flux uncertainty of BasicPSFPhotometry, without finding the "elbow" manually for each PSF fit where the uncertainty begins to shrink while the flux does not change?

The uncertainty comes from the fit_info from the fitter. The basic call signature is:

```python
photometry_obj = BasicPSFPhotometry(group_maker=DAOGroup(fwhm), bkg_estimator=MedianBackground(), psf_model=epsf,
                                        fitter=fitting.LevMarLSQFitter(), fitshape=phot.star_size, aperture_radius=fwhm)
    psfphot_tbl = photometry_obj(image=image.subclean, init_guesses=Table(clean_references.xy, names=['x_0', 'y_0']))
```

Basically the fitter is `fitting.LevMarLSQFitter()`, fitshape was by default the full cutout size, but has now been made a multiple of the `fwhm` (previous determined from the image and is in units of image pixels), and `DAOGroup` helps with stellar crowding, and bkg_estimator is `MedianBackground` **BUT** the image has already been background subtracted previously using another estimator such as `BackGround2D.SExtractorBackground` with sigma clipping.

Finally, initial guesses for the stellar positions (PSF centers) are passed in, although it is not forced, meaning the PSF can move around.

I wonder if the bkg_estimator is doing something wonky due to its smoothness? Or, I suspect that the uncertainty estimate is actually poorly defined because we are interested in not how well the PSF fits the relatively smooth background at multiple FWHM but in how it fits the majority of the flux at 2-3 FWHM from the center, and that is the uncertainty we care about.

Previous issue see: #1130 

![output_as_mag](https://user-images.githubusercontent.com/11209690/174994618-3dce3ba5-54a5-4edd-ba2d-484304bc1b7e.png)

**Comment by larrybradley** [comment]
I'd need to investigate this further.  The PSF flux uncertainties come from the astropy fitter class which in turn come from the scipy optimizers, e.g., `scipy.optimize.leastsq` for the `LevMarLSQFitter` fitter.

**Comment by emirkmo** [comment]
@larrybradley I think that Astropy 5 may have solved one aspect of this issue, where nans/masked values were involved. But the behavior still remains. Just an update.

**Comment by larrybradley** [comment]
@emirkmo Error arrays can now be input into `PSFPhotometry`.  The error arrays are used to weight the fits, and when used with astropy >= 5.3, they are propagated to the parameter uncertainties.  Can you please try with the new `PSFPhotometry` class and see if it resolves this issue?
