### ISSUE TITLE
Exceptions when writing SourceCatalog QTable to FITS using Table write() method.

### ISSUE THREAD

**Issue by brantr** [astropy/photutils#1371]
Possibly just a question, but I could not find the solution in the photutils documentation:

If I use the SourceCatalog `.to_table()` method to create a QTable, and then I use the `.write()` method inherited from astropy.table.Table, I receive the following exceptions when setting format='fits':

```
Unexpected exception formatting exception. Falling back to standard exception

File "[path to astropy]/astropy/io/fits/column.py", line 2401, in _convert_record2fits
    raise ValueError(f'Illegal format `{format}`.')
ValueError: Illegal format `object`.
```

For reference, using `.write(format='ascii')` works as expected.

I considered posting to astropy directly, but the work-around sequence:

tbl = [SourceCatalog instance].to_table()
tbl.write('output.ascii',format='ascii')
tbl_from_ascii = QTable.read('output.ascii',format='ascii')
tbl_from_ascii.write('output.fits',format='fits')
tbl_from_fits = QTable.read('output.fits',format='fits')

works as expected. I only encounter exceptions if I convert SourceCatalog to a QTable and then attempt to write the QTable to fits, e.g.,

tbl = [SourceCatalog instance].to_table()
tbl.write('output.fits',format='fits')

**Comment by larrybradley** [comment]
@brantr FITS binary tables do not support the Python `None` object.  I suspect that the table you are trying to serialize to FITS has one or more `None` values.  You could replace `None` values with a sentinel value (e.g., `np.nan`, or 99, etc.) and then serialize to FITS.

**Comment by larrybradley** [comment]
You can also remove any columns that are all `None` (e.g., `sky_centroid` if you did not input a WCS) before serialization, e.g. `tbl.remove_column('sky_centroid')`.

**Comment by brantr** [comment]
Yes, indeed that was the issue. Thanks for your prompt reply!
