### ISSUE TITLE
Import Error for 'make_2dgaussian_kernel'

### ISSUE THREAD

**Issue by RedShiftSevn** [astropy/photutils#1395]
Have been going through the image segmentation portion of Photutils and am running into an import error. Everything is updated to 

ImportError: cannot import name 'make_2dgaussian_kernel' from 'photutils.segmentation' (C:\Users\music\anaconda3\lib\site-packages\photutils\segmentation\__init__.py)

Is there any way to fix this?

**Comment by larrybradley** [comment]
`make_2dgaussian_kernel` is a new function that was introduced in photutils version 1.5.0.  You will need to update to this version.
