### ISSUE TITLE
TypeError & ImportError keeps showing up when import 

### ISSUE THREAD

**Issue by dutry** [astropy/photutils#1396]
Whatever sub-module  of `photutuls` I import (I have tried `from photutils.datasets import make_noise_image`,  `from photutils.isophote import EllipseGeometry`,  `from photutils.datasets import make_100gaussians_image`), I will always obtain such error:

```
~/anaconda3/lib/python3.9/site-packages/photutils/segmentation/detect.py in <module>
    290 
    291 
--> 292 @deprecated_renamed_argument('kernel', None, '1.5', message='"kernel" was '
    293                              'deprecated in version 1.5 and will be removed '
    294                              'in a future version. Instead, if filtering is '

TypeError: deprecated_renamed_argument() got an unexpected keyword argument 'message'
```

**Comment by larrybradley** [comment]
It appears you are using an unsupported (older) version of `astropy`.  `astropy 5.0+` has been required for the last 2 `photutils` versions.

**Comment by dutry** [comment]
@larrybradley Thank you for the reply. Yes I have made sure my environment

**Comment by larrybradley** [comment]
The `deprecated_renamed_argument` function added the `message` keyword in astropy 5.0 (https://docs.astropy.org/en/stable/api/astropy.utils.decorators.deprecated_renamed_argument.html).  The error message you are getting (`TypeError: deprecated_renamed_argument() got an unexpected keyword argument 'message' `) strongly suggests that you have an older version of astropy in your current Python environment.  You can check your `astropy` version in your python session this with:
```python
import astropy
print(astropy.__version__)
```

**Comment by dutry** [comment]
@larrybradley 
I tried to re-install via `conda` instead (originally I installed via `pip`) and the TypeError becomes ImportError:

```
~/anaconda3/lib/python3.9/site-packages/photutils/segmentation/properties.py in <module>
     24 from ..utils._convolution import _filter_data
     25 from ..utils._moments import _moments, _moments_central
---> 26 from ..utils._wcs_helpers import _pixel_to_world
     27 
     28 __all__ = ['SourceProperties', 'source_properties', 'LegacySourceCatalog']

ImportError: cannot import name '_pixel_to_world' from 'photutils.utils._wcs_helpers' (/home/duhc/anaconda3/lib/python3.9/site-packages/photutils/utils/_wcs_helpers.py)
```

**Comment by larrybradley** [comment]
@dutry There appears to be an issue with your `photutils` installation.  The `properties.py` module and `_pixel_to_world` function no longer exist in `photutils` -- so you are using an old version of photutils (< 1.4.0).  But even with an older version, `_pixel_to_world` would have worked.  It appears that perhaps you somehow have mixed versions.

Installation issues are hard to diagnose, so I would suggest starting with a fresh conda environment and do this (the "newenv" name is arbitrary):

```
conda create -n newenv python==3.10
conda activate newenv
conda install photutils -c conda-forge
```

You could also do this:
```
conda create -n newenv python==3.10
conda activate newenv
pip install photutils
```

**Comment by dutry** [comment]
Then problem is solved by change the environment.
