### ISSUE TITLE
Can´t import ApertureStats from photutils.aperture

### ISSUE THREAD

**Issue by jortiz12** [astropy/photutils#1402]
Dear community

I can not execute the cod eline `from photutils.aperture import ApertureStats`, as I get the fowwwing error message

`ImportError: cannot import name 'ApertureStats' from 'photutils.aperture' (/usr/local/lib/python3.7/dist-packages/photutils/aperture/__init__.py)`

Have the latest version installed. Any advice would be much welcomed.

Kind Regards
Jose

**Comment by larrybradley** [comment]
`ApertureStats` was added in version 1.4.0.   Version 1.4.0 requires Python 3.8+.  Your error message shows that you using Python 3.7, so you must have an older version of photutils installed in your current environment.  Are you sure you are in the correct python environment?  

To check from within Python:
```python
>>> import photutils
>>> photutils.__version__
```

**Comment by jortiz12** [comment]
Thxs @larrybradley.

Indeed that's the case, as I'm running my notebook in Google Colab which uses python 3.7  by default.

Have followed the steps in [[How can I update Google Colab's Python version?](https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version)](https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version) to upgrade to python3.9, but after this upgrade is made, the `pip `command to install some libraries no longer work.

Any advice would be much welcome.

Kind Rgds

**Comment by larrybradley** [comment]
I don't have any experience with Colab, so I don't have any suggestions.  It sounds like the SO Python upgrade instructions are broken or incomplete because `pip` should still work.  The command could have changed to `pip3.9` (or `pip3`) or the instructions are wrong.

**Comment by jortiz12** [comment]
Thxs @larrybradley . If I find a solution , I´ll post it here. I´ve seen similar issue (ie upgrading to python3.9 and pip not importing libraries elsewhere).
Kind rgds, Jose

**Comment by larrybradley** [comment]
Thanks, @jortiz12.  I'm closing this for now, but please post if you find a solution how to upgrade Python in Google Colab.

**Comment by jortiz12** [comment]
Of course @larrybradley .
thxs for the attention.
