### ISSUE TITLE
PSF Photometry: Need different box size for fitting vs. PSF subtraction.

### ISSUE THREAD

**Issue by jluastro** [astropy/photutils#1427]
In the PSF photometry classes, currently the fitshape parameter controls both the box size to fit the PSF to a source and the size of the region to use when subtracting that scaled PSF model. Often, we want to use a fit box centered on the core (where SNR is maxed and confusion is less likely) but we want to subtract a much bigger region, especially for bright stars. Currently, this is not possible. 

The code implementation is in photutils.psf.photometry:
```
def star() 
...          
            try:
                image = subtract_psf(image, self.psf_model, param_table,
                                     subshape=self.fitshape)
            except NoOverlapError:
                pass

```
I would recommend allowing subshape to be set as a variable on the object instead of using fitshape by default.

**Comment by larrybradley** [comment]
@jluastro Many thanks for this suggestion.  I agree that would be helpful.
