### ISSUE TITLE
Error "b_out must be greater than b_in" wrongly invoked using Python > 3.6

### ISSUE THREAD

**Issue by NikkiZabel** [astropy/photutils#1440]
When using EllipticalAnnulus. It works fine in Python 3.6 and older.

**Comment by larrybradley** [comment]
It appears to be working fine.  Note that `b_out` comes before `b_in` if you input both parameters; `b_in` is optional (see [EllipticalAnnulus](https://photutils.readthedocs.io/en/stable/api/photutils.aperture.EllipticalAnnulus.html)).

```python
>>> import photutils
>>> photutils.__version__
'1.5.0'

>>> from photutils.aperture import EllipticalAnnulus
>>> EllipticalAnnulus((50, 50), 5, 10, 20, 12)
<EllipticalAnnulus([50., 50.], a_in=5.0, a_out=10.0, b_in=12.0, b_out=20.0, theta=0.0)>

>>> EllipticalAnnulus((50, 50), a_in=5, a_out=10, b_out=20, b_in=12)
<EllipticalAnnulus([50., 50.], a_in=5.0, a_out=10.0, b_in=12.0, b_out=20.0, theta=0.0)>

>>> EllipticalAnnulus((50, 50), 5, 10, 20)
<EllipticalAnnulus([50., 50.], a_in=5.0, a_out=10.0, b_in=10.0, b_out=20.0, theta=0.0)>
```

The error is raised if you reverse the inputs:
```python
>>> EllipticalAnnulus((50, 50), 5, 10, 12, 20)
ValueError: "b_out" must be greater than "b_in".
```

Can you please provide a simple example that incorrectly gives an error?

**Comment by larrybradley** [comment]
Please re-open if you are still having problems. Thanks.
