### ISSUE TITLE
Feature request: Add a way to calculate the PSF uncertainty only using non-background pixels

### ISSUE THREAD

**Issue by emirkmo** [astropy/photutils#1441]
See related unsolved issue: #1369

But this is a feature request not strictly related to that bug.

It would be great if we could limit the flux uncertainty calculation only to pixels containing flux above the background, when doing PSF fitting. As shown in #1369, sometimes, the PSF fitting box being larger results in better fits, but has the deleterious effect of changing the significantly changing the flux uncertainty.

One proposed solution is to re-compute the correlation matrix or fit while masking out all regions identified as background, then I suppose the error should be more reflective of the flux falling on relevant pixels. Would need to add a threshold parameter for this (such as ~10% over median or whatever background identifier used). 

Alternatively these regions could be masked even when doing the initial fit, or some sort of rescaling constant could be computed via an algorithm unknown to me right now, which takes into effect differences between background and non-background pixels.

**Comment by larrybradley** [comment]
@emirkmo When calling the PSF-fitting classes on data, there is a `mask` keyword that can be used to ignore pixels.  This keyword was introduced in version 1.5.0.  Does that work for your use case?

**Comment by larrybradley** [comment]
The PSF tools have been rewritten and have much better error propagation, including the ability to input error arrays.  There is also the `mask` keyword mentioned above which could be generated using a threshold value.
