### ISSUE TITLE
load_simulated_hst_star_image() has a connection problem.

### ISSUE THREAD

**Issue by PaulLiu666** [astropy/photutils#1481]
<img width="536" alt="截屏2022-12-14 12 26 35" src="https://user-images.githubusercontent.com/94830897/207505708-2f709dc0-fb12-47ee-8cec-4e05c7f4290e.png">
When I want to get data from load_simulated_hst_star_image(), there is a connection problem.
I want to know whether this is my problem or a problem with the datasets?
<img width="445" alt="截屏2022-12-14 12 20 00" src="https://user-images.githubusercontent.com/94830897/207505689-263ce084-202b-4186-999f-9a81541c3461.png">

**Comment by larrybradley** [comment]
It works fine for me.  The URL that it's trying to download from is: https://github.com/astropy/photutils-datasets/raw/main/data/hst_wfc3ir_f160w_simulated_starfield.fits.  For some reason, your connection to that URL is being refused.

**Comment by PaulLiu666** [comment]
Thank you!
