### ISSUE TITLE
How can i do about PSF Photomerty flux_fit  Not equal to flux_0  in fixed aperture_radius

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [astropy/photutils#1483]
Hello ,
My understanding is that PSF is also needed to fit a model based on the aperture and calculate the flux,
I think the flux_fit should be very close to flux_0 (aperture flux) to be correct.
When I set the aperture size to a fixed size (aperture_radius=7.58) ,
I found that flux_0 is not equal to flux_fit and the difference is very big,
How can I make flux_fit get the correct flux size?
What can I do to get the correct psf flux?
Looking forward to your reply!

![image](https://user-images.githubusercontent.com/21216881/207915124-5c6b0bf8-591b-4625-a6ac-a20a8de62cd1.png)

`import pandas as pd
from astropy.io import fits
from astropy.modeling.fitting import LevMarLSQFitter
from astropy.table import Table
import numpy as np
from matplotlib.colors import LogNorm
import matplotlib.pyplot as plt
from photutils import DAOGroup, MMMBackground, IRAFStarFinder, IntegratedGaussianPRF, IterativelySubtractedPSFPhotometry, BasicPSFPhotometry, CircularAperture, aperture_photometry
from photutils.datasets import (make_noise_image, make_gaussian_sources_image)

np.set_printoptions(threshold=np.inf)
pd.set_option('display.width', 300)  # 设置字符显示宽度
pd.set_option('display.max_rows', None)  # 设置显示最大行
pd.set_option('display.max_columns', None)  # 设置显示最大列，None为显示所有列

hdu = fits.open(r"C:\Users\Administrator\Desktop\set_0\img_r.fits")

daogroup = DAOGroup(crit_separation=1)
mmm_bkg = MMMBackground()
psf_model = IntegratedGaussianPRF()
psf_model.sigma.fixed = False
psf_model.x_0.fixed = True
psf_model.y_0.fixed = True
pos = Table(names=['x_0', 'y_0'], data=[[394, 284.5, 193, 348],
                                        [464, 294, 441, 389.5]])
photometry = BasicPSFPhotometry(group_maker=daogroup,
                                bkg_estimator=mmm_bkg,
                                psf_model=psf_model,
                                fitter=LevMarLSQFitter(),
                                aperture_radius=7.58,
                                fitshape=(47, 47))
phot_results = photometry(image=hdu[0].data * 0.002, init_guesses=pos)
df1 = pd.DataFrame({'id': phot_results['id'], 'group_id': phot_results['group_id'],
                    'x_0': phot_results['x_0'], 'y_0': phot_results['y_0'],
                    'flux_0': phot_results['flux_0'],
                    'sigma_0': phot_results['sigma_0'],
                    # --------------------------------
                    'sigma_fit': phot_results['sigma_fit'],
                    'x_fit': phot_results['x_fit'], 'y_fit': phot_results['y_fit'],
                    'flux_fit': phot_results['flux_fit'],
                    })

print(df1)`

The fit file is url：https://pan.baidu.com/s/1KkqJwP6Nadi5mfMGyyDc0w 
pwd：z6f1

**Comment by xiaoguaishoubaobao** [comment]
Thanks for your reply
This is a mask.fits file with many layers, each layer contains the position of each star/galaxy and the outline information.
The reason I use this mask.fits file to measure Psf is because it is an image without background, and I know that the flux from it is more accurate because there is no interference from the background.
And then the warning mentioned above appears
Can I calculate the PSF of a point separately when there is only one point in an image? 
If so how should I set it up?

I also have a question
When I measure the psf img_r.fits flux with sextractor+psfex 
I found that with the same settings and the same input fits file (simulated by phosim with the same parameters),
some images all predictions is normal and some images all  predictions  is comparatively largeas 
shown in the figure below
![image](https://user-images.githubusercontent.com/21216881/207923867-aa8a5e08-82e0-434e-8fba-8de9cb76c4f4.png)
The horizontal axis is the correct value The vertical axis is the sextractor+psfex predicted value
The same parameter settings are correct for the real database.
 What is the problem?

I've got the fits file and the coordinate information and the configuration file all packed up.

url：https://pan.baidu.com/s/128YPhDgT8vJVZuvgHejXHg 
pwd：wpvr 

Thanks again for your help!

**Comment by larrybradley** [comment]
`flux_0` is just an initial guess of the flux from the aperture photometry.  The fit flux (`flux_fit`) being different from `flux_0` doesn't mean that it's incorrect.  The value of `flux_0` depends on the `aperture_radius` (if fluxes are not input in `init_guesses`).

**Comment by xiaoguaishoubaobao** [comment]
Thanks for your reply!
