### ISSUE TITLE
Ellipse fits to isophotes: higher harmonic values are opposite of what they should be

### ISSUE THREAD

**Issue by perwin** [astropy/photutils#1486]
I'm working on moving my galaxy isophote analysis over to photutils.isophote from IRAF, but I seem to have run into a bug(?) in how the higher harmonics (a3,b3,a4,b4) are computed when ellipses are fit to the isophotes. Specifically, they seem to be the negative of how they are computed by the IRAF ellipse task (and, indeed, the original formulation by [Jedrzejewski 1987](https://ui.adsabs.harvard.edu/abs/1987MNRAS.226..747J/abstract)).

Here's an example, using ellipse fits to the SDSS *r*-band image of the elliptical galaxy NGC 3377. The first figure is the position angle and ellipticity from the IRAF ellipse fits [black] and the isophote.Ellipse.fit_image analysis [red], which agree rather well. The second and third figures shows a3 and b3 (sin and cos 3 theta) and a4 and b4 (sin and cos 4 theta), respectively. In both cases, the IRAF and isophote values are mirror images of each other. For comparison, I've also included the "Cos(4  theta)" plot from Fig.4 of Jedrzejewski (1987) for this galaxy (you can ignore the "NGC 1549" panel), which shows that the b4 values are indeed disky (b4 > 0) at small radii and boxy (b4 < 0) at large radii.

(Edited to add: macOS 12.6.2, Python 3.10.5, photutils 1.6.0)

![n3377_ellpa](https://user-images.githubusercontent.com/2163943/212891516-b10be074-fd5c-4936-9ec9-37c23a664ac6.png)
![n3377_a3b3](https://user-images.githubusercontent.com/2163943/212892728-9c8ce7d6-a51b-4d07-8448-c7f336011880.png)
![n3377_a4b4](https://user-images.githubusercontent.com/2163943/212891574-800d5506-43d1-41cb-9111-d5047fe36a8a.png)
![jedrzejewski87_for_github](https://user-images.githubusercontent.com/2163943/212894481-c96f6203-a2c1-4121-94df-d2aeda7e9d6e.png)

**Comment by larrybradley** [comment]
@perwin - Many thanks for reporting this issue. It certainly looks like there is a sign bug. The `photutils` isophote code was written by Ivo Busko, who was also an author of the original IRAF code.  He just retired, so I'll have to dig into the code.

@stscirij - any additional insights?

**Comment by larrybradley** [comment]
@perwin Thanks again for reporting this bug.  I've fixed it in #1501 and it will appear in the next release (version 1.7.0).
