### ISSUE TITLE
How do you extract a point spread function from a fits image?

### ISSUE THREAD

**Issue by PaulLiu666** [astropy/photutils#1493]
I have read the user documentation of 'Building an effective Point Spread Function (ePSF)', but I still have some questions, for example, how can I get the FWHM of the PSF?

**Comment by larrybradley** [comment]
You can also use the the `gaussian_fwhm` attribute of the new `RadialProfile` class:  https://photutils.readthedocs.io/en/latest/api/photutils.profiles.RadialProfile.html#photutils.profiles.RadialProfile
