### ISSUE TITLE
Any way to specify enclosed flux fraction for elliptical apertures

### ISSUE THREAD

**Issue by wjcramer** [astropy/photutils#1544]
I was wondering if there was an easy way to fit ellipse to galaxies that encloses a given fraction of the flux  (say 50%) based on the total flux within the Kron radius. I could brute force this by just fitting a series of concentric ellipse to the galaxy and finding that which comes closest to 50%, but was wondering if there was a less computationally intensive way.

thanks!

**Comment by larrybradley** [comment]
@wjcramer The way to do this is to use a root finder with an objective function.  `SourceCatalog` does this to compute the circular `fluxfrac_radius` (e.g., half-light radius). Here's a quick example notebook for elliptical apertures:  https://gist.github.com/larrybradley/1221394afa555881d0b337e7220054f0

**Comment by wjcramer** [comment]
Thanks very much, this was extremely helpful!
