### ISSUE TITLE
DAOStarFinder to include `minsep_fwhm` ?

### ISSUE THREAD

**Issue by cylammarco** [astropy/photutils#1561]
Hi, is it possible to include `minsep_fwhm` in the `DAOStarFinder`? It looks to me from the top level that it is a simple implementation that can be copied and pasted from the `IRAFStarFinder`, not sure if it would cause problems in other places though...

In the current `DAOStarFinder`:

https://github.com/astropy/photutils/blob/88437049ef3909e9ced1c5ed3c06076a86d17020/photutils/detection/daofinder.py#L203-L211

From `IRAFStarFinder`:

https://github.com/astropy/photutils/blob/88437049ef3909e9ced1c5ed3c06076a86d17020/photutils/detection/irafstarfinder.py#L163

and

https://github.com/astropy/photutils/blob/88437049ef3909e9ced1c5ed3c06076a86d17020/photutils/detection/irafstarfinder.py#L176-L186

**Comment by larrybradley** [comment]
Thanks, @cylammarco .  A `min_separation` keyword was added to `DAOStarFinder` (and `IRAFStarFinder`) in #1663.  It will be included in the next release.
