### ISSUE TITLE
Documentation - RTD latest points to an old version?

### ISSUE THREAD

**Issue by keflavich** [astropy/photutils#1588]
When I load the "latest" version on RTD, I see a very old version:
```
[photutils 0.1.dev154+gd2d7a98](https://photutils.readthedocs.io/en/latest/index.html#) »
```

RTD is building at each PR, but it looks like latest is pointing to the wrong place.

**Comment by larrybradley** [comment]
The "latest" docs are actually correct and up-to-date for the latest dev version, but the version number is incorrect.  #1591 fixes that.
