### ISSUE TITLE
Cannot Convert SourceCatalog into QTable with .to_table() Method

### ISSUE THREAD

**Issue by Cossas11204** [astropy/photutils#1595]
I cannot find any discussion related to this topic on the site.
The version of my Photutils is 1.8.0.

I have successfully created a SourceCatalog object with the following code:
```
cat = SourceCatalog(image, segm_deblend, convolved_data=smoothed_image, 
                    wcs=wcs, error=error, 
                    kron_params=[1.2, 2.5],
)
```
Then tried to convert it into a QTable object:
```
cat = cat.to_table()
```
However, I got an error raised:
```
ValueError                                Traceback (most recent call last)
---> 6 cat.to_table()

File /usr/local/lib/python3.9/dist-packages/photutils/segmentation/catalog.py:990, in SourceCatalog.to_table(self, columns)
    987     if self.isscalar:
    988         values = (values,)
--> 990     tbl[column] = values
    991 return tbl

File [~/.local/lib/python3.9/site-packages/astropy/table/table.py:2092](https://vscode-remote+ssh-002dremote-002b140-002e114-002e94-002e230.vscode-resource.vscode-cdn.net/mnt/D/D220624-data/JWST_data/COSMOS/NIRCAM/~/.local/lib/python3.9/site-packages/astropy/table/table.py:2092), in Table.__setitem__(self, item, value)
   2088 def __setitem__(self, item, value):
   2089     # If the item is a string then it must be the name of a column.
   2090     # If that column doesn't already exist then create it now.
   2091     if isinstance(item, str) and item not in self.colnames:
-> 2092         self.add_column(value, name=item, copy=True)
   2094     else:
   2095         n_cols = len(self.columns)

File [~/.local/lib/python3.9/site-packages/astropy/table/table.py:2414](https://vscode-remote+ssh-002dremote-002b140-002e114-002e94-002e230.vscode-resource.vscode-cdn.net/mnt/D/D220624-data/JWST_data/COSMOS/NIRCAM/~/.local/lib/python3.9/site-packages/astropy/table/table.py:2414), in Table.add_column(self, col, index, name, rename_duplicate, copy, default_name)
   2411 # Ensure that new column is the right length
   2412 # print(self.colnames, len(col), len(self))
   2413 if len(self.columns) > 0 and len(col) != len(self):
-> 2414     raise ValueError("Inconsistent data column lengths")
   2416 if rename_duplicate:
   2417     orig_name = name

ValueError: Inconsistent data column lengths
```
After some investigations, I found this error occurred specifically when adding the `sky_centroid` column  (`add_column` method was called) to the table.
The `value` from `getattr()` of  `sky_centroid` column is somthing like this:
```
[<Quantity [ 1805.77165651,  2795.85961361,  3269.3291403, ...,
           11312.37471452,  8412.44542591,  8438.93134069]>, <Quantity [  22.99822404,   28.0461725 ,   19.82057481, ..., 4476.35647722,
           4481.46115479, 4480.37687532]>]
```
Then the `add_column()` method raised the `ValueError` due to the shape of `sky_centroid = 2` instead of the length of the `sky_centroid[0]`.

Is there any solution for this?

**Comment by larrybradley** [comment]
The `sky_centroid` should be a `SkyCoord` array.  `photutils` requires a WCS object that supports the [Shared Python Interface for World Coordinate Systems](https://docs.astropy.org/en/stable/wcs/wcsapi.html#shared-python-interface-for-world-coordinate-systems).  Internally the code calls `wcs.pixel_to_world(xcen, ycen)`, which should return a `SkyCoord` array of coordinates.  From your report, it appears `pixel_to_world` is returning separate RA and Dec arrays, which does not conform to the standard.

You can check your wcs object by running: `wcs.pixel_to_world(np.arange(5), np.arange(5))`.  You can also check the catalog `sky_centroid` values using:
```
>>> cat = SourceCatalog(image, segm_deblend, convolved_data=smoothed_image, 
...                     wcs=wcs, error=error,  kron_params=[1.2, 2.5],
>>> cat.sky_centroid
```

**Comment by Cossas11204** [comment]
I see.
After inspecting the `wcs`, I found it was corrupted, therefore the `pixel_to_world()` cannot handle it properly. 
By assigning the correct wcs object, the issue has been solved.

Thanks for your help.
