### ISSUE TITLE
Feature request - return pixel values instead of sum

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#161]
### Suggestion

I would like to suggest that we add either a new function (or a new option to `aperture_photometry`) that would basically return two 2-d arrays with shape `(n_sources, n_pix)` - the first array would contain in each row the pixels contained in the aperture, and the second array would contain the weights to apply to each pixel.
### Motivation

There have been discussions in a few places about gain, error, and I think we all agree that different people may want to compute errors differently. Having such a function would allow users to define their own way of collapsing this into a single flux and error per source.
### Implementation

I think that the easiest place to add this would be to update the `aperture_funcs` functions to either return a 1-d or 2-d array depending on an argument passed to this function that would indicate whether to collapse or not. This could be e.g. `reduce='sum'`, `reduce='mean'`, `reduce='median'`, or `reduce=None`, with the latter one returning an uncollapsed array (or two arrays, since we need the weights).

Of course, each source may end up with a slightly different number of pixels, but if that happens then once can simply pad a row with `0` and set the weight to `0`.

If we did this, we could also remove all the code that relates to `gain` and `error` currently, and instead then have a higher level function that wraps `aperture_photometry` that could deal with this for a given definition of gain and error (but users could then use `aperture_photometry` directly with `reduce=None` if they want to access the uncollapsed pixel values.

If this is done by adding an option to `aperture_photometry`, this would result in vector columns being returned instead of `aperture_sum`.
### Memory

At first this might seem prohibitive in terms of memory, but in fact this is not the case - provided that there isn't much overlap between apertures, the output array cannot be much larger than the input array if every pixel is used only once.
### Benefits
- Allow custom errors
- Simplify code (remove current gain/error from core code)
- Allow unforeseen applications where one needs the actual pixel values

This would resolve https://github.com/astropy/photutils/issues/8

cc @cdeil @larrybradley @bsipocz @eteq @kbarbary @keflavich

If people generally think this could be useful, I could try and implement this if no one else is interested.

**Comment by pllim** [comment]
I was just looking for this functionality, because I want to generate various background statistics for pixels in an annulus. It is unfortunate that it is not yet implemented.

**Comment by keatonb** [comment]
I'm glad to see that you all are already thinking about adding this functionality.  I just ran up against the problem of stars in the sky annulus increasing the calculated mean that I interpret as my background.  I would ideally subtract a more robust median.  Will try to come up with a workaround for now.

Thanks for putting the good work into photutils!

**Comment by larrybradley** [comment]
This feature was added in #453.  See the `ApertureMask` object.
