### ISSUE TITLE
Facing issue in finding stars using IRAFStarFinder

### ISSUE THREAD

**Issue by Srini-1997** [astropy/photutils#1612]
I am using the IRAFStarFinder package to detect the stars in my frame but it is missing out even the brightest stars even after setting a very low threshold (image attached below). When I use the DAOStarFinder package I am able to detect the stars that were not detected by IRAFStarFinder. But the problem with DAOStarFinder is that i am not able to calculate the fwhm which I  need for photometry. 
![output](https://github.com/astropy/photutils/assets/123535631/ff19c9cf-8db2-4d13-93ad-ddb094542db3)

**Comment by larrybradley** [comment]
@Srini-1997 Try relaxing the `sharplo, sharphi, roundlo, and roundhi` values.
