### ISSUE TITLE
prepare_psf_model issue with Fittable2DModel

### ISSUE THREAD

**Issue by christegk** [astropy/photutils#1614]
I am trying to use Gaussian2D from astropy as a psf model with prepare_psf_model in order to perform psf photometry but I am getting the type error : "psf_model must be an astropy Fittable2DModel". 
In fact, I tried other models and they all give the same error. This only occurs in 1.9 version - I have an almost identical code based on photutils 1.8 where I am able to use Gaussian2D in prepare_psf_model without any errors.

I have pyhton 3.11.4, photutils 1.9,  astropy 5.3.2 , numpy 1.25.2 on ubuntu 22.04

**Comment by larrybradley** [comment]
@christegk With `photutils 1.10.1` there is a new function called `make_psf_model` (a fixed version of `prepare_psf_model`, which is now deprecated).  Outputs from `make_psf_model` can be using with the `PSFPhotometry` class.

https://photutils.readthedocs.io/en/latest/api/photutils.psf.make_psf_model.html
