### ISSUE TITLE
ApertureStats does not support a list of Aperture like aperture_photometry

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1615]
https://github.com/astropy/photutils/blob/a6d629774c52cc82af18d0444c6e5584e5d0b492/photutils/aperture/stats.py#L74

but you have

https://photutils.readthedocs.io/en/stable/aperture.html#aperture-photometry-with-multiple-apertures-at-each-position

**Comment by larrybradley** [comment]
`aperture_photometry` returns a simple table that returns only the "aperture sum" as a new column for each new aperture.  `ApertureStats` computes much more than the aperture sum, and the results are stored as class attributes.  They are separate tools for different use cases. It would be difficult to allow a list of different aperture shapes to `ApertureStats`.  Every statistical property would need to be duplicated for each additional aperture.  That said, you *can* input an Aperture object that has multiple positions, but has the same shape properties (e.g., radius).

**Comment by pllim** [comment]
If Imviz ever going to roll out "mass aperture photometry," I guess I will bug you again. I can see Imviz handing ApertureStats a lot of different apertures in the same call. Perhaps multiprocessing is the answer instead. 🤷‍♀️
