### ISSUE TITLE
How to mask non-target source using photutils

### ISSUE THREAD

**Issue by bijusaha-astro** [astropy/photutils#1619]
I have a FITS file of 1000 x 1000 dimensions, including a galaxy (target object) at the center along with various other background and foreground stars. I wish to mask all other objects except my target object. I have started doing this by labelling every objects by following the segmentation and deblending approach. Now I need to mask all other non-target sources with some random background value, leaving the target galaxy. 

Any suggestion regarding how to go about this would be helpful.

**Comment by larrybradley** [comment]
@bijusaha-astro The `SegmentationImage` object has several methods for modifying the segmentation image, such as `keep_labels()` where you can keep only a single or subset of labels:  https://photutils.readthedocs.io/en/latest/segmentation.html#modifying-a-segmentation-image

Further, the `Segmentation` `data` attribute gives you a 2D array, from which you can create a boolean mask.

**Comment by larrybradley** [comment]
Hopefully this suggestion helped.  Please feel free to post here if you have other questions.
