### ISSUE TITLE
No module named 'numpy.lib.index_tricks' (numpy 2.0)

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1620]
Saw it this morning over at Jdaviz using numpy nightly wheel.

```
.../photutils/__init__.py:16: in <module>
    from . import background
.../photutils/background/__init__.py:7: in <module>
    from .background_2d import *  # noqa: F401, F403
.../photutils/background/background_2d.py:15: in <module>
    from numpy.lib.index_tricks import index_exp
E   ModuleNotFoundError: No module named 'numpy.lib.index_tricks'
```

https://github.com/astropy/photutils/blob/5d8795814b07654541eaa7ddde9031c481eb246f/photutils/background/background_2d.py#L15C13-L15C13

Hard to tell from https://github.com/numpy/numpy/pull/24581 but looks like all you need to do is use `numpy.index_exp` directly? Maybe it is even backward compatible.

**Comment by larrybradley** [comment]
Yes, I'm aware and working on this and other NumPy 2.0 deprecations.
