### ISSUE TITLE
How is the PSFPhotometry 'flux_err' calculated?

### ISSUE THREAD

**Issue by Sfosch** [astropy/photutils#1631]
Hi!

I'm converting my aperture-photometry scripts to a `PSFPhotometry `procedure. I'm quite new to this way of doing photometry.
Thanks to the nice tutorials available I was able to obtain an `ePSF `and fit my data nicely.

However, I don't find a documentation on how the '`flux_err`' is obtained. 
Is it possible to have more information about this fit output and how is it calculated? 
I think this is important in order to correctly constrain the precision of my targets magnitudes.

Tell me if you need more information.
Thanks!
Clear skies,
Sacha

**Comment by larrybradley** [comment]
Please re-open if I didn't answer your question.
