### ISSUE TITLE
unable to upgrade to latest Photutils version

### ISSUE THREAD

**Issue by bijusaha-astro** [astropy/photutils#1639]
Hello,

I had Photutils version 0.4 (as I figured out using the command photutils.test(), assuming this is the correct method). I have attached a screenshot of the output, which mentions that photutils version in 0.4. 

In order to resolve the "radial gradient computation" error, mentioned in one of the earlier issues, I want to switch to 0.7 or later versions. I employed the upgrade commands (Using pip: pip install --upgrade photutils. For conda: conda update photutils) and then ran the photutils.test(), which still shows the same 0.4 version (refer to the same screenshot).

How do I understand if at all, my photutils was upgraded? If not, how do I upgrade it to later versions?

![Screenshot from 2023-10-08 12-05-47](https://github.com/astropy/photutils/assets/101668391/7b80ae8c-b253-401c-9a22-74d41d5eb98f)

**Comment by larrybradley** [comment]
@bijusaha-astro Your screenshot indicates you are using a very old version of Python (2.7).  Photutils v0.4.1 was the last version that was compatible with Python 2.7.  If you want a newer version of Photutils, you will need to first upgrade your Python version.
