### ISSUE TITLE
How to use custom PSF models

### ISSUE THREAD

**Issue by Firestar-Reimu** [astropy/photutils#1644]
I have a SDSS image and I want to subtract the stars from a galaxy

![Screenshot_20231029_100334](https://github.com/astropy/photutils/assets/65082432/770c43f3-412d-48c2-b131-6a1555b88987)

SDSS PSF model is like this:

$${\rm PSF} = \exp{\left(-\frac{1}{2}(r/\sigma_1)^2\right)} + b \exp{\left(-\frac{1}{2}(r/\sigma_2)^2\right)} + p_0 \left(1+ \frac{1}{\beta}\left(\frac{r}{\sigma_p}\right)^2\right)^{-\beta/2}$$

https://www.sdss4.org/dr17/imaging/images/#PSFData

And I have all values of parameters.

But `photutils` seems to have no function to use custom PSF models.

**Comment by Firestar-Reimu** [comment]
Also, how to use `PSF` from FITS files like [DESI](https://www.legacysurvey.org/viewer/coadd-psf/?ra=349.6259&dec=18.6890&layer=ls-dr9-south)

**Comment by larrybradley** [comment]
@Firestar-Reimu You can create a custom astropy model from a user-defined function using https://docs.astropy.org/en/stable/api/astropy.modeling.custom_model.html.
Then you can use `make_psf_model` (requires photutils 1.10.0) to make a PSF model (https://photutils.readthedocs.io/en/latest/api/photutils.psf.make_psf_model.html) that can be used with `PSFPhotometry`.

To use a 2D array as a PSF, use `FittableImageModel`:  https://photutils.readthedocs.io/en/latest/api/photutils.psf.FittableImageModel.html
