### ISSUE TITLE
Add wcs parameter to photutils.morphology.data_properties()

### ISSUE THREAD

**Issue by rgkey** [astropy/photutils#1645]
Hi, a small suggestion to the morphology functionality.

It would be great to allow `data_properties` to take a WCS convention/header, since `data_properties()` returns a `source_catalogue()` with SkyCoordinate attributes. This would allow the user to apply `data_properties` across a known list of objects in a crowded field, and quickly return the morphology of objects, but with the sky coordinates of the centroids returned for tracebacks.

**Comment by larrybradley** [comment]
Thanks, @rgkey .  This was added in #1648 and will appear in the next release.
