### ISSUE TITLE
test_interpolate_missing_data fails on i386

### ISSUE THREAD

**Issue by olebole** [astropy/photutils#1671]
On i386, **test_interpolate_missing_data** fails on the installed package with 1.10.0:
```
________________________ test_interpolate_missing_data _________________________

    @pytest.mark.skipif(not HAS_SCIPY, reason='scipy is required')
    def test_interpolate_missing_data():
        data = np.arange(100).reshape(10, 10)
        mask = np.zeros_like(data, dtype=bool)
        mask[5, 5] = True
    
        data_int = _interpolate_missing_data(data, mask, method='nearest')
        assert 54 <= data_int[5, 5] <= 56
    
        data_int = _interpolate_missing_data(data, mask, method='cubic')
>       assert data_int[5, 5] == 55
E       assert 54 == 55

/usr/lib/python3/dist-packages/photutils/psf/tests/test_utils.py:69: AssertionError
```
[Full test log](https://ci.debian.net/data/autopkgtest/testing/i386/p/photutils/40218498/log.gz). This is a regression, it did not happen on 1.9.0. Also, ARM/32 bit passes.

**Comment by larrybradley** [comment]
Thanks for reporting this.  This failure is from a test I recently added to increase coverage.  The code itself was unchanged -- it's just a "bad" test.  Apparently the `scipy.interpolate.CloughTocher2DInterpolator` results are machine-dependent.
