### ISSUE TITLE
Forced photometry with fixed position still seems to be fitting a position

### ISSUE THREAD

**Issue by aarranshaw** [astropy/photutils#1678]
Has anybody had this issue? 

photutils 1.10.0
astropy 6.0.0

I have a situation where, in some cases, I need to fix the x_0 and y_0 position of my psf and just fit for flux. A snippet of my code:

`pos = Table(names=["x_0", "y_0", "flux_init"], data=[(xout,), (yout,), (ap_out["counts_bkgsub"][0],)])`
`psf.x_0.fixed = True`
`psf.y_0.fixed = True`

Where `xout`, `yout` and `ap_out["counts_bkgsub"][0]` are just my initial x, y and flux values and `psf` is a photutils compatible model output from WebbPSF. I run PSFPhotometry like so:

`photometry = PSFPhotometry(`
            `grouper=None,  #no grouper needed, one well-defined source`
            `localbkg_estimator=None,`
           ` psf_model=psf,`
           ` fitter=fitter,`
            `fit_shape=(fitbox,fitbox),`
            `aperture_radius=r[f[0].header["FILTER"]]`
       ` )`

`result_tab = photometry(data=data.data[i]-apphot_bg, init_params=pos, mask=dq.data[i] > 0)`

And my output (just one example) looks like the following, even with psf.x_0.fixed set to True (Highlighted x_0, y_0 and x_fit, y_fit):

`id group_id local_bkg       **x_init           y_init**         flux_init           **x_fit             y_fit**            flux_fit      x_err y_err      flux_err      npixfit group_size        qfit                cfit         flags
--- -------- --------- ----------------- --------------- ----------------- ----------------- ----------------- ------------------ ----- ----- ------------------ ------- ---------- ------------------ -------------------- -----
  1        1       0.0 **82.54984351468708 84.413051744848** 66.68241135466099 **83.00775477794804 84.52412607853876** 193.02504841041116   nan   nan 45.951291469995844     118          1 2.2353772326890318 -0.17924899612524195     1

Note how the error on x and y is nan, as if they _have_ been fixed, but x_fit and y_fit differ from their initial values, as if they _haven't_ been fixed

I'm at a loss as to how to fix this right now, so I thought I'd post an issue and see if anybody else had experienced this. Just a note, fixing psf position with almost the same code worked fine in 1.8.0.

Thanks in advance, sorry if my formatting sucks but hopefully it's readable :)

**Comment by larrybradley** [comment]
@aarranshaw PSF-fitting relies on the Astropy modeling framework to fix the PSF model parameters.  What are you using for your PSF model?  You can also double-check the fixed parameters with `print(psf.fixed)`.  Is `psf.fixed` the same before and after you run PSF photometry?

Here's a quick example of forced PSF photometry on a single source.  The x and y fit parameters are the same as the initial parameters:  
https://gist.github.com/larrybradley/5746ea3a4f9a7892397d223b3e3d485f

**Comment by aarranshaw** [comment]
Hi @larrybradley, thanks for the quick response.

My PSF model is a GriddedPSFModel output from WebbPSF:

`<photutils.psf.griddedpsfmodel.GriddedPSFModel>`
`Detector: ('NRCB1', 'Detector name')`
`Filter: ('F070W', 'Filter name')`
`Grid_shape: (1, 1)`
`Number of ePSFs: 1`
`ePSF shape (oversampled pixels): (404, 404)`
`Oversampling: (4, 4)`

And `psf.fixed` shows `{'flux': False, 'x_0': True, 'y_0': True}` both before and after I run the PSF photometry. Could it be something to do with the WebbPSF output I use?

**Comment by larrybradley** [comment]
@aarranshaw Thanks for responding. I can reproduce this using a `GriddedPSFModel`.  I'll have a fix soon.

**Comment by aarranshaw** [comment]
@larrybradley thank you so much, I will keep an eye on this thread.

**Comment by larrybradley** [comment]
@aarranshaw Thanks again for reporting this.  It's fixed in #1679.  You can install the dev version of photutils to test it:  

`pip install "photutils[all] @ git+https://github.com/astropy/photutils.git"`

**Comment by aarranshaw** [comment]
@larrybradley Everything works perfectly, thank you for solving this so quickly!
