### ISSUE TITLE
FEAT: Nightly dev wheel

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1689]
Since this package has C-extension, might be nice to have a nightly dev wheel uploaded like `astropy`, so downstream packages (e.g., acstools, jdaviz) do not have to build photutils from source for their devdeps jobs.

Maybe a simpler version of https://github.com/astropy/astropy/blob/main/.github/workflows/publish.yml

Will need @astrofrog's help to set up the upload destination. 🙏

**Comment by bsipocz** [comment]
I would strongly advocate for an openastronomy destination, that could host astropy, sunpy, pyerfa, photutils, regions, etc. 

x-ref: cc @nabobalis and https://github.com/scientific-python/upload-nightly-action/issues/50

**Comment by pllim** [comment]
astropy already has an established and advertised location, so I probably won't move that. But other packages downstream sharing a space will be nice, if quota isn't an issue.

**Comment by bsipocz** [comment]
> astropy (and pyerfa) already has an established and advertised location

that can also still nicely changed. As the pyerfa stuff is still not at all trivial or intuitive (and got used more widely only in the past month or so)

**Comment by pllim** [comment]
Re: astropy and/or pyerfa -- If it can have redirect, would be nice. Otherwise, will have to carefully plan the transition. Also pyerfa is technically not part of Astropy (it is upstream, so need to ask pyerfa devs).

**Comment by bsipocz** [comment]
> pyerfa is technically not part of Astropy

Thus the "openastronomy" umbrella. As in practice as an astropy downstream user we only need the pyerfa wheel as astropy is otherwise incompatible, we have absolutely no direct or indirect usage of it.

**Comment by pllim** [comment]
Let me ping pyerfa (https://github.com/liberfa/pyerfa) devs: @avalentino @mhvk @astrofrog

**Comment by mhvk** [comment]
Definitely a good idea to have all the packages in a single location! (Though easy to say as I'm not sure how to actually do it...)

**Comment by larrybradley** [comment]
@pllim Is there any interest in creating a shared location for astropy affiliated packages?  Or should I close this?

**Comment by pllim** [comment]
> creating a shared location for astropy affiliated packages?

@astrofrog owns the space where astropy core nightly wheel goes. He also set up pyerfa nightly wheel (separately). So he would be the best person to answer this.

**Comment by larrybradley** [comment]
@astrofrog Do you have any plans to set this up?  I know of a few packages that would benefit from having nightly `photutils` wheels.

**Comment by astrofrog** [comment]
I'm happy to give it a go this week.

**Comment by larrybradley** [comment]
Added in #1834.  Currently the schedule is for a weekly dev build.
