### ISSUE TITLE
Centroids (photutils.centroids) uncertainty 

### ISSUE THREAD

**Issue by Istwan93** [astropy/photutils#1692]
There is no way to get the uncertainty from the Centroids (photutils.centroids) function. I need to be able to retrieve uncertainty due to using the tool to measure velocities requiring an amount of error to be documented. I have dug through so much documentation and am completely lost. Please help.

**Comment by larrybradley** [comment]
@Istwan93 As you've discovered, none of the centroid functions return a propagated uncertainty yet.  If you are using a center-of-mass centroid, here's one way to calculate the uncertainty:  https://sextractor.readthedocs.io/en/latest/Position.html#position-uncertainties-errx2-erry2-errxy-erra-errb-errtheta-errcxx-errcyy-errcxy
