### ISSUE TITLE
Make aperture_funcs.py into a Cython file

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#170]
Inspired by https://github.com/astropy/photutils/pull/169, I think we can maybe do a lot of optimization in aperture_funcs by having the loop over positions be cythonized. As https://github.com/astropy/photutils/pull/169 also showed, this has to be done carefully to actually see benefits. This is low priority, but could be a fun project at some point.

**Comment by larrybradley** [comment]
Closing since `aperture_funcs` no longer exists after the refactors in #446 and #453.
