### ISSUE TITLE
Higher Order Deviation from Ellipse

### ISSUE THREAD

**Issue by eckerl** [astropy/photutils#1722]
Hi,

I am using Photutils extensivly to perform photometric analysis and i am quite happy with your program. I recently encountered a really boxy galaxy, so the normal isophotes left a "cross" pattern in the center. By setting "high_harmonics= True" i thought this will change since i am measuring significant a4,b4 parameters. Unfortunatly visually nothing seemed to change. I subtracted the normal elliptical_isophotes from the ones by setting "high_harmonics=True" and the Residuals are minimal. For me it seems like the measurement of the higher harmonics is correct but the build_ellipse_model does not cover it. I wanted to ask if someone/you runs into the same problems by fitting boxy isophotes or not. Any help would be super nice.

Best regards

**Comment by larrybradley** [comment]
@eckerl From a quick look at the code, it appears the higher harmonics are included in `build_ellipse_model`.  https://github.com/astropy/photutils/blob/main/photutils/isophote/model.py#L120

Could you please provide a simple example showing your issue so that I can investigate further?

**Comment by larrybradley** [comment]
@eckerl Your issue may be related to #1776.  Would you be willing to share an example to verify that and to use as a test case?

**Comment by larrybradley** [comment]
@eckerl This was fixed in #1810. Please report back if you still have issues. Thanks.
