### ISSUE TITLE
Tar-ball on PyPI

### ISSUE THREAD

**Issue by kinoshitadaisuke** [astropy/photutils#1723]
Hello,

Tar-ball files of source code of previous versions of photutils on PyPI are named as photutils-1.11.0.tar.gz, photutils-1.10.0.tar.gz, photutils-1.9.0.tar.gz, etc.
But, the one for version 1.12.0 is named as photutils-1.12.tar.gz.
Is the file name for version 1.12.0 is intended to be photutils-1.12.tar.gz?

thank you,

Daisuke

**Comment by larrybradley** [comment]
The source tarball and wheels are built and uploaded to PyPI by an automated GitHub Action workflow.  I'm not sure why in this case it removed the `.0` from the source tarball (but not the wheels).  However, it is the correct file:
https://github.com/astropy/photutils/actions/runs/8667792853/job/23771641408#step:4:32

**Comment by kinoshitadaisuke** [comment]
Thank you for the information.

**Comment by saimn** [comment]
Setuptools issue it seems: https://github.com/pypa/setuptools/issues/4302

**Comment by larrybradley** [comment]
Thanks, @saimn!
