### ISSUE TITLE
photutils.detection.DAOStarFinder magnitude and flux error

### ISSUE THREAD

**Issue by ferromatteo** [astropy/photutils#1724]
Hello, is there a way to easily compute the error associated with the magnitude and flux for every detected source from DAOStarFinder? I'm fairly new to photutils so I maybe missed it.

**Comment by navii98** [comment]
Hi! In case this information is still useful, you will need to perform aperture photometry on the targets you find using DAOStarFinder.
Have a look at - https://photutils.readthedocs.io/en/stable/aperture.html

**Comment by larrybradley** [comment]
@ferromatteo Using the x, y centroids returned by the star finder, you could then perform aperture photometry (as suggested by @navii98), or if you have a PSF model, you could perform PSF-fitting photometry (https://photutils.readthedocs.io/en/latest/psf.html).
