### ISSUE TITLE
PyPI Source Distribution has incorrect version

### ISSUE THREAD

**Issue by Hellseher** [astropy/photutils#1727]
Hi,

While upgraded the full chain of Astronomical packages in Guix I've notices that
source distribution of `photutils` does not have (1.12) the same version as Built
Distributions (1.12.0)

See screenshot:
![Screenshot from 2024-04-17 23-13-59](https://github.com/astropy/photutils/assets/6786129/15dafa78-57e5-4876-8d5b-1bc56436067f)

https://pypi.org/project/photutils/#files

Thanks,
Oleg

**Comment by larrybradley** [comment]
It is the correct source file.  Please see https://github.com/astropy/photutils/issues/1723.  This was due to an issue in `setuptools`.
