### ISSUE TITLE
Have datasets use Quantity with units, or at least test that this works

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#173]
While looking at the notebook @larrybradley made in #160 I noticed the `photutils.datasets` subpackage.  I also noticed that this package does not seem to be using units at all.

I think it would be extremely valuable if the units of the output images at least had the option of appropriate units.  E.g., a `flux` input should actually _be_ units of flux (or at least something that astronomers recognize as flux-like).  

It may not make sense to have this forced into the `datasets` functions, as sometimes you may want `adu` and other times actual flux units... But I think it would be valuable to make sure this works, and examples should make use of it so users are exposed to how `units` can make things easier.

A more general question for @larrybradley and @cdeil that may or may not be closely tied to this: I have some code that does something like this for my own work, but it also does things like allowing you to specify extra bits like read noise and telescope aperture, and then makes sure all the units are consistent.  Should I try to adapt this into `datasets`?  Or should there be another photutils module along the lines of "simulated images"?

**Comment by larrybradley** [comment]
Not sure if this is still relevant 6 years later.... :)  Feel free to submit a PR to add something like `MockImage` to create realistic simulated images.
