### ISSUE TITLE
Calculating FWHM on bad photo iterates way too long

### ISSUE THREAD

**Issue by PieterVuylsteke** [astropy/photutils#1775]
I am using Photutils version 1.11.0 in a windows environment.

When I analyse a timeseries of photo's it can happen that there are bad photo's in the series. 
Asking for the value of FWHM on an Aperture can then take gigantically long. 

After some searching it appears the while loop in stats.py, _covariance routine is the culprit.

Just before the while loop I added this code :    
if covar_det < -1000:
         covar = [[None,None],[None,None]]
         return covar

In my case the covar_det was -48988638457.28642, so that would have taken extremely long.

**Comment by larrybradley** [comment]
@PieterVuylsteke Many thanks for reporting this.  I'm preparing a fix.  Could you please share an image with a short example that I can use as a test case?  I'm having a hard coming up with an example image that triggers this loop.  Thanks!

**Comment by PieterVuylsteke** [comment]
@larrybradley : do you still need an example ? I have a bit difficulty for the moment to find one, and I see you solved the issue ?

**Comment by larrybradley** [comment]
The issue should be fixed.  Please let me know if you find any issues in the next release (1.13.0).  Thanks again.
