### ISSUE TITLE
Error/gain API

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#178]
In the discussion of https://github.com/astropy/photutils/pull/160, @cdeil suggests removing the `gain` parameter.  In the photometry routines, `gain` is currently used with a background-only `error` to compute the total `error`, including the Poisson noise of the sources:

`error_tot = np.sqrt(error_b**2 + (data / gain))`

where `error_b` is the "background" error (really all sources of error except source Poisson error) and `gain` (not CCD gain) is a conversion factor when multiplied by the data puts the data in count units (e.g. electrons or photons) where Poisson statistics can be applied.

A function could be provided to compute `error_tot` from `error_b` and `gain`.  We could then remove the `gain` parameter and require the photometry routines to accept only the total `error`.

However, the detection routines (e.g. `detect_sources`) require an `error` input that is *only* the "background" error.  This is because source detections are determined by a significance level above the background noise.  Without a `gain` parameter, one would need to carry around both the background-only error array (e.g., `background_rms`) for the detection routines and a total `error` array for the photometry routines.  In this case, I also think the error input parameters for detection and photometry routines should have different names to limit potential confusion.

Any thoughts about which is preferable?

**Comment by hamogu** [comment]
The point about photometry applies to both aperture photometry and PSF photometry. When this point is addressed, both interfaces need to be adapted and there should be one functions that calculates the error to be used for both of them.

**Comment by larrybradley** [comment]
@hamogu So are you in favor of my suggestion to:

1.  Remove the `effective_gain` parameter from the current photometry routines (aperture, PSF, segmentation-based isophotal, etc.).
2.  Create a separate function to calculate total error from background error and `effective gain`.

It simplifies the code, but the downside is that it changes the user API a bit.

**Comment by hamogu** [comment]
Yes, I am in favour. I think we are still in the phase of improving without an explicit promise of a stable API for such advanced features.

**Comment by larrybradley** [comment]
OK, I'll make these changes.  Yes, we've clearly stated in the docs that we will change the API if something can be done better.

**Comment by hamogu** [comment]
Maybe give it a day until #159 is merged, which has the changes in the PSF stuff. (@eteq is working on it right now).

**Comment by mwcraig** [comment]
fyi, there is also this in astropy: [astropy.stats.signal_to_noise_oir_ccd](http://astropy.readthedocs.org/en/stable/api/astropy.stats.signal_to_noise_oir_ccd.html#astropy.stats.signal_to_noise_oir_ccd)

Not exactly what you need here but might be nice to have all of these sorts of functions in one place (ping @crawfordsm).

**Comment by larrybradley** [comment]
Thanks, @mwcraig, but that's different.  I actually already added the needed function to `photutils` a while back (http://photutils.readthedocs.org/en/latest/api/photutils.utils.calculate_total_error.html#photutils.utils.calculate_total_error).  It was used internally in some `photutils` functions, but not all.

**Comment by larrybradley** [comment]
Implemented in #368.
