### ISSUE TITLE
Implement more robust tests for exact aperture photometry

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#18]
As demonstrated in #12 and #17, some bugs in the exact algorithms only appear when the aperture has a particular alignment on the grid, i.e. when pixel vertices end up on special locations relative to the aperture, for example on the edge of the aperture. We need to implement more tests for these 'special' positions to ensure that these do not cause any issues.

**Comment by bsipocz** [comment]
The exact geometries are being moved to regions, so I suggest to close this issue here. If it's still relevant, then please @astrofrog move it over to region and reopen.
