### ISSUE TITLE
Limit offsets when fitting

### ISSUE THREAD

**Issue by keflavich** [astropy/photutils#1801]
As noted in #1799, it is possible to limit the flux to be positive by setting the model flux min to be zero:
```python
    dao_psf_model.flux.min = 0
```

which is useful for rejecting negative sources during fitting.

I'd like a mechanism to do the same for `x_0` and `y_0`, but restricting those parameters doesn't work since they need to be set to the local x,y value.  Instead, the limits need to be set independently for each source.  I think that could be accommodated in `make_psf_model`.

One use case is very crowded fields:  I've seen DAOFind-found peaks close enough that they jump within the 5x5 fit zone onto another star's peak.  

A workaround I'll try (but expect to have limited success with) is grouping.

**Comment by larrybradley** [comment]
@keflavich I'm considering adding a keyword (`bound_xy = True | False`) to `PSFPhotometry` and `IterativePSFPhotometry` which would bound the fitted x, y position to be within the `fit_shape` region.  Would that work for you, or would you want to have x/y bounds that are different than `fit_shape`?

**Comment by keflavich** [comment]
I'd also want x/y bounds that are different than fit shape in some cases: specifically, in crowded fields, specifying that x,y can't be larger than 1 pixel would be useful.

**Comment by larrybradley** [comment]
Good to know.  I can add something like a `bound_shape` keyword.

**Comment by larrybradley** [comment]
Would you ever want asymmetric bounds on x/y or is a simple shape (which will be centered on the "central" pixel) sufficient?

**Comment by keflavich** [comment]
It seems pretty unlikely that I'd want asymmetric bounds.  I'm sure that case exists in theory, but probably in practice is only for detectors with asymmetric pixels... which I don't think are ever used.  So, yeah, let's run with simple shape.

**Comment by larrybradley** [comment]
Related -- would you ever want the x and y bounds to be different?

**Comment by keflavich** [comment]
I could imagine it, but unlikely.

A more realistic need, though, is for a tied constraint - that (x^2 + y^2), i.e., the radial distance, is less than some value.  Would that be more straightforward than imposing a 2D shape?

**Comment by larrybradley** [comment]
Bounded constraints are much easier than tied constraints.  And IIRC, tied constraints will slow down the fitting.

**Comment by keflavich** [comment]
Yeah, that sounds right to me, though it's been a long time since I looked into the guts of lmfit.  So, fine, allow bounds, don't try to tie them.
