### ISSUE TITLE
cannot import name '<class_name>' from 'photutils.<folder>' 

### ISSUE THREAD

**Issue by dornyx** [astropy/photutils#1803]
Hi. I'm having some **issues in importing some classes** into my Jupyter notebook. I'm using latest VSCode stable release on Ubuntu 22.04 LTS on Intel machine. I use **conda**, so I've tried installing Photutils both as:
```
conda install -c conda-forge photutils
conda install -c conda-forge photutils[all]
```
I've just removed the astropy packages and retried the installation but errors keep on popping up.

Other relevant installed packages are:
```
python                    3.11.6          hab00c5b_0_cpython
asdf-astropy              0.6.0              pyhd8ed1ab_0    conda-forge
astropy                   6.0.0           py311h1f0f07a_0    conda-forge
astropy-healpix           1.0.2           py311h1f0f07a_1    conda-forge
astropy-iers-data         0.2024.2.12.0.31.0    pyhd8ed1ab_0    conda-forge
pytest-astropy            0.11.0             pyhd8ed1ab_0    conda-forge
pytest-astropy-header     0.2.2              pyhd8ed1ab_0    conda-forge
numpy                     1.24.3          py311h08b1b3b_1  
numpy-base                1.24.3          py311hf175353_1  
numpydoc                  1.5.0           py311h06a4308_0
photutils                 1.8.0           py311h1f0f07a_0    conda-forge
```

The problematic lines of code are:
```
from photutils.psf.photometry import PSFPhotometry
from photutils.background import LocalBackground
```
Before them in the Jupyter I have:
```
import numpy as np
import pandas as pd
import os
from typing import Tuple
from pathlib import Path
from scipy import optimize
from astropy.io import fits
from astropy.table import Table
from astropy.stats import mad_std, SigmaClip, sigma_clipped_stats
import matplotlib.pyplot as plt
%matplotlib inline
from photutils.detection import DAOStarFinder
from photutils.aperture import aperture_photometry, CircularAperture, CircularAnnulus, ApertureStats
from photutils.profiles import CurveOfGrowth, RadialProfile
from photutils.psf.models import IntegratedGaussianPRF
```

The **errors** I'm getting are these ones:
```
ImportError: cannot import name 'PSFPhotometry' from 'photutils.psf.photometry'
ImportError: cannot import name 'LocalBackground' from 'photutils.background'
```
I've taken a look in the respective directories and in the whole directory of Photutils, but I couldn't find files containing "PSFPhotometry" or ¨LocalBackground" or using the variables "inner_radius" and "outer_radius" (needed for LocalBackground?).
It does look like installing through conda doesn't download all the needed files for a fully working and complete installation.
Please, tell me straightaway if I did anything wrong and help me find a solution/mitigation.

**Comment by larrybradley** [comment]
@dornyx Your installation version of `photutils` is version 1.8.0.  The `PSFPhotometry` and `LocalBackground` classes were introduced in version 1.9.0.

In a clean environment `conda install -c conda-forge photutils` should install the latest version (1.12.0).   I would recommend starting again from a fresh environment.  You could also try updating photutils with `conda update -c conda-forge photutils`.  `conda list photutils` will list the installed version.

**Comment by dornyx** [comment]
> @dornyx Your installed version of `photutils` is version 1.8.0. The `PSFPhotometry` and `LocalBackground` classes were introduced in version 1.9.0.
> 
> In a clean environment `conda install -c conda-forge photutils` should install the latest version (1.12.0). I would recommend starting again from a fresh environment. You could also try updating photutils with `conda update -c conda-forge photutils`. `conda list photutils` will list the installed version.

Looks like conda installs the 1.8.0 version and considers it as the newest. Installing through pip in the same conda environment installed the correct version. Looks like the conda-forge channel is maybe a little behind...?

**Comment by larrybradley** [comment]
I just tried it, and I get `1.12.0` (which is actually behind by one version; 1.13.0 is the latest).  Not sure why you got 1.8.0.

https://anaconda.org/conda-forge/photutils

**Comment by dornyx** [comment]
> t). Not sure why you got 1.8
I don't know. I've got around the problem by using **pip**, but I had tried fresh install via **conda-forge** a couple of times today and always got the same issue, every time. I hope this has been useful to someone else.

Thank you very much for the support and keep up the great work!
