### ISSUE TITLE
Docs missing definition of wcs in aperture photometry overview

### ISSUE THREAD

**Issue by havijw** [astropy/photutils#1814]
In the section [Converting Between Pixel and Sky Apertures](https://photutils.readthedocs.io/en/stable/aperture.html#converting-between-pixel-and-sky-apertures) in the aperture photometry overview documentation, the example usage of `Aperture.to_sky` and `SkyAperture.to_pixel` use a variable `wcs` that is not defined anywhere. Both cases are introduced as _examples_ of how `to_sky` and `to_pixel` could be used with a WCS object. However, it's not possible to run the code as written and the tutorial could be improved by constructing a basic WCS object.

**Comment by larrybradley** [comment]
@havijw Thanks.  I've added a mock `wcs` to the aperture docs in #1814.
