### ISSUE TITLE
Cannot install current master

### ISSUE THREAD

**Issue by hamogu** [astropy/photutils#183]
I cannot compile the current master of photutils.
Given that it passes on Travis, that must mean that something on my configuration is missing...
But what?
@astrofrog 

```
moritz@moritz-laptop:~/photutils$ git checkout master
Switched to branch 'master'
moritz@moritz-laptop:~/photutils$ python setup.py build
Freezing version number to photutils/version.py
running build
running build_py
copying photutils/psf.py -> build/lib.linux-i686-2.7/photutils
copying photutils/version.py -> build/lib.linux-i686-2.7/photutils
running build_ext
cythoning photutils/geometry/circular_overlap.pyx to photutils/geometry/circular_overlap.c

Error compiling Cython file:
------------------------------------------------------------
...
# Licensed under a 3-clause BSD style license - see LICENSE.rst

# The functions defined here allow one to determine the exact area of
# overlap of a rectangle and a circle (written by Thomas Robitaille).

from __future__ import (absolute_import, division, print_function,
                       ^
------------------------------------------------------------

photutils/geometry/circular_overlap.pyx:6:24: future feature absolute_import is not defined
building 'photutils.geometry.circular_overlap' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c photutils/geometry/circular_overlap.c -o build/temp.linux-i686-2.7/photutils/geometry/circular_overlap.o
photutils/geometry/circular_overlap.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
```

I am using system python on Ubuntu with the following versions:

```
Python 2.7.3 (default, Feb 27 2014, 20:00:17) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import Cython

In [2]: Cython.__version__
Out[2]: '0.15.1'
```

**Comment by rmjc** [comment]
I believe I'm having a similar issue, except I'm running Cython 0.21.2. When I try to install photultils via pip install --no-deps photutils, I get the following Cpython error:

    Downloading/unpacking photutils
    Running setup.py egg_info for package photutils
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    
    Installing collected packages: photutils
    Running setup.py install for photutils
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    cythoning photutils/geometry/circular_overlap.pyx to photutils/geometry/circular_overlap.c
    warning: /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/Cython/Includes/numpy.pxd:868:17: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/Cython/Includes/numpy.pxd:868:24: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                    # need to call releasebuffer
                    info.obj = self
    
                if not hasfields:
                    t = descr.type_num
                    if ((descr.byteorder == '>' and little_endian) or
                                           ^
    ------------------------------------------------------------

    /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/Cython/Includes/numpy.pxd:254:40: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).

**Comment by cdeil** [comment]
@rmjc That looks like an issue with your Python / Numpy / Cython installation (not exactly sure what the issue is though), I don't think there's anything in Astropy / Photutils we can change to fix this.

EPD 7.3 is a few years old ... you could try to get help with this issue from Enthought, but if at all possible my suggestion would be you install a new Python and all the packages you like using Anaconda or Macports or Enthought Canopy (see http://www.astropy.org/#osx). If you don't want to investigate and try these options, my suggestion would be to go get Anaconda.
