### ISSUE TITLE
Ensuring Consistent Galaxy Sampling for SED Fitting Across Photometric Bands

### ISSUE THREAD

**Issue by andreea-varasteanu** [astropy/photutils#1867]
Hi there,

I’m working on fitting a consistent SED for a galaxy, and I’m concerned about ensuring that I’m sampling the same parts of the galaxy across different photometric bands.

Initially, I’ve taken the approach of fitting a double Sérsic model to the surface brightness profile, correcting this to face-on values using the axis ratio b/a and using uniform spacing based on the K band semi-major axes (smas).
However, I’m uncertain whether this approach ensures that I’m actually measuring the same physical regions of the galaxy in all bands. Would this method actually be adequate for ensuring that the SED fitting is consistent ?

Alternatively, I’m considering placing elliptical apertures based on the K band geometry (fixing position angle and ellipticity) and adjusting for inclination at each step. I would appreciate any advice on whether this would be a better method, or if there are other approaches that could further improve consistency in my SED fitting.

Thanks for your insights!

**Comment by larrybradley** [comment]
@andreea-varasteanu I don't have insight into which is the better approach.  More generally, this appears to be a general data analysis question.  This GitHub issue tracker is for issues and bugs about the specific `photutils` software package.  Your question is better suited to a general Astronomy/data analysis help desk, so I'm closing this issue.  Perhaps the "Python users in Astronomy" group (although I'm not even sure this is a Python question) or Astronomy/Physics Stackoverflow are better forums.  Feel free to reopen if you have a specific `photutils` issue to report.
