### ISSUE TITLE
TST: Use paid runner for aarch64

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#1883]
Requested by @larrybradley in https://github.com/astropy/astropy/issues/16565#issuecomment-2354071908 but I wanted to wait and see the cost from `astropy` alone first before unleashing this to other repos. So please ping me in a few weeks. If you want to wait till end of the year to see how `astropy` feature freeze would impact things, also acceptable. If you don't ping me, I will likely forget.

Action items:

- [x] Decide if the paid runner has enough money left for another repo.
- [x] Decide if `photutils` can use it sparingly in a way that is cost effective.
- [x] If yes, then Astropy org admin will have to add `photutils` to the list of allowed repos for the paid runner.
- [x] Then, `photutils` maintainer will have to do something like https://github.com/astropy/astropy/pull/17024 to actually use it.

Out of scope: Building aarch64 wheels for release.

**Comment by pllim** [comment]
@larrybradley , I enabled this runner for photutils. Please see https://github.com/astropy/astropy/blob/f7dc2aaa27fe8f43d1dae3e277d5d7a05e74d35b/.github/workflows/ci_cron_weekly.yml#L175 on example usage. Good luck.

**Comment by larrybradley** [comment]
Thanks, @pllim!  PR: #1893.
