### ISSUE TITLE
Math explanation in `ApertureStats.sum_err` docstring

### ISSUE THREAD

**Issue by qiushitian** [astropy/photutils#1888]
Docstring of `ApertureStats.sum_err` in [photutils/aperture/stats.py](https://github.com/astropy/photutils/blob/3064f3eafc383f02e0e01f9fa4ebd6b0fd4e4a5f/photutils/aperture/stats.py) reads:

> ``sum_err`` is the quadrature sum of the total errors over the unmasked pixels within the aperture:
> 
> $$\Delta F = \sqrt{\sum_{i \in A} \sigma_{\mathrm{tot}, i}^2}$$
> 
> where **$\Delta F$ is the `sum`**, $\sigma_{\mathrm{tot, i}}$ are the pixel-wise total errors (``error``)

I believe $\Delta F$ is supposed represent `sum_err`, not `sum`. Is that right?

**Comment by larrybradley** [comment]
Thanks for reporting this!  It's fixed in #1889.
