### ISSUE TITLE
Source catalogue to_table method giving RepresenterError

### ISSUE THREAD

**Issue by jensmelinder** [astropy/photutils#1952]
I'm trying to output the results from SourceCatalog into a Qtable with the to_table method using columns that are not the defaults.
(Photutils v 2.0.2)

The output fails giving me the error:
`RepresenterError: ('cannot represent an object', 'eccentricity')`

(removing eccentricity from the list of columns to include leads to other columns raising the same error, e.g. area, orientation and so on)

This is the code I use to get the source catalog and table:
```
scat = SourceCatalog(data_det, segmap_debl, convolved_data=None, error=err_det, mask=mask_det==0, wcs=wcs)
outcols = ['label', 'xcentroid_win', 'ycentroid_win', 'sky_centroid_win', 'area', 'semimajor_sigma', 'semiminor_sigma', 'eccentricity', 'orientation', 'segment_flux', 'segment_fluxerr']
dettab = scat.to_table(columns=outcols)
```
Using the default column names works fine (`scat.to_table()`) and outputs the offending columns just fine. But I need some of the non-default outputs as well. I can of course manually construct a table from the source catalog, but it would be simpler if `to_table` would work for this.

I suspect this has something to do with the units of the columns? But the error output is not very informative (YAML error maybe?) so I can't tell for sure.

**Comment by larrybradley** [comment]
@jensmelinder I cannot reproduce this error using your code.  `RepresenterError` is a YAML error (which is unrelated to photutils), so I think you are getting this error from a different line of code.  Are you perhaps trying to write the table to a FITS binary table?  That will not work for a couple reasons - the table contains astropy Quantity and SkyCoord objects that cannot be serialized to FITS.  If that's the case, please try using the "ECSV" output file format (see https://docs.astropy.org/en/stable/io/ascii/ecsv.html).

**Comment by jensmelinder** [comment]
I do indeed save to fits, and it seems I got it wrong when the error appears. It is the saving to fits step that fails. 

However it's not related to the skycoord, since I treat that separately (by adding RA/Dec columns to the QTable and removing the skycentroid column). I do think it is related to the units of the offending columns though.

What is very weird to me is that the default_columns save a table with some of the same columns but this table can be written to fits just fine. ASFAIK QTable should be able to handle writing units columns to fits tables.

This is the rest of the code to output the fits table:
```
dettab['RA'] = dettab['sky_centroid_win'].ra
dettab['Dec'] = dettab['sky_centroid_win'].dec
dettab.remove_column('sky_centroid_win')
dettab.write('detcat.fits', overwrite=True)
```
(if using the default columns I change `sky_centroid_win` to `sky_centroid`)

I guess this might be a Table output problem rather than photutils, but the difference between the default output and selected columns seems strange? 

Anyway, thanks for looking into it. I can work around this, but if it can be reproduced I think it indicates a bug somewhere (in to_table or in the Table fits writing routines).

**Comment by larrybradley** [comment]
Thanks for confirming that this error is from saving the table to FITS.  

I get this same error even when trying to save the default table to FITS.  One thing I did just notice that the column-name representation for the mixin `Quantity` columns are different in NumPy 2.0+, e.g., 
```
 np.str_('area'),
 np.str_('semimajor_sigma'),
 np.str_('semiminor_sigma'),
 np.str_('orientation'),
 np.str_('eccentricity'),
```
instead of just `'area', 'semimajor_sigma', etc.`.  I'm wondering if this could be a bug in astropy tables with NumPy 2.0+.  I'll look into that more.

In the meantime, you can easily convert your `QTable` to `Table` to avoid the `Quantity` mixin columns before you write the file, with:  `dettab = Table(dettab)` (you'll need to import Table from astropy).  However, note you will get warnings because several column names are longer than 8 characters.

**Comment by larrybradley** [comment]
I am preparing a fix for Photutils to avoid this issue of the numpy.str column dtypes.  I still need to investigate if there is an upstream issue with QTables.
