### ISSUE TITLE
Fix documentation PDF output on readthedocs

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#210]
Currently the documentation PDF build on readthedocs is broken.

* https://readthedocs.org/builds/photutils/2008877/

I didn't look yet what is wrong.
We should try and fix this before the release ... having a PDF e.g. for offline reading can be useful to some people.

Currently the whole content of the PDF is this:
* https://media.readthedocs.org/pdf/photutils/latest/photutils.pdf
![screen shot 2014-12-16 at 12 04 48](https://cloud.githubusercontent.com/assets/852409/5452513/0e5cb97c-851c-11e4-83a6-ef734e29bfe3.png)

:-)

**Comment by larrybradley** [comment]
Fixed in #301.
