### ISSUE TITLE
Enable AppVeyor Windows CI testing

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#220]
We should enable Windows testing on AppVeyor now that this is active in Astropy:
https://github.com/astropy/astropy/pull/2755

I'm putting this for the 0.2 milestone because it might not be trivial to configure and could turn up Windows-specific issues that will take some time to fix.

**Comment by astrofrog** [comment]
If anyone wants to do this, it should be simple: copy over the following three files:

* ``.install-miniconda.ps1``
* ``appveyor.yml``
* ``.appveyor_windows_sdk.cmd``

Then adjust the dependencies in ``appveyor.yml``. I've already enabled appveyor on their side but it will only work once there is an ``appveyor.yml`` file here.

**Comment by larrybradley** [comment]
This was implemented in #232.
