### ISSUE TITLE
Sub-pixel precision peak finder and image value lookup

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#235]
@adonath and I need functions that find peaks and lookup image values with sub-pixel precision (because our images are very slow to compute at high resolution, see example [here](http://nbviewer.ipython.org/github/gammapy/gammapy-extra/blob/master/notebooks/ts_map_computation.ipynb))

@larrybradley already implemented [photutils.morphology.centroid_2dg](http://photutils.readthedocs.org/en/latest/api/photutils.morphology.centroid_2dg.html) which is one method to measure the sub-pixel peak location (using e.g. a 3 x 3 cutout image around the brightest pixel).

I think it would be nice to add a `subpixel` option [photutils.detection.find_peaks](http://photutils.readthedocs.org/en/latest/api/photutils.detection.find_peaks.html) that defaults to `False` and if set to `True` runs `centroid_2dg` on 3x3 pixel cutouts for all peaks?
Or add a separate utility function to do this?

Then we need to look up the values at these sub-pixel positions in other aligned smooth maps.
For this maybe we could add a `lookup_image_value` function that either uses `centroid_2dg` again or some interpolation method.

@larrybradley and all: Do you have any thoughts how this should be added?

**Comment by larrybradley** [comment]
@cdeil  I was planning to add a feature exactly like that for `subpixel` peak finding, so I'll go ahead with that implementation.

I'm not sure exactly what you want for the look up function, but my guess is that is probably better as a separate function?

**Comment by cdeil** [comment]
@larrybradley - Yes, `lookup_image_value` should be a separate function.

**Comment by larrybradley** [comment]
Implemented in #244.
