### ISSUE TITLE
Docs build on RTD broken

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#255]
The `photutils` docs build on RTD is broken:
https://readthedocs.org/builds/photutils/2413314/

The issue is that `pip install scikit-image` fails and then `pip install astropy` isn't executed and `python setup.py build_sphinx` fails with an `ImportError` for `from astropy.extern import six`.

I tried fixins this in https://github.com/astropy/photutils/commit/8d879d5d479344704093eaa52545972e3cee98fa, but `pip install scikit-image` still fails like this:
```
Downloading/unpacking networkx (from -r docs/rtd-pip-requirements (line 5))
Downloading/unpacking scikit-image (from -r docs/rtd-pip-requirements (line 6))
  Running setup.py (path:/var/build/user_builds/photutils/envs/latest/build/scikit-image/setup.py) egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/var/build/user_builds/photutils/envs/latest/build/scikit-image/setup.py", line 123, in <module>
        check_requirements()
      File "/var/build/user_builds/photutils/envs/latest/build/scikit-image/setup.py", line 118, in check_requirements
        raise ImportError(dep_error)
    ImportError: You need `networkx` version 1.8 or later.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/var/build/user_builds/photutils/envs/latest/build/scikit-image/setup.py", line 123, in <module>

    check_requirements()

  File "/var/build/user_builds/photutils/envs/latest/build/scikit-image/setup.py", line 118, in check_requirements

    raise ImportError(dep_error)

ImportError: You need `networkx` version 1.8 or later.
```

@astrofrog Any idea how to fix this? Is this something that should be reported as a `scikit-image` issue?

**Comment by gongenhao** [comment]
same here

**Comment by astrofrog** [comment]
Can you try adding ``networkx>=1.8`` to the pip requirements file?

**Comment by cdeil** [comment]
@astrofrog – I did add `networkx` to the pip requirement file in https://github.com/astropy/photutils/commit/8d879d5d479344704093eaa52545972e3cee98fa . If you look at the output above, it says:
```
Downloading/unpacking networkx (from -r docs/rtd-pip-requirements (line 5))
```
but doesn't say that it's running `setup.py` from `networkx` so I guess it didn't install it!???

I don't think adding `>=1.8` for `networkx` would help ... just putting `networkx` in the pip requirements file should install the latest stablenetworkx, which is [1.9.1 ](https://pypi.python.org/pypi/networkx/1.9.1).

Weird ... ?!

**Comment by astrofrog** [comment]
@cdeil - this may be a case again of the fact that pip requires all packages to be able to run ``setup.py egg_info`` without any dependencies being installed. Can you try creating an empty python environment and then running ``python setup.py egg_info`` in the expanded tar file for ``scikit-image``? If it gives the same error it's a ``scikit-image`` bug.

**Comment by cdeil** [comment]
@astrofrog – Looks like there might be a fix for this coming soon in `scikit-image` (see https://github.com/scikit-image/scikit-image/pull/1426#issuecomment-82192746) ... let's just wait a bit, OK?

**Comment by astrofrog** [comment]
@cdeil - ok, sounds good. If you want to test that fix, basically you need to make sure ``python setup.py egg_info`` runs with no dependencies installed.

**Comment by cdeil** [comment]
Today a bugfix release for scikit-image was made (see https://github.com/scikit-image/scikit-image/issues/1067#issuecomment-88397648) and the Sphinx build for the latest version of photutils on readthedocs works again (see https://readthedocs.org/builds/photutils/2518642/).

The Sphinx build for the stable photutils 0.1 version still fails (see https://readthedocs.org/builds/photutils/2518690/). I'm not sure why or what needs to be done (need to wipe? declare Cython dependency?).

If anyone has an idea how to fix this, please comment or go ahead. Otherwise we could just let it go, because we don't do bugfixes for the 0.1 branch, so the docs don't need to be updated ever.

**Comment by larrybradley** [comment]
The stable docs built fine today on RTDs:
https://readthedocs.org/builds/photutils/2545719/

**Comment by bsipocz** [comment]
I close this as both devel and stable version are OK on RTD at the moment.
