### ISSUE TITLE
Feature request - masks from apertures

### ISSUE THREAD

**Issue by keflavich** [astropy/photutils#259]
This may be better thought of as a pyregion issue, but it is relevant to the existing photutils setup and highlights some of the overlap between the two packages.

I would like to be able to return a 2D mask from an image given an input aperture (either Sky or pixel).  Both a boolean mask (containing all overlap or all contained pixels) and a floating-point fractional pixel mask could be useful depending on the situation.

This is also related to #161, but specifically about 2D masks.

**Comment by larrybradley** [comment]
@keflavich This is a good suggestion and it was actually how I thought about approaching #161.  I've been a bit swamped lately, but I hope to get to this soon.

**Comment by pllim** [comment]
I was just looking for this feature and sad to find that it does not exist...

**Comment by larrybradley** [comment]
Patience, @pllim.  I'm working on it.

**Comment by pllim** [comment]
So far, I can get around it by getting the fractions out of the aperture and build a mask off it. But you said you're going to remove the fractions, so please keep me updated. Thanks!

**Comment by rjavila** [comment]
Oh I could really use this right now.

**Comment by larrybradley** [comment]
This feature was added in #453.  See the `ApertureMask` object.
