### ISSUE TITLE
photutils 0.2

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#262]
I was asked to give a tutorial on `photutils` at the upcoming User Training in JWST Data Analysis meeting (http://www.stsci.edu/institute/conference/ut_jwst_da/).  They will need to establish the software dependencies for the participants in next couple of weeks.  I'd like to have a `photutils 0.2` release ready that incorporates the additions/changes since `0.1` and perhaps a few more additions, like settling the API for things like https://github.com/astropy/photutils/pull/261.

However, that would mean pushing most of the 20 open `0.2` issues to `0.3` (or later).  Does anyone object to having a `0.2` release in the next couple of weeks?

**Comment by cdeil** [comment]
:+1:

**Comment by bsipocz** [comment]
:+1:

**Comment by bsipocz** [comment]
Maybe we can also follow the astropy approach of only milestoning issues when they are critical, or we definitely want to solved them before the new release.  Otherwise milestoning after merge.

**Comment by astrofrog** [comment]
:+1: and also :+1: to @bsipocz's suggestion

**Comment by larrybradley** [comment]
The workshop is going to use the current dev version of `photutils`, so I didn't need to rush out a `0.2` release.

:+1: to @bsipocz suggestion.  I'll remove the milestones on current issues.

**Comment by cdeil** [comment]
We have a "future" milestone in photutils (and I think it exists in Astropy, too).

The difference wrt. no milestone set is small.
A new issue or PR that comes in has no milestone set.
Then one of the maintainers looks at it and sets a milestone.
So having a "future" milestone helps a bit to make sure important issues aren't forgotten because no-one set a milestone.

I think it's a bit useful, but I'm also not opposed to removing the future milestone if others think it's complicated.

**Comment by bsipocz** [comment]
I'm :+1:  for the "future" milestone, your argument totally makes sense. Also I don't mind if we keep the old system, but it can be an unconscious blocking for new releases to still have so many issues open, and a bad omen to remilestoning them all the time...

**Comment by larrybradley** [comment]
It doesn't look like `astropy` is using "future" in that way (I don't know how it's actually being used).  Setting things to "future" to note that a maintainer has seen the issue is fine with me.

**Comment by larrybradley** [comment]
Just a quick update that I plan to make a `0.2` release in the coming weeks (before Dec. 18).  I'm currently working on source deblending, which I'd like to include in the new release.

**Comment by larrybradley** [comment]
I have one more PR to complete, after which I will make a `0.2` release.  This will occur sometime next week.

**Comment by bsipocz** [comment]
Sounds great. I will try to get the aperture phot fixes in by that time.

**Comment by larrybradley** [comment]
@bsipocz Will your PR be ready today (and btw, what issue is that?)?  I hope to do the release later today.  Thanks!

**Comment by bsipocz** [comment]
Sorry, it won't happen today, I couldn't work on it during my holidays. I wanted to get #278 merged, and also investigate a bug report/feature request I got via email (not sure which category it will fall into).

Anyway, these are far from being release critical, so please go ahead with releasing 0.2.

**Comment by larrybradley** [comment]
0.2 is released now.  Thanks everyone!
