### ISSUE TITLE
adding parsing for galfit output files

### ISSUE THREAD

**Issue by astronomeralex** [astropy/photutils#264]
I have a little module for parsing galfit output files into python objects (https://github.com/astronomeralex/galfit-python-parser). @cdeil mentioned that photutils would be a good place so this has more community visibility. Where shall I put it? I will need to clean up the code and document it better. Never imagined other people would find this useful...

**Comment by cdeil** [comment]
I think having convenience functions to work with `galfit`, `sextractor`, `psfex`, IRAF ... input or output files would be nice to have in photutils, both for developers to compare results to `photutils` and for end-users. A lot of astronomers have written such scripts, but they're scattered and hard to find.

It wouldn't be extra dependencies in any way, just convenience functions like @astronomeralex's for `galfit`.

If others agree, how about putting them in a separate sub-package? I don't have a good idea for a name, maybe `legacy_tools` or ... ?

But first: @larrybradley @astrofrog @bsipocz would you agree this is good or at least OK to have in photutils.

**Comment by bsipocz** [comment]
I think it would be definitely good to have it in somewhere, though I'm not sure it belongs to ``photutils``. E.g. there are readers for ``sextractor`` and ``daophot`` already in ``astropy.io.ascii``. Maybe it would make more sense to have ``galfit`` and company there as well?

**Comment by larrybradley** [comment]
Yes, this would be good to have somewhere.  If the `galfit` output files can be read into an astropy `Table`, then I agree with @bsipocz that it should probably go in `astropy.io`.

**Comment by bsipocz** [comment]
I'm closing this as the consensus seems to be that astropy.io is a better place for such a parser.
