### ISSUE TITLE
Should kwarg unit override header BUNIT 

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#272]
I got a bug report saying that ``aperture_photometry`` fails as the current code requires the ``unit`` kwarg to be the same unit as the header ``BUNIT``. However ``BUNIT`` is ``'JY/BEAM'`` in this case which is unrecognisable by the parser, and thus ``unit`` cannot override it with the correct format.

I cannot find any notes why we chose to have this requirement and not the other way, but propose the following two options to solve this:
  1) Have ``unit`` override ``BUNIT`` (and maybe other ``dataunit``, too)
  2) Check if ``BUNIT`` is Unrecognizable, and if yes allow ``unit`` to override.

I prefer the second option, but if your experience says that ``BUNIT`` tend to be wrong in some cases, then I see the logic doing the first option. PR to follow when this is decided.

cc: @astrofrog, @larrybradley

**Comment by larrybradley** [comment]
I would go for the first option because there's no guarantee that `BUNIT` is correct.  But if the units don't  agree, I would recommend issuing a warning.
