### ISSUE TITLE
Travis tests fail with stable astropy

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#274]
Travis tests failed for #273 when tests were run against astropy stable as it didn't recognize ``UnitConversionError`` (that was fixed in v1.0.3).

The current stable version is 1.0.3, however v1.0.1 is picked up during the travis tests for no obvious reason.

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.10 -- pytest-2.5.1

Running tests with Astropy version 1.0.1.
Running tests in photutils /home/travis/build/astropy/photutils/docs.

Platform: Linux-2.6.32-042stab090.5-x86_64-with-debian-wheezy-sid

Executable: /home/travis/miniconda/envs/test/bin/python

Full Python Version: 
2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.8.2
Scipy: 0.14.0
Matplotlib: 1.3.1
scikit-image: 0.10.1
Astropy: 1.0.1
```

Any idea what goes wrong?

**Comment by bsipocz** [comment]
This may affect other affiliated packages that are using ``conda install`` rather than ``pip install`` for the travis runs against astropy stable.

ping @astrofrog, @embray

**Comment by embray** [comment]
I don't know. I don't have any control over when or how the conda packages get made.

**Comment by astrofrog** [comment]
Can anyone with a Linux box check if 1.0.3 is the latest version on conda?

**Comment by bsipocz** [comment]
Weird, very weird. Trying to do my first ever conda install, following what is in ``.travis.yml``,  v1.0.3 gets installed. It's on the usual old RHEL server I run the tests.
I checked the travis runs for astroquery and the same happening there, too, it installs v1.0.1.

**Comment by astrofrog** [comment]
I've always suspected that Travis may be caching many of the conda packages because the download speeds are usually ridiculous (as in, almost unphysical). So it's possible that this is just that the cache hasn't been updated in a while.

**Comment by bsipocz** [comment]
#275 provides a workaround for this, and I close this as it isn't a photutils issue. 
@astrofrog - should I open an issue somewhere else? If yes, where?

**Comment by astrofrog** [comment]
I think this was due to the fact we haven't produced astropy conda packages for astropy-ci-extras (combinations of astropy + numpy versions not covered by the official astropy package). @mwcraig - is it easy to add astropy v1.0.3 with old numpy versions to astropy-ci-extras?

**Comment by mwcraig** [comment]
Should be able to do it this weekend, if not before.

**Comment by mwcraig** [comment]
@astrofrog -- this ought to happen every time there is a stable release of astropy, right?

**Comment by astrofrog** [comment]
@mwcraig - yes, if possible
