### ISSUE TITLE
elliptical_overlap_grid generating nan's in some cases

### ISSUE THREAD

**Issue by tepickering** [astropy/photutils#277]
When setting up regression tests for ``elliptical_overlap_grid``, I ran into a number of failures where the masks were filled with ``nan``. The ones I tracked down all had equal semi-major and semi-minor axis sizes.  An example failure case is:

```
In [4]:
m = elliptical_overlap_grid(-1, 1, -1, 1, 1000, 1000, .8, .8, 0.5, 1, 10)
m.mean()
Out[4]:
nan
```

Slightly changing one of the axis values yields appropriate numbers:

```
In [13]:
m = elliptical_overlap_grid(-1, 1, -1, 1, 1000, 1000, .8, .80001, 0.5, 1, 10)
m.max()
Out[13]:
1.0000000000001465
```

Setting ``use_exact`` to 0 also yields correct results in all cases so the bug is somewhere within the ``use_exact`` code.

**Comment by bsipocz** [comment]
Closing as this was fixed in #276.
