### ISSUE TITLE
Photutils 0.1 tests fail with numpy 1.10

### ISSUE THREAD

**Issue by sergiopasra** [astropy/photutils#293]
I'm seeing errors when testing photutils 0.1 with numpy 1.10.1 and numpy 1.10.2rc

The failing tests are:
photutils/datasets/tests/test_make.py::test_make_noise_image_unit
photutils/datasets/tests/test_make.py::test_make_poisson_noise_unit
photutils/datasets/tests/test_make.py::test_make_gaussian_sources_unit
photutils/tests/test_aperture_photometry.py::test_aperture_pixel_positions
photutils/tests/test_aperture_photometry.py::TestInputNDData::test_basic_circular_aperture_photometry

**Comment by sergiopasra** [comment]
The tests in 'master' passes. It's only an issue in the released version

**Comment by larrybradley** [comment]
Thanks, @sergiopasra.  I hope to release version 0.2 in the coming weeks.

**Comment by larrybradley** [comment]
@sergiopasra, `photutils 0.2` is out now.  Thanks again.
