### ISSUE TITLE
appveyor problem with python3.5

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#294]
It may be trivial for someone with windows experience (@mwcraig  or @astrofrog), but I run out of ideas, so leave it here in an issue before merging #292 without adding py3.5 to appveyor. 

https://ci.appveyor.com/project/Astropy/photutils/build/1.0.153/job/xs87di6qchlworuf
https://ci.appveyor.com/project/Astropy/photutils/build/1.0.154/job/vt999t9pemy8dcqq

**Comment by mwcraig** [comment]
The problem (I think) is that default compiler on Windows [changed in python 3.5](http://stevedower.id.au/blog/building-for-python-3-5/) but the appveyor setup scripts (`%CMD_IN_ENV%` in particular) configures the compiler to that used in python 3 prior to 3.5.

Will end up resolving this over the weekend for the affiliate builder, I hope, and port the change here (or to the new CI helper package).

**Comment by astrofrog** [comment]
@mwcraig - it would be great to fix this in the ci-helpers if this applies to all packages with compiled code

**Comment by bsipocz** [comment]
@astrofrog - And also we have to come up with something to reproduce this error in ``ci-helpers``, as it seems that the py3.5 builds pass there.

**Comment by mwcraig** [comment]
@bsipocz -- actually, I don't think it is necessary to add a test. Changing the default compiler seems to happen only every ~5+ years, and my understanding is that in the future it will not be necessary to match compiler versions as is necessary now, so the current config should, in principle, be good for a long while. I don't understand all of it, but the current situation is discussed here: http://stevedower.id.au/blog/building-for-python-3-5-part-two/

**Comment by bsipocz** [comment]
Fixed in #296
