### ISSUE TITLE
Problem generating HTML docs

### ISSUE THREAD

**Issue by algerdnazgul** [astropy/photutils#297]
After generationg of docs in html format we have some problems included in screenshot.
![bugdoc](https://cloud.githubusercontent.com/assets/13625665/11527194/7f3c63c0-98f0-11e5-8287-1662730efd73.jpg)

**Comment by larrybradley** [comment]
@algerdnazgul, thanks for your report.  To generate the class inheritance diagram, `Sphinx` requires that `graphviz` (http://www.graphviz.org/) be installed.  `graphviz` is not a python package, but it's available, for example, via `conda`/`anaconda`.

I was able to reproduce your issue by uninstalling `graphviz`.  In that case you should see a warning when generated the docs that `dot` (part of `graphviz`) is not installed:

```WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting```

**Comment by bsipocz** [comment]
@larrybradley - You were faster, I was just reinstalling graphviz to confirm this, but fink was super slow, and buggy, too.

Anyway, I'm closing this as it's not an issue within photutils, @algerdnazgul please feel free to reopen and attach the failing build log if installing ``graphviz`` doesn't solve the problem.

**Comment by algerdnazgul** [comment]
Thanks a lot, i will try it in the shortest time.
