### ISSUE TITLE
Add circle-circle intersection area function

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#30]
I'm currently integrating PyFACT into gammapy (https://github.com/gammapy/gammapy/pull/68).

There's a function that computes the circle-circle overlap area that I think would fit better in photutils, because it already contains similar functionality:
[circle_circle_intersection](http://pyfact.readthedocs.org/en/latest/_modules/pyfact/tools.html#circle_circle_intersection_a)

This could fit in `photutils.geometry`.

**Comment by larrybradley** [comment]
Cleaning up some old issues.....  Intersections of regions is planned as part of the `regions` package.
