### ISSUE TITLE
How did you fix the windows link error?

### ISSUE THREAD

**Issue by moorepants** [astropy/photutils#312]
Hi,

I found this appveyor build:

https://ci.appveyor.com/project/Astropy/photutils/build/1.0.154/job/vt999t9pemy8dcqq

Which has this error:

`LINK : fatal error LNK1117: syntax error in option 'MANIFEST:EMBED,ID=2'`'

I'm having the same issue here:

https://github.com/pydy/pydy/pull/315

I was wondering what you did to fix that? I'm having trouble figuring it out.

**Comment by moorepants** [comment]
I figured it out. Thanks.

**Comment by giampaolo** [comment]
I have the same problem. Can you tell me how you fixed it?

**Comment by moorepants** [comment]
I can't quite remember. Maybe I dropped some python versions. You can see the working files here:

https://github.com/pydy/pydy/pull/315/files

And maybe compare to yours.

**Comment by moorepants** [comment]
In that PR I wrote:

> The compilation was failing due to a mismatch in the installed miniconda python version (i.e. Miniconda35 was being downloaded when I thought it was Miniconda3.4).

**Comment by bsipocz** [comment]
@moorepants @giampaolo - #294 is the relevant issue, and the actual fix was done in ``ci-helpers`` in https://github.com/astropy/ci-helpers/pull/29

Hope it helps.

**Comment by bsipocz** [comment]
Btw you can use ``ci-helpers``, too if you like, it does take care of these standard setup issues. Usage example is in the ``.travis.yml`` and ``appveyor.yml``, and an example for a bit more complicated matrix can be found in astropy's travis.yml.
