### ISSUE TITLE
Error in loading dataset image

### ISSUE THREAD

**Issue by mirca** [astropy/photutils#325]
I'm getting the following error when trying to execute this [example](http://photutils.readthedocs.org/en/latest/photutils/getting_started.html)
``>>> hdu = datasets.load_star_image()``

![capture d ecran 2016-02-12 a 20 40 56](https://cloud.githubusercontent.com/assets/13077051/13023853/d94b6ea6-d1cb-11e5-80a5-c0cb968d5ef8.png)

I looked for installing ``bsddb``, however it looks like it has been deprecated since Python 2.6 and it is not present in Python 3 (see https://docs.python.org/2/library/bsddb.html).

It's probably worth to mention that I'm running ``photutils`` on ``OSX El Capitan 10.11.3``

I'm new to this repo, so, sorry if this is unrelated and I may be messing up here.

**Comment by astrofrog** [comment]
@mirca - what version of astropy are you using?

**Comment by astrofrog** [comment]
See the suggested fix here:

http://docs.astropy.org/en/stable/known_issues.html#remote-data-utilities-in-astropy-utils-data-fail-on-some-python-distributions

Basically install the bsddb3 package.

**Comment by mirca** [comment]
Hi @astrofrog, thanks for pointing that out, but I'm still getting the same error.

![capture d ecran 2016-02-12 a 21 26 25](https://cloud.githubusercontent.com/assets/13077051/13024123/75cbf888-d1cf-11e5-9a0e-044d337148d7.png)

**Comment by mirca** [comment]
Maybe this is an issue with ``shelve`` and not with ``astropy`` and ``photutils``?

**Comment by mirca** [comment]
Interestingly, I'm not getting this error in ``python3.5``.

**Comment by mirca** [comment]
Solved. I used the following workaround in the function ``_open_shelve`` from ``astropy/utils/data.py``
```python
if six.PY2:
        try:
            shelf = shelve.open(shelffn, protocol=2)
        except ImportError:
            import bsddb3
            db = bsddb3.hashopen(shelffn, flag='c')
            shelf = shelve.Shelf(db)
```
Thanks to https://bugs.archlinux.org/task/25058.

Sorry @astrofrog, this was probably only in my ``python2.7`` distribution.
