### ISSUE TITLE
PSF photometry - ValueError: 'axis' entry is out of bounds

### ISSUE THREAD

**Issue by stefanocovino** [astropy/photutils#326]
Hi all,

I read data from a frame with:

from astropy.io import get data
import numpy
from photutils.psf import create_prf
data = getdata(file)

then I convert to ndarray with:

dt = numpy.asarray(data.data)

and, finally, I try to derive a pdf with:

prf = create_prf(dt,positions=poslist,size=5,mode='median')

but I always get the error message: ValueError: 'axis' entry is out of bounds

Am I doing something wrong?

Thanks,
    Stefano

**Comment by eteq** [comment]
There have been some incompatible changes in astropy that caused this, I believe.  we're working on a fix for this as a follow-on to #159...

**Comment by pkrskr** [comment]
Hi! I'm new to Astropy and trying to contribute. Is there anything I can do to fix this?

**Comment by bsipocz** [comment]
@stefanocovino - There has been a new v0.3 release for photutils, with most of the psf module worked over. Could you please have a look at it and see whether your issue had been addresses? 
While I'm closing this one, feel free to reopen this or open another if you run into further errors.
