### ISSUE TITLE
Fix PSFPhotometrySpitzer notebook to work with new psf changes

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#328]
The changes in #159 have led to some subtle issues with the PSFPhotometrySpitzer notebook that may be a sign of problems in the code, or might be quirks of the notebook.  Will need to fix that, and then rename the notebook back to `.ipynb` and add it to the docs.

**Comment by bsipocz** [comment]
Said notebook had been moved to ``photutils-datasets`` so I'm closing this issue here, and opening a reminder there to double check and make the updates.
