### ISSUE TITLE
PSF homogenisation

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#337]
I'm looking for some Python code to do PSF homogenisation.

I'm not aware of good references, a short description is here:
http://adsabs.harvard.edu/abs/2011ASPC..442..435B

The use case we have in [Gammapy](https://github.com/gammapy/gammapy) is Fermi-LAT images in energy bands, and the Fermi-LAT PSF varies by almost two orders of magnitude from the lowest to the highest energies (see [here](http://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance_files/gPsfAve95Energy_P8R2_SOURCE_V6fb_10MeV.png)).
What I want is a function that gives me the kernel I need to use to smooth the data from multiple energy bands so that the smoothed images have the same shape for point sources.
In this case the PSF is radially symmetric, i.e. represented by 1-dim curves (in Gammapy we have the [TablePSF](https://gammapy.readthedocs.org/en/latest/api/gammapy.irf.TablePSF.html) class for that).

For example, let's assume we have two 2D Gaussian PSFs with width sigma1 and sigma2.
Then the image with sigma1 PSF can be smoothed with a 2D Gaussian of width sigma2, and the image with sigma2 PSF with a 2D Gaussian of width sigma1, and both smoothed images will have the same PSF of width `sqrt(sigma1 ** 2 + sigma2 ** 2)`. Gaussians are a special case where the homogenisation kernels can be computed analytically.

I'm not sure what a good, simple method is to do this for arbitrary PSFs.
This looks very sophisticated:
http://adsabs.harvard.edu/abs/2011ASPC..442..435B
I'm really looking for something simpler / doesn't need to be super-precise.
E.g. one could assume some parametrised shape for the homogenisation kernels (like Gaussian or King profile) and fit the parameters e.g. using chi^2 as measure for the difference of homogenised PSFs.

Any ideas how to do this?
Is this appropriate for photutils or should we start implementing something in Gammapy?

**Comment by mirca** [comment]
I would like to tackle this! =)

**Comment by cdeil** [comment]
@mirca - Great!

Here's a quick outline how I would do this:
* Use [TablePSF](https://gammapy.readthedocs.org/en/latest/api/gammapy.irf.TablePSF.html) to represent both the input PSFs and the computed output homogenisation kernels.
* To test, use  [gammapy.irf.TablePSF.from_shape](https://gammapy.readthedocs.org/en/latest/api/gammapy.irf.TablePSF.html#gammapy.irf.TablePSF.from_shape) to create test PSFs.
* Looks like there's no code available to compute the TablePSF that results from convolving two TablePSF. Add a utility function or method for that, that uses [TablePSF.kernel](https://gammapy.readthedocs.org/en/latest/api/gammapy.irf.TablePSF.html#gammapy.irf.TablePSF.kernel) to compute 2-dim images of the PSF and homogenisation kernel with very fine sampling, and then computes the radial profile of the convolved image. I hadn't realised that this code isn't in place yet (I think it's also not in Astropy or photutils) ... this and fixing bugs / adding tests for TablePSF is already a significant PR.

Once that is in place, you have to decide how to model the PSF homogenisation kernel. Either choose Gaussian for now, or take the `dp_domega` amplitudes at a few given `offset` nodes as free parameters.
Implement a chi^2 cost function that compares two convolved outputs and do a fit.

Hopefully others will chime in and also make suggestions what method could be implemented and which parts from Astropy and affiliated packages would be useful to build a prototype.

**Comment by larrybradley** [comment]
@cdeil  I think this is completely appropriate for `photutils` -- performing photometry on PSF-matched images is a common use case.

When working with multiple bandpasses in UV/O/IR data with different PSF widths, the typical procedure is to blur all of the (n-1) images to the image with the widest (worst) PSF, which is usually the reddest band.  To do this, "matching" kernels are needed to go from the individual images to the reference image.  In your simple example of two images with sigma1 and sigma2, one wouldn't convolve image1 with sigma2 and convolve image2 with sigma1 (that works, but you're unnecessarily blurring too much).  If sigma2 > sigma1, then you can simply take image2 as the reference image and convolve image1 with a Gaussian of ``sigma = sqrt(sigma2**2 - sigma1**2)`` (that would be the "matching" kernel).  I think most people still use IRAF's [psfmatch](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?psfmatch) for this task, so a python replacement would be great!

**Comment by eteq** [comment]
I 100% agree this is a good thing to have in `photutils` - I've been asked mutliple times about `psfmatch` equivalents.

That said, I don't think `TablePSF` is the way to go, as it's not a part of `photutils`.  The `photutils.psf` module now has machinery fully compatible with the `astropy.modeling` framework, so it's better for `psfmatch`-like functionality in photutils to follow the patterns there (and of course it should also live in the `photutils.psf` module).

@cdeil - `TablePSF` looks to me like it more-or-less follows the `astropy.modeling` 2D model "interface", though, right?  So making it compatible with one might also do the other?

**Comment by pkrskr** [comment]
Hi,

I am interested in contributing to Astropy for GSoC 2016. I was originally planning to work on an idea involving PSF photometry for fitting multiple overlapping objects with variable PSFs and spans. However, I see that there have already been two applications for the same project. 

While looking for open issues to solve, I stumbled upon this issue of PSF homogenisation. While it has been classified under the effort-medium tag, would it be possible for me to work on this as a GSoC project by increasing its relevant scope?

My background is as follows: I'm a Doctoral student at IIIT-Hyderabad, India. I work in the area of computational photography and over the last year I have been working on the analysis of how different PSFs corresponding to different depths in a scene merge with each other, from the perspective of simulation, i.e. we would like to correctly replicate a captured picture given the arrangement and nature of PSF for different scene locations.

**Comment by larrybradley** [comment]
@cdeil This functionality was added in https://github.com/astropy/photutils/pull/403.  The docs are at http://photutils.readthedocs.io/en/latest/photutils/psf_matching.html.

**Comment by cdeil** [comment]
@larrybradley - Thank you very much!

Minor suggestion: for http://photutils.readthedocs.io/en/latest/photutils/psf_matching.html : Maybe use `matplotlib.pyplot` instead of `matplotlib.pylab`? It seems to be the common / recommended thing to do (see [here](http://matplotlib.org/faq/usage_faq.html#matplotlib-pyplot-and-pylab-how-are-they-related))

For [photutils.psf.matching.create_matching_kernel](http://photutils.readthedocs.io/en/latest/api/photutils.psf.matching.create_matching_kernel.html), I think there's not enough info how the `window` callable should work. I.e. it's not mentioned that it will be called with the PSF kernel shape and what it should do with that. Maybe just link to http://photutils.readthedocs.io/en/latest/photutils/psf_matching.html#matching-psfs because it's hard to describe with a few words?

I'd like to try this out for my data soon. Is it possible to give users any guidance how to choose the `window` function and parameters? Maybe there is some paper or webpage that explains this "ratio of Fourier transforms" that has some info about `window` or how the method works in general that would be useful to reference? Or should I just play around with the window until the matching kernel convolved with the source PSF matches the target PSF when plotted as an image or profile?

**Comment by larrybradley** [comment]
@cdeil  Thanks for noticing the use of `pylab`.  I don't use it either -- I must have blindly copied it from another doc page (it was used in several pages, probably propagating from a single source).  In any case, `pylab` is now gone from all `photutils` docs.  Thanks.

Yes, the window keyword isn't easy to describe in a few words, so I added a link from `create_matching_kernel` back to the narrative docs.  Thanks.

Additional guidance about selecting a particular `window` function is more difficult.  It seems to be more of an art than science.  I think your approach of playing around with the window until the  resulting kernel convolved with the source "best" matches the target PSF is the correct approach.  In general, I would start with the `CosineBellWindow`.  That's what the IRAF psfmatch task used:
http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?psfmatch

Here are some real examples that also used a cosine bell window function:
http://dirty.as.arizona.edu/~kgordon/mips/conv_psfs/conv_psfs.html

There is a detailed paper (http://adsabs.harvard.edu/abs/2011PASP..123.1218A) about creating matching kernels, which I will add to the docs.  Equation 10 is the Fourier ratio method I implemented in `create_matching_kernel`.  Equation 11 describes a `SplitCosineBell` window function, which is the most general form for a window function.  All of the other windows I implemented (`Hanning`, `Tukey`, `CosineBell`, and `TopHat`) are special forms of the `SplitCosineBell`.

**Comment by cdeil** [comment]
@larrybradley - Thank you very much for adding the references for further information.
Printing the paper now ...

**Comment by saimn** [comment]
There is a code that was recently published and could be of interest : https://github.com/aboucaud/pypher (and https://arxiv.org/abs/1609.02006)

**Comment by cdeil** [comment]
OK, wow. Maybe for now, just add a link from `photutils.psf.matching` to `pypher` and their paper, and then long-term talk to them about collaboration / avoiding duplication?
