### ISSUE TITLE
imcopy equivalent?

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#338]
Is the cutout image functionality in `photutils` equivalent to IRAF `imcopy`? If so, could you please give an example on how to replace the following IRAF command? The key here is to preserve the cutout WCS.

```
imcopy file.fits[10:20,100:400] newfile.fits
```
Thanks.

**Comment by larrybradley** [comment]
The equivalent cutout functionality is `astropy.utils.Cutout2D` [1].  It operates on arrays in memory, so you would need to write a command-line tool to parse the array slice and operate on FITS files.

[1] http://docs.astropy.org/en/stable/api/astropy.nddata.utils.Cutout2D.html

**Comment by pllim** [comment]
Thanks, @larrybradley . But I still have some questions, please see example below.

In IRAF:
```
ecl> imcopy file.fits[10:20,100:400] newfile.fits
```

```python
from astropy.io import fits
from astropy.nddata.utils import Cutout2D 

pf = fits.open('file.fits')

# Doc says (x, y) but doesn't say 0- or 1-indexed. 
# Also, it is confusing that position has to be (x, y)
# but size (see below) has to be (ny, nx).
# Is the doc wrong?
# Should this be (100, 10) or (9, 99) or (99, 9)???
position = (10, 100)

# Size. I added 1 because I think IRAF coords are
# inclusive, unlike Python.
# Or is the doc wrong? Should this be (11, 301)???
size = (301, 11)

cutout = Cutout2D(pf[0].data, position, size)
pf.close()

# Not very sure how to pass this object into FITS module
# while preserving the cutout WCS...
hdu = fits.PrimaryHDU(cutout)  # ???

hdu.writeto('newfile.fits')
```

**Comment by larrybradley** [comment]
> Doc says (x, y) but doesn't say 0- or 1-indexed. 
> Also, it is confusing that position has to be (x, y)
> but size (see below) has to be (ny, nx).
> Is the doc wrong?
> Should this be (100, 10) or (9, 99) or (99, 9)???
> position = (10, 100)

None of the above.  `position` is zero-indexed (as all python is), but it is the *center* of the cutout, not one of the corners.  And yes, sigh, position is `(x, y)` order, but `size` is in `(ny, nx)` order.  I don't like it either, but `size` (or `shape`) keywords in scipy/numpy are always axis order.  On the other hand, image `position` is usually in `(x, y)` order.

In your example, assuming these are 1-based `iraf` pixels, the center `position` would be `(14, 249)`.

> Size. I added 1 because I think IRAF coords are
> inclusive, unlike Python.
> Or is the doc wrong? Should this be (11, 301)???
> size = (301, 11)

If you want x = 10:20 and y=100:400 *inclusive* then you should set `size = (301, 11)` ([400-100+1, 20-10+1] pixels).

> Not very sure how to pass this object into FITS module
> while preserving the cutout WCS...
> hdu = fits.PrimaryHDU(cutout)  # ???

This is a generic problem of updating a FITS header with only new WCS keywords.  However, it's easy for the cutout wcs since it only changes the CRPIX values.  So you only need to do:
```
>>> header['CRPIX1'] = cutout.wcs.wcs.crpix[0]
>>> header['CRPIX2'] = cutout.wcs.wcs.crpix[1]
```

**Comment by pllim** [comment]
@larrybradley , thanks but can you please be more specific? Can I pass the cutout object directly into a HDU? If not, how to I pass in the original header info before able to modify the CRPIXn values?

**Comment by larrybradley** [comment]
@pllim You would need to replace the HDU data with the cutout data and update the CRPIX header keywords.  Here's a complete example:

```
from astropy.io import fits
from astropy.nddata import Cutout2D
from astropy.wcs import WCS

pf = fits.open('file.fits')
position = (14, 249)
size = (301, 11)
wcs = WCS(pf[0].header)
cutout = Cutout2D(pf[0].data, position, size, wcs=wcs)

pf[0].data = cutout.data
pf[0].header['CRPIX1'] = cutout.wcs.wcs.crpix[0]
pf[0].header['CRPIX2'] = cutout.wcs.wcs.crpix[1]
pf.writeto('file_cutout.fits')
pf.close()
```

**Comment by pllim** [comment]
@larrybradley , that's just what I need. However, I have one last request -- can you please change

```python
pf = fits.open('file.fits')
```

to

```python
pf = fits.open('file.fits', mode='update')
```

?

This is such that in the future, people who revisit this issue would have a correct working example. Thank you!

**Comment by larrybradley** [comment]
@pllim  My example should work without `mode='update'` since I call `pf.writeto()` with a different FITS filename (i.e. I'm not updating the original FITS file).

**Comment by pllim** [comment]
@larrybradley , ah okay, you're right!

So, the user was satisfied with your example. I am closing this.
