### ISSUE TITLE
Broken links in class inheritance diagram docs.

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#345]
The links here in the photutils docs are broken:
http://photutils.readthedocs.org/en/latest/photutils/aperture.html#class-inheritance-diagram

E.g. clicking on "CircularAperture" leads to
http://photutils.readthedocs.org/en/api/photutils.aperture_core.CircularAperture.html#photutils.aperture_core.CircularAperture
which results in a page saying "error: doesn't exist".

@bsipocz - A known issue?

**Comment by bsipocz** [comment]
Ouch, no at least I didn't notice this yet. One more :+1: to finally set up a link checker (though that would be more useful for checking external links).

**Comment by larrybradley** [comment]
The inheritance diagrams links appear to be broken in `astropy` too, so this is probably an `astropy-helpers` issue.

I also just noticed that in the  `photutils 0.2.1` docs, the inheritance diagrams don't even have links.

**Comment by bsipocz** [comment]
@cdeil @larrybradley - This was an upstream bug in sphinx. Hopefully https://github.com/sphinx-doc/sphinx/issues/2484 makes it into the next bugfix release.

**Comment by bsipocz** [comment]
(The bug only affected the svg version of the inheritance diagram, so if we want a workaround until the fix is released, we can switch and use the png version).

**Comment by larrybradley** [comment]
Thanks for tracking this down, @bsipocz!

**Comment by larrybradley** [comment]
This is an upstream issue with `Sphinx` and a duplicate issue is open on astropy (https://github.com/astropy/astropy/issues/4935) so I'm going to close this one.

**Comment by bsipocz** [comment]
Btw this seems to be fixed in the photutils docs in the meantime (but not astropy core). I yet to figure out what have fixed it, but if you have any recollection please let me know.

**Comment by larrybradley** [comment]
@bsipocz  Interesting!  I wasn't trying to fix this issue, but I think I did so inadvertently with this PR:
https://github.com/astropy/photutils/pull/610.  I simply moved the docs up one level from `docs/photutils` to `docs`.  😄

**Comment by bsipocz** [comment]
Ohh, I see. But then it means this is seriously broken for astropy as we need to keep the subdirs around for it.

**Comment by larrybradley** [comment]
Yes, my guess is that an upstream fix is really still required.
