### ISSUE TITLE
Possible bug in pixel_to_icrs_coords

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#346]
@larrybradley - Why is ``origin=1`` here: https://github.com/astropy/photutils/blob/master/photutils/utils/wcs_helpers.py#L125
We couldn't figure out the reason when copying code to regions, so it may be a bug? https://github.com/astropy/regions/pull/10#discussion-diff-57536568

cc @astrofrog, @keflavich

**Comment by larrybradley** [comment]
I have no idea why that's there.  It's definitely a bug!  Fixing it now, thanks.
