### ISSUE TITLE
How to create synthetic test images of stars ?

### ISSUE THREAD

**Issue by MiraYugario** [astropy/photutils#351]
I have developed a source extraction algorithm and I need to test it. To do so I am planning to create an image with some sources of known fluxes. First, I would like to create the synthetic image with no background and then with some white noise. Can I do it with photutils?

**Comment by bsipocz** [comment]
``photutils.datasets`` [0] provides some example datasets routines to generate images.

[0] - http://photutils.readthedocs.org/en/latest/photutils/datasets.html

For other non photutils solutions I would suggest to write to either the astropy mailing list, or the Python users in Astronomy facebook group, as there are large group of people on both lists with a wide range of experiences with other tools and packages.
