### ISSUE TITLE
Background calculation algorithms can also be reused for source/peak finding?

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#374]
@hcferguson mentioned this in the sprint tag-up yesterday, so I am opening an issue here so it is not forgotten.

**Comment by larrybradley** [comment]
This is specifically for `ofilter`, which is essentially a 1D centroiding algorithm.  The background estimation is "centroiding" the data histogram.  I'm going to close this, but we can add `ofilter` when it's ready, e.g.:
https://github.com/astropy/photutils/issues/375#issuecomment-226290839
