### ISSUE TITLE
find_peaks documentation inconsistent

### ISSUE THREAD

**Issue by hcferguson** [astropy/photutils#387]
The documentation on readthedocs says that `find_peaks()` does not do any centroiding (always returns  integer pixel coordinates). However the documentation in the docstring says that it has a `subpixel=True` option that will fit a 2D Gaussian and return the local centroid and peak value.

**Comment by larrybradley** [comment]
Thanks, @hcferguson.  I added the `subpixel` option later and unfortunately didn't update the narrative docs.

**Comment by larrybradley** [comment]
Fixed in #391.
