### ISSUE TITLE
Generic settings to maximize the number of detected sources

### ISSUE THREAD

**Issue by vterron** [astropy/photutils#390]
I would like to get rid of all non-Python dependencies in [our pipeline](https://github.com/vterron/lemon/), and the first one that I'm tackling is SExtractor. I've followed the section of the [photutils documentation on source detection](http://photutils.readthedocs.io/en/v0.2.2/photutils/detection.html), but I'm encountering a little problem: I cannot manage to get it running properly without knowing anything a priory about the image — such as, for example, the FWHM. Would it be possible to use photutils so that as many possible sources as possible are detected, via some sort of generous defaults? False positives would not be an issue, as in our case they would be automatically discarded at a later stage.

For comparison, the "blind settings" that we currently use with SExtractor identify 971 sources [on this image](http://www.iaa.es/~vterron/123m-CAHA_2012.01_raw_120108_ferM_0093.fits)

**Comment by mirca** [comment]
I think [detect_sources](http://photutils.readthedocs.io/en/v0.2.2/api/photutils.detection.detect_sources.html#photutils.detection.detect_sources) and [find_peaks](http://photutils.readthedocs.io/en/v0.2.2/api/photutils.detection.find_peaks.html#photutils.detection.find_peaks) are the most generalized functions to find sources that we have in ``photutils``.
Could you post the blind settings you used with SExtractor?
Also, we would be happy to implement other source detection algorithms soonish :)

**Comment by bsipocz** [comment]
@vterron -  As "blind" initial value you could use the pixel scale from the image header to set the fwhm to the typical (or even best) seeing of the observing site.

**Comment by vterron** [comment]
@mirca, the SExtractor configuration files are [these](https://github.com/vterron/lemon/tree/master/sextractor).

@bsipocz, that's a very good idea, thanks. I'll try it. The only problem I see with it is that it would require us to ask the user to input the pixel scale, or we would have to make assumptions as to how that information is stored in the FITS header. Another option that I am considering is using [SEP](https://github.com/kbarbary/sep), doing something [along these lines](https://gist.github.com/vterron/5fa1800081c6550debe7).

**Comment by bsipocz** [comment]
@vterron - In your gist example you're already using the wcs from the header, so using that you can easily figure out the pixel scale, too.

**Comment by larrybradley** [comment]
@vterron But your SExtractor configuration file also is assuming a FWHM.  Your kernel is defined as `FILTER_NAME = sextractor.cov` in your `sextractor.sex`.   Just pass that same exact kernel array as the `filter_kernel` keyword input into the `detect_sources` function.

**Comment by larrybradley** [comment]
@vterron   It appears you are using a 3x3 Gaussian kernel with a FWHM of 2 pixels.

**Comment by larrybradley** [comment]
@vterron We haven't heard back, so I'm closing this now.  Please reopen if you still have a question about this.
