### ISSUE TITLE
Sphinx latexpdf docs failing

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#393]
This is causing RTD builds to report failure, even though the HTML docs build fine.

It appears this started around the time #379 was merged.

**Comment by mirca** [comment]
@larrybradley I see those failures. Investigating...

**Comment by bsipocz** [comment]
astroplan also has similar issues: https://github.com/astropy/astroplan/issues/214

**Comment by bsipocz** [comment]
This was fixed by #405, thus closing.
