### ISSUE TITLE
Change psf_photometry function to class-based architecture

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#406]
This came up in one of the GSoC 2016 hangouts, where I think we came to agreement, but I'm leaving it here as a reminder to actually implement this.

The basic idea is to change the high-level PSF routines to be callable classes, a la the work in #379 and #370 .  So the idea would be to replace the current `psf_photometry` function with a callable class that contains the configurable bits (for `psf_photometry` that's essentially just the model and the fitter, I think).

The simplest approach would be to just take that function, move its guts to a `do_photometry` function and build it as a totally separate implementation but with the same interface (and perhaps a shared base class) like `DAOPhotPSFPhotometry` from #385.  But @mirca and @hamogu pointed out that actually what `psf_phometry` does is probably entirely subsumed by `DAOPhotPSFPhotometry`, as `psf_photometry` is basically that but with no iterative DAOPHOT-style subtracting and re-finding. So it _might_ make more sense to instead have the `psf_photometry` replacement class be a subclass of `DAOPhotPSFPhotometry` and just call it with many of the parameters hard-coded.

A few more details that come to mind for me:
- If we go with this plan, I suggest some name changes that make it clear what these classes actually do.  The `psf_photometry()` replacement class could be something like `SimplePSFPhotometry` and `DAOPhotPSFPhotometry` could be changed to something slightly more descriptive of what it actually does like `IterativeSubtractionPSFPhotometry`.
- The current `psf_photometry` function uses a clever trick to support `NDData` objects as inputs: it uses the `astropy.nddata.support_nddata` decorator.  We'll want this class to do something similar so that it can just be called with an `nddata` object, but whether that should use `support_nddata` or instead should be something in the `__call__` or `do_photometry` method is an implementation question.
- The example notebooks in https://github.com/astropy/photutils-datasets will need to be updated to use the new class instead of `psf_photmetry()`

Note that @mirca volunteered to work on this (it won't let me assign him to the issue for reasons I'm trying to fix, but this will suffice as a "soft assign")

cc @mirca @hamogu @bsipocz

**Comment by eteq** [comment]
Just for the record, following a discussion as part of one of the JWST PSF photometry sprints, we had a re-thinking of the structure here. The idea we came up with will hopefully also resolve the problem of how to replace the existing `psf_photometry` class and a few other issues that have been rolling around in our collective heads.  This is the idea:
* Write a new class called something generic like `BasicPSFPhotometry`.  It would take all the same arguments as the current `DAOPhotPSFPhotometry` except `niters`, and it would mostly be a straight copy-and-paste of most of `DAOPhotPSFPhotometry` without the loop.  `do_photometry` for that would return just the table, *not* the subtracted image (although the users is of course free to do their own subtraction). `finder` can be None, which means just use the positions if they are given as an argument to `psf_photometry` (or if both are None raise an error)
* Replace the existing `DAOPhotPSFPhotometry` with a class called something like `IterativelySubtractedPSFPhotometry`.  This would look just like the current `DAOPhotPSFPhotometry`, but the internal implementation would just basically use `BasicPSFPhotometry` so it would end up a lot simpler than the current `DAOPhotPSFPhotometry`.  `do_photometry` would also just return the table, unlike the current one, which also returns the residual image, but it would do something like `self.residual_image = residual_image` at the very end so that the user can access it if they want it.  For this class `finder` *cannot* be None - attempting to do so should raise an error  
* Add a *subclass* of `IterativelySubtractedPSFPhotometry` called `DAOPhotPSFPhotometry`.  This would take all of the parameters that all of the *sub-objects* used in `DAOPhotPSFPhotometry` require, rather than explicitly setting e.g. the grouper, finder, etc.  Its implementation would be just an `__init__` which creates the relevant objects to reproduce the “daophot-style algorithm”

**Comment by bsipocz** [comment]
I think this can be closed now, can you confirm @eteq, @mirca ?

**Comment by mirca** [comment]
Yes @bsipocz :D
