### ISSUE TITLE
analogous parameter settings for aperture_photometry and iraf.phot? 

### ISSUE THREAD

**Issue by cgosmeyer** [astropy/photutils#407]
Hi,
Have there been any tests done to compare the ``aperture_photometry`` function to ``iraf.phot``?  Or is there a chart about how to set parameters so that the two get ~matching results?  
I have been finding discrepancies in flux counts on the same sources up to 20% or more in circular apertures radii of 3-20pixels (the range I have so far look at) no matter my combination of setting centroiding on or off in ``iraf.phot`` or setting subpixels in ``aperture_photometry``.  Any help would be great; I need to provide an explanation for the discrepancy if I am to justify to my team switching the photometry scripts over from iraf.  It's not clear to me what is going on under the hood of ``aperture_photometry``.

**Comment by larrybradley** [comment]
When doing comparisons between IRAF and python it's important to note that IRAF uses 1-based indices, while Python uses 0-based indices.  That's means you will need to subtract 1 from your IRAF-based `x` and `y` positions when using `photutils`.  Have you done that?

**Comment by cgosmeyer** [comment]
Yes, I subtracted 1's from the coordinate file I fed iraf.   I think that, regardless of whether I can get the two results to match, there should be documentation available that compares the two routines.

**Comment by larrybradley** [comment]
OK, glad to hear you shifted the coordinates.

I've never used `iraf.phot` and I doubt any other `photutils` developers have either.  The parameters for `photutils` aperture photometry are very straightforward.  To define a circular aperture the only parameters are `x`, `y`, and `r` (radius).  For the `aperture_photometry` function, the `mask` and `method` (and `subpixels`) keywords are the only parameters that could change the photometry results.  Note that the default is `method=exact`, which may not be same method your tool uses.  For example, to get the exact results as `SExtractor` (a standard photometry tool) one would use `method='subpixel', subpixels=5` (`photutils` has been tested against `SExtractor`).

Note that `iraf.phot` may also be changing your input data (e.g. global/local background subtraction and/or masking of bad data values) or parameters (e.g. re-centroiding `x, y`), which would also lead to differences with `photutils` (I suspect this may be the case). `photutils.aperture_photometry` does not subtract any background nor does it re-centroid `x, y` (but there are other tools in `photutils` to do both).  If you want any data values to be masked, you can input a `mask` array to `aperture_photometry`.

You could try both tools on a simulated source where you know the correct answer to see what is different.  `photutils` has been well-tested in this regard (and against `SExtractor`), but I can't rule out a possible edge-case bug.

**Comment by cgosmeyer** [comment]
Thanks for the feedback!  I also suspect that re-centroiding is a primary culprit, since smaller apertures give the most divergent results.  I will try as you suggest to compare photometry using a simulated source.

**Comment by larrybradley** [comment]
The conclusion is that IRAF is approximating the aperture using polygons, while the `photutils` default calculates the exact pixel-aperture overlaps.
