### ISSUE TITLE
questions about development directions

### ISSUE THREAD

**Issue by indebetouw** [astropy/photutils#41]
I just wrote a Region class that stores circular or irregular polygon apertures, knows how to expand them to make annular background regions, and is in sky coords and wcs-aware so you give it images and it returns aperture photometry. So
1. are you intending/hoping to make this package wcs-aware, or is the intent to keep things modular and write other things that call this package (I was thinking about making my code call this to do the actual calculations, once I had done the sky->pixel conversion)
2. are there plans for irregular polygon, and/or objections to me adding it to this (which would make it trivial for me to then have my code call this to do the calculations - my code doesn't do subpixel calculations for example)

my bg:  lots of astronomical coding experience, but a lot of it old-school, i.e. OOP comes a little harder to my brain, and although I've included python in my tools for 4-5 years, I might need some wrist-slapping to fit your standards.  I list Tom as my character reference since he knows me well :)

thanks
remy

**Comment by cdeil** [comment]
@indebetouw - If you haven't had a look at photutils in a while, check out what's there now: http://photutils.readthedocs.org/

I think it's best to close old issues like this one "questions about development directions" that discuss a bunch of things (polygon apertures, WCS handling, statistic argument).

@indebetouw - If that's OK with you, could you please close this issue and create new issues (or even better pull requests), one per feature request like "Implement polygon apertures"?

**Comment by larrybradley** [comment]
@indebetouw I'm going to close this issue.  There are separate issues open about polygon apertures (#467), dependent on the `regions` package, and local background subtraction (#473).  Also, there are now sky-coordinate based apertures in photutils that are WCS-aware.
