### ISSUE TITLE
Add a doc section about "how to choose your PSF"

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#412]
From a DADF sprint: we should add a doc section dedicated to discussing how to create a PSF that goes into the rest of the machinery.

**Comment by mirca** [comment]
Basically, how to use ``prepare_psf_model``?

**Comment by eteq** [comment]
@mirca - that would be part of it, but this would be more complicated then that.  It would need (eventually) to account for cases like having multiple exposures of the same field, how to choose the specific stars you want, etc. This is one part that really depends a lot on the science case so it might need to end up a rather sprawling document.

Right now we're missing some of the key funcionality for this, but hopefully it will get in soon as it's part of the JWST PSF sprints currently happening.
