### ISSUE TITLE
Cython dependency installing dev version

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#415]
When installing the latest dev version of `photutils` as stated [here](https://photutils.readthedocs.io/en/latest/photutils/install.html#building-and-installing-using-pip):

```
$ pip install --no-deps git+https://github.com/astropy/photutils.git
```

the `cython` package is needed, otherwise it will fail. Perhaps this dependency should be added as necessary in that sub-section.

**Comment by larrybradley** [comment]
The "Installing the latest development version" section begins with a "Prerequisites" subsection that states "Cython" is required to build `photutils` from the source distribution.  

http://photutils.readthedocs.io/en/latest/photutils/install.html#prerequisites

That applies to both building manually or using pip.  I'm not sure what is missing.

**Comment by Gabriel-p** [comment]
D'oh.

My bad, missed the above section.
