### ISSUE TITLE
Duplicate prepare_psf_model functions

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#416]
`psf.funcs.prepare_psf_model` is identical to `psf.models.prepare_psf_model`.

**Comment by larrybradley** [comment]
https://github.com/astropy/photutils/blob/master/photutils/psf/funcs.py#L64

https://github.com/astropy/photutils/blob/master/photutils/psf/models.py#L466

Is `psf.models.prepare_psf_model` the one intended to be kept?

**Comment by eteq** [comment]
@mirca - can you confirm this wasn't intentional? (I actually don't remember if you did this or I did it ;)  I think it probably makes more sense to put this in models, as `funcs` I envision as "tasks that don't fit in one of the other places" more-or-less.

**Comment by mirca** [comment]
@eteq I'm not sure who did this, haha. It was probably myself. I think ``models`` is the right place too.
