### ISSUE TITLE
Make photutils citable

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#422]
We get these requests from time to time, so I wonder whether we should at least make a zenodo entry for photutils (unless there are some other ideas in the pipeline).

cc @larrybradley @eteq

**Comment by eteq** [comment]
Definitely should make this possible!  It's a good question whether we want it to tell people to cite a Zenodo entry or try to write a photutils paper (or both), though. The paper is obviously more work, but it provides better "credit" for academics who've worked on it... but I'm not sure.


My instinct is that the best thing for now is to use Zenodo for each version, then down the road *if* we ever have a paper about it we use that?  If we like that I'm happy to do the legwork for setting up the Zenodo connection for the current release (might need to be me anyway as one of the `astropy` org admins... not sure how their permissions work).

@larrybradley - do you have any opinions on this?

**Comment by eteq** [comment]
Oh, regardless, whatever we decide we should probably have a note in the docs describing what to do.

**Comment by larrybradley** [comment]
@eteq  I agree.  I think Zenodo is best for now.  I actually have intentions to write a `photutils` paper at some point, but that's not likely to happen in the immediate future.

**Comment by eteq** [comment]
@larrybradley - OK, should I just go ahead and do it for 0.2, then?

**Comment by larrybradley** [comment]
@eteq Sounds good.  `0.3` will probably come near the end of October.

**Comment by eteq** [comment]
Aaand here it is!  Took all of 3 min:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.155353.svg)](https://doi.org/10.5281/zenodo.155353)

From now on, anytime a "github release" is made, it'll auto-mint the citable DOI.  Because of that I suggest only doing github releases for major version numbers (i.e. the next one should be v0.3, then v0.4 after that) to not dilute citations. Does that sound good, @larrybradley?

**Comment by larrybradley** [comment]
Great, thanks!

Sounds good, but for reference how do I create a PyPI bugfix (minor) release without creating a "github release"?  I think a github release is created automatically whenever a new version tag is created.
