### ISSUE TITLE
Write PSF photometry docs

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#43]
@adonath added PSF photometry methods to photutils in #26.

At the moment no tutorial-style docs are included in the `photutils` repo, but there is an external notebook: http://nbviewer.ipython.org/gist/adonath/6550989/PSFPhotometrySpitzer.ipynb

This or something similar should be integrated into the main `photutils` docs.
(and the link to the external notebook in the `psf_photometry` docstring needs to be removed)

@astrofrog Are the example files small enough that they can be in the repo or where should they be located?

**Comment by eteq** [comment]
The specific discussion here is outdated due to the #159 changes, so I'm opening a new issue for this.
