### ISSUE TITLE
cannot import name circular_overlap_grid

### ISSUE THREAD

**Issue by KickFrontFlip** [astropy/photutils#447]
Hello,
I'm surprised  this issue has yet to be reported (this could indicate something on my end). However, when I run the code:

```
fit_unscaled = fits.getdata(image_file, extname='SCI')
positions = [(2000., 2000.), (2000., 2000.)]
apertures = CircularAperture(positions, r=3.)
data = np.ones((100, 100))
phot_table = aperture_photometry(fit_unscaled, apertures)
print(phot_table) 
```

image_file being the name of my fits file

I am met with the error: "ImportError: cannot import name circular_overlap_grid"
Looking through my directories, and the directories in this website for photutils I cannot find a file named "circular_overlap_grid" is it missing?
## Here is the full error:

ImportError                               Traceback (most recent call last)
<ipython-input-69-c1e6464c2de8> in <module>()
      8 apertures = CircularAperture(positions, r=3.)
      9 data = np.ones((100, 100))
---> 10 phot_table = aperture_photometry(fit_unscaled, apertures)
     11 print(phot_table)

//anaconda/lib/python2.7/site-packages/astropy/utils/decorators.py in aperture_photometry(data, apertures, unit, wcs, error, effective_gain, mask, method, subpixels, pixelwise_error)
    520 
    521         func = make_function_with_signature(func, name=name,
--> 522                                             **_get_function_args(wrapped))
    523         func = functools.update_wrapper(func, wrapped, assigned=assigned,
    524                                         updated=updated)

//anaconda/lib/python2.7/site-packages/astropy/nddata/decorators.pyc in wrapper(data, _args, *_kwargs)
    135                 data = data.data
    136 
--> 137             result = func(data, _args, *_kwargs)
    138 
    139             if unpack:

//anaconda/lib/python2.7/site-packages/photutils/aperture_core.pyc in aperture_photometry(data, apertures, unit, wcs, error, effective_gain, mask, method, subpixels, pixelwise_error)
   1411                                          subpixels=subpixels, error=error,
   1412                                          effective_gain=effective_gain,
-> 1413                                          pixelwise_error=pixelwise_error)
   1414     if error is None:
   1415         phot_col_names = ('aperture_sum', )

//anaconda/lib/python2.7/site-packages/photutils/aperture_core.pyc in do_photometry(self, data, error, effective_gain, pixelwise_error, method, subpixels)
    310                                       pixelwise_error=pixelwise_error,
    311                                       method=method,
--> 312                                       subpixels=subpixels)
    313         return flux
    314 

//anaconda/lib/python2.7/site-packages/photutils/aperture_funcs.pyc in do_circular_photometry(data, positions, radius, error, effective_gain, pixelwise_error, method, subpixels, r_in)
    145         subpixels = 1
    146 
--> 147     from .geometry import circular_overlap
    148 
    149     for i in range(len(flux)):

//anaconda/lib/python2.7/site-packages/photutils/geometry/circular_overlap_grid.py in <module>()

**Comment by larrybradley** [comment]
@KickFrontFlip  Thanks for your report.  `circular_overlap_grid` is located in a `Cython`-generated C module that needs to be compiled during the installation.  This `ImportError` is due to `circular_overlap_grid` not being compiled correctly during installation.

I see you are using `conda`.  Can you please report exactly how you are installing `photutils` using `conda` and if you see any error messages during installation?  And what platform are you using?

A simple `conda install photutils -c astropy` should be all that is needed (assuming you have a C compiler installed).

**Comment by larrybradley** [comment]
@KickFrontFlip  Hopefully that solved your installation issue, but please let us know if not.  Thanks.
