### ISSUE TITLE
Changing default rtd from "latest" to "stable"

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#457]
It happened it the past that users got confused by the difference in the latest documentation and their installed released version.
I suggest to change the RTD default to be the stable version (so ``http://photutils.readthedocs.org/`` will point to stable rather than latest), so maybe there will be a bit fewer such cases in the future.

I can do this after given the green light by @larrybradley and @eteq.

**Comment by larrybradley** [comment]
@bsipocz Sounds good to me, thanks!

**Comment by bsipocz** [comment]
Done.
