### ISSUE TITLE
What is a reasonable crit_separation value in DAOPhotPSFPhotometry?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#458]
The `DAOPhotPSFPhotometry` class was modified (as far as I can tell), and now it requires a mandatory `crit_separation` value.

It is not clear from the description what would be a resonable value for this parameter. I've noticed that the larger it gets, the longer it takes `DAOPhotPSFPhotometry` to complete but I'm not entirely sure why.

**Comment by Gabriel-p** [comment]
I just found it here https://photutils.readthedocs.io/en/latest/api/photutils.psf.DAOGroup.html#photutils.psf.DAOGroup

> Assuming the psf fwhm to be known, crit_separation may be set to k*fwhm, for some positive real k.

**Comment by mirca** [comment]
@Gabriel-p 
Also refer to the API docs for the three classes for performing photometry: [BasicPSFPhotometry](https://photutils.readthedocs.io/en/latest/api/photutils.psf.BasicPSFPhotometry.html#photutils.psf.BasicPSFPhotometry), [IterativelySubtractedPSFPhotometry](https://photutils.readthedocs.io/en/latest/api/photutils.psf.IterativelySubtractedPSFPhotometry.html#photutils.psf.IterativelySubtractedPSFPhotometry), and [DAOPhotPSFPhotometry](https://photutils.readthedocs.io/en/latest/api/photutils.psf.DAOPhotPSFPhotometry.html#photutils.psf.DAOPhotPSFPhotometry). And the [narrative docs](https://photutils.readthedocs.io/en/latest/photutils/psf.html) =D.
