### ISSUE TITLE
Different results in source detection with DAOStarFinder versus DAOPhotPSFPhotometry

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#459]
As far as I understand, the `DAOPhotPSFPhotometry` class uses the `DAOStarFinder` class to search for sources.

I'm seeing rather different results using both classes on the same image:

![figure_1](https://cloud.githubusercontent.com/assets/6054951/20117495/9ebf8d24-a5df-11e6-927c-50981392bdd4.png)

Shouldn't both return the same results if I use the same parameters?

The code is here, if needed I can upload the original .fits file.

```
import matplotlib.pyplot as plt
import numpy as np

from astropy.io import fits
from astropy.stats import gaussian_sigma_to_fwhm

from photutils.utils import cutout_footprint
from photutils.background import MADStdBackgroundRMS
from photutils.psf import IntegratedGaussianPRF
from photutils.psf import DAOPhotPSFPhotometry
from photutils import DAOStarFinder
from photutils import CircularAperture

# Load data.
image_file = 'test.fits'

# Image data.
hdulist = fits.open(image_file)
hdu_data = hdulist[0].data
hdulist.close()
# Crop image
crop = cutout_footprint(hdu_data, (2100, 1800), (500, 1100))
hdu_crop = crop[0]

bkgrms = MADStdBackgroundRMS()
std = bkgrms(hdu_crop)
thresh = 50. * std
sigma_psf = 5.
fwhm_sigma = sigma_psf * gaussian_sigma_to_fwhm
fitshape = int(3 * np.ceil(fwhm_sigma) // 2 * 2 + 1)

# DAOStarFinder
stfind = DAOStarFinder(threshold=thresh, fwhm=fwhm_sigma)
sources = stfind(hdu_crop)
print(sources)

# DAOPhotPSFPhotometry
psf_model = IntegratedGaussianPRF(sigma=sigma_psf)
photometry = DAOPhotPSFPhotometry(
    crit_separation=3. * fwhm_sigma, threshold=thresh, fwhm=fwhm_sigma,
    psf_model=psf_model, fitshape=fitshape)
result_tab = photometry(image=hdu_crop)
print(result_tab)

median, std = np.median(hdu_crop), np.std(hdu_crop)

plt.subplot(1, 2, 1)
plt.title('DAOStarFinder')
plt.imshow(hdu_crop, cmap='viridis', aspect=1, interpolation='nearest',
           origin='lower', vmin=0., vmax=median + std)
positions = (sources['xcentroid'], sources['ycentroid'])
apertures = CircularAperture(positions, r=4.)
apertures.plot(color='red', lw=1.5)
plt.colorbar(orientation='horizontal', fraction=0.046, pad=0.04)

plt.subplot(1, 2, 2)
plt.title('DAOPhotPSFPhotometry')
plt.imshow(hdu_crop, cmap='viridis', aspect=1, interpolation='nearest',
           origin='lower', vmin=0., vmax=median + std)
positions = (result_tab['x_fit'], result_tab['y_fit'])
apertures = CircularAperture(positions, r=4.)
apertures.plot(color='red', lw=1.5)
plt.colorbar(orientation='horizontal', fraction=0.046, pad=0.04)

plt.show()
```

**Comment by mirca** [comment]
@Gabriel-p Hi Gabriel, I haven't had the chance to look closer into this, but it seems that `hdu_crop` is not background subtracted when used by ``DAOStarFinder``, while ``DAOPhotPSFPhotometry`` always perform background subtraction. See [DAOPhotPSFPhotometry](https://photutils.readthedocs.io/en/latest/api/photutils.psf.DAOPhotPSFPhotometry.html#photutils.psf.DAOPhotPSFPhotometry). More importantly, thank you for trying out the PSF photometry machinery! Keep the issues coming!

**Comment by Gabriel-p** [comment]
@mirca if I understand correctly [cutout_footprint](http://photutils.readthedocs.io/en/latest/api/photutils.utils.cutout_footprint.html?highlight=cutout_footprint) (what I use to produce the crop) does not perform any background subtraction. In either case, the same cropped region (`hdu_crop`) is used by both methods.

The only reason I could think of to explain the differences is the background subtraction performed `DAOPhotPSFPhotometry`. But if that's the case, shouldn't then `DAOPhotPSFPhotometry` generate *better* results? Because the exact opposite is happening, and I'm not sure why.

**Comment by mirca** [comment]
@Gabriel-p Any luck if you use `niters=1` in ``DAOPhotPSFPhotometry``?

**Comment by Gabriel-p** [comment]
That was it. With `niters=1` the results are identical. Thank you @mirca!

**Comment by mirca** [comment]
The default is ``niters=3``, but I guess we may change that? @eteq

**Comment by bsipocz** [comment]
I'm sure @eteq will comment on changing the default, but I would leave it on 3. Checking the images above, it seems that with more iteration more faint sources are found, which is expected, and in a the case of a crowded field, I expect it to lead to a much better result.
(Finding the artefacts around the bright star is an unfortunate, but is also somewhat expected side effect.)

**Comment by mirca** [comment]
I totally agree with you @bsipocz
