### ISSUE TITLE
Add quality-of-fit information to the photometry fit outputs

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#462]
This overlaps somewhat with #443, but is somewhat distinct - the psf photometry machinery should output quality-of-fit information.  There are two particular things that I think might be relatively easy to do now:

1. A chi (or chi-squared) for the fit.  This could be just a directly computed chi-squared from the model, but *might* be best done to match the ALLSTAR implementation of `chi`... That may or may not be the same as a textbook `sqrt(chi-squared)`...  I'm not sure but it's probably written down somewhere?  @mirca have you you seen anything about this?
2. Information from the fitter itself.  For `LevMarLSQFitter` I'm thinking about the `fitter.fit_info['ierr']` or `fitter.fit_info['message']`.  I think we *don't* necessarily want the message by default (because that could dominate the size of the output table), but maybe ierr?  Or maybe this should be something the user can decide if they want output or not?  Need to be cautious about this because probably not all fitters will have this information (sort of like for #443), but when available this information might be important.

**Comment by johnnygreco** [comment]
Hey @eteq, this issue is pretty old, but I still think having this info in the output would be super useful! Is anyone working on this?

**Comment by larrybradley** [comment]
The new PSF photometry tools include two fit metrics and information from the `fit_info` results is also available.
https://photutils.readthedocs.io/en/latest/psf.html
