### ISSUE TITLE
Make the <something>_0 and <something>_fit machinery that was in psf_photometry work in the new psf photometry classes

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#464]
In the `psf_photometry` function that was in prior to #451 (although never in a release), the function had a feature that if the input table had a column named `<something>_0` and the model had a parameter called `<something>`, the `psf_photometry` function would automatically use that to set the default value for parameter `<something>`.   I'm *pretty* sure this was removed in #451 (i.e., it's not in `BasicPSFPhotometry`), is that right @mirca ?  If so, we should add that back in when we get a chance.  This should also pass through any parameter that is not `fixed` as `<something>_fit`.

The idea here is that some PSF models might have parameters beyond x_0/y_0/flux, which either actually contain useful information about the target objects (e.g., if there's some distortion in the PSF across the field), *or* are model parameters that the user wants to set different for different objects, but doesn't want to actually fit (if the parameter is `fixed`).

**Comment by mirca** [comment]
@eteq 👍
