### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by jankansky** [astropy/photutils#468]
If I run:

git clone https://github.com/astropy/photutils.git
cd photutils
sudo python ./setup.py install

The build fails at:

running build_ext
error: [Errno 2] Could not find C/C++ file photutils/geometry/elliptical_overlap.(c/cpp) for Cython file photutils/geometry/elliptical_overlap.pyx when building extension photutils.geometry.elliptical_overlap. Cython must be installed to build from a git checkout.: 'photutils/geometry/elliptical_overlap.c'

**Comment by mirca** [comment]
Could you please provide your astropy, photutils, and numpy versions?

**Comment by larrybradley** [comment]
@jankansky  To build `Photutils` from the source, you must have `Cython` installed.  According to the warning message, you don't have `Cython` installed.  See the prerequistes here: http://photutils.readthedocs.io/en/latest/photutils/install.html#prerequisites

**Comment by jankansky** [comment]
Thank you.  Cython was not installed.
