### ISSUE TITLE
Save cropped fits to file?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#469]
Say I have the following code:

```
from astropy.io import fits
from photutils.utils import cutout_footprint

hdulist = fits.open('myimage.fits')
hdu_data = hdulist[0].data

# Some center and box
xc, yc, xbox, ybox = 1000., 1000., 500., 700.
hdu_crop = cutout_footprint(hdu_data, (xc, yc), (ybox, xbox))[0]
```

How can I save the cropped image to a new fits file and conserve the header information?

**Comment by Gabriel-p** [comment]
BTW, I can't shake the feeling that this is not the place to be asking these questions since they are not issues with the code. 

Wouldn't it be better to direct these doubts to stackoverflow? Perhaps even create a `photutils` tag that developers (and users) could follow?

**Comment by Gabriel-p** [comment]
I found how to do it. I now have the issue that the ra,dec coordinates are apparently not properly conserved.

I'll open a question artSO using the `astropy` tag. I won't be making this kind of questions here, sorry for the noise.

**Comment by larrybradley** [comment]
@Gabriel-p To make 2D cutouts and update the WCS you should use `astropy.nddata.utils.Cutout2D`:

http://docs.astropy.org/en/stable/api/astropy.nddata.utils.Cutout2D.html

**Comment by Gabriel-p** [comment]
Thank you @larrybradley, I got an answer mentioning that class here: http://stackoverflow.com/q/40821565/1391441

**Comment by larrybradley** [comment]
Great.  I wrote `Cutout2D` after `cutout_footprint`.  `Cutout2D` is a more general-purpose function, while `cutout_footprint` is specialized function because of the`footprint` aspect of it.

**Comment by Gabriel-p** [comment]
I'd make it clear in [cutout_footprint](http://photutils.readthedocs.io/en/latest/api/photutils.utils.cutout_footprint.html) that the `box_size` is in the sense `(y, x)` and *not* `(x, y)` as one would tend to assume by default.

**Comment by larrybradley** [comment]
Thanks, will do.

**Comment by larrybradley** [comment]
Done in https://github.com/astropy/photutils/commit/c883e8ef3e3eb6ee3f25890854a155506d195b6b.
