### ISSUE TITLE
Modeling-related changes to PSF/PRF photometry

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#48]
Comments from @eteq, copied from #26:

* First, a few comments about how `astropy.modeling` is used here.  It looks to me like `DiscretePRF` and `GaussianPSF` are the *only* allowed classes, rather than arbitrary models from `astropy.modeling.models`.  This seems to mostly stem from the use of the `fit` method of the PSF/PRF classes.  Why is this necessary?  I can certainly imagine wanting to try other PSF models (most crucially, the Moffat function).  So I think it would be better if `DiscretePRF` and `GaussianPSF` obeyed standard convnetions for `Fittable2DModel`s, and the work of massaging those models into a form appropriate for `psf_photometry` should be done elsewhere (either a container class or in the `psf_photometry` function itself.  Otherwise, we effectively have two slightly different model-fitting frameworks 
* Why doesn't `GaussianPSF` use `modeling.models.Gaussian2D`? It seems to have implemented all the gaussian behavior separately?
* Why is the `fitter` hard-coded into the PSF/PRF class instead of following the convention used in `astro.modeling` of having it be a separate object?  Don't we want to allow other fitting methods?
* I think it would make sense to try to make `psf_photometry` and `aperture_photometry` more consistent.  E.g., right now `aperture_photometry` gets its centers from 2 arguments `xc` and `yx`, while `psf_photometry` accepts a single `positions` argument.  At the very least, these should be the same. It also might be useful to allow using `aperture_photometry` apertures to define the region in which a star is fit (although maybe that's more of a feature request).

**Comment by hamogu** [comment]
Reply to @larrybradley (a few comment above at https://github.com/astropy/photutils/issues/48#issuecomment-43771581 ): opened https://github.com/astropy/astropy/issues/4572 for that.
