### ISSUE TITLE
Cannot import DAOStarFinder

### ISSUE THREAD

**Issue by SiqiLiu-647** [astropy/photutils#480]
Hi, I met a issue like this: ImportError: cannot import name DAOStarFinder. 
All the test suites run well (photutils.test()).

**Comment by larrybradley** [comment]
`DAOStarFinder` was introduced in `photutils` version 0.3.  You can check your version using:

```
>>> import photutils
>>> photutils.__version__
'0.3'
```

**Comment by SiqiLiu-647** [comment]
Thanks, I later realized that is a version problem. Solved, thanks!
