### ISSUE TITLE
aperture radius in BasicPSFPhotometry

### ISSUE THREAD

**Issue by stefanocovino** [astropy/photutils#482]
Apparently setting an aperture radius for PSF photometry by BasicPSFPhotometry has no effect. The photometry is always computed with a radius equal to the adopted FWHM.

Thanks.

**Comment by mirca** [comment]
Hi @stefanocovino, thanks for reporting! Nevertheless, could you provide an minimal example where this issue arise? 
From the examples I quickly tried here, ``aperture_radius`` is correctly set to the value the user provided (if ``None``, it is indeed set to the FWHM of the PSF model).
Thanks again!

**Comment by stefanocovino** [comment]
Sure.

Here is the script. I have a large frame and I created a subframe to make the computation quicker. By the way, as well as for the aperture photometry, the possibility to provide a local background estimator might help. Essentially, it happens to be interested in deriving the photometry of a few selected objects and deriving a global background map can be a long task.

Thanks, 
   Stefano

-----
import numpy as np
from astropy.io.fits import getdata
from photutils.background import MMMBackground
from astropy.modeling.fitting import LevMarLSQFitter
from astropy.stats import gaussian_sigma_to_fwhm
from photutils.psf import IntegratedGaussianPRF, DAOGroup
from astropy.table import Table
from photutils.psf import BasicPSFPhotometry


fname = '/Users/covino/ownCloud/Data/GW/VST/G211117/2015-12-27/G211117_VST_r_20151227_p0.fits'
data = getdata(fname)

X = 16413.1409838
Y = 10859.3948134

i = np.rint(X).astype(np.int)-1
l = np.rint(Y).astype(np.int)-1
size = 75
image = data[l-size:l+size,i-size:i+size]

mmm_bkg = MMMBackground()
fitter = LevMarLSQFitter()

FWHM = 5.0
sigma_psf = FWHM/gaussian_sigma_to_fwhm
daogroup = DAOGroup(3.0*sigma_psf*gaussian_sigma_to_fwhm)

psf_model = IntegratedGaussianPRF(sigma=sigma_psf)
psf_model.x_0.fixed = True
psf_model.y_0.fixed = True

pos = Table(names=['x_0', 'y_0'], data=[[X-np.rint(X)+size],[Y-np.rint(Y)+size]])

photometry = BasicPSFPhotometry(group_maker=daogroup,bkg_estimator=mmm_bkg,psf_model=psf_model,fitter=LevMarLSQFitter(),fitshape=15,aperture_radius=5.)
rt = photometry(image=image, positions=pos)
print("Aperture 5 pixels: ", rt['flux_fit'][0])


photometry = BasicPSFPhotometry(group_maker=daogroup,bkg_estimator=mmm_bkg,psf_model=psf_model,fitter=LevMarLSQFitter(),fitshape=15,aperture_radius=7.)
rt = photometry(image=image, positions=pos)
print("Aperture 7 pixels: ", rt['flux_fit'][0])

photometry = BasicPSFPhotometry(group_maker=daogroup,bkg_estimator=mmm_bkg,psf_model=psf_model,fitter=LevMarLSQFitter(),fitshape=15)
rt = photometry(image=image, positions=pos)
print("Aperture FWHM: ", rt['flux_fit'][0])

-----


And the result is:

Aperture 5 pixels:  2158.77526169
Aperture 7 pixels:  2158.77526169
Aperture FWHM:  2158.77526169

**Comment by mirca** [comment]
Hi @stefanocovino, thanks for your quick reply :)!

Could you please print the values of rt['flux_0'] as well?

Thanks!

**Comment by stefanocovino** [comment]
Done.

Aperture 5 pixels:     x_0        y_0         flux_0     id group_id   x_fit      y_fit       flux_fit
---------- ---------- ------------- --- -------- ---------- ---------- -------------
75.1409838 75.3948134 1673.12912819   1        1 75.1409838 75.3948134 2158.77526169
Aperture 7 pixels:     x_0        y_0         flux_0     id group_id   x_fit      y_fit       flux_fit
---------- ---------- ------------- --- -------- ---------- ---------- -------------
75.1409838 75.3948134 1673.12912819   1        1 75.1409838 75.3948134 2158.77526169
Aperture FWHM:     x_0        y_0         flux_0     id group_id   x_fit      y_fit       flux_fit
---------- ---------- ------------- --- -------- ---------- ---------- -------------
75.1409838 75.3948134 1673.12912819   1        1 75.1409838 75.3948134 2158.77526169
Aperture 0.1 pixels:     x_0        y_0         flux_0     id group_id   x_fit      y_fit       flux_fit
---------- ---------- ------------- --- -------- ---------- ---------- -------------
75.1409838 75.3948134 1673.12912819   1        1 75.1409838 75.3948134 2158.77526169


If it helps I am running python 3.5.2 and photutils 0.3.

   Stefano

**Comment by mirca** [comment]
@stefanocovino thanks! I'm looking into that, but it's definitely strange!

**Comment by mirca** [comment]
@stefanocovino I got it :). The bug is that ``BasicPSFPhotometry`` is changing your ``pos`` so that it adds a ``flux_0`` column in ``pos`` which shouldn't be added.

I am going to open a pull request for this in the next few days. In the meantime, you can just repeat ``pos = Table(names=['x_0', 'y_0'], data=[[X-np.rint(X)+size],[Y-np.rint(Y)+size]])``, before calling ``rt = photometry(image=image, positions=pos)``. Also, you can just do ``photometry.aperture_radius = value`` to change the value of ``aperture_radius``.

@stefanocovino, again, thanks for reporting :)

**Comment by stefanocovino** [comment]
Hi,

Thanks a lot!


However, I tried to do as you suggest and actually flux_0 changes, while flux_fit remains always the same value.

Bye,
  Stefano



__________________

Mobilis in mobile

**Comment by mirca** [comment]
@stefanocovino That's good that ``flux_fit`` does not change :) It means the optimization algorithm is kind of robust to different values of the initial guess ``flux_0``. Also, your parameter space is one dimensional (only ``flux`` is being fitted), that should be pretty easy for ``LevMarLSQFitter`` to find the optimal value :)

**Comment by stefanocovino** [comment]
Ah, sorry! This is something I indeed misunderstood. 
The output is the total integrated flux for the PSF, not the flux within the aperture radius. With DAOPHOT, for instance, typically the flux you get is within the so-called fitting radius. Is there a way to get the fit flux within a given radius and not only to infinite?

For a 2DGaussian or pure analytic PSF the problem is easily solvable with a numeric integration to compute the correction factor. However with possible future semi-empirical PRF models this might be useful.

Bye,
  Stefano

Mobilis in Mobile

**Comment by mirca** [comment]
Hi @stefanocovino, oh yeah, I think I know what you mean. For now, the PSF Photometry classes available do not provide the fitting radius interface that you mention. However, you can adjust how much data is passed to the fitting process (which is what fitting radius does in DAOPHOT, right?) through ``fitshape``. The main difference is that ``fitshape`` takes a rectangular area of the image, while ``fitting radius`` in DAOPHOT would take a circular area... We definitely want to provide this feature, I'm going to add it to my todo list.

**Comment by stefanocovino** [comment]
> 
> Hi @stefanocovino <https://github.com/stefanocovino>, oh yeah, I think I know what you mean. For now, the PSF Photometry classes available do not provide the fitting radius interface that you mention. However, you can adjust how much data is passed to the fitting process (which is what fitting radius does in DAOPHOT, right?) through fitshape. The main difference is that fitshape takes a rectangular area of the image, while fitting radius in DAOPHOT would take a circular area... We definitely want to provide this feature, I'm going to add it to my todo list.
> 
> 

Very good, of course.

In this specific case I solved the problem since integrating a 2DGaussian with no covariance and equal sigma in both axis is trivial. If I assume, as I guess it is the case, that the flux_fit is within the FWHM radius circle then correction factor for flux within any circle can easily be derived.

Thanks again,

	Stefano
