### ISSUE TITLE
Make PSF/PRF fitting robust to NaN values

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#49]
As commented in #26:

It may be that we should make sure the fitting is robust to there being NaN values in the PRF. At the end of the day, if the PRF has NaN values, we should just ignore them with the fitting and fit only where there are valid model and data values?

**Comment by pkrskr** [comment]
Hi!
I wish to be of some help here. Please provide me with any relevant pointers if possible.

**Comment by larrybradley** [comment]
This was implemented in #159.
