### ISSUE TITLE
Broken badges

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#495]
For some reason many of the badges on the Readme page appear to be broken. However opening the image links individually in separate tabs works fine.
![screen shot 2017-01-24 at 16 34 53](https://cloud.githubusercontent.com/assets/6788290/22256606/3310cb82-e253-11e6-9ba2-95e33292e181.png)

**Comment by larrybradley** [comment]
@bsipocz They work for me.  It may have been a temporary glich (I think github caches badge images).

**Comment by bsipocz** [comment]
Indeed. All but one works for me now. Sorry for the noise, it seemed to be an odd issue from the beginning.
