### ISSUE TITLE
Background2D

### ISSUE THREAD

**Issue by dnfarias** [astropy/photutils#496]
A little question; I can't manage to do some background estimation using Background2D keyword  edge_method = 'pad' ('crop' does fine); this is the error (and it's pretty common on numpy arrays):

ValueError: total size of new array must be unchanged

Does anyone know something about this?

**Comment by bsipocz** [comment]
@dnfarias - Could you provide more info please? E.g. could you paste here the whole snippet of the code that produce this error? What is version of photutils you're using? What is the version of astropy and numpy?

**Comment by dnfarias** [comment]
hdulist = fits.open(image)
data = np.array(hdulist[0].data)
sigma_clip = SigmaClip(sigma=3., iters=20)
bkg = Background2D(data,box_size=[25,25],edge_method='pad',sigma_clip=sigma_clip)

numpy version: '1.11.2'
astropy version: 1.2.1

Thanks for your quick reply

**Comment by larrybradley** [comment]
Which version of `photutils` are you using?  Also, what is the shape of your `data` array?

**Comment by dnfarias** [comment]
photutils version: 0.3.dev2140
data shape: (91, 1676)

**Comment by dnfarias** [comment]
If you can reproduce the error please let me know; as you can see with box_size=[25x25] I tend to lose some information in the background using 'crop'.

**Comment by larrybradley** [comment]
Thanks, @dnfarias, for reporting this.  Indeed it is a bug, which will be fixed when #498 is merged.

**Comment by dnfarias** [comment]
Hi everyone, I'm sorry for 're-opening' this, but I have a doubt; I updated my version of photutils using:

pip install --no-deps git+https://github.com/astropy/photutils.git

and it fixed the error I had before (and I could run the code with no errores several times with different data shape; (91, 1677) for example). The main issue I have now is that I 'changed' the 'data'  and I added a mask with these shapes:

(91, 1675) (both)

and for some odd reason my code fails (again): 

 bkg = Background2D(back,mask=mask,box_size=[5,5],edge_method='pad',sigma_clip=sigma_clip)
  File "/home/dafh/miniconda2/envs/iraf27/lib/python2.7/site-packages/photutils/background/background_2d.py", line 335, in __init__
    self._prepare_data()
  File "/home/dafh/miniconda2/envs/iraf27/lib/python2.7/site-packages/photutils/background/background_2d.py", line 507, in _prepare_data
    self.nyboxes, self.box_size[0], self.nxboxes, self.box_size[1]),
  File "/home/dafh/miniconda2/envs/iraf27/lib/python2.7/site-packages/numpy/ma/core.py", line 4474, in reshape
    result = self._data.reshape(*s, **kwargs).view(type(self))
ValueError: total size of new array must be unchanged

But! If I change the box_size to e.g. [10,10], it works flawlessly. Could you explain me why this happens?

**Comment by larrybradley** [comment]
Thanks, @dnfarias.  I can reproduce this and I'm looking into it.

**Comment by larrybradley** [comment]
@dnfarias This is fixed now.  Please report back if you find anything else!
