### ISSUE TITLE
RectangularAperture creating masks that are too large

### ISSUE THREAD

**Issue by tepickering** [astropy/photutils#499]
I'm trying to use ``photutils.RectangularAperture`` to define apertures in Shack-Hartmann wavefront sensor data.  Rather than do photometry, though, I need to calculate centroids within each aperture.  So I use ``photutils.RectangularAperture.to_mask()`` to  generate the list of masks, loop through that list, and use ``ApertureMask.cutout()`` to generate the sub-image to centroid for each mask.  However, ``to_mask()`` is generating masks that are much larger than the apertures I'm defining.  In my case, ``w = h = 22`` for the apertures, but the masks being generated have a shape of ``(32, 32)``.  This looks suspiciously like a ``sqrt(2)`` scaling bug somewhere.

My workaround for now is to use ``CircularAperture`` which properly generates ``(23, 23)`` sub-images.

**Comment by larrybradley** [comment]
Thanks, @tepickering.  Yes, the issue is that the minimal bounding boxes for rectangles aren't currently "minimal".  Currently they are a factor of `sqrt(2)` larger to handle possible rotation (for photometry, the mask array size doesn't really matter, it's only for efficiency to be minimal).  I'll work on generating *actual* minimal bounding boxes.  Thanks.

**Comment by tepickering** [comment]
ah, that makes sense.  thanks for the quick response.

**Comment by larrybradley** [comment]
Instead of using `RectangularAperture`, could you use http://docs.astropy.org/en/stable/api/astropy.nddata.utils.Cutout2D.html and then perform a centroid on the cutout?

**Comment by tepickering** [comment]
i certainly could do things at a lower level like that.  however, it turns out i actually need to use circular apertures to more properly handle our one wavefront sensor that has hexagonal lenslets.  in that case, ``ApertureMask.cutout()`` does exactly what i want with a cutout of the right size with pixels outside the aperture radius filled to 0.0.  otherwise the corners of the cutouts are contaminated by light from neighboring apertures in that case.  so i'm good to go in terms of solving my immediate problems.  just wanted to highlight some behavior that i found to be "surprising" at first glance.

**Comment by larrybradley** [comment]
I implemented a true minimal bounding box in #507.
