### ISSUE TITLE
Use python3 on RTD?

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#505]
@bsipocz   Is it OK to switch RTD to `python3` or will this cause problems?

**Comment by bsipocz** [comment]
I think it should be fine, astropy core has switched already.

**Comment by larrybradley** [comment]
OK, doing it now.  Thanks!

**Comment by larrybradley** [comment]
The docs failed to build.  This is the only warning that I see:

copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist

@bsipocz Have you seen this before?

**Comment by bsipocz** [comment]
No, I haven't run into this one yet.
