### ISSUE TITLE
group stars from different iterations in the PSF Photometry algorithms

### ISSUE THREAD

**Issue by mirca** [astropy/photutils#517]
I think it would make sense to put stars which are identified in different iterations, but which overlap each other, in the same group. Further, one could re-fit that group with the correct model (i.e., correct number of stars), instead of treating stars identified in different iterations independently.

So, a pseudo code might be

```
1. perform psf photometry at iteration n
2. look for remaining stars in the residual image (iteration n+1)
3. put every star found in step 2 in the group that they overlap with.
4. using the data from iteration n, perform psf photometry with the new groups
5. repeat until either a given number of iterations is reached or no stars are found
```

**Comment by larrybradley** [comment]
This sounds reasonable to me.

**Comment by larrybradley** [comment]
This option is available in the new `IterativePSFPhotometry` class using the `mode='all'` option.
