### ISSUE TITLE
Return instrumental magnitude along with aperture sum

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#536]
The [aperture_photometry](https://photutils.readthedocs.io/en/stable/api/photutils.aperture_photometry.html) function currently returns just the sum of the flux within the aperture. Since the [instrumental magnitude](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?phot) can be obtained with:

    mag = -2.5 * log10((aperture_sum - bckg) / itime)

where `bckg` is the sky value estimate and `itime` is the exposure time, simply requesting the user to input the exposure would be enough to return the instrumental magnitude.

This would seem to be a much more useful quantity than the aperture sum?

**Comment by larrybradley** [comment]
Thanks, @Gabriel-p.  This is encompassed in #463.

BTW, I'm not sure why you have `itime` in your equation.  That must assume that the input `data` are in some specific units, which we definitely don't require.

**Comment by Gabriel-p** [comment]
Thank you @larrybradley.

The exposure (or integration) time `itime` is used by the [IRAF task](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?phot) `phot` to calculate the instrumental magnitude.

![captura realizada el 2017-04-19 20 51 42](https://cloud.githubusercontent.com/assets/6054951/25208563/eb49b3a4-254b-11e7-98e6-2354ef92b876.png)

As far as I understand it is used to bring frames of different exposures to a common scale. I guess it could be passed as part of the `zeropoint` factor defined in your `calibrate_magnitudes` function in #463?
