### ISSUE TITLE
Question on snr in make_source_mask and detect_threshold

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#539]
I was looking at `make_source_mask` documentation and the [source code](https://photutils.readthedocs.io/en/stable/_modules/photutils/segmentation/detect.html#make_source_mask) and became curious about the term `snr`. Maybe I am misunderstanding some concepts. If you find I'm wrong with something, comments will be very helpful.

-----

Usually the roughly estimated signal to noise ratio, or the SNR, for **one pixel**, is defined as something like

`(count - msky) / (sqrt(count * gain + rd**2) / gain)`, or
`(count - msky) / sqrt(count / gain + (rd / gain)**2)`,

where `count` is the pixel value (thus containing source, sky, and dark current values; but dark ~ 0 or have already been subtracted in most cases), `msky` is the estimated sky value which can be sigma-clipped median, `gain` is the gain in e/adu, and `rd` is the readout noise in electrons. (I used `gain` to correct each term to be in ADU scale, not in electrons unit)

Since `detect_threshold` returns `background + (error * snr)`, I think the `error` here should include the Poisson noise of the pixel, not the background standard deviation, but the documentation says the `error` should **not** include the Poisson noise. If `snr` is used to be multiplied to the `error` (which is the standard deviation of sigma clipped statistics of masked image), I think it is confusing to use the name `snr`. 

**But this is what `make_source_mask` does**, as far as I understood. In the source code of it, it has 
```python
threshold = detect_threshold(data, snr, background=None, error=None, ...
```
Sicne `error` is given as `None`, it means the `threshold` is the "sigma clipped mean of image + `snr` * sigma clipped std of image", which is not expected at least for me, since the input of `make_source_mask` was `snr`, not something like `ksigma` (k-sigma clipping). 

-----

In otherwords, I think the following features are needed:

* A function which generates pixel-wise SNR map with the same size of that of the input image, e.g., `make_snr_map(input, gain=1.0, readnoise=0.0, msky=None, sigclip_sigma=3, sigclip_iters=10)`.   
  * If `msky != None` (float or numpy ndarray), that will be used for SNR calculation. If `None`, it will be estimated from `sigma_clipped_stats(input, sigma=sigclip_sigma, iters=sigclip_iters)`.
* Instead of `detect_threshold`, I think the following can be used for `make_source_mask`:
```python
# concept sketch
# backward compatibility: add `use_snr_map = False` to `make_source_mask`
if use_snr_map:
    snr_map = make_snr_map(data, msky=None, 
                           gain=gain, readnoise=readnoise, 
                           sigclip_sigma=sigclip_sigma, 
                           sigclip_iters= sigclip_iters)
    segm = detect_sources(snr_map, threshold=snr, npixels=npixels, filter_kernel=kernel)
```
  * I am not sure how the `filter_kernel` should be used; this is just a concept sketch.

Are these already available in astropy or photutils? Or am I misunderstanding something on the parameter `snr`?

**Comment by ysBach** [comment]
As a very primitive manner, I have made the following code for check:

```python
def my_make_source_mask(data, snr, npixels, mask=None, mask_value=None,
                     filter_fwhm=None, filter_size=3, filter_kernel=None,
                     sigclip_sigma=3.0, sigclip_iters=5, dilate_size=11,
                     gain=1.0, readnoise=0.0, use_snr_map=False):

    from scipy import ndimage
    from photutils import detect_threshold, detect_sources
    from astropy.stats import gaussian_fwhm_to_sigma
    from astropy.convolution import Gaussian2DKernel
    threshold = detect_threshold(data, snr, background=None, error=None,
                                 mask=mask, mask_value=None,
                                 sigclip_sigma=sigclip_sigma,
                                 sigclip_iters=sigclip_iters)

    kernel = None
    if filter_kernel is not None:
        kernel = filter_kernel
    if filter_fwhm is not None:
        sigma = filter_fwhm * gaussian_fwhm_to_sigma
        kernel = Gaussian2DKernel(sigma, x_size=filter_size,
                                  y_size=filter_size)
    if kernel is not None:
        kernel.normalize()

    if use_snr_map:
        snr_map = make_snr_map(data, msky=None,
                               gain=gain, readnoise=readnoise,
                               sigclip_sigma=sigclip_sigma,
                               sigclip_iters= sigclip_iters)
        segm = detect_sources(snr_map, threshold=snr, npixels=npixels, filter_kernel=kernel)
    else:
        segm = detect_sources(data, threshold, npixels, filter_kernel=kernel)

    selem = np.ones((dilate_size, dilate_size))
    
    return ndimage.binary_dilation(segm.data.astype(np.bool), selem)


def make_snr_map(data, gain=1.0, readnoise=0.0, msky=None, 
                 sigclip_sigma=3, sigclip_iters=10):
    datacp = data.copy()

    if msky==None:
        avg, med, std = sigma_clipped_stats(data, sigma=sigclip_sigma, iters=sigclip_iters)
        msky = med

    signal = datacp - msky
    noise = np.sqrt(datacp / gain + (readnoise / gain)**2)
    return signal/noise
```

and used it as
```python
snr=3
mask1 = my_make_source_mask(img, snr=snr, npixels=5,
                            use_snr_map=True,
                            gain=0.94, readnoise=5)
mask2 = make_source_mask(img, snr=snr, npixels=5)

plt.imshow(img, vmin=9000, vmax=11000, origin='lower')
plt.colorbar()
plt.imshow(mask2-mask1, alpha=0.35,origin='lower')
```
Following figures are the results from `snr=3` and `snr=5`, respectively.
In the overplotted image, **yellow-ish overplot** = *new function detected while the original did not*.
![anr3](https://cloud.githubusercontent.com/assets/17214293/25565934/d675c1e8-2e0b-11e7-93f2-5229a8a2e6c2.png)
![snr5](https://cloud.githubusercontent.com/assets/17214293/25565935/d7dd1f86-2e0b-11e7-8684-1e7204ef36de.png)

**Comment by larrybradley** [comment]
Thanks, @ysBach Indeed, `snr` was the wrong name for this keyword.  It was renamed to `sigma` back in #917.
