### ISSUE TITLE
Better center coordinates given initial values

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#540]
The [phot IRAF task](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?phot.hlp) computes accurate center coordinates given initial approximate values. Is there some function in `photutils` that can do this?

This is a rough sketch I made using [cutout_footprint](http://photutils.readthedocs.io/en/stable/api/photutils.utils.cutout_footprint.html) and [centroid_2dg](http://photutils.readthedocs.io/en/stable/api/photutils.centroid_2dg.html)

```
def reCenter(hdu_data, xy_initial, side=30):
    """
    Find better center coordinates using 'centroid_2dg'.
    """
    xy_cent = []
    for x, y in xy_initial:
        crop = cutout_footprint(hdu_data, (x, y), side)[0]
        xy_cent.append(centroid_2dg(crop))
    return xy_cent
```

**Comment by larrybradley** [comment]
The `centroid_sources` function does this:  https://photutils.readthedocs.io/en/latest/api/photutils.centroids.centroid_sources.html#photutils.centroids.centroid_sources
