### ISSUE TITLE
Help reproducing fitparams task

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#546]
Disclaimer: _This is not an issue with `photutils`. I'm just out of ideas and I don't where else to turn for help. I will therefore understand completely if this is closed on the spot. That said, I will really appreciate any help you could give me, since I've been trying to figure this out for weeks now._

--------------------------------------------------------------------------
I'm trying to reproduce the [fitparams](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?fitparams) task from the `photcal` package.

I've already sent en email to the STScI (the developers of Pyraf), posted in the [IRAF forum](http://iraf.net/forum/viewtopic.php?msg=1&showtopic=1469632), and even wrote to Lindsey Davis. The STScI guys told me they don't work with this package and I should ask in the forum, the forum post has been sitting there for ~20 days (it doesn't look like it's going to receive an answer), and I never got a response from Dr Davis.

In page 32 of the [A user's guide to stellar CCD photometry with IRAF](https://www.mn.uio.no/astro/english/services/it/help/visualization/iraf/daophot2.pdf)  guide, an output of doing a `:vshow` in `fitparams` is shown in Fig 27:

![captura realizada el 2017-05-23 16 36 17](https://cloud.githubusercontent.com/assets/6054951/26372927/fd75dfe0-3fd5-11e7-9cda-03c915157da2.png)

Where `function, fit` are the observed and predicted values in the best found least squares regression, `residuals=function-fit`, and I have no idea how `sigma` is obtained or what it represents (issue 1. below). I'd like to reproduce the statistical values found for the fit. I can (almost) reproduce most of these:

```
standard deviation 0.0214969
reduced chi        1.0036573
average error      0.0214577
average scatter    ?
RMS                0.0183326
```

 as follows :

* **standard deviation**

      sum_sq = np.sum((function - fit) ** 2)
      nu = len(function) - deg
      stddev = np.sqrt(sum_sq / nu)

   where `deg=3` since 3 parameters parameters are being fitted.

* **reduced chi**

      chisq = np.sum(((function - fit) / sigma) ** 2)
      nu = len(function) - deg
      red_chi = chisq / nu

* **average error**

      avrg_error = stddev / np.sqrt(red_chi)

* **average scatter**

      avrg_scatter = ?

* **RMS**

      RMS = np.sqrt(((function - fit) ** 2).mean())

The issues I find are:

1. I don't know how the `sigma` column (rightmost column in Fig 27) is obtained. Following the trace, I see that the `iraf/pkg/xtools/inlfit/ingresults.gx` file writes to that column the following values:

        (sqrt (PIXEL (1.0) / Mem$t[wts1+i-1]))

   I assume `Mem$t[wts1+i-1]` is some kind of standard deviation? I tried diving in deeper into the code, but the language used (some kind of mixture between `C` and `Fortran`?) looks like an impossible mess to decipher to me.
1. I can not reproduce the `average scatter` value. I have no idea what formula is used. I've tried several to no avail.
1. Most of the statistical parameters shown above (except the `average scatter`) are *almost* reproduced using those equations. There are visible differences nonetheless,  which I can only assign to floating point rounding errors by `fitparams` (as long as the formulas shown above are correct).

**Comment by larrybradley** [comment]
@Gabriel-p I left this open for a week hoping someone could answer, but apparently not -- so I'm closing this now.  Even though this is not a python question, you could try to ping the "Python users in Astronomy" Facebook group, which has a wider audience of over 2300 members.  Ultimately, you may need to decipher the code (unless you can find the original author).  If it helps, the language is called "Subset Preprocessor Language (SPP)".  Here is the SPP reference manual:  http://stsdas.stsci.edu/documents/SPP/SP_72.html

**Comment by Gabriel-p** [comment]
Thanks @larrybradley. I knew it was a long shot asking here, but I had to try. I know the FB group you mention. I sent a request for joining months ago, but it is still pending.

**Comment by mirca** [comment]
@Gabriel-p I think I can add you to the FB group, but you need to be my friend first (:

**Comment by bsipocz** [comment]
@kelle is one of the admins there (I'm not sure who else), they can add you as a member.

**Comment by kelle** [comment]
@Gabriel-p I've just approved your request to join the FB group.

**Comment by Gabriel-p** [comment]
Thank you all!
