### ISSUE TITLE
Using a Moffat PSF

### ISSUE THREAD

**Issue by saimn** [astropy/photutils#558]
Using `IterativelySubtractedPSFPhotometry` with a `Moffat2D` from Astropy (master) does not work:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-47-57afc0e78197> in <module>()
      5                                                 fitter=LevMarLSQFitter(),
      6                                                 niters=2, fitshape=(11,11))
----> 7 result_tab = photometry(imsub.data)
      8 residual_image = photometry.get_residual_image()

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/dev/photutils/photutils/psf/photometry.py in __call__(self, image, init_guesses)
    194         """
    195 
--> 196         return self.do_photometry(image, init_guesses)
    197 
    198     @deprecated_renamed_argument('positions', 'init_guesses', '0.4')

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/dev/photutils/photutils/psf/photometry.py in do_photometry(self, image, init_guesses)
    660             if self.aperture_radius is None:
    661                 if hasattr(self.psf_model, 'fwhm'):
--> 662                     self.aperture_radius = self.psf_model.fwhm.value
    663                 elif hasattr(self.psf_model, 'sigma'):
    664                     self.aperture_radius = (self.psf_model.sigma.value *

AttributeError: 'numpy.float64' object has no attribute 'value'
```
Maybe related to https://github.com/astropy/astropy/pull/6027 which added a `fwhm` attribute which is a scalar (so no `.value` attribute) ?

**Comment by saimn** [comment]
I also tested with `Gaussian2D` from Astropy, just to see, and get another (different) failure. Is it required to use a photutils-specific PSF object ?

**Comment by mirca** [comment]
@saimn This can be solved by initializing ``aperture_radius`` with a positive float value when creating a ``IterativelySubtractedPSFPhotometry`` object.

> Is it required to use a photutils-specific PSF object ?

In principle, no. ``psf_model`` should be any ``astropy.modeling.Fittable2DModel`` which meets the criterion of having ``x_0``, ``y_0``, and ``flux`` as parameters.

**Comment by mirca** [comment]
@saimn 

> Maybe related to astropy/astropy#6027 which added a fwhm attribute which is a scalar (so no .value attribute) ?

I guess so, ``fwhm`` has been added as a property which indeed does not have ``value`` as attribute.

**Comment by saimn** [comment]
@mirca - indeed, setting `aperture_radius` allows to bypass the first issue. But then I get almost the same error as with `Gaussian2D`:
```
ValueError                                Traceback (most recent call last)
<ipython-input-32-4e074b1e2332> in <module>()
      5                                                 fitter=LevMarLSQFitter(), aperture_radius=5,
      6                                                 niters=2, fitshape=(11,11))
----> 7 result_tab = photometry(imsub.data)
      8 residual_image = photometry.get_residual_image()

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/dev/photutils/photutils/psf/photometry.py in __call__(self, image, init_guesses)
    194         """
    195 
--> 196         return self.do_photometry(image, init_guesses)
    197 
    198     @deprecated_renamed_argument('positions', 'init_guesses', '0.4')

~/dev/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/dev/photutils/photutils/psf/photometry.py in do_photometry(self, image, init_guesses)
    665                                             gaussian_sigma_to_fwhm)
    666 
--> 667             output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
    668         return output_table
    669 

~/dev/photutils/photutils/psf/photometry.py in _do_photometry(self, param_tab, n_start)
    691 
    692         output_table = Table()
--> 693         self._define_fit_param_names()
    694 
    695         for (init_param_name, fit_param_name) in zip(self._pars_to_set.keys(),

~/dev/photutils/photutils/psf/photometry.py in _define_fit_param_names(self)
    395         """
    396 
--> 397         xname, yname, fluxname = _extract_psf_fitting_names(self.psf_model)
    398         self._pars_to_set = {'x_0': xname, 'y_0': yname, 'flux_0': fluxname}
    399         self._pars_to_output = {'x_fit': xname, 'y_fit': yname,

~/dev/photutils/photutils/psf/funcs.py in _extract_psf_fitting_names(psf)
     42         fluxname = 'flux'
     43     else:
---> 44         raise ValueError('Could not determine flux name for psf_photometry.')
     45 
     46     return xname, yname, fluxname

ValueError: Could not determine flux name for psf_photometry.
```

**Comment by mirca** [comment]
@saimn That's because ``Gaussian2D`` does not have a parameter name called ``flux`` (or ``x_0`` and ``y_0``). Check [this](https://photutils.readthedocs.io/en/stable/api/photutils.psf.prepare_psf_model.html#photutils.psf.prepare_psf_model) out for a function which converts a ``Fittable2DModel`` into a "valid" PSF model.

**Comment by saimn** [comment]
I tried with `prepare_psf_model` but still no luck. First, it sets attributes `xname`, `yname`, but `_extract_psf_fitting_names` looks for `psf_xname` and `psf_yname`. Then, if I fix `_extract_psf_fitting_names` (seems the most obvious solution), I end up with this:
```
--------------------------------------------------
AttributeError   Traceback (most recent call last)
<ipython-input-36-cf9020d6de41> in <module>()
      6                                                 aperture_radius=5,
      7                                                 niters=2, fitshape=(11,11))
----> 8 result_tab = photometry(imsub.data)
      9 residual_image = photometry.get_residual_image()

~/lib/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/lib/photutils/photutils/psf/photometry.py in __call__(self, image, init_guesses)
    188         """
    189 
--> 190         return self.do_photometry(image, init_guesses)
    191 
    192     @deprecated_renamed_argument('positions', 'init_guesses', '0.4')

~/lib/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/lib/photutils/photutils/psf/photometry.py in do_photometry(self, image, init_guesses)
    657                                             gaussian_sigma_to_fwhm)
    658 
--> 659             output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
    660         return output_table
    661 

~/lib/photutils/photutils/psf/photometry.py in _do_photometry(self, param_tab, n_start)
    714             star_groups = self.group_maker(init_guess_tab)
    715             table, self._residual_image = super(IterativelySubtractedPSFPhotometry,
--> 716                     self).nstar(self._residual_image, star_groups)
    717 
    718             star_groups = star_groups.group_by('group_id')

~/lib/photutils/photutils/psf/photometry.py in nstar(self, image, star_groups)
    350                                     image[usepixel])
    351             param_table = self._model_params2table(fit_model,
--> 352                                                    len(star_groups.groups[n]))
    353             result_tab = vstack([result_tab, param_table])
    354 

~/lib/photutils/photutils/psf/photometry.py in _model_params2table(self, fit_model, star_group_size)
    462                 for param_tab_name, param_name in self._pars_to_output.items():
    463                     param_tab[param_tab_name][i] = getattr(fit_model,
--> 464                                                            param_name + '_' + str(i)).value
    465         else:
    466             for param_tab_name, param_name in self._pars_to_output.items():

~/lib/astropy/astropy/modeling/core.py in __getattr__(self, attr)
   2784         # This workaround allows descriptors to work correctly when they are
   2785         # not initially found in the class __dict__
-> 2786         value = getattr(self.__class__, attr)
   2787         if hasattr(value, '__get__'):
   2788             # Object is a descriptor, so we should really return the result of

~/lib/astropy/astropy/modeling/core.py in __getattr__(cls, attr)
   2215             return getattr(cls, attr)
   2216 
-> 2217         raise AttributeError(attr)
   2218 
   2219     def __repr__(cls):

AttributeError: x_mean_2_0
```

**Comment by conornally** [comment]
I have a different error using Moffat2D that i was hoping someone could give me some insight as to its origin or repair.
Initialising the fitter with:
`fitter = Moffat(alpha=2.5)`

And i have created a DiscretePRF instance (from images) to use as a psfmodel.
I get this error straight:
[log.txt](https://github.com/astropy/photutils/files/2106290/log.txt)

When using the default fitter, i dont seem to get it, however the moffat fitter is quite important to the work im trying to do.
Thanks in advance!

**Comment by larrybradley** [comment]
@conornally `Moffat2D` is a *model* not a fitter.  Did you mean to set the `psf_model`?  

Here are the astropy fitters:  http://docs.astropy.org/en/stable/modeling/#module-astropy.modeling.fitting

**Comment by conornally** [comment]
ah wonderful! i must have gotten mixed up

**Comment by conornally** [comment]
Hi again, i have a more related question this time,
A picture generated psf seems to cause flux calculation problems in my daophot run through, so im experimenting using moffat2d as the psf instead.
After running the `Moffat2D(alpha=2.5)` through `prepare_psf_model()`, i get the same errors as above when  try to set the names to `x_0, y_0, flux`. 

>   File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 190, in __call__
    return self.do_photometry(image, init_guesses)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 669, in do_photometry
    output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 730, in _do_photometry
    self._residual_image, star_groups)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 356, in nstar
    len(star_groups.groups[n]))
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 471, in _model_params2table
    '_' + str(i)).value
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2888, in __getattr__
    value = getattr(self.__class__, attr)
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2280, in __getattr__
    raise AttributeError(attr)
AttributeError: x_0_2_0


So i tried leaving them as the defaults but `DAOPhotPSFPhotometry()` gives me this error. I get the same error when i am using `Gaussian2D()` as well.

> Traceback (most recent call last):
  File "run.py", line 73, in <module>
    psfcatalog = daophot(datatools.openfits(filename), psf)
  File "/home/conor/research/M32/src/psfPhotometry.py", line 26, in __call__
    self.catalog = self.psfphot(self.data.copy(), self.psf)
  File "/home/conor/research/M32/src/psfPhotometry.py", line 59, in psfphot
    return daophot(data)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 190, in __call__
    return self.do_photometry(image, init_guesses)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 669, in do_photometry
    output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 730, in _do_photometry
    self._residual_image, star_groups)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 356, in nstar
    len(star_groups.groups[n]))
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 471, in _model_params2table
    '_' + str(i)).value
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2888, in __getattr__
    value = getattr(self.__class__, attr)
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2280, in __getattr__
    raise AttributeError(attr)
AttributeError: offset_0_0

**Comment by conornally** [comment]
Hi again, i have a more related question this time,
A picture generated psf seems to cause flux calculation problems in my daophot run through, so im experimenting using moffat2d as the psf instead.
After running the `Moffat2D(alpha=2.5)` through `prepare_psf_model()`, i get the same errors as above when  try to set the names to `x_0, y_0, flux`. 

>   File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 190, in __call__
    return self.do_photometry(image, init_guesses)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 669, in do_photometry
    output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 730, in _do_photometry
    self._residual_image, star_groups)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 356, in nstar
    len(star_groups.groups[n]))
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 471, in _model_params2table
    '_' + str(i)).value
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2888, in __getattr__
    value = getattr(self.__class__, attr)
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2280, in __getattr__
    raise AttributeError(attr)
AttributeError: x_0_2_0


So i tried leaving them as the defaults but `DAOPhotPSFPhotometry()` gives me this error. I get the same error when i am using `Gaussian2D()` as well.

> Traceback (most recent call last):
  File "run.py", line 73, in <module>
    psfcatalog = daophot(datatools.openfits(filename), psf)
  File "/home/conor/research/M32/src/psfPhotometry.py", line 26, in __call__
    self.catalog = self.psfphot(self.data.copy(), self.psf)
  File "/home/conor/research/M32/src/psfPhotometry.py", line 59, in psfphot
    return daophot(data)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 190, in __call__
    return self.do_photometry(image, init_guesses)
  File "/usr/local/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 669, in do_photometry
    output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 730, in _do_photometry
    self._residual_image, star_groups)
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 356, in nstar
    len(star_groups.groups[n]))
  File "/usr/lib64/python3.6/site-packages/photutils/psf/photometry.py", line 471, in _model_params2table
    '_' + str(i)).value
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2888, in __getattr__
    value = getattr(self.__class__, attr)
  File "/usr/local/lib64/python3.6/site-packages/astropy/modeling/core.py", line 2280, in __getattr__
    raise AttributeError(attr)
AttributeError: offset_0_0

**Comment by mirca** [comment]
@conornally Thanks for reporting this issue! How exactly are you using ``Moffat2D`` into ``prepare_psf_model``?

**Comment by jbodenst** [comment]
I actually have the same question as @mirca, how do I convert Moffat2D into a usable PSF model with prepare_psf_model?

**Comment by hamogu** [comment]
@jbodenst : I don't know what @conornally did, but to answer your question:
```
psffunc = astropy.models.Moffat2D(amplitude=1, gamma=2, alpha=2.8, x_0=0, y_0=0)
psf1 = photutils.psf.prepare_psf_model(psffunc, xname='x_0', yname='y_0', fluxname=None)
```
should work.

**Comment by bsipocz** [comment]
Actually I'm going ahead and close this one and reopen the duplicate #845 as that one has a copy paste-able minimal failing example that enormously helps testing.
