### ISSUE TITLE
plotting the RectangularAperture results in TypeError

### ISSUE THREAD

**Issue by panossk** [astropy/photutils#559]
Hi, 
I'm working on a photometry measuring script for which I will ultimately need to make rectangular apertures. My script works fine with circular ones, but once I switched to rectangular ones, 
the script fails in the plotting part, regardless of the fact that the photometry seems to be measured ok. 

So i define my aperture:

apertures = RectangularAperture(pix_coords, w= 20, h= 20, theta= 0) 

and later on in the plotting section even I specify no arguments at all, as in:

apertures.plot()

I get the following error: 
TypeError: _init_() takes exactly 4 arguments (6 given) 

I can't figure out what the issue with the arguments is. How am I giving 6 arguments? And how can I control this since I basically give 0 arguments? 
It points me to the package's rectangle.py file, line 205. From what I can tell, it refers to the 4 arguments provided in the previous line, but I can't understand how do I end up with 6. 
Of course if I try to specify aesthetic details (colors, linewidths, etc) the number goes up. 
Any one can help?

It is a single aperture right now, but next I'll need multiple ones, and it will be crucial that I be able to control their positioning visually at every attempt.

**Comment by larrybradley** [comment]
@panossk I cannot reproduce this error.  What version of `photutils` are you using?

```python
import numpy as np
from photutils import RectangularAperture

data = np.random.rand(100, 100)
aper = RectangularAperture((30, 30), w=20, h=20, theta=0)
plt.imshow(data)
aper.plot(color='white', lw=3)
```

![download](https://user-images.githubusercontent.com/4992897/27886326-92d2efde-61a9-11e7-9f36-c0107e100c1f.png)

**Comment by panossk** [comment]
Hi Larry, thanks for answering. 

I noticed I was on 0.2.2, and upgraded to 0.3.2.  
That doesn't seem to solve my problem though. I executed your bit of script, and it resulted in the same error:

`>>> import matplotlib.pylab as plt
>>> import numpy as np
>>> from photutils import RectangularAperture
>>> data = np.random.rand(100,100)
>>> aper = RectangularAperture((30,30),w=50, h= 20, theta= 45)
>>> 
>>> plt.imshow(data)
>>> aper.plot()`

and the result was:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/photutils/aperture/rectangle.py", line 205, in plot
    **kwargs)
TypeError: __init__() takes exactly 4 arguments (6 given)


However, this might help us locate the issue better, as I noted that executing the same script on my laptop worked fine (on 0.3 and 0.3.2), it just doesn't work on my workstation (on which I should keep working, as it contains all the data I need to work on, and they're pretty massive). 
Does this mean some **other** package/installation of my python distrib may be the culprit?

**Comment by bsipocz** [comment]
@panossk - I wonder whether the matplotlib versions differ on the two computers?

**Comment by larrybradley** [comment]
That suggests that `matplotlib` is the culprit.  Line 205 of `rectangle.py` (from your traceback) is a call to `matplotlib.mpatches.Rectangle`.

**Comment by panossk** [comment]
thanks, Brigitta and Larry for pointing this out, I will check it right away, and get back to you.

**Comment by bsipocz** [comment]
@larrybradley - maybe we should state a minimum mpl somewhere in the docs?

**Comment by larrybradley** [comment]
@bsipocz - yep, it's already there in the installation docs: `matplotlib > 1.3` (http://photutils.readthedocs.io/en/latest/photutils/install.html)

**Comment by panossk** [comment]
ok, so indeed, on my workstation it was version 1.2.0, whereas on my laptop 1.3.1.

I just updated it to the latest (2.0.something), and it seems to handle it worse. 
Now the error message is many lines long. 

I tried to install v1.3.1 specifically but pip fails this particular task, for yet another reason I can't understand. 

So right now I'm without functional matplotlib.

**Comment by larrybradley** [comment]
@panossk I'm using the latest`matplotlib` (2.0.2), so perhaps something happened with your installation.  If you are using pip, you could try uninstalling first (`pip uninstall matplotlib`; perhaps run this more than once to be sure) and then `pip install matplotlib` (v2.0.2) (or `pip intstall matplotlib==1.3.1`).

**Comment by panossk** [comment]
If I use version 2.0.2 of mpl, I can't even import mpl without an error saying I'm missing the module called Tkinter.
If I google this rapidly, it seems related to python3. 
Now the last thing I'd want to mess with is python versions beyond 2.7 (if I understand what I'm seeing well). 

I did what you suggested, but demanding the specific version (also 1.4, which i tried randomly), results in a pip error.  I will again, and will repeat the uninstall as you propose, to see if it helps.

**Comment by larrybradley** [comment]
If `pip` is giving you trouble, you can always directly download the source tarball for whichever version you want (from https://github.com/matplotlib/matplotlib/releases).

Unpack the tarball, cd to the matplotlib directory, and then run `python install setup.py`.

In case your not aware of it, I'd also suggest you look into Anaconda/Conda (https://www.continuum.io/downloads; https://conda.io/docs/) as your package manager.

**Comment by panossk** [comment]
I must be doing something very wrong. 

I tried installing it as you suggested ( i suppose you meant `python setup.py install`, right? because with "install" first, it looks for a file called install), and nothing happens. 

I downloaded v1.3.1 from the link you provided, unpacked, went into the directory with setup.py, executed the command, it shows some text starting with "==========" and some parameters below, but nothing happens in the end.

**Comment by larrybradley** [comment]
@panossk Sorry, yes, `python setup.py install`.  I'm not sure what else to suggest other than trying Anaconda/Miniconda.  Any ideas, @bsipocz?

**Comment by panossk** [comment]
As far as version 2.0.2 goes, my issue is this module called "tkinter", which I can't understand what it is about. 

I'm trying Anaconda as we speak.

**Comment by larrybradley** [comment]
Have you tried to install `tkinter`:  `pip install tkinter`?

**Comment by panossk** [comment]
yes, it is not a "package" so pip doesn't find it.

**Comment by panossk** [comment]
Anaconda seems to be re-installing the whole python distribution. I hope that's not a problem.

**Comment by panossk** [comment]
**Update**:

ok so with Anaconda it seems the python distrib was re-installed or something like this. 
Matplotlib is available (2.0.2) but photutils is gone. That should be easy to re-install too, so I might be close to the end of the tunnel.

**Comment by panossk** [comment]
Ok, I guess I'm not going to be lucky any time soon. 

Photutils is installed but python now can't "see" it and acts like it's not.

I already uninstalled it and re-installed it but to no avail.

**Comment by larrybradley** [comment]
`photutils` isn't included with Anaconda, but you can easily install it from the astropy channel:

`conda install photutils -c astropy`

**Comment by larrybradley** [comment]
Does it show up in `conda list`?

**Comment by bsipocz** [comment]
Locally I have 2.0.0 and 2.0.2 for python2.7 and python3.5 using pip. I've never run into this tkinter issue (it seems to be the python interface to tcl/tk, I have the installed by fink). So without digging into the specifics of your system, the easiest I can suggest is indeed to go with conda.

All the astropy affiliates are available in the ``astropy`` channel, you can specify it with ``-c astropy`` for the conda commands.

**Comment by bsipocz** [comment]
Oh, one more thing. If it was your desktop, probably you've used the system package manager to install the python packages, rather than pip? (e.g. apt-get, dpkg, etc). If that's the case, you may want to try them to install mpl, as pip could mess up those cases...

**Comment by panossk** [comment]
@larrybradley 
thanks for the command line, I started looking for it and it seemed not obvious to find (most fora pointed to Windows for some reason...).

Ok so now photutils is installed, everything seems correctly imported in my python (it also installed ipython, which for some reason I could not before, and I find it quite more handy when working interactively), and my script worked! I can finally see my much needed rectangle on the image data! 
I notice btw that the new interface for the plots has been "uplifted", wow, we can even configure the axes on the plot directly now! 

@bsipocz indeed there might be some of that in the story, as I received the desktop at my workplace already configured by other colleagues so I didn't know all the details of how they did it. 
Anaconda seems to have solved this part too. 
Clearly if it's as simple to use as pip but so much more robust, I'll undoubtedly switch to it. 

Anyway, I can't thank you guys both for your instant and patient assistance. 
I think I'm out of the swamp for now.  It's great to know we can rely on you when in desperation, working with photutils will be much more painless thanks to you. 

That said, I hope I wont have to return and nag you too soon after this, as I surely tend to get stuck often. Thanks again!

**Comment by larrybradley** [comment]
@panossk Glad to hear to you got it working!
