### ISSUE TITLE
Attribute error for multiple positions

### ISSUE THREAD

**Issue by charlotteolsen** [astropy/photutils#560]
I'm getting an attribute error when trying to create a phot_table for multiple positions. 
Here is what happens when I try to run  the example for multiple elliptical apertures.
<
**positions = [(30., 30.), (40., 40.)]

a = [5., 6., 7.]
b = [3., 4., 5.]
theta = np.pi / 4.
apertures = [EllipticalAperture(positions, a=ai, b=bi, theta=theta)
              for (ai, bi) in zip(a, b)]
phot_table = aperture_photometry(data, apertures)
print(phot_table)

Traceback (most recent call last):

  File "<ipython-input-107-02fc72f87c39>", line 6, in <module>
    phot_table = aperture_photometry(data, apertures)

  File "//anaconda/lib/python2.7/site-packages/astropy/utils/decorators.py", line 636, in aperture_photometry
    func = make_function_with_signature(func, name=name, **wrapped_args)

  File "//anaconda/lib/python2.7/site-packages/astropy/nddata/decorators.py", line 138, in wrapper
    result = func(data, *args, **kwargs)

  File "//anaconda/lib/python2.7/site-packages/photutils/aperture_core.py", line 1394, in aperture_photometry
    pixelpositions = ap.positions * u.pixel

AttributeError: 'list' object has no attribute 'positions'>**

I'm running python 2.7 
Seems like it should be something simple, and yet...
Any ideas?
Thank you in advance.

**Comment by larrybradley** [comment]
@charlotteolsen Your example works fine for me.  It appears that you are using an older version of `photutils` that does not support multiple apertures.  That feature was introduced in v0.3.

What version are you using?  Here's how you can check:

```python
>>> import photutils
>>> print(photutils.__version__)
```

**Comment by charlotteolsen** [comment]
Aha! That looks like it's the problem. It appears I'm running version 0.2.2

I will update!

Thank you so much!
