### ISSUE TITLE
Defining a custom aperture

### ISSUE THREAD

**Issue by Mahyaaa** [astropy/photutils#564]
Is there the possibility to define a ds9 region (any kind of polygon) and do the photometry inside the region? Since I should measure the flux for the filaments, the regular shapes of apertures can not be used. Therefore, I need to define a custom aperture in a shape of an arbitrary polygon.

**Comment by larrybradley** [comment]
@Mahyaaa  Not yet.  There are plans to add polygon regions to the astropy regions package (http://astropy-regions.readthedocs.io/en/stable/), but they are not defined yet.  Once added there, they could be used to perform photometry.

**Comment by bsipocz** [comment]
For the record, there is already an issue about it #467

**Comment by suvadip31** [comment]
Now that the polygon regions are added to the astropy `regions` package, any idea how to use `photutils` to do photometry in a polygon region defined in ds9?
