### ISSUE TITLE
problem in centroid_com

### ISSUE THREAD

**Issue by stefanocovino** [astropy/photutils#580]
I have just installed photutils 0.3.2 under python 3.6.1 as provided by anaconda on Mac OS X.

However, running my code, I get this error:

File "/Users/covino/miniconda3/lib/python3.6/site-packages/photutils-0.3.2-py3.6-macosx-10.7-x86_64.egg/photutils/centroids/core.py", line 101, in centroid_com
    from skimage.measure import moments
ModuleNotFoundError: No module named 'skimage'

Thanks a lot,
   Stefano

**Comment by larrybradley** [comment]
The `scikit-image` (aka `skimage`) package is required to run the `centroid_com` function.  You can install it with conda:  `conda install scikit-image`.

**Comment by stefanocovino** [comment]
> 
> The scikit-image (aka skimage) package is required to run the centroid_com function. You can install it with conda: conda install scikit-image.
> 
> 

Yes, I discovered it just after having written. I was surprised that after the installation there was no mention of missing packets.

Thanks anyway,

	Stefano
