### ISSUE TITLE
Is there a class or a function to build PSF model from the stars in an image?

### ISSUE THREAD

**Issue by iskren-y-g** [astropy/photutils#581]
Hi,

I am heavily using the IRAF's psf task in the daophot package to build a PSF model from the stars in an image. This gives the power to create a spatially variable PSF model that I can use with allstar. Is there a way to do the exact same thing within photutils? I understand that prepare_psf_model can be used to create the model, but as far as I understand you don't use stars to fit moffat or gauss functions, like in the IRAF's psf task. It's just not clear to me how can one do this. Is there are tutorial or example that I'm missing to find?

Thanks!
Iskren

**Comment by mirca** [comment]
Hi @iskreng,

We don't have this exact feature implemented yet. But you can definitely fit analytical models to stars:

> - https://photutils.readthedocs.io/en/stable/photutils/psf.html
> - https://github.com/astropy/photutils-datasets/blob/master/notebooks/ArtificialCrowdedFieldPSFPhotometry.ipynb

Please, let us know whether or not that helps!

**Comment by iskreng** [comment]
Thanks @mirca for the ipynb link. That will be useful. It will be great if in the future one could have the possibility to create/use spatially variable PSF. Looking forward to that.

Cheers,
Iskren

**Comment by Gabriel-p** [comment]
If I understand correctly, the `create_from_image` method from the [DiscretePRF](http://photutils.readthedocs.io/en/stable/api/photutils.psf.sandbox.DiscretePRF.html) class should allow you to generate a PRF model from observed sources to use as a PSF model, as described here https://github.com/astropy/photutils-datasets/blob/master/notebooks/PSFPhotometrySpitzer.ipynb

Note that the above notebook is outdated, and

    from photutils.psf import create_prf
    prf_discrete = create_prf()

is not longer valid. Instead you should use

    from photutils.psf.sandbox import DiscretePRF
    prf_discrete = DiscretePRF.create_from_image()

Not sure if this can be extended to a *variable* PSF though.

**Comment by larrybradley** [comment]
This can be done with the `EPSFBuilder`:  https://photutils.readthedocs.io/en/latest/epsf.html
