### ISSUE TITLE
Suggestion on the improvements on centroiding functions

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#593]
Currently, the centroiding functions, which are designed to find the centroid of a single source image, calculates the centroid by using input ``data`` and ``mask``. 
It does suffice all the needs, but it is possible to improve it slightly and gain much convenience. **In short, I think it will be helpful if we put some "semi-automatic" masking functionality into the centroiding functions.**

This contains motivation, simple solution, demonstrations (of how the "solution" works), discussion, and conclusion. I want to ask if this makes sense, and if so, I want to start implement this functionality and make a pull request.

# Motivation
In the image below, there are pixels even below 0, so it is desirable to mask such pixels properly. But even if we mask all those pixels (to value 0), there are some noisy pixels which have positive value, and thus the centroid will be slightly shifted towards bottom left direction. Therefore, we need certain threshold to mask "background" or "noisy" pixels, so that we are taking only "source-dominated" pixels when calculating the centroid. 

![figure_1-1](https://user-images.githubusercontent.com/17214293/31317533-8d639d7c-ac7d-11e7-8551-4fce235fa19b.png)

Currently, it must be done by the user and put it as the ``mask``. But many users may forget to take care of ``mask`` or how to choose proper threshold for ``mask``.

# Simple Solution
Reference [1] has shown that the best way to find the centroid is to set the threshold as ``noise_mean + 3 * noise_std``. **Thus, I propose centroiding functions to have an option to take this semi-automatic masking functionality.**

For test, I used only ``centroid_com``. I put three new parameters to it, namely, ``noise_mean``, ``noise_std``, and ``thresh_sigma``, and named this test function as ``centroid_com2`` for this moment:
```python
def centroid_com2(data, mask=None, noise_mean=0., noise_std=0, 
                 thresh_sigma=3.):
    """
    Calculate the centroid of a 2D array as its "center of mass"
    determined from image moments.

    Invalid values (e.g. NaNs or infs) in the ``data`` array are
    automatically masked.

    Parameters
    ----------
    data : array_like
        The 2D array of the image.

    mask : array_like (bool), optional
        A boolean mask, with the same shape as ``data``, where a `True`
        value indicates the corresponding element of ``data`` is masked.

    noise_mean : float, optional
        The averaged noise level. The simplest way to calculate it is to take
        the median or mean of the ``data`` after 3-sigma clipping with few 
        iterations. This, however, may overestimate the noise level (since the
        nearby pixels are brightened by the light source), so it is best to use
        the pixels well outside the source to estimate background level. 
        Defaults to 0.
    
    noise_std : float, optional
        The fluctuation (standard deviation) of noise (error source). It can
        also be calculated as ``noise_mean`` by using sigma clipping, but it
        is better to use pixels well apart from the source. Defaults to 0.
    
    thresh_sigma : float, optional
        The threshold above the ``noise`` to mask pixels for centroiding. Only 
        the pixels having value above ``noise_mean + thresh_sigma * noise_std`` 
        will be used for the centroiding. It is known that the 3-sigma
        criterion, i.e., ``noise + 3 * noise_sigma``, is a good threshold 
        (Ma et al. 2009, Optics Express, 17, 8525), so the recommended value is 
        ``thresh_sigma=3``. Defaults to 3.

    Returns
    -------
    centroid : `~numpy.ndarray`
        The ``x, y`` coordinates of the centroid.
    """

    from skimage.measure import moments
    
    data = np.ma.asanyarray(data)

    if mask is not None and mask is not np.ma.nomask:
        mask = np.asanyarray(mask)
        if data.shape != mask.shape:
            raise ValueError('data and mask must have the same shape.')
        data.mask |= mask
    
    mask_noise = data < (noise_mean + thresh_sigma * noise_std)
    data.mask |= mask_noise
    print('threshold =', noise_mean + thresh_sigma * noise_std)
    print('N_masked =', np.count_nonzero(data.mask))
    
    if np.any(~np.isfinite(data)):
        data = np.ma.masked_invalid(data)
        warnings.warn('Input data contains input values (e.g. NaNs or infs), '
                      'which were automatically masked.', AstropyUserWarning)

    # Convert the data to a float64 (double) `numpy.ndarray`,
    # which is required for input to `skimage.measure.moments`.
    # Masked values are set to zero.
    data = data.astype(np.float)
    data.fill_value = 0.
    data = data.filled()

    m = moments(data, 1)
    xcen = m[1, 0] / m[0, 0]
    ycen = m[0, 1] / m[0, 0]
    
    return np.array([xcen, ycen])
```
I intentionally put some print functions for test. The only differences from the original version are the docstring and the four lines containing ``mask_noise`` and print functions.

# Demonstration
I want to show some examples to convince the importance of masking. 

## Demo 1
For the first demonstration, I want to use the data used by the [documentation](https://photutils.readthedocs.io/en/stable/photutils/centroids.html).

In the following, ``x1, y1``, ``x2, y2``, and ``x3, y3`` are the same as the documentation (centroid com, 1dg, and 2dg). 
``x4, y4`` is the position of centroid when the pixel mask is done for ``value < 0``. 
``x5, y5`` is when the pixels are masked based on the Reference's criterion with true noise mean and std (5, 5, respectively; see [here](https://photutils.readthedocs.io/en/stable/api/photutils.datasets.make_4gaussians_image.html#photutils.datasets.make_4gaussians_image)), so this can be regarded as the true centroid measured by com. 
Finally, ``x6, y6`` is when the masking is based on inference on noise mean and std (3-sigma clipping using ``astropy.stats.sigma_clipped_stats``).

The locations from ``centroid_com2`` are shown by ``x`` marker.

```python
from photutils.datasets import make_4gaussians_image
from photutils import centroid_com, centroid_1dg, centroid_2dg
import matplotlib.pyplot as plt
from astropy.stats import sigma_clipped_stats

data = make_4gaussians_image()[43:79, 76:104]    # extract single object
xy_str = '{:s}: ({:.5f}, {:.5f})'
x1, y1 = centroid_com(data)
print(xy_str.format('centroid_com', x1, y1))
x2, y2 = centroid_1dg(data)
print(xy_str.format('centroid_1dg', x2, y2))
x3, y3 = centroid_2dg(data)
print(xy_str.format('centroid_2dg', x3, y3))
print('-'*80)
# default values:
x4, y4 = centroid_com2(data, noise_mean=0, noise_std=0) 
print(xy_str.format('centroid_com2', x4, y4))
print('-'*80)
# if we know the true values:
print('True noise (mean, med, std) = 5.0, 5.0, 5.0')
x5, y5 = centroid_com2(data, noise_mean=5, noise_std=5, thresh_sigma=3) 
print(xy_str.format('centroid_com2', x5, y5))
print('-'*80)
# if we do not know the true values:
noise_mean, noise_med, noise_std = sigma_clipped_stats(make_4gaussians_image(), 
                                                       sigma=3, iters=50)
print('Estimated noise (mean, med, std) =', 
      noise_mean, noise_med, noise_std)
x6, y6 = centroid_com2(data, noise_mean=noise_mean, noise_std=noise_std, 
                       thresh_sigma=3) 
print(xy_str.format('centroid_com2', x6, y6))

fig, ax = plt.subplots(1, 1)
ax.imshow(data, origin='lower', interpolation='nearest', cmap='viridis')
marker = '+'
ms, mew = 30, 2.
plt.plot(x1, y1, color='#1f77b4', marker=marker, ms=ms, mew=mew)
plt.plot(x2, y2, color='#17becf', marker=marker, ms=ms, mew=mew)
plt.plot(x3, y3, color='#d62728', marker=marker, ms=ms, mew=mew)
plt.plot(x4, y4, color='r', marker='x', ms=20, mew=mew)
plt.plot(x5, y5, color='k', marker='x', ms=20, mew=mew)
plt.plot(x6, y6, color='b', marker='x', ms=20, mew=mew)
```
I skipped the zoomed-in image part. The result is as follows:
```
centroid_com: (13.93158, 17.05123)
centroid_1dg: (14.04035, 16.96231)
centroid_2dg: (14.00221, 16.99613)
--------------------------------------------------------------------------------
threshold = 0.0
N_masked = 19
centroid_com2: (13.93009, 17.05271)
--------------------------------------------------------------------------------
True noise (mean, med, std) = 5.0, 5.0, 5.0
threshold = 20
N_masked = 366
centroid_com2: (13.99611, 17.00239)
--------------------------------------------------------------------------------
Estimated noise (mean, med, std) = 5.49662890322 5.40802826546 5.2490393209
threshold = 21.2437468659
N_masked = 392
centroid_com2: (13.99089, 16.98284)
```
![figure_1-2](https://user-images.githubusercontent.com/17214293/31317684-5f8b438e-ac80-11e7-988c-06a68cdc707a.png)

As can be seen, all are consistent with each other. (confirmed ``centroid_com2`` works well)

* accepted: all

## Demo 2
For the second demonstration, I used the first image (source at the corner of the data rather than center), i.e., ``data = make_4gaussians_image()[10:30, 130:160]`` (all other code lines identical). Then
```
centroid_com: (18.49531, 13.30201)
centroid_1dg: (19.99518, 15.00513)
centroid_2dg: (20.01413, 15.00670)
--------------------------------------------------------------------------------
threshold = 0.0
N_masked = 75
centroid_com2: (18.42292, 13.19838)
--------------------------------------------------------------------------------
True noise (mean, med, std) = 5.0, 5.0, 5.0
threshold = 20
N_masked = 481
centroid_com2: (20.02485, 14.74312)
--------------------------------------------------------------------------------
Estimated noise (mean, med, std) = 5.49662890322 5.40802826546 5.2490393209
threshold = 21.2437468659
N_masked = 488
centroid_com2: (19.99919, 14.80074)
```
![figure_1-3](https://user-images.githubusercontent.com/17214293/31317729-1f73cc3e-ac81-11e7-8c6e-7e273ecec031.png)

Now it is visible that the original ``centroid_com`` (skyblue plus) and the default ``centroid_com2``(red cross) are not satisfactory. All other (including original 1dg, 2dg) coincide with each other.

* accepted: 1dg, 2dg, and ``centroid_com2`` with proper input

## Demo 3
Now I use the star image:
```
from photutils.datasets import load_star_image
data = load_star_image()[520:540, 385:400]
```
and all other code lines identical, but I erased ``x5, y5`` since we don't have true noise value. Then 
```
centroid_com: (7.38774, 10.35603)
centroid_1dg: (-11.42871, 15.42895)
centroid_2dg: (8.39294, 15.40005)
--------------------------------------------------------------------------------
threshold = 0.0
N_masked = 0
centroid_com2: (7.38774, 10.35603)
--------------------------------------------------------------------------------
Estimated noise (mean, med, std) = 3768.70797549 3744.0 234.867366443
threshold = 4473.31007482
N_masked = 185
centroid_com2: (9.12297, 13.18774)
```
![figure_1-5](https://user-images.githubusercontent.com/17214293/31318340-90e4044c-ac8b-11e7-811e-c881427562b1.png)

The ``centroid_2dg`` seems to be fallen into a strange local minimum, which is unexpected. 
The ``centroid_1dg`` gives the most reliable value, while ``centroid_com2`` with proper input (blue cross) is also marginally acceptable.

* accepted: 1dg
* ``centroid_com2`` with proper intput can marginally be accepted.

## Demo 4
I now want to use an observed data of a galaxy UGC 1324 (observed by KMTNet/CTIO, observed on UT 2015-12-21). The result is
```
centroid_com: (149.05460, 101.70518)
centroid_1dg: (79.61474, 115.93930)
centroid_2dg: (144.21234, 116.90994)
--------------------------------------------------------------------------------
threshold = 0.0
N_masked = 0
centroid_com2: (149.05460, 101.70518)
--------------------------------------------------------------------------------
Estimated noise (mean, med, std) = 429.618985696 428.903198242 17.935913277
threshold = 483.426725527
N_masked = 39002
centroid_com2: (147.93215, 113.94106)
```
![figure_1-6](https://user-images.githubusercontent.com/17214293/31318603-fb34b270-ac8f-11e7-918d-661457ca0bcb.png)
``centroid_1dg`` now gave the worst result (the left cyan plus marker). Maybe because of a strange local minimum.
Now ``centroid_2dg`` gives the best result: the center of bulge.
``centroid_com`` is at the edge of bulge, which is not good. Same goes true for the ``centroid_com2`` with default parameters.
``centroid_com2`` with proper input also gave reasonable result. 

* accepted: ``centroid_2dg``, ``centroid_com2`` with proper input.

# Discussion
From the demonstrations (and I tried hundreds of different cases by myself) the ``centroid_1dg`` seems the best centroid-finding function, and the only exception was the last demonstration. Unfortunately, Gaussian fits always have possibility of getting stuck in unexpected local minima, so we need care. 

The ``centroid_com2``, which uses automatic masking by threshold given by the Ref[1], is very reliable since there is no possibility for it to fall into a local minimum. It usually gives good guess on centroids for all possible cases, unless strong secondary source is in the data. 

Possible way to get around the local minima issue of Gaussian fit is to accept centroid results only when it's in the image, and make the data size to be very small. This is what many astronomers do for non-extended sources, such as [IRAF](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?centerpars):
> cbox = 5.(scale units)
>   The width of the subraster used for object centering in units of the DATAPARS scale parameter. Cbox must be big enough to include a reasonable number of pixels for center determination but not so large so as to include a lot of noise. Recommended initial values are 2.5-4.0 * the FWHM of the PSF value. 
This ``cbox`` is related to the size of the input ``data`` for photutils' centroiding functions. 

# Conclusion
The importance of masking is clear from the demonstrations (by seeing how the ``centroid_com`` results improved when updated to ``centroid_com2``). 
Thus it will be helpful if making ``mask`` becomes easier. I thus suggest to put some functionality to centroiding functions.

Any opinions are welcomed :)

[1] Ma et al. 2009, "Error analysis of CCD-based point source centroid computation under the background light", Optics Express, 17, 8525

**Comment by larrybradley** [comment]
@ysBach Many thanks for your detailed report!  I really appreciate the time you've taken to evaluate the centroiding functions!

My first impression is that adding three new keywords to all new and current centroiding functions to effectively add one line of code to modify the mask (i.e. `mask |= data < (noise_mean + thresh_sigma * noise_std)`) isn't the best approach from a developer or a user perspective.  I think a much better approach is to add to the centroiding narrative *documentation* (e.g. with your examples and images) explaining to the users why this type of additional masking can be beneficial to centroiding and how it can be easily added with a simple one-line modification of the `mask`.

**Comment by ysBach** [comment]
@larrybradley Thanks for the reply and the suggestion!
Now that I hear it, I also think it's better to make an enhanced document to show the importance of the ``mask``, rather than put some additional lines to the original code. 
Do you think it is better to add to the contents to the official documents or add a link to, e.g., a notebook? (I will make a separate notebook then).

**Comment by larrybradley** [comment]
@ysBach If you are going to show several examples, then it is probably better to put in a notebook. 
 If you do a notebook, please submit it to the `photutils-datasets` github repo and then another PR here updating the docs with the link (after the notebook is merged).  Thanks.
