### ISSUE TITLE
Add default values for RectangularAperture?

### ISSUE THREAD

**Issue by mirca** [astropy/photutils#594]
I think it would make sense to give some sane default values for the attributes of some aperture classes. For instance, I think it's often the case where ``theta=0`` for ``RectangularAperture``.

What y'all think? @larrybradley @bsipocz  @eteq :)

**Comment by larrybradley** [comment]
I think it's fine to set the default `theta=0` for both rectangular and elliptical apertures.  I'm inclined not to set defaults for other parameters (e.g. radius, etc.), but I'll let others weigh in.

**Comment by mirca** [comment]
@larrybradley I was mostly thinking about ``theta=0`` as well
