### ISSUE TITLE
Convert the photutils.psf photometry tools to a more flexible version

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#596]
This issue is prompted by discussion at workshop held at STScI Oct 3/4.  We settled on some modifications to the PSF photometry machinery that we think end up covering most, if not all, of the PSF photometry use cases considered by the participants at this workshop (including crowded-field HST imaging, AO, LSST/survey image deblending, galaxy model-fitting photometry, and probably some other cases I forgot...)

The basic idea is to add a few more pieces to the "toolbox" of PSF photometry steps.  These can all fit into the `IterativelySubtractedPSFPhotometry` class, but .  A diagram of these elements is here: https://stsci.box.com/s/ju63yvhirs2pr7ov79rmlov43rrv0fvw - it might not be obvious what some of these are, but the plan is to get a draft implementation from some of the folks at the workshop and then that can be reviewed more thoroughly.

And at the workshop, @mirca tentatively volunteered to try to implement this, so I'm assigning it to him.

**Comment by mirca** [comment]
Awesome, Erik!

**Comment by larrybradley** [comment]
The 2017 PSF photometry plan is archived on the `photutils` wiki page.
