### ISSUE TITLE
PSF: stars outside the image

### ISSUE THREAD

**Issue by HBarker13** [astropy/photutils#606]
Hi,

I'm trying to construct a psf to make a star subtracted image. Daofind and pstselect are working fine, but when I run psf, there's an error flagged for every star saying its outside the image. Below is a snippet. I'm definitely giving psf the same filepath as the other tasks, and I've plotted the coordinates of the stars in the pstselect output list to check they are in my (4100, 2048) size image.

```
Star 26219 has been added to the PSF star list
	X:  907.67 Y: 3062.77  Mag:  17.661  Dmin: 145.  Dmax: 12797.
Star 391 has been added to the PSF star list
	X: 1439.28 Y:   49.57  Mag:  17.665  Dmin: 110.  Dmax: 11630.
Star 777 has been added to the PSF star list
	X: 1693.95 Y:  101.16  Mag:  17.667  Dmin: 146.  Dmax: 13422.

100 PSF stars read from /star_subtraction/ccd1_pstselect-out.pst

Star 26219 is outside the image
Star 391 is outside the image
Star 777 is outside the image

Fitting function gauss    norm scatter: 9.999

Analytic PSF fit 
    Function: gauss  X: 1023.5  Y: 2049.5  Height: 0.  Psfmag: 16.453
    Par1: 0.  Par2: 0.
Too few stars to compute PSF lookup tables
```

Do you have any idea why psf would throw this error when the other tasks don't? Is there any way for me to override this error?

Thanks

**Comment by mirca** [comment]
Hi @HBarker13,

Sorry, but, can you remind me (with a piece of python code, for example) where this output come from? I don't recognize any photutils tool with this output. 

Thanks!

**Comment by HBarker13** [comment]
Sorry!!! I had multiple tabs open when looking for a solution to this and posted in the wrong one. Please ignore this post - sorry again for bothering you.
