### ISSUE TITLE
Accessing photometric uncertainties

### ISSUE THREAD

**Issue by rachel3834** [astropy/photutils#607]
I'm developing a function to perform photometry on my imaging data, along the lines of the [CrowdedFieldPSFPhotometry python notebook.](http://photutils.readthedocs.io/en/stable/photutils/psf.html)  It worked smoothly, but in examining the tabular photometry output, I was not sure how to access or compute the photometric uncertainties on the flux_fit measurements, using the objects from your package.  

@larrybradley kindly composed a notebook demonstrating how to access the flux uncertainties, [here](https://gist.github.com/larrybradley/e23d905cd69ca44d032541f69c2b5433#file-psf_uncertainties-ipynb) and [plans](https://github.com/astropy/photutils/issues/605) to update the documentation as well.  

When I try the code from this example notebook line-by-line however, I get the following output:

`fitter = LevMarLSQFitter()
basic_psf = BasicPSFPhotometry(finder=daofind,
   ...:                                group_maker=daogroup,
   ...:                                bkg_estimator=mode_bkg,
   ...:                                psf_model=psf_model,
   ...:                                fitter=fitter,
   ...:                                fitshape=(11, 11))

tbl = basic_psf(data)
tbl
`
Out[11]: 
<Table length=1>
     x_0           y_0          flux_0      id  group_id    x_fit         y_fit        flux_fit  
   float64       float64       float64    int32  int32     float64       float64       float64   
------------- ------------- ------------- ----- -------- ------------ ------------- -------------
25.1459755734 25.0192852629 14820.9881508     1        1 25.137338515 24.9983032084 15926.8427138

No flux_unc column is included in the table produced, and tbl['flux_unc'] produces  a KeyError.  

The same happens when I use IterativelySubtractedPSFPhotometry as well.  

For the record, I'm using:
photutils.version '0.3.2'
astropy.version '2.0'

**Comment by larrybradley** [comment]
@rachel3834 Ah!  The PSF-fitting uncertainties were added after the `0.3.2` release (https://github.com/astropy/photutils/pull/516; I should have asked you that before!).  This feature will appear in the next release, `0.4`, which will be very soon (by Oct 31).  If you don't want to wait, you could try out the photutils `dev` version (see http://photutils.readthedocs.io/en/latest/photutils/install.html#installing-the-latest-development-version).  Thanks again!
