### ISSUE TITLE
Reasonable box_size for Background2D?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#613]
The [2D Background and Noise Estimation](https://photutils.readthedocs.io/en/stable/background.html#d-background-and-noise-estimation) states that:

>  Background2D requires the size of the box (`box_size`) in which to estimate the background. Selecting the box size requires some care by the user. The box size should generally be larger than the typical size of sources in the image, but small enough to encapsulate any background variations.

All other parameters have some reasonable default values that can be used, but not `box_size`.

Is there a reasonable rule of thumb for selecting this value? I've found that (for some frames I'm processing) a value of ~7xFWHM produces reasonably cleaned images. Smaller values produce a noisy cleaned image (`data - bckg`) and larger values show no improvements.

Is this a reasonable rule or it's this the case for my images only? Can a reasonable general rule even be stated? If so, could it be added to the docs.

**Comment by larrybradley** [comment]
@Gabriel-p  I don't think this can be generalized into a universal recommendation (other than the one about source size).  The problem is that the distribution of object sizes can vary greatly between various images.  7xFWHM may work for your scene, but may not work, for example, on a galaxy cluster image with many large cluster galaxies.  If the `box_size` is less than a typical source size, then many boxes will be filled primarily by sources only (no background) and thus the background estimation will be poor.  On the other hand, you could probably use a smaller `box_size` for a stellar field.

**Comment by Gabriel-p** [comment]
Thanks for the answer @larrybradley. Would you say that a "general box size" is possible if we limit the cases to non-crowded frames containing only stars with reasonably similar FWHM's (for example, a standard field used for calibration)?

**Comment by larrybradley** [comment]
Yes, for that particular case one could probably define a reasonable box size.  Without doing a lot of tests, I'm not sure what that size is though.  Is that your case where `7 * FWHM` gave good results?  If there is a good box size recommendation for that particular case, I'd be happy to include it in the docs.

**Comment by Gabriel-p** [comment]
What I found is that for a box size < `~6*FWHM` (not 7, the FWHM is ~4.8 in the image) there are some artifacts left in the background subtracted image, and that for sizes larger than that there were no apparent changes in the subtracted image.

You can see the results in these images: https://photos.app.goo.gl/PUIgfktKwsOgHzTV2

I'm not sure if this can be generalized to all similar (ie: non crowded, stellar only) frames.

**Comment by larrybradley** [comment]
Thanks, @Gabriel-p.  If you think there is some good recommendation that can be added to the docs for the `box_size` of non-crowded stellar-only fields, then feel free to submit a PR.

**Comment by Gabriel-p** [comment]
I honestly don't know. I was hoping the issue would be more clear-cut to resolve, but it clearly is not. Please feel free to close this issue and thank you very much for your comments.

**Comment by larrybradley** [comment]
Thanks, @Gabriel-p.  I tried to be descriptive as possible for recommended values, but I think this is one parameter that does require some trial and error on the part of the user for their particular scene.
