### ISSUE TITLE
Deblending error

### ISSUE THREAD

**Issue by saimn** [astropy/photutils#616]
Trying the detection & deblending code I have the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-11b338bc9d78> in <module>()
      1 from photutils import deblend_sources
      2 segm_deblend = deblend_sources(data, segm, npixels=5,
----> 3                                filter_kernel=kernel)

~/lib/photutils/photutils/segmentation/deblend.py in deblend_sources(data, segment_img, npixels, filter_kernel, labels, nlevels, contrast, mode, connectivity, relabel)
    135                              'in detect_sources and deblend_sources.  If '
    136                              'this issue persists, then please inform the '
--> 137                              'developers.'.format(label))
    138 
    139         if source_deblended.nlabels > 1:

ValueError: Deblending failed for source "83".  Please ensure you used the same pixel connectivity in detect_sources and deblend_sources.  If this issue persists, then please inform the developers.
```
I cannot share the image but will try to make a reproductible example or identify the issue. A first hint with the `source_deblended.data` and `source_segm.data` arrays below, it seems that the source in the bottom left corner appeared while deblending the big blob:
 
![image](https://user-images.githubusercontent.com/311639/32656339-b7f51b76-c611-11e7-9fd1-87776356f6cc.png) 
![image](https://user-images.githubusercontent.com/311639/32656344-bb5b4d4e-c611-11e7-83da-a32a4d5da60b.png) ![image](https://user-images.githubusercontent.com/311639/32656348-be8b6dfa-c611-11e7-96e1-794b0b02539a.png)

```
ipdb>  np.where(source_deblended.data.astype(bool) != source_segm.data.astype(bool))
(array([3, 4, 4, 4, 5, 5, 5, 6]), array([2, 1, 2, 3, 1, 2, 3, 2]))
```

**Comment by saimn** [comment]
I update the images to show the input image, and use the correct orientation, so the extra source is now on the bottom left ;)

Otherwise it seems to do a good job!

**Comment by NiallMac** [comment]
Hi guys, I'm seeing this error and I'm guessing it's because I installed using conda install (from the astropy channel), and this fix hasn't made it into the release version yet? If this is the case, do you have an idea of when this will make it into the conda version? Thanks!

**Comment by bsipocz** [comment]
@NiallMac - Indeed, the fix is in the development version, but not yet released.

The initial plan for the 0.5 release was a little bit after astropy 3.0 is out (it's not yet released), so I would guess it will be out in at least a few more weeks, 1-2 month time.

**Comment by bsipocz** [comment]
In the meantime you can install the development version following the docs here: https://photutils.readthedocs.io/en/stable/install.html#installing-the-latest-development-version
