### ISSUE TITLE
issue with aperture photometry on faint sources - missing flux?

### ISSUE THREAD

**Issue by panossk** [astropy/photutils#618]
Hi, 
I'm doing some simple measurements on faint sources in HST data, using CircularAperture().
When I compare my photometry to a reference catalog I have, I notice that in the wavelengths where my sources are pretty faint, I end up missing up to 0.5 mag of flux, whereas in the longer wavelengths where my sources are bright, I find the expected values.  
Being that I'm no expert in measuring photometry, is there something basic I'm missing here? 
I only could notice that some pixels in the sky background can have negative values (a result of the 
reduction I suppose), is this something that is properly taken into account in CircularAperture()?

**Comment by larrybradley** [comment]
The `aperture_photometry` function assumes that the input `data` is properly background subtracted.  It doesn't alter the `data` in any way, but simply measures the sum of the data within the given aperture.

**Comment by panossk** [comment]
thanks larry, for this information. I will have to make more tests I guess, to see if I can pinpoint the problem better, and will come back. 
As far as I was told, my data are supposed to be ready for use.
