### ISSUE TITLE
Add datamin & datamax values to StarFinders

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#620]
IRAF's [starfind](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?starfind) algorithm allows to set `datamin` and `datamax` values to filter out detections.

Would be a nice (and relatively simple?) addition for both star finders.

**Comment by larrybradley** [comment]
The star finders have `peakmax` and `brightest` keywords that can do that.
