### ISSUE TITLE
Why is finder=None not accepted in IterativelySubtractedPSFPhotometry?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#623]
The `BasicPSFPhotometry` class accepts `finder=None`, but `IterativelySubtractedPSFPhotometry` [does not](https://photutils.readthedocs.io/en/stable/_modules/photutils/psf/photometry.html#IterativelySubtractedPSFPhotometry):

> "finder cannot be None for IterativelySubtractedPSFPhotometry - you may want to use BasicPSFPhotometry. Please see the Detection section on photutils documentation."

Why is this? I could not find an explanation anywhere in the docs.

**Comment by mirca** [comment]
The concept behind ``IterativelySubtractedPSFPhotometry`` is that it would iterate over the residual image (i.e., the image generated by subtracting the PSFs estimated in the first iteration) in a attempt to find previously undetected sources.

**Comment by Gabriel-p** [comment]
I understand, but what about the first iteration? Why couldn't it make use of already detected sources?

**Comment by mirca** [comment]
Sorry, what exactly do you mean by ``already detected sources``?

In the first iteration you can provide initial guesses in case you already know a rough estimate of the positions of the sources of interest.

For the next iterations though, a finder is needed.

If it's the case that you don't want to perform further iterations, then you might want to check out [BasicPSFPhotometry](https://photutils.readthedocs.io/en/stable/api/photutils.psf.BasicPSFPhotometry.html#photutils.psf.BasicPSFPhotometry).

**Comment by Gabriel-p** [comment]
I'm sorry, I misunderstood the idea behind `finder=None` not being accepted. I thought (don't know why) that meant *initial guesses* were also not accepted for this class. I see now what you mean so I'm closing this issue. Thank you!
