### ISSUE TITLE
Add 'verbose' mode to PSFPhotometry  classes

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#626]
I'm doing PSF photometry on some crowded frames and I've been staring at a screen that shows no changes for well over 10 min now.

Could a `verbose` mode be added to these classes that would print some relevant information regarding the process as it moves forward?

**Comment by mirca** [comment]
I like that idea! What you all think @eteq @bsipocz @hamogu?

**Comment by bsipocz** [comment]
Yes, this sounds sensible to me, like the rolling beachball for the terminal ;) 
Can we maybe use the astropy progress bar for this?

**Comment by Gabriel-p** [comment]
I was actually thinking of printing relevant information about the state of the process, rather than a progressbar. Of course, this is more complicated since those messages need to be written first.

In any case, anything beats staring at a blank screen for an hour.

**Comment by larrybradley** [comment]
If this gets implemented, please use the astropy logger (i.e. `log.info()`) and not `print()` calls.
