### ISSUE TITLE
The source coordinates do not sample all sub-pixel positions. Reduce the value of the subsampling parameter

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#630]
I'm trying to generate a model PRF from some ~30 sources using the [DiscretePRF](http://photutils.readthedocs.io/en/stable/api/photutils.psf.sandbox.DiscretePRF.html) class, given an observed frame (`hdu_data`) and source coords (`coords`):

    prf_discrete = DiscretePRF.create_from_image(hdu_data, coords, size=15, subsampling=5)

I get:

    ValueError: The source coordinates do not sample all sub-pixel positions. Reduce the value of the subsampling parameter.

I can get rid of this error by (obviously) reducing the `sumsampling` to 2, but I want to understand why this error occurs. Is it because the number of sources is too small? Is it related to the `size` parameter? Is it both? Where can I learn more about the underlying process that is responsible for this?

**Comment by eteq** [comment]
`DiscretePRF` is in the sandbox because it pre-dates the most recent set of updates to `photutils.psf`.  So I'm not really sure much about the implementation details, and it's not clear when that's going to get the TLC needed to bring it out of the "sandbox".  Have you tried `FittableImageModel` though, @Gabriel-p ?  Does it not fit your needs?

**Comment by Gabriel-p** [comment]
I started using `DiscretePRF` because it seemed like the natural replacement of the old `create_prf` class used in the [PSF/PRF Photometry on Spitzer Data](https://github.com/astropy/photutils-datasets/blob/master/notebooks/PSFPhotometrySpitzer.ipynb) notebook.

I have not tried `FittableImageModel`, is there an example of its use anywhere?

**Comment by larrybradley** [comment]
The `DiscretePSF` class no longer exists.
