### ISSUE TITLE
Unexpected behavior in aperture_photometry

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/photutils#637]
I need to process a list of sources with `aperture_photometry`. To maintain the order of the elements (used by my code somewhere else), some of these sources have `(-999.9, -999.9)` center coordinates. This value positions these sources way outside the data frame, which has minimum values of `(0, 0)`.

When I run `aperture_photometry` for my list of sources (using some fixed aperture value), I would expect the flux (`aperture_sum` column) for these sources to be zero. Instead I get the same value for all: `190537.529674`.

Is this intended?

**Comment by larrybradley** [comment]
@Gabriel-p  If there is no intersection of the aperture with the data, then the `aperture_sum` should return `nan`.  I checked this for all of the apertures and all of the `method` options and I couldn't reproduce your issue.  Can you provide example code where this fails?

**Comment by Gabriel-p** [comment]
I tried reproducing this with some artificial data:

```
from astropy.io import fits
from photutils import CircularAperture
from photutils import aperture_photometry
import numpy as np

n = np.random.uniform(0., 100.0, (100, 100))
hdu = fits.PrimaryHDU(n)
hdul = fits.HDUList([hdu])
hdul.writeto('test2.fits')

hdulist = fits.open('test2.fits')
data = hdulist[0].data

positions = [(-999.9, -999.9)]
aper = CircularAperture(positions, r=10.)
phot_table = aperture_photometry(data, aper)

print(phot_table)
```

but I could not:

```
 id xcenter ycenter aperture_sum
      pix     pix               
--- ------- ------- ------------
  1  -999.9  -999.9          nan
```

So I used one of my own [files](https://drive.google.com/file/d/1mx4HuRWKgF45kHcn5fFmPZe-UIcGsvxp/view?usp=sharing) (~64Mb, other than erasing the header I did not modify it):

```
from astropy.io import fits
from photutils import CircularAperture
from photutils import aperture_photometry

hdulist = fits.open('test.fits')
data = hdulist[0].data

positions = [(-999.9, -999.9)]
aper = CircularAperture(positions, r=10.)
phot_table = aperture_photometry(data, aper)

print(phot_table)
```

and this is the result:

```
 id xcenter ycenter  aperture_sum
      pix     pix                
--- ------- ------- -------------
  1  -999.9  -999.9 169740.969906
```

Is there something happening with my .fits files or am I not understanding something?

**Comment by larrybradley** [comment]
Thanks.  I found the bug...fix coming.
