### ISSUE TITLE
Test failures due to numpy 1.14

### ISSUE THREAD

**Issue by bsipocz** [astropy/photutils#638]
There are a couple of test failure due to changes in numpy 1.14, see e.g. here:

https://travis-ci.org/astropy/photutils/jobs/333608051#L1552

**Comment by larrybradley** [comment]
Do you know how to fix the formatting issues in such a way that it will pass for all numpy versions?  I assume this was an output formatting change in `numpy 1.14`?

**Comment by bsipocz** [comment]
I can look into a fix around the weekend or next week.
