### ISSUE TITLE
Aperture photometry bug for subpixel mode on 32-bit

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#644]
Recent updates to the CircleCI config revealed an aperture photometry bug with `method='subpixel'` on 32-bit machines.  Example:

```python
>>> from photutils import aperture_photometry, CircularAperture
>>> data = np.ones((20, 20))
>>> apertures = CircularAperture((10, 10), r=3.)
>>> tbl = aperture_photometry(data, apertures, method='subpixel', subpixels=5)
```

On 64-bit, the aperture sum result is 27.96.  On 32-bit, the aperture sum is 28.12.  The difference is due a bug somewhere in the low-level geometry `Cython` functions.

The 64-bit aperture mask is:
```
array([[0.  , 0.  , 0.32, 0.44, 0.32, 0.  , 0.  ],
       [0.  , 0.68, 1.  , 1.  , 1.  , 0.68, 0.  ],
       [0.32, 1.  , 1.  , 1.  , 1.  , 1.  , 0.32],
       [0.44, 1.  , 1.  , 1.  , 1.  , 1.  , 0.4 ],
       [0.32, 1.  , 1.  , 1.  , 1.  , 1.  , 0.32],
       [0.  , 0.68, 1.  , 1.  , 1.  , 0.68, 0.  ],
       [0.  , 0.  , 0.32, 0.4 , 0.32, 0.  , 0.  ]])
```

The 32-bit aperture mask is:
```
array([[0.  , 0.  , 0.32, 0.4 , 0.32, 0.  , 0.  ],
       [0.  , 0.68, 1.  , 1.  , 1.  , 0.68, 0.  ],
       [0.32, 1.  , 1.  , 1.  , 1.  , 1.  , 0.32],
       [0.44, 1.  , 1.  , 1.  , 1.  , 1.  , 0.4 ],
       [0.32, 1.  , 1.  , 1.  , 1.  , 1.  , 0.32],
       [0.  , 0.76, 1.  , 1.  , 1.  , 0.76, 0.  ],
       [0.  , 0.  , 0.32, 0.44, 0.32, 0.  , 0.  ]])
```

The biggest differences are on the second-to-last row (0.68 vs 0.76).  Also note the differences in the center pixels along the edges (0.4 vs 0.44) -- although their sums are the same over those pixels.

I would have expected the mask to be symmetric (the aperture is centered on a pixel), which is not true even for the 64-bit case.  There may be a more general bug with the subpixels mode.

CC:  @astrofrog

**Comment by astrofrog** [comment]
Thanks for figuring this out! We should update the CircleCI config in the regions package too, and we really should switch over to using the Cython code from regions to avoid having to maintain two parallel sets of Cython code.

**Comment by larrybradley** [comment]
> Thanks for figuring this out! We should update the CircleCI config in the regions package too

Yes, I'll submit a PR to `regions`.

> really should switch over to using the Cython code from regions to avoid having to maintain two parallel sets of Cython code (that is, we can switch to using the Cython code in regions before we switch over to using the higher-level regions stuff)

Yes, I agree.  I was waiting for the geometry functions to make their way to astropy (i.e after `regions` went into `astropy`).  Using `regions` means yet another "optional-but-really-required" dependency for `photutils`.

**Comment by astrofrog** [comment]
@larrybradley - it might be a while before regions makes its way into astropy core, so I wouldn't wait on that. I think it's fine to have another dependency - most users won't notice with pip/conda.

**Comment by larrybradley** [comment]
Closing as @astrofrog reports this really isn't a bug (https://github.com/astropy/regions/pull/155#issuecomment-362566144).
