### ISSUE TITLE
Sources order in BasicPSFPhotometry

### ISSUE THREAD

**Issue by abeelen** [astropy/photutils#645]
When using `BasicPSFPhotometry` with Fixed Centroids the returned list of sources do not follow the same order as the input `init_guesses`, but rather the grouping order (thanks to the `hstack` at the end of the function), this could lead to confusion. 

I would suggest returning the results using the same order, or to place a clear warning in the documentation and/or docstring.

**Comment by larrybradley** [comment]
The new PSF photometry classes return sources in the same order as the initial guesses.  https://photutils.readthedocs.io/en/latest/psf.html
