### ISSUE TITLE
generating an average surface brightness profile?

### ISSUE THREAD

**Issue by moustakas** [astropy/photutils#647]
Forgive me if this information is readily available in the documentation, but I was encouraged by @larrybradley to post this as an issue.

I'd like to take the intensity profile from ellipse-fitting and turn it into a surface brightness profile, but I'm not finding the appropriate `area` measurement within which the mean intensity has been estimated.  I thought the [`sarea` or "sector area"](http://photutils.readthedocs.io/en/stable/api/photutils.isophote.IsophoteList.html#photutils.isophote.IsophoteList.sarea) attribute of the `IsophoteList` class might be what I need, but I don't think so.  

Moreover, the documentation states that `sarea` has units of pixels, which perhaps might be a bug.

Is there a measure of the area of the elliptical apertures as a function of semi-major axis which accounts for masked and partial pixels and, if not, are there any suggestions for how to derive this area profile using existing methods?  Thanks!

**Comment by larrybradley** [comment]
@ibusko Can you take a look at this?

**Comment by moustakas** [comment]
I think it would be generally useful for others to have an answer to this question. However, in the meantime I was able to deal with the problem by simply converting my input images to surface brightness *before* performing ellipse-fitting.  

@larrybradley feel free to close this issue.

**Comment by ibusko** [comment]
The mean intensity that is extracted by the 'ellipse' algorithm is already expressed as a per-unit-area quantity, in units of 'whatever per pixel'. To convert from the raw values extracted by the algorithm, to surface brightness values, all that needs to be accounted for is the conversion from pixel to whatever units you want your areas expressed in, such as arcsec-squared or similar. 

I believe this kind of conversion, being problem-dependent, is outside the scope of the package.

**Comment by larrybradley** [comment]
@moustakas I fixed the `sarea` unit in the documention (see #657).  Thanks!
