### ISSUE TITLE
How do you install V0.4 on Ubuntu for python3? 

### ISSUE THREAD

**Issue by rankinstudio** [astropy/photutils#649]
apt-get only installs 0.2

Thanks!

**Comment by larrybradley** [comment]
@olebole do you make the `apt-get` packages for affiliated packages?

**Comment by olebole** [comment]
Short answer: yes.
But it is a bit more complicated. What I currently do is to package the latest version of photutils for the next versions of Debian (and also implicitly Ubuntu). This version gets fixed when the distribution goes into a freeze (~1,5 months for Ubuntu, ~6 months for Debian). After that, the version that is directly in the distribution remains unchanged. Only bug fixes are possible then (no new versions).
To get a new version running on an older Debian/Ubuntu version, one needs to do a "backport", which may include a backport of dependent packages (f.e. when the new version of photcal requires a newer version of astropy). I don't have the manpower to do backporting myself (I do the packaging in my spare time).
So, if you see a need here, and if you want to help us, please volunteer to backport. I gladly offer any help to get it done. If nobody volunteers, I am afraid that you have to live with the version that was there when your Ubuntu distribution was released. My email is olebole@debian.org -- just contact me.

**Comment by bsipocz** [comment]
I naively ask, whether there is much benefit in doing the backports while users can easily do a `pip install photutils --user`?

**Comment by rankinstudio** [comment]
On Ubuntu 16.04 I was able to get it installed by using pip3.

**Comment by larrybradley** [comment]
Thanks, @olebole.  I don't see the need to backport here when `pip` can be used.

@rankinstudio Glad you got it installed.
