### ISSUE TITLE
scikit-image not specified in dependencies

### ISSUE THREAD

**Issue by jctello** [astropy/photutils#653]
I was just attempting this tutorial: http://photutils.readthedocs.io/en/stable/psf.html
And as a consequence the file  photutils/photutils/detection/findstars.py  tries to import skimage.morphology, that error disappears by installing scikit-image

I'm new here, but should this be specified in photutils or astropy's setup.py?

**Comment by larrybradley** [comment]
@jctello  Thanks for trying out the PSF tutorial.  `scikit-image` is an optional dependency of `photutils` (see http://photutils.readthedocs.io/en/stable/install.html).  We don't require installation of the optional dependencies to be able to `import photutils`, but they are needed for various functionality within `photutils` (as you've found).

`astropy` follows the same approach:  http://docs.astropy.org/en/stable/install.html

**Comment by jctello** [comment]
Thanks for the clarification. 

I imagine it could be out of form, but it could be useful to include an exception pointing out that skimage is part of scikit-image.

**Comment by larrybradley** [comment]
`skimage` **is**  the package name for `scikit-image`.  They are the same thing.
