### ISSUE TITLE
Performance issue with centroid

### ISSUE THREAD

**Issue by abeelen** [astropy/photutils#655]
I have been trying to use  `photutils.detection.find_peaks` function with the `subpixel=True` option and ran into a performance issue which prevent me to use it in a Monte Carlo simulation. I tracked this down to the `photutils.centroid.fit_2dgaussian` which use `astropy.modeling` to fit a custom 2d gaussian + constant model at each of the peaks.

Looking at `photutils.centroid.GaussianConst2D` class I wondered if this custom made compound was the culprit, so I ran a little benchmark to compare it to other definition of compound models and utilmately to `scipy.optimize.curve_fit`.  [Gist here](https://gist.github.com/abeelen/f3bf445cb0628dc4fe7a4fc3a89be28c) 

It turns out that for small data set, which `find_peaks` is doing, the overhead is huge :
* 13x compared to `curve_fit`,
* or even 3x compared to a simple  `astropy.modeling.custom_model` decorator

Things are worse when adding a little bit of noise.

I could work out a PR to write a proper model for `GaussianConst2D` but i would still be (much, 6x) slower than a simple curve_fit. What would be the best way to proceed here ?

**Comment by larrybradley** [comment]
@abeelen Thanks for reporting this issue.  Yes the compound model fit can be slow.   I submitted a PR (#656) to allow the `find_peaks` function to accept any centroiding function/callable, which will make it more flexible (i.e. you can pass your own fast centroid function).  One small change is that the fitted peak values are no longer returned, because the user-defined centroid function may simply be an empirical calculation and not a fitter.

**Comment by larrybradley** [comment]
I've merged #656.  You can use the development version to try it out prior to the next release.

The fastest method would be to use the `photutils.centroids.centroid_com` function as the input `centroid_func`.  It's ~100x faster than using `photutils.centroids.centroid_2dg` (essentially the same function used for `subpixel=True`).  If you actually need a fast fitting routine, you can now input a custom function to `centroid_func` (and you could also submit a PR to add it to `photutils.centroids` too).  I'm closing this now, but feel free to reopen if you are still having an issue.
