### ISSUE TITLE
detect_sources detects sources with npixel < npixels

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#661]
I was about to extract a large source with ``npixels > 500`` in a FITS file, but somehow ``detect_sources`` detected smaller objects (area smaller than ``npixels``).
I uploaded the test fits file [here](https://drive.google.com/open?id=1zjdbmo03KXC1A3uLQgQGv68NMZ89zU1D).
The code snippet:
```python
from photutils import detect_sources, source_properties
from astropy.nddata import CCDData
from astropy.stats import sigma_clipped_stats

ccd = CCDData.read('test.fits')
bkg = sigma_clipped_stats(ccd)[1] # median
segm = detect_sources(ccd.data, threshold=bkg, npixels=500, connectivity=8)
props = source_properties(ccd, segm, background=bkg).to_table()
print(props['area'])
# [2.3247e+04 1.0000e+00 1.4000e+01 1.0000e+00] pix2
```
As can be seen, the last three objects have 1, 14, and 1 pixels only, while I set ``npixels = 500``. 
Although I can reject them using, e.g., ``props['area'] > 500``, I guess they should not be returned from the beginning according to the [documentation](https://photutils.readthedocs.io/en/stable/api/photutils.segmentation.detect_sources.html#photutils.segmentation.detect_sources)..?

**Comment by larrybradley** [comment]
@ysBach Many thanks for reporting this bug.  I'm working on a fix.
