### ISSUE TITLE
find_peaks and wcs

### ISSUE THREAD

**Issue by abeelen** [astropy/photutils#667]
When `find_peaks` find no sources given a threshold, and one pass a `wcs` object, `pixel_to_skycoord` raise an `InconsistentAxisTypesError` as `x_peaks`, `y_peaks` are empy

```
import numpy as np
from astropy.wcs import WCS
from photutils import find_peaks

w = WCS()
w.wcs.ctype = ['RA---RAN', 'DEC--TAN']
find_peaks(np.random.normal(size=(10,10)), 1, wcs=w)
```

**Comment by larrybradley** [comment]
@abeelen Thanks for reporting this.  I'm working on a fix.
