### ISSUE TITLE
how to properly deal with the warning about SIP and WCS

### ISSUE THREAD

**Issue by panossk** [astropy/photutils#669]
Hi, 
I'm working on photometry extraction of HST data (drizzled), and I have this warning/info that is printed on screen each time WCS from astropy.wcs is called, as is mentioned on this page:
[Note about SIP and WCS](http://docs.astropy.org/en/stable/wcs/note_sip.html#)

I can't figure out if it does apply coefficients that mess up the coordinates or not. It doesn't appear to be the case at the level of what I can visually control (ie. my coordinates do seem to appear where they're meant to be when I plot the data).  

I did check that the CTYPE's in the header are of the form 'RA---TAN' and 'DEC--TAN', and do not contain the -SIP suffix.

My question is two-fold: 
- do I have to worry about this actually having a nefarious effect on the photometries I measure?
- how can I stop the message from appearing? (I'd like to keep the script's output as a log, and I'd rather not having this interrupting it each time WCS is called). 

In the link I attached above it seems to be explained, but without giving like a complete example or making all steps/how-to explicit. It proposes to remove the SIP coefficients from the header (but I don't find any in the header, are they called something else?) by calling 
`wcsobj.sip = None`
but I don't know how I must properly initiate this or what I must import, for it not to result in an error. 

What do you suggest I do? Can I maybe change something directly on the header, without causing other issues? 
Thanks!

**Comment by larrybradley** [comment]
@panossk This is an `astropy` issue with `WCS` objects, not a `photutils` issue.

You appear to have a FITS file with an inconsistent header where you have SIP coefficients, but the CTYPES do not have the -SIP suffix.  If you *want* to apply the SIP coefficients, simply update header CTYPES to include the -SIP suffix.  If you *don't want* to apply the SIP coefficients, then remove them from the header.  HST SIP coefficients are `A_*` and `B_*`.  You have to decide.

If you are really using a drizzled (rectified, undistorted) image, then you should *not* have SIP coefficients.  If SIP coefficients are present then they are *always* applied by astropy.wcs.  That means your WCS is wrong for a drizzled image.  If you are using the `Sky*`-based apertures, then your photometry will also be wrong.

**Comment by panossk** [comment]
oh, I'm so sorry for posting this at the wrong section, I didn't pay attention on this :/ 
thanks for your answer. 
Ok now I see them in the header. 
I will consult the responsible of the data on whether we must apply them or not. 
My apertures are defined on the pixel coordinates (having used wcs_world2pix before), 
does what you say apply to this too?

**Comment by larrybradley** [comment]
Note that `wcs_world2pix` applies only the core transformation (no distortions, including SIP).  I don't know if that is correct for your data.  If you need the SIP transforms, then your (sky) -> (x, y) transformation will be wrong.  In that case you need to use `all_world2pix` instead.

If your WCS header info is consistent, then `wcs_world2pix` and `all_world2pix` will give the same results for a drizzled (rectified, undistorted) image.





does *not* use any distortion information (including SIP).  I don't know if that is correct for your data or not.  `

**Comment by panossk** [comment]
Ok, thanks for that last precision, that will come up very handy actually, in terms of double-checking. 
The `all_world2pix` had skipped my mind, previously. 
Many thanks for your assistance :)

**Comment by panossk** [comment]
Ok, I hope I'm not spamming at this point, but in case it might be of use by future visitors, 
it turns out that the difference between using  `wcs_world2pix` and `all_world2pix` is strong enough that it's impossible to miss. 
So without making changes in the header, the former does the correct transformation as it does land on the target I'm interested in, whereas the other ends up in a significantly shifted position. 
But it's better that now I know what is actually going on with this.
