### ISSUE TITLE
shape of numpy ndarray

### ISSUE THREAD

**Issue by hujh08** [astropy/photutils#670]
It seems some treatments of ndarray's shape in isophote package are not right.
For example, in ellipse.py, line 183
```
            _x0 = image.shape[0] / 2
            _y0 = image.shape[1] / 2
```
which should be
```
            _x0 = image.shape[1] / 2
            _y0 = image.shape[0] / 2
```
similar sentences also exist in many other source files

**Comment by larrybradley** [comment]
@hujh08 Thanks for reporting this.  I've fixed it in #673.

I'm also CCing the original developer:  @ibusko.
