### ISSUE TITLE
Allow for PSF_Sigma to be array of values in BasicPSFPhotometry/IntegratedGaussianPRF

### ISSUE THREAD

**Issue by steveehlert** [astropy/photutils#676]
I have a project where I need to perform PSF photometry in one image (at fixed x-y positions) and fit for the psf_sigma, and then apply those same psfs to photometric measurements in another image at the same coordinates. Is there an elegant way to do this in BasicPSFPhotometry? It looks like my PSF sigma can only be a scalar.

**Comment by larrybradley** [comment]
In the new PSF photometry tools, you can input the sigma initial values in the `init_params` table.
https://photutils.readthedocs.io/en/latest/psf.html
