### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by olebole** [astropy/photutils#677]
The current version (0.4) has a number of test failures with numpy 1.14. They seem to be fixed in the git repository (36b1f6a6a9802d0d49d34837434630b9136cf0b2, 397bdbe11e53a1893168a92d640cc9c4d201820e, a4ec8afcd1bad1b3cc3f29223682d867ac24694c, and fbc518f41888f610b5cc5e730b750f3e4455ed99); however it would be nice to have a new proper release here that we can use for packaging in Debian & Co.
Is there anything planned soon?

**Comment by larrybradley** [comment]
@olebole  I do plan to release a new version soon (before 6/29).  I'm currently finishing up some new tools for ePSF building that I want to put in the new release.

**Comment by lupinix** [comment]
Any news on this? I also need this for Fedora packaging as we have failures due to newer numpy (as @olebole) mentioned and especially scikit-image (seems to be fixed with #685). A new release would help :)

If this still takes some time: Is it safe to package a current git snapshot? This will land in Fedora Rawhide (development tree) only, to be replaced by the release later.

**Comment by bsipocz** [comment]
@lupinix - The master branch is not feature complete, but aimed to be self consistent and to have no test failures. So I suspect you can use it as a placeholder for development trees while waiting for a release. As it was mentioned before, more features are coming as well as potential fixes while we iron out e.g python 3.7 compatibility (first upstream in astropy, then in the affiliated packages).

**Comment by lupinix** [comment]
Thanks, then I'll package a snapshot in meantime.

**Comment by larrybradley** [comment]
Photutils 0.5 was released today.  It requires Python 3.5+.

I'm also considering making a 0.4.1 bugfix release for those still using Python 2.7.

**Comment by olebole** [comment]
Thanks, I pulled the package and just uploaded it to Debian (dropping Python 2 package).
