### ISSUE TITLE
No Module Named PhotUtils

### ISSUE THREAD

**Issue by Mawgui1956** [astropy/photutils#681]
I have installed Photutils on Windows 10.  The prerequisite programs are in place.  Clang is installed.  Photutils appears to install.  On running a simple test program, I receive a traceback:

from astropy.stats import sigma_clipped_stats
from photutils import datasets
hdu = datasets.load_star_image()    
data = hdu.data[0:400, 0:400]    
mean, median, std = sigma_clipped_stats(data, sigma=3.0, iters=5)    
print((mean, median, std))
Traceback (most recent call last):

  File "<ipython-input-2-a45e12abd962>", line 2, in <module>
    from photutils import datasets

ModuleNotFoundError: No module named 'photutils'

I have attempted to run more involved programs: photutils is the only module "not found"  I have uninstalled an reinstalled photutils.  I am only posting this query because the wall is getting soft where my head has been hitting it... or vice versa.  Please advise troubleshooting steps and I will follow.

Thank you!

**Comment by Mawgui1956** [comment]
Additional infor:  If I try to pip install photutils, I receive the message:
"Requirement already satisfied: photutils in c:\...(path name)

**Comment by larrybradley** [comment]
@Mawgui1956 You can try to uninstall and then reinstall using `pip`:

```
pip uninstall photutils
pip install photutils
```

Note that you need a C compiler (e.g. gcc or clang) to be installed for the installation to succeed (see https://photutils.readthedocs.io/en/stable/install.html).

I highly recommend using `conda` (i.e. download Anaconda or Miniconda) for python package management (https://conda.io/docs/).

**Comment by torna4o** [comment]
> @Mawgui1956 You can try to uninstall and then reinstall using `pip`:
> 
> ```
> pip uninstall photutils
> pip install photutils
> ```
> 
> Note that you need a C compiler (e.g. gcc or clang) to be installed for the installation to succeed (see https://photutils.readthedocs.io/en/stable/install.html).
> 
> I highly recommend using `conda` (i.e. download Anaconda or Miniconda) for python package management (https://conda.io/docs/).

The issue persists in a Windows 10 environment, in miniconda.
