### ISSUE TITLE
Reason for deprecating exclude_border in DAOStarFinder?

### ISSUE THREAD

**Issue by ysBach** [astropy/photutils#691]
I am using DAOStarFinder for finding sources, and found `exclude_border` option quite helpful. After updated to photutils v 0.4, I see Deprecation warnings.

Is there any reason for deprecating this option? I couldn't find any issue here.

**Comment by larrybradley** [comment]
@ysBach  Since you find it useful, I'll remove the deprecation.  Thanks.
