### ISSUE TITLE
Performance: Faster aperture photometry

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#708]
Taken from Astropy project performance survey.

<hr/>

Loading FITS files (e.g., Herschel) and doing aperture photometry (`photutils`) takes a few seconds for each aperture.

**Comment by larrybradley** [comment]
I cannot reproduce this.  With 10,000 apertures, it takes 768 ms (76.8 us per aperture) on my machine.  Including input errors for error propagation, it's 2.5 s (250 us per aperture).  Even in the worst case, this is ~10,000x faster than reported.  I would need a specific example to test further.
