### ISSUE TITLE
Should the epsf_stars classes be in the public API?

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#714]
#695 added the ePSF builder.  But it also looks like it added all of the stuff in `epsf_stars` to the public API.  I think those classes are rather dangerous because they have overly-generic and somewhat ambiguous names - e.g. `Star` / `Stars`, which are actually narrowly focused on the problem of building the ePSFs.

So while it's nominally a backwards-incompatible change, I think we should remove those from the public API (or change their names to something more explicit if that's not possible).

cc @larrybradley

**Comment by larrybradley** [comment]
I'm open to changing the names (I did call them `PSFStar`/`PSFStars` at one point), but these classes are fairly generic for holding cutout images.

These classes need to be public for the use case where you already have the cutout images or perhaps *only* have access to cutout images (e.g. from a cutout service).  For example, see this example Kepler notebook: 
 https://gist.github.com/larrybradley/bdb29b68c3dd181e49c3e40141740464

**Comment by moustakas** [comment]
Indeed, I'm playing around with the new `ePSF` tools the same way, i.e., by passing it my own set of cutouts from stars in [Legacy Surveys](http://legacysurvey.org) imaging.

**Comment by eteq** [comment]
Ah, ok, given @moustakas example and @larrybradley's comment (and some in-person discussion I had with him), now I see the point of the class being public.

I still think it's overly-generic of a name right now though.  @larrybradley and I discussed and I think settled on `EPSFStar`/`EPSFStars`? That makes it clearer that they are for this use case while still keeping them public.

(The idea would be to change the name but then leave in a backwards-compatible version for a while that first yields a deprecation warning, then later an error).
