### ISSUE TITLE
r.m.s. of a local background

### ISSUE THREAD

**Issue by steveschulze** [astropy/photutils#719]
Hi,

To estimate the local background, I defined an annulus encircling the source region. Is it possible to extract the r.m.s. from the region (not only the sum)?

Cheers,

Steve

**Comment by larrybradley** [comment]
@steveschulze Yes, you can use Aperture masks (https://photutils.readthedocs.io/en/stable/aperture.html#aperture-masks) to do this.  Essentially the aperture mask gives you access to the pixels in the aperture, from which you can use any statistic that you like.

I plan to soon update the docs with examples of this feature.  In the meantime, please see this tutorial notebook that I gave at the AAS workshop:  https://github.com/astropy/astropy-workshop/blob/master/09-Photutils/photutils_local_backgrounds.ipynb.  The notebook calculates the sigma-clipped median in the annulus, but you can use any statistic.

**Comment by steveschulze** [comment]
Thanks! It worked nicely.

Cheers,

Steve
