### ISSUE TITLE
Perform photometry only on certain sources

### ISSUE THREAD

**Issue by kobe90** [astropy/photutils#720]
Hello, I was wondering if it is possible, in photutils, performing PSF photometry only on certain sources, providing their positions on the frame (without asking 'IterativelySubtractedPSFPhotometry' to find the sources).

Thank you in advance

**Comment by larrybradley** [comment]
@kobe90 You can use the `BasicPSFPhotometry` class (https://photutils.readthedocs.io/en/stable/api/photutils.psf.BasicPSFPhotometry.html#photutils.psf.BasicPSFPhotometry) and set `finder=None`.  In that case, you will need to input an astropy Table of the initial guesses for the positions (see `https://photutils.readthedocs.io/en/stable/api/photutils.psf.BasicPSFPhotometry.html#photutils.psf.BasicPSFPhotometry.__call__`).

**Comment by kobe90** [comment]
Thank you for your suggestion. The problem is that I don't know how I could specify the list of sources on which BasicPSFPhotometry is asked to perform Photometry on.
Could you help me?
Thank you in advance.

**Comment by kobe90** [comment]
Perfect, thank you very much for your help!

Thank you again

Renato

*********************************************************************************************
Renato Martone - 
Ph.D. Candidate at Department of Physics and Earth Sciences

University of Ferrara

Via Saragat, 1

44122 Ferrara, Italy


re.martone90@gmail.com

*********************************************************************************************

**Comment by bsipocz** [comment]
It looks to me a solution has been reached here. If there is anything else we can do on the photutils side, feel free to reopen.
