### ISSUE TITLE
'IterativelySubtractedPSFPhotometry' assigns all IDs in a subtraction loop starting from 1.

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#731]
The way IterativelySubtractedPSFPhotometry is defined ``sources = self.finder(self._residual_image)`` always produces a list starting from 1. Thus two sources found in two separate loops (such as a fainter source hidden behind a brighter source, revealed by its subtraction) will have ID=1, when they presumably should have unique IDs = [1, 2]. A simple fix to add a tracker ``max_id`` of the largest ID found through all iterations breaks the requirement of groupings (specifically in this case ``DAOGroup``), and so perhaps will require a slightly larger refactor to always get unique IDs after each subtraction-source find-fit loop.

**Comment by larrybradley** [comment]
No longer an issue with the new PSF tools.
