### ISSUE TITLE
ePSF weights are passed as data.uncertainty

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#734]
When creating ``EPSFStar`` instance in ``extract_stars`` weights can be pulled from ``data.uncertainty.array`` but are never converted to weights, with ``weights`` simply being the quoted uncertainty. This is then propagated into ``EPSFFitter._fit_star`` where weights can be passed to ``fitter``, which would lead to the case that lower quality data would receive a higher relative weighting than high signal-to-noise data.

**Comment by larrybradley** [comment]
Added in #1821.
