### ISSUE TITLE
Error cannot import name 'NUMPY_LT_1_14_1'

### ISSUE THREAD

**Issue by HelenUsher** [astropy/photutils#742]
I'm new to using python for photometry so I'm working through the Photutils tutorial on Background extraction, Aperture photometry etc I'm using a notebook in Python 3 and have downloaded the latest Photutils package using anaconda. 
Astropy version 3.0.4 and Photutils 0.5
When I try to do this:

```
from photutils import CircularAperture
positions = [(30., 30.), (40., 40.)]
apertures = CircularAperture(positions, r=3.)
from astropy import units as u
from astropy.coordinates import SkyCoord
from photutils import SkyCircularAperture
positions = SkyCoord(l=[1.2, 2.3] * u.deg, b=[0.1, 0.2] * u.deg,
                     frame='galactic')
apertures = SkyCircularAperture(positions, r=4. * u.arcsec)
```

I get this:
ImportError                               Traceback (most recent call last)
<ipython-input-19-e30a53df1cd9> in <module>()
----> 1 from photutils import CircularAperture
      2 positions = [(30., 30.), (40., 40.)]
      3 apertures = CircularAperture(positions, r=3.)
      4 from astropy import units as u
      5 from astropy.coordinates import SkyCoord

C:\ProgramData\Anaconda3\lib\site-packages\photutils\__init__.py in <module>()
     30 
     31 if not _ASTROPY_SETUP_:            # noqa
---> 32     from .aperture import *        # noqa
     33     from .background import *      # noqa
     34     from .centroids import *       # noqa

C:\ProgramData\Anaconda3\lib\site-packages\photutils\aperture\__init__.py in <module>()
      6 
      7 from .bounding_box import *    # noqa
----> 8 from .circle import *          # noqa
      9 from .core import *            # noqa
     10 from .ellipse import *         # noqa

C:\ProgramData\Anaconda3\lib\site-packages\photutils\aperture\circle.py in <module>()
      3 import math
      4 
----> 5 from astropy.coordinates import SkyCoord
      6 
      7 from .core import PixelAperture, SkyAperture

C:\ProgramData\Anaconda3\lib\site-packages\astropy\coordinates\__init__.py in <module>()
      8 
      9 from .errors import *
---> 10 from .angles import *
     11 from .baseframe import *
     12 from .attributes import *

C:\ProgramData\Anaconda3\lib\site-packages\astropy\coordinates\angles.py in <module>()
     14 from .. import units as u
     15 from ..utils import isiterable
---> 16 from ..utils.compat import NUMPY_LT_1_14_1, NUMPY_LT_1_14_2
     17 
     18 __all__ = ['Angle', 'Latitude', 'Longitude']

ImportError: cannot import name 'NUMPY_LT_1_14_1'

I'm not sure if this has any relevance, but here is the installation log for when I installed photutils yesterday so you can see package versions
![image](https://user-images.githubusercontent.com/42624604/46668100-6d714080-cbc3-11e8-9ea0-08a92d1f6e2f.png)
Thanks
Helen

**Comment by larrybradley** [comment]
@HelenUsher The error you are seeing is actually from the `astropy` package.  Do you possibly have an older version of astropy installed?  Here's how you can check from within python:

```python
>>> import astropy
>>> astropy.__version__
'3.0.4'
```

If `astropy` is correctly installed, you shouldn't get an error when doing the following (this is what is causing your reported error):

```python
>>> from astropy.utils.compat import NUMPY_LT_1_14_1, NUMPY_LT_1_14_2
```

If the above gives an error, then something would appear to be wrong with your `astropy` installation.

Here's an additional check that it's working correctly (`NUMPY_LT_1_14_1` and `NUMPY_LT_1_14_2` are boolean variables):

```python
>>> import numpy
>>> numpy.__version__
'1.15.2'
>>> NUMPY_LT_1_14_1
False
>>> NUMPY_LT_1_14_2
False
```

**Comment by larrybradley** [comment]
We haven't heard back, so assuming it's resolved.  Closing this issue.

**Comment by larrybradley** [comment]
@juliaespositon If you are still having issues, please report this to the `astropy` GitHub respository.
