### ISSUE TITLE
Add overview of available datasets and fetch_all_remote function

### ISSUE THREAD

**Issue by cdeil** [astropy/photutils#75]
We should generate an overview table summarising the available datasets (image size, dtype, file size) and add a function that fetches all remote data files into the cache on the user's machine so that after calling it she can use them all offline.

**Comment by bsipocz** [comment]
https://photutils.readthedocs.io/en/stable/datasets.html now exists along with API docs, so I go ahead and close this. While adding a `fetch_all` or similar hasn't been implemented, it didn't proved to be a real blocker either.

If anyone would use such a function, please feel free to reopen this or even better, add a PR for it.
