### ISSUE TITLE
Travis-CI returns a build error due to hanging test_aperture_photometry test run

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#752]
Occasionally while running Travis-CI builds the entire build returns an error due to one matrix run failing to complete, always failing at ``test_aperture_photometry``. Below is an example test run where this error occurred, full log [here](https://travis-ci.org/astropy/photutils/jobs/439249685). I would guess the error occurs on a specific remote build version, but I don't know enough about Travis-CI or the internals of the remote machine builds to be able to pinpoint the problem. However, the problem is always that one of the tests in ``test_aperture_photometry`` never completes, suggesting some kind of internal crash/segfault.

```
running install_scripts
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.4, py-1.6.0, pluggy-0.6.0
Running tests with photutils version 0.6.dev220.
Running tests in photutils.
Date: 2018-10-09T17:52:31
Platform: Linux-4.4.0-112-generic-x86_64-with-debian-jessie-sid
Executable: /home/travis/miniconda/envs/test/bin/python
Full Python Version: 
3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15
Numpy: 1.12.1
Scipy: 1.1.0
Matplotlib: 2.2.2
Cython: 0.28.5
Astropy: 3.0.4
scikit-image: 0.14.0
scikit-learn: 0.20.0
astropy_helpers: 3.0.2
Using Astropy options: remote_data: none.
rootdir: /tmp/photutils-test-7a75sape/lib/python3.6/site-packages, inifile: setup.cfg
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 1190 items                                                           
photutils/aperture/bounding_box.py ..                                    [  0%]
photutils/aperture/tests/test_aperture_photometry.py ............
```
Unless I am miscounting, the first 12 tests have passed, so I believe the first failure is ``<Function 'test_aperture_plots[CircularAperture-params0]'>``, based on a simple ``pytest test_aperture_photometry.py --collect-only``.

**Comment by larrybradley** [comment]
It's just a transient travis error.  I restarted the travis test and it passed.

**Comment by bsipocz** [comment]
@Onoddil - there are several people who can trigger a rebuild, so pinging us on slack in e.g. the ci-issues channel is a quick way to solve these issues (or to double check whether it's a real issue of the package rather than a transient).
