### ISSUE TITLE
roundlo(hi), sharplo(hi) in IRAFStarFinder and DAOStarFinder

### ISSUE THREAD

**Issue by mcara** [astropy/photutils#770]
I wonder why default values for `roundlo(hi)` and `sharplo(hi)` are different in `IRAFStarFinder` and `DAOStarFinder`:

```python
class IRAFStarFinder(StarFinderBase):
    def __init__(self, threshold, fwhm, sigma_radius=1.5, minsep_fwhm=2.5,
                 sharplo=0.5, sharphi=2.0, roundlo=0.0, roundhi=0.2, sky=None,
                 exclude_border=False)
```
and
```python
class DAOStarFinder(StarFinderBase):
    def __init__(self, threshold, fwhm, ratio=1.0, theta=0.0,
                 sigma_radius=1.5, sharplo=0.2, sharphi=1.0, roundlo=-1.0,
                 roundhi=1.0, sky=0.0, exclude_border=False)
```

Do these parameters measure different things in the two functions? If so, what is their exact meaning?

**Comment by larrybradley** [comment]
I discussed this a long time ago with @mcara.  These two parameters measure different things.  As described in the docs `IRAFStarFinder` calculates roundness and sharpness based on 2D image moments.  `DAOStarFinder` has custom calculations for roundness and sharpness based on object symmetry and comparing the filtered/unfiltered images.
