### ISSUE TITLE
Cannot install --- python 2.7

### ISSUE THREAD

**Issue by mpatir** [astropy/photutils#771]
Cannot run setup.py when I try to install, 
ImportError: No module named configparser python 2.7

File "setup.py", line 8, in <module>
    from configparser import ConfigParser
  File "~/anaconda2/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named configparser

**Comment by mpatir** [comment]
-- use conda install

**Comment by larrybradley** [comment]
The latest version of `photutils` is not compatible with python 2.7.  Python 3.5+ is required.

An older version of `photutils` (0.4.1) is compatible with python 2.7 and can be installed with conda.
