### ISSUE TITLE
utils of photutils

### ISSUE THREAD

**Issue by adrn** [astropy/photutils#789]
I don't know how to make an issue about this without sounding like a :trollface:, but I'm wondering if the `photutils.utils` subpackage is redundant — the double utils could be confusing to users. Do those modules really need to live in another layer of utils?

**Comment by pllim** [comment]
I propose we rename `misc.py` to `utils.py`, so it becomes `photutils.utils.utils`.

**Comment by adrn** [comment]
I actually [made a branch to do that](https://github.com/adrn/photutils/tree/fix-module-name), but decided I needed to dial back the troll / snark a little bit :)

**Comment by pllim** [comment]
FWIW only 3 more months until Apr 1... 😉

**Comment by bsipocz** [comment]
My take that `packagename.utils` is most of the time contains stuff that is developer focused. And indeed, we don't have narrative docs nor examples for those tools for photutils, only the API docs, so users won't come across those functionality.

Most of our packages has that subpackage, so at this point it would be more confusing to call it something else just for the sake of avoiding "utils". So I say this ship has sailed when photutils/specutils got named with `utils` in their name.
