### ISSUE TITLE
CircularAperture.plot transposes x, y coordinates when plotting two circles

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#790]
When plotting two apertures a ``CircularAperture`` instance will plot the tranpose of the x and y coordinates via its inbuilt plotting routine -- i.e., if my two objects are at ``a, b`` and ``c, d`` then the resultant circles are plotted at ``a, c`` and ``b, d``. The correct behaviour is produced when plotting N != 2 circles. Similar behaviour is seen in ``EllipticalAperture`` as well, so I suspect the bug is deeper than ``aperture.plot`` and simply requires a catch for two-length input.

Minimum working test:

```
from photutils.detection import find_peaks
from photutils import CircularAperture
import numpy as np
import matplotlib.pyplot as plt
a = np.zeros((15, 15), float)
a[1, 2] = 1
a[5, 12] = 5

b = find_peaks(a, threshold=0.5)

plt.imshow(a, cmap='gray', origin='lower', interpolation=None)
positions = (b['x_peak'], b['y_peak'])
positions2 = np.array((b['x_peak'], b['y_peak'])).T
apertures = CircularAperture(positions, r=1.)
apertures.plot(color='blue', lw=0.5)
apertures2 = CircularAperture(positions2, r=1.)
apertures2.plot(color='red', lw=0.5)
plt.show()
```

**Comment by larrybradley** [comment]
@Onoddil  Thanks for reporting this.  The code is actually behaving as documented, so it's not technically a bug.  However, I agree that this can be confusing and I'm going to address it in an upcoming PR.

The `positions` argument in `Aperture` objects is currently very flexible in that it can accept:

* a single (x, y) tuple
* a list of (x, y) tuples
* `Nx2` or `2xN` `ndarray` (or `Quantity`)

Obviously this API collides when the input is `2x2`.  In that case, `positions` is interpreted as `Nx2` (i.e. two rows of (x, y)).  This "feature" is documented in all of the `Aperture` classes (e.g. https://photutils.readthedocs.io/en/latest/api/photutils.CircularAperture.html#photutils.CircularAperture).  I thought a warning was also issued for `2x2` input, but it's not.  I'm going to deprecate allowing positions to have a `2xN` shape to avoid this confusion and ambiguity.  In that case the user simply needs to transpose the inputs.

**Comment by Onoddil** [comment]
Ah, I guess I missed the note in the API, apologies. I agree that a warning added to the output is good to doubly try to inform users of this clash (since they, obviously, fail to read documentation properly as I oh-so-successfully proved...). Removing one of the two options of accepted ``ndarray`` would be one way to solve the problem, but with more rigorous warnings it might not actually be an issue. 

Removing ``2xN`` as the option will require the updating of the documentation, as my example was more or less stolen straight from the example given [here](https://photutils.readthedocs.io/en/stable/detection.html), which gives the first suggestion of ``(a, b)`` as the ``positions`` argument, not that that's a particularly big issue to overcome.
