### ISSUE TITLE
Proposal to add an offset crosshair option to Centroids

### ISSUE THREAD

**Issue by kakirastern** [astropy/photutils#791]
I would like to propose adding an offset crosshair feature to highlight some regions of interest in a FITS image, much like the cross used in [Centroids.](https://photutils.readthedocs.io/en/stable/centroids.html) Just would like to double check such feature or option is not already in existence in another name in the Photutils package in the current stable version. The crosshairs would highlight some point of interest in the FITS image, with an offset to it that avoids obscuration.

**Comment by larrybradley** [comment]
@kakirastern I'm not sure what you mean by an "offset" crosshair.  The crosshairs in the centroids example plot were added with `matplotlib`.  `photutils` isn't a plotting package, but perhaps `matplotlib` has a plotting feature that you want.
