### ISSUE TITLE
Using exposure map to estimate the error

### ISSUE THREAD

**Issue by prajwel** [astropy/photutils#797]
Hi,

Is there a way to use an exposure map while carrying out PSF photometry to estimate the errors? I am unable to find this feature inside the existing photutils documentation. 

Thank you!

**Comment by larrybradley** [comment]
The new PSF photometry tools allow you to input error arrays.  The best-fit parameter errors are returned in the output table.
https://photutils.readthedocs.io/en/latest/psf.html
