### ISSUE TITLE
Why does ePSF need user to create a whole new table?

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#800]
In https://photutils.readthedocs.io/en/latest/epsf.html , there is this awkward step that seems unnecessary:

```python
>>> from astropy.table import Table
>>> stars_tbl = Table()
>>> stars_tbl['x'] = peaks_tbl['x_peak']
>>> stars_tbl['y'] = peaks_tbl['y_peak']
```

Why can't `photutils` use keyword arguments or something, instead of requiring user to create a whole new table?

cc @eteq and @mcorrenti

**Comment by larrybradley** [comment]
The `extract_stars` function allows for very flexible input types.  For example, the inputs may not even include the x, y positions, but SkyCoord values instead.  x and y are not required.  

https://photutils.readthedocs.io/en/latest/api/photutils.psf.extract_stars.html#photutils.psf.extract_stars.
