### ISSUE TITLE
source deblending fails for source 256

### ISSUE THREAD

**Issue by mth-gsk** [astropy/photutils#808]
We had a few cases of failed deblending of segmentation images; the pixel connectivity warning is triggered for a number of images. Curiously enough, source 256 triggers the error in all of them (4 different images in a pool of about 100). In three of the four cases, removing border region (with relabeling) helps; in one case, removing the border sources maintains the issue, although with relabel = True a DIFFERENT source 256 is causing the issue now.

Dropping region 256 solves all issues.

My feeling is that solution to issue #616 may be having some overflow issues - perhaps line 250 is a good place to start looking? 

As a feature request, it may be beneficial to add a flag allowing you to log a failed deblend and keep the original region, as opposed to throwing an error.

**Comment by larrybradley** [comment]
@mth-gsk Thanks for reporting this issue.  This issue is actually the same as #803, which I just fixed and merged in #806.  Please install the development version of photutils (https://photutils.readthedocs.io/en/latest/install.html#installing-the-latest-development-version) and let me know if you still see the issue.  Thanks!

**Comment by archipleym** [comment]
Hi @larrybradley, apologies to bring this up again as I see this issue should be closed. I am using version 1.9.1.dev70+g83d1047 but still running into "Deblending failed for source "256". Please ensure you used the same pixel connectivity in detect_sources and deblend_sources." I got this error when I tried using SourceFinder and changing the contrast to a non-default value, then I got the error again when using detect_sources and deblend_sources separately and changing the contrast value. Any help would be greatly appreciated!

**Comment by larrybradley** [comment]
@archipleym Would it be possible for you to send me your code (and data) that shows the error (a minimal example with the data would be even better)?  I would need that to debug your issue.

**Comment by larrybradley** [comment]
@archipleym Could you also try adding assigning a new label number for segment 256, e.g., `segment.reassign_label(label=256, new_label=9999)` after you run `detect_sources` but before `deblend_sources`?

**Comment by larrybradley** [comment]
Also can you please double check your photutils version from within Python?
```
>>> import photutils
>>> photutils.__version__
````

**Comment by larrybradley** [comment]
@archipleym I just fixed a corner-case issue where an error was raised if `contrast=1` (meaning no deblending):  https://github.com/astropy/photutils/pull/1636.  Were you using `contrast=1`?  If you still encounter an error, please open a new GitHub issue with the details.  Thanks.
