### ISSUE TITLE
BasicPSFPhotometry table does not list ID as first column

### ISSUE THREAD

**Issue by pllim** [astropy/photutils#809]
I am used to seeing ID column first (left-most) but here is what I get:

![Screenshot from 2019-03-20 13-27-49](https://user-images.githubusercontent.com/2090236/54705817-03ff4180-4b14-11e9-92b1-277ad1e5576b.png)

Feature or bug?

**Comment by larrybradley** [comment]
I would agree that `id` should be first, so I'd say that is a bug.  @eteq?

**Comment by larrybradley** [comment]
No longer relevant in the new PSF photometry tools.  Source ID is the first column.
