### ISSUE TITLE
ellipse.fit_image() not fitting for the full galaxy

### ISSUE THREAD

**Issue by PrayaagKatta** [astropy/photutils#814]
Hello. I am facing an issue with ellipse.fit() where it is not fitting for the disk of the galaxy, and stops after the bulge/bar portion. If I keep the maxsma as the size of the galaxy, the ellipses still does not fit for the galaxy. What can I do to fix this? 
This is my first time posting here, so please tell me if I haven't followed the protocols correctly.
I have attached the image below.
Thank you!
![image](https://user-images.githubusercontent.com/29648524/55456999-36c23300-5606-11e9-9e92-a51d67dfc6ba.png)

**Comment by PrayaagKatta** [comment]
Hello, I am ready to give the image used for this code, if it helps. I also tried increasing the maxrit, and playing with other parameters, but the issue is still persisting.

**Comment by larrybradley** [comment]
@ibusko Can you please take a look at this?

**Comment by ibusko** [comment]
@larrybradley yes, I will see what can be done.

**Comment by ibusko** [comment]
@PrayaagKatta from the looks of the image, I suspect that there is a large jump in the ellipse geometric parameters (basically position angle and ellipticity) at about the point it stops working. It could be that the algorithm, with the settings you used, is unable to follow the rapid change and thus gives up. If you don't mind, I would like to have a copy of the image so I can try it myself. Challenging cases like this can be good in helping to perfect the algorithm.

**Comment by PrayaagKatta** [comment]
Thanks for the reply! It has not properly for the following images - 
[ngc936_gb.fits.zip](https://github.com/astropy/photutils/files/3055935/ngc936_gb.fits.zip) (This is the one in the example.)
And also
[VCC857_g.fits.zip](https://github.com/astropy/photutils/files/3055937/VCC857_g.fits.zip) (Another case)

Please ask me if anything else is needed.
Thank you.

**Comment by PrayaagKatta** [comment]
@ibusko Thank you for taking time to go through this issue. I will definitely use your suggestions to try and fix the problem. I'll get back to you soon with the results.

**Comment by PrayaagKatta** [comment]
@ibusko Hello again! I followed your advice, and it has given positive results. I am attaching the file to show it to you.
![ngc936git](https://user-images.githubusercontent.com/29648524/56365828-64ff5f80-620f-11e9-87de-d409d2fa1b21.png)

This is actually the kind of fitting that we wanted! So, I thank you for guiding me towards it.

**Comment by ibusko** [comment]
Glad it did work! In case you run into problems again, just ask.

**Comment by larrybradley** [comment]
Thanks, @ibusko.
