### ISSUE TITLE
Verbose mode in elliptical isophote fitting 

### ISSUE THREAD

**Issue by ibusko** [astropy/photutils#823]
Elliptical isophote fitting can be slow, depending on the size of the galaxy being fitted. Even relatively small images as provided in the tutorials in `photoutils-datasets` take tens of seconds to complete. In the meantime, no feedback is sent back to the user that sits waiting, thinking that maybe the code is frozen in an infinite loop. This situation seems even more disconcerting when running the method from a Jupyter notebook, since no command line prompt or anything else shows up. The notebook just looks frozen. 

To partially fix that situation, the fitting loop provided in method `fit_image` in class `Ellipse` used to have a verbose mode that would print at the terminal a line with fitting results for evey completed ellipse fitted. The option is no longer available though. It should be put back in place to minimize user confusion.

This may be re-addressed once a speed-up of the code can be put in place, as suggested in issue #802.

**Comment by ibusko** [comment]
@larrybradley are you cool with this? I have some available time for coding now, and I could add back the verbose feature as an optional keyword parameter with minimal work.

**Comment by moustakas** [comment]
This is a separate issue, but another related feature request would be to (optionally) speed up the `fit_image` method using the `multiprocessing` module, assuming each semimajor axis can be fitted independently.

**Comment by larrybradley** [comment]
@ibusko Reporting progress is fine with me, but please leave the final output in an Astropy Table.  Thanks.

**Comment by larrybradley** [comment]
@moustakas Can you please open a new issue with your feature request so it doesn't get lost (i.e. when this issue is closed)?

**Comment by ibusko** [comment]
@larrybradley sure. I envision 'verbose' mode as just help for more tricky situations. The main output will still be the astropy Table that's already there. 'verbose' by default will be off as well, so it won't affect existing user scripts and the like.

**Comment by ibusko** [comment]
This relates to #891

**Comment by larrybradley** [comment]
Verbose mode was added in #947.
