### ISSUE TITLE
TravisCI Build Fails

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#829]
There seems to be something broken in the TravisCI build tests. I discovered an issue in test 4 for ``detections.findstars.py`` where suddenly Sphinx didn't like the multiply defined URLs so submitted #828 thinking that was an easy fix to replace the slightly tidier format for referencing ``daofind`` and ``starfind`` with anonymous URLs.

However, that subsequently uncovered an issue with TravisCI test 6 (``ASTROPY_VERSION=development EVENT_TYPE='pull_request push cron'``) where any test that goes through ``astropy.modeling.core`` hits an astropy deprecation warning (``astropy.utils.exceptions.AstropyDeprecationWarning: This function is no longer needed, directly use `inspect.Signature`.``) which TravisCI interprets as an error and the build fails.

It seems kinda coincidental to me that both errors mysteriously happened at the same time, so I suspect that my PR #828 might not be necessary if whatever deeper build failure is fixed, but it is available if necessary (or if the error persists after this bigger astropy bug is solved). I don't know enough about the astropy deprecation system to know what's causing the second warning (turned error) message, however.

Can we just put a flag somewhere to ignore that warning, or turn warnings back into warnings and not failing errors?

**Comment by bsipocz** [comment]
@Onoddil - Please post links directly to the failing travis logs, and also copy paste full trace logs. The current description above is very difficult to parse.

**Comment by bsipocz** [comment]
Also, unexpected CI-failures can be reported to the ci-issues slack channel, there are more people watching it than the individual repos.

**Comment by Onoddil** [comment]
Sorry @bsipocz - the build link is https://travis-ci.org/astropy/photutils/builds/523570561?utm_source=github_status&utm_medium=notification (specific test https://travis-ci.org/astropy/photutils/jobs/523570567). I can't paste the full traceback as it's too many characters for the comment but an example (I think they're all basically the same) is:

=================================== FAILURES ===================================
[31m[1m_____________ test_centroids[25.7-26.2-3.2-5.7-0.5235987755982988] _____________[0m

xc_ref = 25.7, yc_ref = 26.2, x_stddev = 3.2, y_stddev = 5.7
theta = 0.5235987755982988

[1m    @pytest.mark.skipif('not HAS_SCIPY')[0m
[1m    @pytest.mark.parametrize([0m
[1m        ('xc_ref', 'yc_ref', 'x_stddev', 'y_stddev', 'theta'),[0m
[1m        list(itertools.product(XCS, YCS, XSTDDEVS, YSTDDEVS, THETAS)))[0m
[1m    def test_centroids(xc_ref, yc_ref, x_stddev, y_stddev, theta):[0m
[1m        model = Gaussian2D(2.4, xc_ref, yc_ref, x_stddev=x_stddev,[0m
[1m                           y_stddev=y_stddev, theta=theta)[0m
[1m        y, x = np.mgrid[0:50, 0:47][0m
[1m        data = model(x, y)[0m
[1m    [0m
[1m        xc, yc = centroid_com(data)[0m
[1m        assert_allclose([xc_ref, yc_ref], [xc, yc], rtol=0, atol=1.e-3)[0m
[1m    [0m
[1m>       xc2, yc2 = centroid_1dg(data)[0m

[1m[31mphotutils/centroids/tests/test_core.py[0m:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[1m[31mphotutils/centroids/core.py[0m:316: in centroid_1dg
[1m    g_init = Const1D(constant_init) + Gaussian1D(*params_init)[0m
[1m[31m/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py[0m:80: in _opfunc
[1m    return _CompoundModelMeta._from_operator(oper, left, right, **kwargs)[0m
[1m[31m/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py[0m:2476: in _from_operator
[1m    new_cls = mcls(name, (_CompoundModel,), members)[0m
[1m[31m/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py[0m:133: in __init__
[1m    cls._handle_special_methods(members)[0m
[1m[31m/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py[0m:389: in _handle_special_methods
[1m    ('equivalencies', None)])[0m
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (<function _ModelMeta._handle_special_methods.<locals>.__call__ at 0x7f0a43828c80>, ('self', 'x'), [('model_set_axis', None), ('with_bounding_box', False), ('fill_value', nan), ('equivalencies', None)])
kwargs = {}
category = <class 'astropy.utils.exceptions.AstropyDeprecationWarning'>

[1m    def deprecated_func(*args, **kwargs):[0m
[1m        if pending:[0m
[1m            category = AstropyPendingDeprecationWarning[0m
[1m        else:[0m
[1m            category = warning_type[0m
[1m    [0m
[1m>       warnings.warn(message, category, stacklevel=2)[0m
[1m[31mE       astropy.utils.exceptions.AstropyDeprecationWarning: This function is no longer needed, directly use `inspect.Signature`.[0m

[1m[31m/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/utils/decorators.py[0m:122: AstropyDeprecationWarning

**Comment by larrybradley** [comment]
Yes, it's due to `https://github.com/astropy/astropy/pull/8408`.  I'm working on a fix.

**Comment by larrybradley** [comment]
After a lot of digging, I found it's actually due to https://github.com/astropy/astropy/pull/7554.

My PR to fix it (at least for v3.2): https://github.com/astropy/astropy/pull/8624.

**Comment by pllim** [comment]
It is fixed upstream. I think this can be closed.
