### ISSUE TITLE
Indexing/slicing of apertures

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#838]
If I start with this:
```
...
some_skycoord = SkyCoord(... an *array* of ras/decs...)
skyap = photutils.SkyCircularAperture(some_skycoord, 2*u.arcsec)
pixap = pixap.to_pixel(some_wcs)
```
That's all great.  However, what if I just want to look at *one* of the apertures?  The following feels natural, but:
```
>>> pixap[0]
TypeError: 'CircularAperture' object does not support indexing
```

Maybe apertures should support slicing, which would then be passed into the coordinate arrays?  One could imagine going all the way to supporting `astropy.utils.ShapedLikeNDArray`, although an intermediate option might just be to enable slicing, and perhaps `len` and `shape` which are thin wrappers into the underlying positions...

**Comment by larrybradley** [comment]
This is a good idea.

**Comment by hamogu** [comment]
:+1:
