### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mdcleir** [astropy/photutils#839]
In the documentation of the SkyEllipticalAnnulus:
https://photutils.readthedocs.io/en/stable/api/photutils.SkyEllipticalAnnulus.html#photutils.SkyEllipticalAnnulus
is indicated that b_out has to be a float. However, I assume this has to be a Quantity instead?

**Comment by larrybradley** [comment]
@mdcleir, many thanks for reporting this!  It's fixed in #840.
