### ISSUE TITLE
aperture_photometry returns NaN

### ISSUE THREAD

**Issue by mdcleir** [astropy/photutils#841]
I encountered a strange problem when running aperture_photometry on an annulus region.
It returns a perfectly fine value for this annulus:
![Screenshot from 2019-05-08 11-35-52](https://user-images.githubusercontent.com/45097951/57365788-0847f280-7186-11e9-9dca-a045ae62e77b.png)
But for just a slightly bigger annulus, it returns a NaN:
![Screenshot from 2019-05-08 11-36-56](https://user-images.githubusercontent.com/45097951/57365799-0e3dd380-7186-11e9-914d-54dc564601e4.png)

I checked and there are no NaN pixels or so in the region. Besides, np.sum works perfectly fine in both regions. What can possibly cause the NaN result here?

**Comment by larrybradley** [comment]
Thanks, @mdcleir  I discovered this last week too (I think it's the same issue).  I'm working on a fix.

**Comment by larrybradley** [comment]
@mdcleir This should be fixed by https://github.com/astropy/photutils/pull/843.  Can you try the development version and see if it fixes your issue?  Here are instructions for installing the dev version: https://photutils.readthedocs.io/en/latest/install.html#installing-the-latest-development-version

**Comment by mdcleir** [comment]
This fix indeed seems to solve my issue. Will this fix be incorporated into the public version soon or do you suggest to keep using the development version for now?

**Comment by larrybradley** [comment]
It will be in version `0.7`, which I'm planning to release at the end of the month.  In the meantime, you can continue using the development version.
