### ISSUE TITLE
Building ellipse model extremely slow

### ISSUE THREAD

**Issue by iskren-y-g** [astropy/photutils#855]
Hi,

I have a (266,266) image data and it didn't took too long to fit an ellipse to it. All plots look just fine, as I would have expected from the data. However, I tried to build a model with build_ellipse_model as per the example in the docs, however, it is taking ages ... in fact, it hasn't finished yet and it's been probably >30min by now and I have to leave office. I had a quick look at the source code, and I'm not sure, but part of the problem might be coming from the for loop, or the while loop. In principle, the for loop is slow and I personally avoid it when I can by defining a function and apply it to the entire data, i.e. isophotes in this case, using the map function, maybe in combination with the multiprocessing pool to add flexibility on how many CPUs to use. Probably you might want to look into this as a performance improvement? Or my problem is not related to this?

Cheers,
Iskren

**Comment by larrybradley** [comment]
CC: @ibusko

**Comment by ibusko** [comment]
Indeed, you're right that the loop is not the optimal way of doing this. It resulted from a (almost) blind translation from the original SPP (IRAF) code, into Python. It is in the plans to re-work the code so a more pythonic approach could help solve the speed problem. 

But your image is too small for the loop slowness effect to be significant. Did you try to run the demo notebook at ` astropy/photutils-datasets/notebooks/isophote/isophote_example3.ipynb ` to exercise the model functionality?

**Comment by iskren-y-g** [comment]
Yes, I was following the notebooks, however, what I just noticed is that it seems that the problem arises from using data sections to only fit a given section of an image. One needs to properly slice the data array. When that's fixed, it seemed that it work fine for me.

**Comment by larrybradley** [comment]
@iskren-y-g Glad it's working for you now.
