### ISSUE TITLE
Print progress (bar?) during ellipse fitting

### ISSUE THREAD

**Issue by iskren-y-g** [astropy/photutils#891]
Hello,

I was just wondering if you'd have the time to include some sort of a progress bar while ellipse  or build ellipse model are running? It is annoying not to know how far it has progressed. Sometimes I notice that for large maxsma (~2000pix) it tends to run very slow and I want to know at least what radius it reached. I think that for masked arrays, e.g. HST images, it tends to run extremely slow, even for small maxsma of ~150-250pix.

Cheers,
Iskren

**Comment by ibusko** [comment]
This relates to #823

**Comment by ibusko** [comment]
Indeed, for masked arrays it runs significantly slower than for non-masked arrays. This has to do with the intrinsic non-regular pixel addressing that is necessary to fetch pixel values from the image array, when building an elliptical sample. The speed-up achievable with numpy operators can't be used.
This might be lessened with future work on #913

**Comment by larrybradley** [comment]
Verbose mode was added in #947.
