### ISSUE TITLE
linear=True is not implemented photutils.isophote.ellipse.fit_image()

### ISSUE THREAD

**Issue by davidjsetton** [astropy/photutils#911]
I am trying to fit isophotes to an image with constant spacing between them using the procedure outlined here (https://photutils.readthedocs.io/en/stable/isophote.html). However, the linear keyword does not appear to be having any effect on the table that is outputted; regardless of how it is set, the same grid of sma are given for the step that I choose.

"
from photutils.isophote import EllipseGeometry
geometry = EllipseGeometry(x0=xbp_ref, y0=ybp_ref, sma=8, eps=0.3,
                           pa=100.*np.pi/180.)

from photutils import EllipticalAperture
aper = EllipticalAperture((geometry.x0, geometry.y0), geometry.sma,
                          geometry.sma*(1 - geometry.eps),
                          geometry.pa)

from photutils.isophote import Ellipse
ellipse = Ellipse(median_flux, geometry)

isolist = ellipse.fit_image(step=1, linear=True)

isolist.to_table()
"

I glanced at the source code and did not see a check for the linear keyword anywhere. Has this feature not been implemented yet?

**Comment by larrybradley** [comment]
@ibusko?

**Comment by ibusko** [comment]
The code in module `geometry.py` has the linear mode handling in lines 507-510. I will check if it is indeed being used, or not.

**Comment by ibusko** [comment]
There is an error in the logic that controls the linear mode. I am working on fixing this. I will submit a PR when done.

**Comment by ibusko** [comment]
@davidjsetton as a stopgap measure, you can force linear stepping by using the following sequence:

ellipse = Ellipse(data)
ellipse._geometry.linear_growth = True
ellipse._geometry.astep = 5.      # the step value in this case is in image pixels.
isolist = ellipse.fit_image()

In case you want to re-use the Ellipse instance, don't forget that it's now set to do linear stepping. You can reset the parameters at will in between calls to the fit_image() method. Or, create a new Ellipse instance every time.

**Comment by ibusko** [comment]
@davidjsetton as a stopgap measure, you can force linear stepping by using the following sequence:

ellipse = Ellipse(data)
ellipse._geometry.linear_growth = True
isolist = ellipse.fit_image(step=2.)   # step expressed in pixels

Note that the step for linear mode is in pixels, hence we have to re-define it to an appropriate value every time we switch from linear to relative mode. 
If you intend to re-use the Ellipse instance, don't forget that it is internally set now to perform linear stepping. You can change the property at any time. Or, create a new Ellipse instance.

**Comment by larrybradley** [comment]
@davidjsetton Many thanks for reporting this issue.  It's been fixed in #912 on master and will appear in the upcoming 0.7 release.
