### ISSUE TITLE
consider using multiprocessing module to speed up Ellipse.fit_image() method

### ISSUE THREAD

**Issue by moustakas** [astropy/photutils#913]
Spinning off from #823, consider using the `multiprocessing` module to (optionally) speed up the `Ellipse.fit_image()` method.  

One approach would be to fit each semi-major axis "step" independently, although perhaps these are not independent.  

Alternatively, perhaps some of the parameter optimization routines lend themselves to parallelization.

**Comment by perwin** [comment]
_One approach would be to fit each semi-major axis "step" independently, although perhaps these are not independent._

Unfortunately, they're not independent. The initial-guess parameter values for the fitting of a given semi-major-axis isophote are the best-fit values from the previous isophote fit, stepping outward or inward in semi-major axis.
