### ISSUE TITLE
Fix epsf tests for changes in modeling

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#921]
Travis is failing on the development version of astropy. The actual error can be seen here:
https://travis-ci.org/astropy/photutils/jobs/569054120

This is a bit weird because I know the branch that that CI merge is from was *passing* in its last commit prior to the merge. My hunch is that the big astropy.modeling PR was merged in the interim, and based on where the tests are failing it seems like it's a mismatch there.

cc @Onoddil (because the error appeared in `test_epsf` in the #817 merge, although it's not clear that's actually related)

**Comment by Onoddil** [comment]
Yeah I would likely agree it's `astropy.modeling` related, as [this astropy function](https://github.com/astropy/astropy/blob/b1526627afe6806f357ca72b5a34d973a3cdaed0/astropy/modeling/core.py#L3890-L3930) is the part where the test calls over, specifically line 3920 `outputs = self.evaluate(*chain(inputs, parameters))`. Digging through the recent commits I found [this](https://github.com/astropy/astropy/commit/65b74f8a829f34a5ac9ce718e43d9052db38057f#diff-ac0f27246d73b3340c870ff56110d511) update to the modeling framework detailing changes to how parameters work, so my guess is that they now get passed around differently now and we need to update to reflect this...

I am not 100% sure as to what we fix to avoid this, as the Travis CI error log says:

```
self = <EPSFModel(flux=4672761.28878858, x_0=0., y_0=0., flux=4672761.28878858, x_0=0., y_0=0.)>
inputs = [array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1...-1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.]])]
...
parameters = array([array([4672761.28878858]), array([0.]), array([0.]),
       array([4672761.28878858]), array([0.]), array([0.])], dtype=object)
```
so somewhere along the way we only have one input, which doesn't look to me like any expected input of presumably `x` or `y`, as the test sets `size=25`, so why do we have a single array of size `7 x 5`, but this may be unrelated; and we seem to have our parameters listed twice, which presumably explains the `TypeError: evaluate() takes 6 positional arguments but 9 were given`...

**Comment by larrybradley** [comment]
It's something specific to #817 (and related to modeling).  `astropy-dev` was passing fine before #817.

**Comment by bsipocz** [comment]
#931 has fixed this.

**Comment by bsipocz** [comment]
> This is a bit weird because I know the branch that that CI merge is from was passing in its last commit prior to the merge.

Trick is to never trust a month old CI status, but have a rebased version rerun. A similar situation  bite us in astropy core, too right before v3.2.
