### ISSUE TITLE
Revert changes to EPSFModel Parameters with potential upstream fix?

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#941]
With a potential fix to the issues surrounding `astropy.modeling` `Parameter`s in the 4.0 release under astropy/astropy#9123, should the (temporary?) fix in #931 be reverted (once the fix is in, of course!)? I believe we could put everything back to how it was previously, but I also think the current version also works, so the question is do we want the flexibility and code readability of two independent definitions of `flux`, `x_0`, and `y_0`, or do we want the super defining the parameters of the subclass which is fine in this case, as pointed out in astropy/astropy#9108?

**Comment by larrybradley** [comment]
The `Parameter` definitions were exactly the same in the subclass.  There's no need to override the parent class with identical definitions.

**Comment by Onoddil** [comment]
Fair enough, I suspected that would be your response, I just figured I'd open the ticket to see if the change should be put back "as was", but if it revealed unnecessary lines of code then we can leave it as _is_. I'll close the issue now then.
