### ISSUE TITLE
pep8speaks.yml being ignored by bot?

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#944]
I admit I don't fully understand how pep8speaks picks its linter, but it seems to me like the pep8speaks.yml at the time of this writing (https://github.com/astropy/photutils/blob/c9a969df4df135ff67107632c2dac488a3a576b3/.pep8speaks.yml) is supposed to be setting the line length limit to 120.  However in this issue, the bot was complaining about lines being too long that are 80-some characters:
https://github.com/astropy/photutils/pull/745#issuecomment-521713647
(since the bot updates its comments sometimes, here's a screenshot):
![image](https://user-images.githubusercontent.com/346587/63114260-6e50cc80-bf62-11e9-8382-304da0284d12.png)

Is there maybe a misconfiguration of the bot or something?  @bsipocz or @pllim have any idea?

**Comment by pllim** [comment]
Ops... maybe `flake8` is a staunch Unix terminal fan. Lemme see...

**Comment by bsipocz** [comment]
PR is merged, but I keep this open until we're sure it indeed worked.

**Comment by bsipocz** [comment]
btw the 120 character is inherited from astroquery where we're much relaxed (due to the occasionally longer url strings), I would leave it to Larry to set the preferences here.

**Comment by eteq** [comment]
FWIW, I am strongly opposed to a strict 80 char limit.  But I could be talked down to 100 :wink:

**Comment by bsipocz** [comment]
hmm, well, it's up to Larry 🙊 
(there are only a mare 38lines that are longer than 80, so that's a totally fine choice here tbh)

**Comment by bsipocz** [comment]
Closing as it now indeed works, didn't complain about the 84 char long lines in #947

**Comment by pllim** [comment]
Phew!
