### ISSUE TITLE
Consider re-working how psf photometry class methods are re-used

### ISSUE THREAD

**Issue by eteq** [astropy/photutils#945]
This is a bit vague of an issue, but has come up in a few contexts (most recently in #740 and #745), so this is a prompt for someone (probably @Onoddil as part of some follow-on PRs already planned?) to look into.

The gist is this: currently the psf photometry classes (`BasicPSFPhotometry`, `IterativelySubtractedPSFPhotometry`, and `DAOPhotPSFPhotometry`) re-use some functionality, but there's a fair amount of copy-and-pasting needed in some of the recent PRs making updates to those classes.  That's a clear sign that more re-use is desirable.  So this issue is to go back and re-examine what parts of the core photometry methods (primarily `__call__`/`do_photometry` but potentially elsewhere) of `IterativelySubtractedPSFPhotometry` and `DAOPhotPSFPhotometry` can be pushed "up" to `BasicPSFPhotometry` instead of being repeated.

As originally designed, I know @mirca and I discussed some of these cases and decided some of the re-use was too burdensome because it was just one or two lines of code that would be inside of a for loop in one case and outside in the other.  But since then some of that code has expanded to be more complex, so it's possible the answer has changed, and instead some of these bits should be moved to private methods in `BasicPSFPhotometry`.  So that's the main task of this issue - to look through the classes and identify which might benefit from that to reduce duplication.

**Comment by larrybradley** [comment]
The new PSF photometry tools have no copy-pasted code.
