### ISSUE TITLE
Rotation angle definition conflict between source_properties and EllipticalAperture

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#957]
`source_properties` (and `SourceProperties`, the class the function calls) has a conflict in its definition of rotation angle `orientation` with `EllipticalAperture`'s `theta`. The [first](https://photutils.readthedocs.io/en/stable/api/photutils.SourceProperties.html?highlight=sourceproperties#photutils.SourceProperties.orientation) defines the `orientation` as being counter-clockwise from the x-axis, while the [second](https://photutils.readthedocs.io/en/stable/api/photutils.EllipticalAperture.html?highlight=ellipticalaperture) defines `theta` as being _clockwise_ from the x-axis.

This seems counter-intuitive, and leads to cases where people might assume the two objects, slated as very nice convenience functions for doing aperture photometry etc., can be plugged one into the other and get apertures that do not align with their image. It would seem sensible to me that any and all ellipse-related products be standardised onto one definition of rotation angle so that all values of `theta`, `orientation` etc. are the same across all of these compatible modules or functions.

**Comment by larrybradley** [comment]
The rotation angle is counter-clockwise for both (and is correctly documented as such in the API docs).  Can you give an example why you think `EllipticalAperture.theta` is clockwise?

One thing to note is that `EllipticalAperture.theta` takes a float in radians (as do all astropy models).  The output `orientation` value is a `Quantity` in degrees, so need `theta` would need to be set to `orient.to(u.rad).value`.  See the plot in this section of the docs (https://photutils.readthedocs.io/en/latest/segmentation.html#centroids-photometry-and-morphological-properties) for an example combining `EllipticalAperture` with `SourceProperties`.

**Comment by larrybradley** [comment]
Also, when plotting with `plt.imshow` be sure to use the `origin='lower'` keyword, otherwise the image will be flipped -- which may lead you to think the angle is clockwise.

**Comment by Onoddil** [comment]
Ahhhh yes I missed the `origin='lower'` keyword not being in the `imshow`, thanks. You are also correct that I cannot read the documentation; but I also failed to read the plotting function to spot the mistake wasn't ours. Thanks for solving the mystery!
