### ISSUE TITLE
Extremely elongated apertures from deblended segmentation image

### ISSUE THREAD

**Issue by thriveth** [astropy/photutils#959]
Extracting and deblending galaxy sources from a fairly noisy field, I have a curious problem, where some of the apertures generated as described in the [online documentation](https://photutils.readthedocs.io/en/stable/segmentation.html#image-segmentation) are extremely elongated, all being close to horizontal. The same does not happen when not deblending the sources, but does happen for a variety of deblending parameter settings and both linear and exponential modes. 

[Data file](https://github.com/astropy/photutils/files/3685501/F225Wcutout.zip)

[Jupyter Notebook reproducing the problem](https://github.com/astropy/photutils/files/3685508/Cutouts.zip)

**Comment by larrybradley** [comment]
Thanks, @thriveth.  I'll take a look.

**Comment by larrybradley** [comment]
@thriveth Your jupyter notebook was only for making the cutout image.  I didn't see a `photutils` notebook for the source properties.  I went ahead and made a simple one using the data you provided:

https://nbviewer.jupyter.org/gist/larrybradley/15747921e0d020144ccfa591794aed70

I don't see any extremely-elongated apertures in the result.  If you could send me your `photutils` notebook that would be great.  Thanks!

**Comment by thriveth** [comment]
@larrybradley  Oh dear, that is ebarrassing! 

This should be the right one.

[Github issue MWE.zip](https://github.com/astropy/photutils/files/3691811/Github.issue.MWE.zip)

**Comment by larrybradley** [comment]
No worries, thanks!

**Comment by larrybradley** [comment]
Can you also send me the `F275Wcutout.fits` file (which your notebook uses)?  I only have `F225Wcutout.fits`?  Or is that a typo (you give it a variable name of `F225W`)?

**Comment by larrybradley** [comment]
nvm, I see the elongated sources in the F225W image.

**Comment by thriveth** [comment]
It was a typo anyway. The F225W is the right image. There's an explanation but it's not interesting.
Apologies for the confusion!

**Comment by larrybradley** [comment]
Thanks, @thriveth.  Indeed this is a bug that I tracked down to a labeling issue in `deblend_sources`.  I fixed it in #961.  Many thanks for providing the test data and MWE that enabled me to find this bug!  I'm planning to do a `0.7.1` release soon that will have the fix.

**Comment by thriveth** [comment]
Nice that it is solved! 
I wonder why it occurred in my code and not originally yours, though?

**Comment by larrybradley** [comment]
I think you had a more stringent `contrast` setting in the `deblend_sources`.  That meant some sources were removed after the initial (internal) deblend pass.  When those sources were removed that left gaps in the labeling sequence, and the downstream code depended on there not being any gaps.  That resulted in unrelated sources (separated by a large distance) having the same final label number -- and that later affected the source properties.

**Comment by larrybradley** [comment]
#961 is merged now, so feel free to test it by installing the `photutils` dev version.  Instructions here:
https://photutils.readthedocs.io/en/latest/install.html#installing-the-latest-development-version-from-source

**Comment by thriveth** [comment]
@larrybradley  Ahaaa! That makes sense. Thanks for the explanation! I'll try to find time to install the dev version. Thanks again!

**Comment by larrybradley** [comment]
Photutils 0.7.1 is now available.
