### ISSUE TITLE
BasicPSFPhotometry does not have an ``init_guesses`` keyword

### ISSUE THREAD

**Issue by astrofrog** [astropy/photutils#970]
The documentation at:

https://photutils.readthedocs.io/en/stable/api/photutils.psf.BasicPSFPhotometry.html#photutils.psf.BasicPSFPhotometry

refers to ``init_guesses`` but it doesn't seem to be a valid keyword argument.

If this was removed, what is now the proper way to provide the list of positions if these have already been determined beforehand?

**Comment by astrofrog** [comment]
My bad it's an argument to ``do_photometry`` and ``__call__`` - however I think in the docstring when this is mentioned:

*If finder is None, initial guesses for positions of objects must be provided*

it would be good to specify how. Also later when it's mentioned that ``init_guesses`` is an argument to ``do_photometry``, it would be good to specify ``__call__`` as well?

**Comment by astrofrog** [comment]
On a related note, the intersphinx link is broken for ``init_guesses``:

![Screenshot from 2019-10-18 13-19-04](https://user-images.githubusercontent.com/314716/67093586-ee392400-f1a9-11e9-978b-17a94a14383a.png)

**Comment by astrofrog** [comment]
On a somewhat related note, it would be good if init_guesses could be smart about the names for the x/y columns (in a similar vein to https://github.com/astropy/photutils/issues/966). It's difficult to have to always make new tables with different names :-/

**Comment by larrybradley** [comment]
The `init_params` table is now very flexible in the allowed x/y column names.
