### ISSUE TITLE
photutils.segmentation.source_properties() does not accept filter_kernel option

### ISSUE THREAD

**Issue by npirzkal** [astropy/photutils#978]
The option filter_kernel is not accepted by photutils.segmentation.source_properties() although it is listed in the documentation at https://photutils.readthedocs.io/en/stable/api/photutils.segmentation.source_properties.html

**Comment by larrybradley** [comment]
The first line of that documentation is generated from the actual function signature, which shows that `filter_kernel` is an optional keyword.  Also, this can be seen in the source code here:
https://photutils.readthedocs.io/en/stable/_modules/photutils/segmentation/properties.html#source_properties

Can you provide a short example showing the problem?  What version of `photutils` are you using?

**Comment by npirzkal** [comment]
yeah.. utter confusion between source_properties and SourceProperties...

**Comment by larrybradley** [comment]
In almost all cases you want to be using the `source_properties` function.  It returns a `SourceProperties` instance.
