### ISSUE TITLE
The parameter `fill_value` in method ApertureMask.multiply

### ISSUE THREAD

**Issue by izkgao** [astropy/photutils#980]
I thought this parameter was to fill the masked value with `fill_value`, but it turned out not. After reading the source code carefully, I found that `fill_value` is used to deal with the situation that the shape of the mask is larger than of the data. Currently, I use the code below instead to do further statistics.

```python
fill_masked_value = np.nan

dat = annu_mask.multiply(image)
dat[annu_mask._mask] = fill_masked_value

print(np.nanmean(dat), np.nanmedian(dat), np.nanstd(dat))
```

Is it possible to add a new parameter related to the above to the method `ApertureMask.multiply`? It will be great if the 0s representing the masked values will no longer be confused with the 0s in the non-masked data.

**Comment by larrybradley** [comment]
This was fixed in #1158.
