### ISSUE TITLE
accounting for pixel weights when generating epsf

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [astropy/photutils#983]
I am wondering about the correct way of specifying pixel-level weights when generating an epsf from a sample of stars. Using photutils v0.6, I tried to pass weights as follows
```
stars = extract_stars(NDData(data=data-median_val), stars_tbl, size=epsf_psf_size_pix)
dqs = extract_stars(NDData(data=dq), stars_tbl, size=epsf_psf_size_pix)
for j,star in enumerate(stars):
    mask_index = np.where(dqs[j].data!=0)
    star.weights[mask_index] = 0
epsf_builder = EPSFBuilder(oversampling=4, progress_bar=True)
epsf, fitted_stars = epsf_builder(stars)
```
where `dq` is the pixel data quality map in which non-zero values indicate undesirable data.

The first epsf shown below is WITHOUT weights
[jw01088002001_01201_00002_g2_cal_photutils0.6_weights-False_epsf.pdf](https://github.com/astropy/photutils/files/3821407/jw01088002001_01201_00002_g2_cal_photutils0.6_weights-False_epsf.pdf)

The second epsf obtained with weights is shown below and the results appears to be worse.
[jw01088002001_01201_00002_g2_cal_photutils0.6_weights-True_epsf.pdf](https://github.com/astropy/photutils/files/3821414/jw01088002001_01201_00002_g2_cal_photutils0.6_weights-True_epsf.pdf)

Can somebody please provide guidance on how to use this functionality correctly?
This issue may be related to #734 and I see that the use of weights is discussed here https://photutils.readthedocs.io/en/stable/api/photutils.psf.EPSFFitter.html

Examples of star cutouts used in this exercise are shown below.
[jw01088002001_01201_00002_g2_cal_photutils0.6_sample_psfs.pdf](https://github.com/astropy/photutils/files/3821424/jw01088002001_01201_00002_g2_cal_photutils0.6_sample_psfs.pdf)

**Comment by larrybradley** [comment]
If you want to simply use a boolean mask, then you should include it in the `NDData` object:

```python
mask = dq != 0  # bool mask is True for bad values
nddata = NDData(data=data-median_val, mask=mask)
stars = extract_stars(nddata, stars_tbl, size=epsf_psf_size_pix)
epsf_builder = EPSFBuilder(oversampling=4, progress_bar=True)
epsf, fitted_stars = epsf_builder(stars)
```

Does that give better results?

**Comment by Johannes-Sahlmann** [comment]
thanks @larrybradley . This improves the results but it looks like not using weights at all is still better: 
[jw01088002001_01201_00002_g2_cal_photutils0.6_weights-True_epsf_nddata.pdf](https://github.com/astropy/photutils/files/3821567/jw01088002001_01201_00002_g2_cal_photutils0.6_weights-True_epsf_nddata.pdf)

**Comment by larrybradley** [comment]
Do you have a lot of pixels with non-zero DQ?  Significantly reducing the number of available pixels will give worse ePSF results (and possibly holes).  Some non-zero DQ pixels may be perfectly fine to keep (e.g. a flagged CR or saturated pixel that was corrected in ramp fitting).

Note that even in the non-masked case, outlier pixels are excluded in the stack of `EPSFStars` cutouts using sigma clipping during the ePSF building procedure.

Also, a lot of your sample stars actually have multiple stars in the cutout.  Ideally, there should only be one star per cutout.  The sigma clipping can help remove some of these outliers, but if a pixel in the stack of stars is contaminated in a lot/most of the stars then that pixel will be bad in the ePSF result.  A cleaner sample of stars may work better, even though there will be less samples per ePSF pixel.

**Comment by Johannes-Sahlmann** [comment]
tagging @tonysohn who is taking over this work.

**Comment by larrybradley** [comment]
Thanks, @Johannes-Sahlmann.
