### ISSUE TITLE
GriddablePSFModel does not accept 2D oversampling

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#990]
Unlike `FittableImageModel`, `GriddablePSFModel` doesn't accept 2D oversampling (in the form of an `(x, y)` tuple). Presumably this should be extended to match the parameters accepted by the base class?

It also appears in the docstring to want an integer oversampling factor, but `FittableImageModel` accepts `float or tuple of two floats`, and `GriddablePSFModel` only checks for `isscalar` for error raising purposes.

**Comment by larrybradley** [comment]
Different x/y oversampling is now available in `GriddedPSFModel`.
