### ISSUE TITLE
Ability to pass weights through PSF photometry fitting routines for use in self.fitter

### ISSUE THREAD

**Issue by Onoddil** [astropy/photutils#999]
Currently in PSF photometry routines (`BasicPSFPhotometry` etc.) the actual fitting routine (`LevMarLSQFitter` by default) only works with unit weights, as there is no option to pass any uncertainties -- or weights, as is wanted by at least the LevMar fitter -- through as a separate array (or bundled in an `NDData` object, etc.), giving the option of downweighting poor quality data in a star fit.

**Comment by larrybradley** [comment]
Errors can be input in the PSF photometry tools.
